<a href="https://colab.research.google.com/github/fzohra-ux/scalableML/blob/main/Clean_Llama_3_2_1B%2B3B_Conversational_%2B_2x_faster_finetuning.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
  <a href="https://github.com/unslothai/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/u54VK8m8tk"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
  <a href="https://ko-fi.com/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Kofi button.png" width="145"></a></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your own computer, follow the installation instructions on our Github page [here](https://github.com/unslothai/unsloth?tab=readme-ov-file#-installation-instructions).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & [how to save it](#Save) (eg for Llama.cpp).

**[NEW] Try 2x faster inference in a free Colab for Llama-3.1 8b Instruct [here](https://colab.research.google.com/drive/1T-YBVfnphoVc8E2E854qF3jdia2Ll2W2?usp=sharing)**

Features in the notebook:
1. Uses Maxime Labonne's [FineTome 100K](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset.
1. Convert ShareGPT to HuggingFace format via `standardize_sharegpt`
2. Train on Completions / Assistant only via `train_on_responses_only`
3. Unsloth now supports Torch 2.4, all TRL & Xformers versions & Python 3.12!

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
%%capture
!pip install ray
!pip install -q optuna
!pip install unsloth
# Also get the latest nightly Unsloth!
!pip uninstall unsloth -y && pip install --upgrade --no-cache-dir --no-deps git+https://github.com/unslothai/unsloth.git@nightly git+https://github.com/unslothai/unsloth-zoo.git

* We support Llama, Mistral, Phi-3, Gemma, Yi, DeepSeek, Qwen, TinyLlama, Vicuna, Open Hermes etc
* We support 16bit LoRA or 4bit QLoRA. Both 2x faster.
* `max_seq_length` can be set to anything, since we do automatic RoPE Scaling via [kaiokendev's](https://kaiokendev.github.io/til) method.
* [**NEW**] We make Gemma-2 9b / 27b **2x faster**! See our [Gemma-2 9b notebook](https://colab.research.google.com/drive/1vIrqH5uYDQwsJ4-OO3DErvuv4pBgVwk4?usp=sharing)
* [**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/drive/1WZDi7APtQ9VsvOrQSSC5DDtxq159j8iZ?usp=sharing)

In [ ]:
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Choose any! We auto support RoPE Scaling internally!
dtype = None # None for auto detection. Float16 for Tesla T4, V100, Bfloat16 for Ampere+
load_in_4bit = True # Use 4bit quantization to reduce memory usage. Can be False.

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-1B-Instruct-bnb-4bit", # or choose "unsloth/Llama-3.2-1B-Instruct"
    max_seq_length = max_seq_length,
    dtype = dtype,
    load_in_4bit = load_in_4bit,
    # token = "hf_...", # use one if using gated models like meta-llama/Llama-2-7b-hf
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.11.6: Fast Llama patching. Transformers: 4.57.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/1.03G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

In [ ]:
from unsloth.chat_templates import get_chat_template
from datasets import load_dataset

# 1. Get chat template for llama-3.1
tokenizer = get_chat_template(
    tokenizer,
    chat_template = "llama-3.1",
)

def formatting_prompts_func(examples):
    convos = examples["conversations"]
    texts = [
        tokenizer.apply_chat_template(
            convo,
            tokenize = False,
            add_generation_prompt = False,
        )
        for convo in convos
    ]
    return {"text": texts}
oogle-research-datasets/mbpp
# 2. Load CodeAlpaca instead of FineTome-100k
dataset = load_dataset("sahil2801/CodeAlpaca-20k", split="train")

# 3. Convert (instruction, input, output) -> ShareGPT-like "conversations"
def codealpaca_to_conversation(example):
    instr = example["instruction"]quelle est la difference entre evals et ce ty
    inp = example.get("input", "") or ""
    out = example["output"]

    if inp.strip():
        user_content = f"{instr}\n\nInput:\n{inp}"
    else:
        user_content = instr

    return {
        "conversations": [
            {"role": "user", "content": user_content},
            {"role": "assistant", "content": out},
        ]
    }

dataset = dataset.map(codealpaca_to_conversation)

# 4. Apply your existing formatting func
dataset = dataset.map(formatting_prompts_func, batched=True)

README.md:   0%|          | 0.00/147 [00:00<?, ?B/s]

code_alpaca_20k.json: 0.00B [00:00, ?B/s]

Generating train split:   0%|          | 0/20022 [00:00<?, ? examples/s]

Map:   0%|          | 0/20022 [00:00<?, ? examples/s]

Map:   0%|          | 0/20022 [00:00<?, ? examples/s]

In [ ]:
dataset[5]["conversations"]

[{'content': 'Create a nested loop to print every combination of numbers between 0-9',
  'role': 'user'},
 {'content': 'for i in range(10):\n    for j in range(10):\n        print(i, j)',
  'role': 'assistant'}]

In [ ]:
dataset[5]["text"]

'<|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nCreate a nested loop to print every combination of numbers between 0-9<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nfor i in range(10):\n    for j in range(10):\n        print(i, j)<|eot_id|>'

In [ ]:
from ray import tune, air
from ray.tune.schedulers import ASHAScheduler
from ray.tune.search.optuna import OptunaSearch

dataset = dataset.shuffle(seed=42).select(range(5000))

# 3) Ray training function
def train_sft_tune(config, dataset, max_seq_length):
    from unsloth import FastLanguageModel, is_bfloat16_supported
    from unsloth.chat_templates import train_on_responses_only
    from transformers import TrainingArguments, DataCollatorForSeq2Seq
    from trl import SFTTrainerdata
    from ray import tune

    # 1) reload base model + tokenizer
    base_model, tok = FastLanguageModel.from_pretrained(
        "unsloth/Llama-3.2-1B-Instruct",
        max_seq_length = max_seq_length,
        dtype = None,
        load_in_4bit = True,
    )

    # 2) apply your LoRA config (tuned by Ray)
    model = FastLanguageModel.get_peft_model(
        base_model,
        r = config["r"],
        target_modules = ["q_proj","k_proj","v_proj","o_proj",
                         "gate_proj","up_proj","down_proj"],
        lora_alpha = config["lora_alpha"],
        lora_dropout = 0,
        bias = "none",
        use
_gradient_checkpointing = "unsloth",
        random_state = 3407,
        use_rslora = False,
        loftq_config = None,
    )

    data_collator = DataCollatorForSeq2Seq(tokenizer=tok)

    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        max_steps = 150,
        learning_rate = config["lr"],
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        save_steps = 0,
        output_dir = "/content/ray_tmp",
        logging_steps = 5,
        optim = "adamw_8bit",
        report_to = "none",
    )

    trainer = SFTTrainer(
        model = model,
        tokenizer = tok,
        train_dataset = dataset,
        dataset_text_field = "text",
        max_seq_length = max_seq_length,
        data_collator = data_collator,
        dataset_num_proc = 2,
        packing = False,
        args = args,
    )

    # train only on assistant responses
    trainer = train_on_responses_only(
        trainer,
        instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
        response_part    = "<|start_header_id|>assistant<|end_header_id|>\n\n",
    )

    # 🚀 actually train
    trainer.train()

    # use last training loss as metric (no eval_dataset)
    history = trainer.state.log_history
    print("history of tuning ", history)  # ← INDENTED

    # Get the final summary which contains 'train_loss'
    final_summary = [h for h in history if "train_loss" in h]
    if final_summary:  # ← INDENTED
        last_loss = final_summary[-1]["train_loss"]
    else:
        # Fallback to step losses if summary not available
        train_losses = [h["loss"] for h in history if "loss" in h]
        last_loss = train_losses[-1] if train_losses else float('inf')

    print(f"Reporting loss: {last_loss}")  # ← INDENTED

    # CRITICAL: Pass as a dictionary, not keyword argument
    tune.report({"train_loss": last_loss})

# ---- Ray Tune config ----
scheduler = ASHAScheduler(grace_period=1)
searcher  = OptunaSearch()

param_space = {
    "lr": tune.loguniform(1e-5, 5e-4),
    "r": tune.choice([8, 16, 32]),
    "lora_alpha": tune.choice([16, 32, 64]),
}

tuner = tune.Tuner(
    tune.with_resources(
        tune.with_parameters(
            train_sft_tune,
            dataset=dataset,
            max_seq_length=max_seq_length,
        ),
        resources={"cpu": 2, "gpu": 0.5},
    ),
    param_space=param_space,
    tune_config=tune.TuneConfig(
        metric="train_loss",
        mode="min",
        scheduler=scheduler,
        search_alg=searcher,
        num_samples=20,
        max_concurrent_trials=2,
    ),
    run_config=air.RunConfig(name="llama_lora_hpo"),
)

results = tuner.fit()
best = results.get_best_result(metric="train_loss", mode="min")
print("Best config:", best.config)
print("Best train_loss:", best.metrics["train_loss"])

[I 2025-11-29 15:54:29,548] A new study created in memory with name: optuna
2025-11-29 15:54:29,553	WARNING callback.py:143 -- The TensorboardX logger cannot be instantiated because either TensorboardX or one of it's dependencies is not installed. Please make sure you have the latest version of TensorboardX installed: `pip install -U tensorboardx`

+----------------------------------------------------------+
| Configuration for experiment     llama_lora_hpo          |
+----------------------------------------------------------+
| Search algorithm                 SearchGenerator         |
| Scheduler                        AsyncHyperBandScheduler |
| Number of trials                 20                      |
+----------------------------------------------------------+

View detailed results here: /root/ray_results/llama_lora_hpo

Trial status: 1 PENDING
Current time: 2025-11-29 15:54:29. Total running time: 0s
Logical resource usage: 0/2 CPUs, 0/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   PENDING    5.61848e-05    32             32 |
+-----------------------------------------------------------------------+

Trial train_sft_tune_3e6a0a4a started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_3e6a0a4a config           |
+------------------------------------------------+
| lora_alpha                                  32 |
| lr                                       6e-05 |
| r                                           32 |
+------------------------------------------------+
(train_sft_tune pid=22163) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=22163) 2025-11-29 15:54:42.391147: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=22163) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=22163) E0000 00:00:1764431682.413885   22229 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=22163) E0000 00:00:1764431682.420850   22229 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=22163) W0000 00:00:1764431682.439699   22229 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=22163) W0000 00:00:1764431682.439737   22229 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=22163) W0000 00:00:1764431682.439741   22229 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=22163) W0000 00:00:1764431682.439744   22229 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=22163) 🦥 Unsloth Zoo will now patch everything to make training faster!

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:54:59. Total running time: 30s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+
(train_sft_tune pid=22163) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=22163)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=22163) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=22163) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=22163)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=22163) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=22163) [2025-11-29 15:55:06,931 E 22163 22205] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=22163) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/5000 [00:00<?, ? examples/s]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:55:29. Total running time: 1min 0s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

Unsloth: Tokenizing ["text"] (num_proc=6):  67%|██████▋   | 3333/5000 [00:15<00:05, 282.64 examples/s]
Unsloth: Tokenizing ["text"] (num_proc=6): 100%|██████████| 5000/5000 [00:15<00:00, 315.59 examples/s]
Map (num_proc=6):   0%|          | 0/5000 [00:00<?, ? examples/s]
Map (num_proc=6):  17%|█▋        | 833/5000 [00:02<00:10, 399.58 examples/s]
Map (num_proc=6):  33%|███▎      | 1666/5000 [00:02<00:03, 878.95 examples/s]
Map (num_proc=6):  83%|████████▎ | 4167/5000 [00:02<00:00, 2835.72 examples/s]
Map (num_proc=6): 100%|██████████| 5000/5000 [00:02<00:00, 1922.61 examples/s]
(train_sft_tune pid=22163) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=22163) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=22163)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=22163) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=22163) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=22163)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=22163) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:55:59. Total running time: 1min 30s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

  1%|          | 1/150 [00:13<33:39, 13.56s/it]
  1%|▏         | 2/150 [00:15<16:59,  6.89s/it]
  2%|▏         | 3/150 [00:18<12:37,  5.15s/it]
  3%|▎         | 4/150 [00:21<10:26,  4.29s/it]

(train_sft_tune pid=22163) {'loss': 1.091, 'grad_norm': 0.4579508304595947, 'learning_rate': 4.4947851128719365e-05, 'epoch': 0.01}

  3%|▎         | 5/150 [00:24<08:34,  3.55s/it]
  4%|▍         | 6/150 [00:26<07:52,  3.28s/it]
  5%|▍         | 7/150 [00:29<07:28,  3.14s/it]
  5%|▌         | 8/150 [00:32<07:17,  3.08s/it]
  6%|▌         | 9/150 [00:35<07:04,  3.01s/it]

(train_sft_tune pid=22163) {'loss': 0.9473, 'grad_norm': 0.36622655391693115, 'learning_rate': 5.463488800990888e-05, 'epoch': 0.02}

  7%|▋         | 10/150 [00:38<06:59,  3.00s/it]
  7%|▋         | 11/150 [00:41<07:03,  3.05s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:56:29. Total running time: 2min 0s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

  8%|▊         | 12/150 [00:44<06:38,  2.89s/it]
  9%|▊         | 13/150 [00:47<06:59,  3.06s/it]
  9%|▉         | 14/150 [00:50<06:33,  2.89s/it]

(train_sft_tune pid=22163) {'loss': 1.0415, 'grad_norm': 0.36332592368125916, 'learning_rate': 5.269748063367098e-05, 'epoch': 0.02}

 10%|█         | 15/150 [00:52<05:54,  2.62s/it]
 11%|█         | 16/150 [00:55<06:03,  2.72s/it]
 11%|█▏        | 17/150 [00:58<06:26,  2.90s/it]
 12%|█▏        | 18/150 [01:00<05:53,  2.68s/it]
 13%|█▎        | 19/150 [01:03<05:57,  2.73s/it]

(train_sft_tune pid=22163) {'loss': 0.9623, 'grad_norm': 0.48425576090812683, 'learning_rate': 5.0760073257433074e-05, 'epoch': 0.03}

 13%|█▎        | 20/150 [01:04<05:09,  2.38s/it]
 14%|█▍        | 21/150 [01:07<05:00,  2.33s/it]
 15%|█▍        | 22/150 [01:09<04:58,  2.33s/it]
 15%|█▌        | 23/150 [01:12<05:04,  2.40s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:56:59. Total running time: 2min 30s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 16%|█▌        | 24/150 [01:15<05:23,  2.57s/it]

(train_sft_tune pid=22163) {'loss': 0.8923, 'grad_norm': 0.3043889105319977, 'learning_rate': 4.882266588119517e-05, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:17<05:26,  2.61s/it]
 17%|█▋        | 26/150 [01:21<05:50,  2.83s/it]
 18%|█▊        | 27/150 [01:23<05:26,  2.66s/it]
 19%|█▊        | 28/150 [01:26<05:38,  2.77s/it]
 19%|█▉        | 29/150 [01:28<05:07,  2.54s/it]

(train_sft_tune pid=22163) {'loss': 1.0356, 'grad_norm': 0.38308387994766235, 'learning_rate': 4.688525850495727e-05, 'epoch': 0.05}

 20%|██        | 30/150 [01:32<05:48,  2.91s/it]
 21%|██        | 31/150 [01:35<05:51,  2.95s/it]
 21%|██▏       | 32/150 [01:37<05:16,  2.68s/it]
 22%|██▏       | 33/150 [01:40<05:37,  2.88s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:57:30. Total running time: 3min 0s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 23%|██▎       | 34/150 [01:43<05:26,  2.82s/it]

(train_sft_tune pid=22163) {'loss': 0.9142, 'grad_norm': 0.394202321767807, 'learning_rate': 4.4947851128719365e-05, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:45<05:03,  2.64s/it]
 24%|██▍       | 36/150 [01:47<04:56,  2.60s/it]
 25%|██▍       | 37/150 [01:50<05:00,  2.66s/it]
 25%|██▌       | 38/150 [01:53<04:52,  2.61s/it]
 26%|██▌       | 39/150 [01:56<05:02,  2.72s/it]

(train_sft_tune pid=22163) {'loss': 0.8111, 'grad_norm': 0.371782124042511, 'learning_rate': 4.301044375248146e-05, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:59<05:01,  2.74s/it]
 27%|██▋       | 41/150 [02:01<04:59,  2.75s/it]
 28%|██▊       | 42/150 [02:04<04:59,  2.77s/it]
 29%|██▊       | 43/150 [02:06<04:35,  2.58s/it]
 29%|██▉       | 44/150 [02:09<04:40,  2.64s/it]

(train_sft_tune pid=22163) {'loss': 0.9208, 'grad_norm': 0.39066481590270996, 'learning_rate': 4.1073036376243554e-05, 'epoch': 0.07}

 30%|███       | 45/150 [02:11<04:18,  2.46s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:58:00. Total running time: 3min 30s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 31%|███       | 46/150 [02:14<04:33,  2.63s/it]
 31%|███▏      | 47/150 [02:17<04:44,  2.76s/it]
 32%|███▏      | 48/150 [02:20<04:56,  2.91s/it]
 33%|███▎      | 49/150 [02:23<04:34,  2.72s/it]

(train_sft_tune pid=22163) {'loss': 0.9383, 'grad_norm': 0.3836340010166168, 'learning_rate': 3.913562900000565e-05, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:26<04:47,  2.87s/it]
 34%|███▍      | 51/150 [02:30<05:07,  3.10s/it]
 35%|███▍      | 52/150 [02:32<04:49,  2.95s/it]
 35%|███▌      | 53/150 [02:35<04:40,  2.89s/it]
 36%|███▌      | 54/150 [02:38<04:30,  2.82s/it]

(train_sft_tune pid=22163) {'loss': 0.8322, 'grad_norm': 0.3830423951148987, 'learning_rate': 3.719822162376775e-05, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:40<04:08,  2.61s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:58:30. Total running time: 4min 0s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 37%|███▋      | 56/150 [02:43<04:13,  2.69s/it]
 38%|███▊      | 57/150 [02:45<03:51,  2.49s/it]
 39%|███▊      | 58/150 [02:47<03:55,  2.56s/it]
 39%|███▉      | 59/150 [02:50<03:58,  2.63s/it]

(train_sft_tune pid=22163) {'loss': 0.9649, 'grad_norm': 0.4560186564922333, 'learning_rate': 3.5260814247529845e-05, 'epoch': 0.1}

 40%|████      | 60/150 [02:53<03:53,  2.59s/it]
 41%|████      | 61/150 [02:56<04:00,  2.70s/it]
 41%|████▏     | 62/150 [02:59<04:26,  3.03s/it]
 42%|████▏     | 63/150 [03:03<04:29,  3.10s/it]
 43%|████▎     | 64/150 [03:06<04:38,  3.23s/it]

(train_sft_tune pid=22163) {'loss': 0.7934, 'grad_norm': 0.38076961040496826, 'learning_rate': 3.332340687129194e-05, 'epoch': 0.1}

 43%|████▎     | 65/150 [03:08<04:09,  2.93s/it]
 44%|████▍     | 66/150 [03:11<04:08,  2.96s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:59:00. Total running time: 4min 30s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 45%|████▍     | 67/150 [03:14<03:49,  2.76s/it]
 45%|████▌     | 68/150 [03:16<03:31,  2.58s/it]
 46%|████▌     | 69/150 [03:18<03:16,  2.42s/it]

(train_sft_tune pid=22163) {'loss': 0.9129, 'grad_norm': 0.37239810824394226, 'learning_rate': 3.138599949505404e-05, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:21<03:37,  2.71s/it]
 47%|████▋     | 71/150 [03:25<03:48,  2.89s/it]
 48%|████▊     | 72/150 [03:27<03:35,  2.76s/it]
 49%|████▊     | 73/150 [03:30<03:37,  2.82s/it]
 49%|████▉     | 74/150 [03:33<03:27,  2.73s/it]

(train_sft_tune pid=22163) {'loss': 1.0046, 'grad_norm': 0.34980344772338867, 'learning_rate': 2.9448592118816137e-05, 'epoch': 0.12}

 50%|█████     | 75/150 [03:36<03:28,  2.79s/it]
 51%|█████     | 76/150 [03:38<03:25,  2.78s/it]
 51%|█████▏    | 77/150 [03:41<03:20,  2.75s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 15:59:30. Total running time: 5min 0s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 52%|█████▏    | 78/150 [03:43<03:05,  2.57s/it]
 53%|█████▎    | 79/150 [03:45<02:57,  2.50s/it]

(train_sft_tune pid=22163) {'loss': 0.9732, 'grad_norm': 0.5251571536064148, 'learning_rate': 2.751118474257823e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:48<03:00,  2.58s/it]
 54%|█████▍    | 81/150 [03:51<03:04,  2.67s/it]
 55%|█████▍    | 82/150 [03:54<03:04,  2.72s/it]
 55%|█████▌    | 83/150 [03:56<02:57,  2.65s/it]
 56%|█████▌    | 84/150 [03:59<02:48,  2.55s/it]

(train_sft_tune pid=22163) {'loss': 1.0107, 'grad_norm': 0.4820999205112457, 'learning_rate': 2.557377736634033e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [04:02<02:53,  2.67s/it]
 57%|█████▋    | 86/150 [04:04<02:41,  2.52s/it]
 58%|█████▊    | 87/150 [04:07<02:50,  2.71s/it]
 59%|█████▊    | 88/150 [04:10<02:51,  2.77s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:00:00. Total running time: 5min 30s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 59%|█████▉    | 89/150 [04:13<02:59,  2.94s/it]

(train_sft_tune pid=22163) {'loss': 1.0088, 'grad_norm': 0.4037856161594391, 'learning_rate': 2.3636369990102424e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [04:15<02:36,  2.61s/it]
 61%|██████    | 91/150 [04:17<02:24,  2.45s/it]
 61%|██████▏   | 92/150 [04:20<02:26,  2.52s/it]
 62%|██████▏   | 93/150 [04:22<02:23,  2.53s/it]
 63%|██████▎   | 94/150 [04:25<02:16,  2.44s/it]

(train_sft_tune pid=22163) {'loss': 0.8135, 'grad_norm': 0.3562389016151428, 'learning_rate': 2.169896261386452e-05, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:28<02:20,  2.56s/it]
 64%|██████▍   | 96/150 [04:30<02:14,  2.50s/it]
 65%|██████▍   | 97/150 [04:33<02:21,  2.68s/it]
 65%|██████▌   | 98/150 [04:36<02:24,  2.78s/it]
 66%|██████▌   | 99/150 [04:39<02:30,  2.94s/it]

(train_sft_tune pid=22163) {'loss': 0.9075, 'grad_norm': 0.39555442333221436, 'learning_rate': 1.9761555237626617e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:41<02:13,  2.67s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:00:30. Total running time: 6min 0s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 67%|██████▋   | 101/150 [04:44<02:06,  2.59s/it]
 68%|██████▊   | 102/150 [04:46<01:59,  2.50s/it]
 69%|██████▊   | 103/150 [04:49<02:01,  2.58s/it]
 69%|██████▉   | 104/150 [04:52<02:02,  2.67s/it]

(train_sft_tune pid=22163) {'loss': 0.9374, 'grad_norm': 0.361033171415329, 'learning_rate': 1.7824147861388715e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:54<01:59,  2.65s/it]
 71%|███████   | 106/150 [04:57<01:53,  2.58s/it]
 71%|███████▏  | 107/150 [05:00<01:57,  2.73s/it]
 72%|███████▏  | 108/150 [05:03<02:01,  2.89s/it]
 73%|███████▎  | 109/150 [05:06<01:56,  2.85s/it]

(train_sft_tune pid=22163) {'loss': 0.8517, 'grad_norm': 0.4266423285007477, 'learning_rate': 1.588674048515081e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [05:08<01:44,  2.62s/it]
 74%|███████▍  | 111/150 [05:11<01:50,  2.84s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:01:00. Total running time: 6min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 75%|███████▍  | 112/150 [05:14<01:52,  2.95s/it]
 75%|███████▌  | 113/150 [05:17<01:39,  2.70s/it]
 76%|███████▌  | 114/150 [05:20<01:40,  2.78s/it]

(train_sft_tune pid=22163) {'loss': 0.8837, 'grad_norm': 0.47825178503990173, 'learning_rate': 1.3949333108912907e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:22<01:30,  2.60s/it]
 77%|███████▋  | 116/150 [05:24<01:27,  2.57s/it]
 78%|███████▊  | 117/150 [05:27<01:31,  2.77s/it]
 79%|███████▊  | 118/150 [05:31<01:33,  2.91s/it]
 79%|███████▉  | 119/150 [05:34<01:31,  2.94s/it]

(train_sft_tune pid=22163) {'loss': 1.0926, 'grad_norm': 0.4428236782550812, 'learning_rate': 1.2011925732675003e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:36<01:22,  2.74s/it]
 81%|████████  | 121/150 [05:39<01:25,  2.94s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:01:30. Total running time: 7min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 81%|████████▏ | 122/150 [05:43<01:25,  3.04s/it]
 82%|████████▏ | 123/150 [05:45<01:18,  2.91s/it]
 83%|████████▎ | 124/150 [05:49<01:18,  3.04s/it]

(train_sft_tune pid=22163) {'loss': 0.8624, 'grad_norm': 0.38736677169799805, 'learning_rate': 1.0074518356437098e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:51<01:12,  2.91s/it]
 84%|████████▍ | 126/150 [05:54<01:10,  2.94s/it]
 85%|████████▍ | 127/150 [05:57<01:07,  2.93s/it]
 85%|████████▌ | 128/150 [06:00<01:02,  2.82s/it]
 86%|████████▌ | 129/150 [06:01<00:52,  2.48s/it]

(train_sft_tune pid=22163) {'loss': 0.865, 'grad_norm': 0.3862144649028778, 'learning_rate': 8.137110980199196e-06, 'epoch': 0.21}

 87%|████████▋ | 130/150 [06:04<00:51,  2.58s/it]
 87%|████████▋ | 131/150 [06:07<00:48,  2.56s/it]
 88%|████████▊ | 132/150 [06:10<00:48,  2.69s/it]
 89%|████████▊ | 133/150 [06:12<00:43,  2.53s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:02:00. Total running time: 7min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 89%|████████▉ | 134/150 [06:16<00:46,  2.90s/it]

(train_sft_tune pid=22163) {'loss': 0.8902, 'grad_norm': 0.4029320478439331, 'learning_rate': 6.1997036039612915e-06, 'epoch': 0.22}

 90%|█████████ | 135/150 [06:18<00:43,  2.87s/it]
 91%|█████████ | 136/150 [06:22<00:41,  2.95s/it]
 91%|█████████▏| 137/150 [06:24<00:34,  2.68s/it]
 92%|█████████▏| 138/150 [06:26<00:31,  2.66s/it]
 93%|█████████▎| 139/150 [06:29<00:28,  2.62s/it]

(train_sft_tune pid=22163) {'loss': 0.9638, 'grad_norm': 0.39059343934059143, 'learning_rate': 4.262296227723388e-06, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:31<00:24,  2.49s/it]
 94%|█████████▍| 141/150 [06:34<00:23,  2.56s/it]
 95%|█████████▍| 142/150 [06:36<00:20,  2.62s/it]
 95%|█████████▌| 143/150 [06:39<00:18,  2.69s/it]

Trial status: 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:02:30. Total running time: 8min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
+-----------------------------------------------------------------------+
| Trial name                status              lr     r     lora_alpha |
+-----------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   RUNNING    5.61848e-05    32             32 |
| train_sft_tune_a367bbff   PENDING    2.02994e-05    32             16 |
+-----------------------------------------------------------------------+

 96%|█████████▌| 144/150 [06:43<00:17,  2.86s/it]

(train_sft_tune pid=22163) {'loss': 0.8937, 'grad_norm': 0.38955846428871155, 'learning_rate': 2.3248888514854844e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:45<00:13,  2.75s/it]
 97%|█████████▋| 146/150 [06:48<00:10,  2.69s/it]
 98%|█████████▊| 147/150 [06:50<00:08,  2.67s/it]
 99%|█████████▊| 148/150 [06:53<00:05,  2.73s/it]
 99%|█████████▉| 149/150 [06:56<00:02,  2.64s/it]

(train_sft_tune pid=22163) {'loss': 0.9605, 'grad_norm': 0.3726881146430969, 'learning_rate': 3.874814752475807e-07, 'epoch': 0.24}

100%|██████████| 150/150 [06:58<00:00,  2.68s/it]

(train_sft_tune pid=22163) {'train_runtime': 420.0605, 'train_samples_per_second': 2.857, 'train_steps_per_second': 0.357, 'train_loss': 0.9325727272033691, 'epoch': 0.24}
(train_sft_tune pid=22163) history of tuning  [{'loss': 1.091, 'grad_norm': 0.4579508304595947, 'learning_rate': 4.4947851128719365e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9473, 'grad_norm': 0.36622655391693115, 'learning_rate': 5.463488800990888e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0415, 'grad_norm': 0.36332592368125916, 'learning_rate': 5.269748063367098e-05, 'epoch': 0.024, 'step': 15}, {'loss': 0.9623, 'grad_norm': 0.48425576090812683, 'learning_rate': 5.0760073257433074e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.8923, 'grad_norm': 0.3043889105319977, 'learning_rate': 4.882266588119517e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0356, 'grad_norm': 0.38308387994766235, 'learning_rate': 4.688525850495727e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9142, 'grad_norm': 0.394202321767807, 'learning_rate': 4.4947851128719365e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8111, 'grad_norm': 0.371782124042511, 'learning_rate': 4.301044375248146e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9208, 'grad_norm': 0.39066481590270996, 'learning_rate': 4.1073036376243554e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9383, 'grad_norm': 0.3836340010166168, 'learning_rate': 3.913562900000565e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8322, 'grad_norm': 0.3830423951148987, 'learning_rate': 3.719822162376775e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9649, 'grad_norm': 0.4560186564922333, 'learning_rate': 3.5260814247529845e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.7934, 'grad_norm': 0.38076961040496826, 'learning_rate': 3.332340687129194e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.9129, 'grad_norm': 0.37239810824394226, 'learning_rate': 3.138599949505404e-05, 'epoch': 0.112, 'step': 70}, {'loss': 1.0046, 'grad_norm': 0.34980344772338867, 'learning_rate': 2.9448592118816137e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9732, 'grad_norm': 0.5251571536064148, 'learning_rate': 2.751118474257823e-05, 'epoch': 0.128, 'step': 80}, {'loss': 1.0107, 'grad_norm': 0.4820999205112457, 'learning_rate': 2.557377736634033e-05, 'epoch': 0.136, 'step': 85}, {'loss': 1.0088, 'grad_norm': 0.4037856161594391, 'learning_rate': 2.3636369990102424e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8135, 'grad_norm': 0.3562389016151428, 'learning_rate': 2.169896261386452e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.9075, 'grad_norm': 0.39555442333221436, 'learning_rate': 1.9761555237626617e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9374, 'grad_norm': 0.361033171415329, 'learning_rate': 1.7824147861388715e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8517, 'grad_norm': 0.4266423285007477, 'learning_rate': 1.588674048515081e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8837, 'grad_norm': 0.47825178503990173, 'learning_rate': 1.3949333108912907e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0926, 'grad_norm': 0.4428236782550812, 'learning_rate': 1.2011925732675003e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8624, 'grad_norm': 0.38736677169799805, 'learning_rate': 1.0074518356437098e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.865, 'grad_norm': 0.3862144649028778, 'learning_rate': 8.137110980199196e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.8902, 'grad_norm': 0.4029320478439331, 'learning_rate': 6.1997036039612915e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9638, 'grad_norm': 0.39059343934059143, 'learning_rate': 4.262296227723388e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.8937, 'grad_norm': 0.38955846428871155, 'learning_rate': 2.3248888514854844e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9605, 'grad_norm': 0.3726881146430969, 'learning_rate': 3.874814752475807e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 420.0605, 'train_samples_per_second': 2.857, 'train_steps_per_second': 0.357, 'total_flos': 4944308261511168.0, 'train_loss': 0.9325727272033691, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=22163) Reporting loss: 0.9325727272033691

Trial train_sft_tune_3e6a0a4a completed after 1 iterations at 2025-11-29 16:02:48. Total running time: 8min 18s
+--------------------------------------------------+
| Trial train_sft_tune_3e6a0a4a result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         489.926 |
| time_total_s                             489.926 |
| training_iteration                             1 |
| train_loss                               0.93257 |
+--------------------------------------------------+

100%|██████████| 150/150 [07:00<00:00,  2.80s/it]

Trial train_sft_tune_a367bbff started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_a367bbff config           |
+------------------------------------------------+
| lora_alpha                                  16 |
| lr                                       2e-05 |
| r                                           32 |
+------------------------------------------------+
(train_sft_tune pid=24517) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:03:00. Total running time: 8min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=24517) 2025-11-29 16:03:03.630915: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=24517) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=24517) E0000 00:00:1764432183.672190   24579 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=24517) E0000 00:00:1764432183.684151   24579 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=24517) W0000 00:00:1764432183.713035   24579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=24517) W0000 00:00:1764432183.713089   24579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=24517) W0000 00:00:1764432183.713093   24579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=24517) W0000 00:00:1764432183.713096   24579 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=24517) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=24517) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=24517)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=24517) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=24517) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=24517)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=24517) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=24517) [2025-11-29 16:03:26,547 E 24517 24555] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:03:30. Total running time: 9min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=24517) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=24517) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=24517) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=24517)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=24517) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=24517) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=24517)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=24517) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:04:00. Total running time: 9min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:13<34:26, 13.87s/it]
  1%|▏         | 2/150 [00:16<17:16,  7.01s/it]
  2%|▏         | 3/150 [00:19<12:43,  5.19s/it]
  3%|▎         | 4/150 [00:21<10:23,  4.27s/it]
  3%|▎         | 5/150 [00:24<08:28,  3.51s/it]

(train_sft_tune pid=24517) {'loss': 1.0933, 'grad_norm': 0.23763950169086456, 'learning_rate': 1.6239506034383506e-05, 'epoch': 0.01}

  4%|▍         | 6/150 [00:26<07:45,  3.23s/it]
  5%|▍         | 7/150 [00:29<07:21,  3.08s/it]
  5%|▌         | 8/150 [00:32<07:11,  3.04s/it]
  6%|▌         | 9/150 [00:35<06:58,  2.97s/it]
  7%|▋         | 10/150 [00:38<06:51,  2.94s/it]

(train_sft_tune pid=24517) {'loss': 0.9688, 'grad_norm': 0.19300755858421326, 'learning_rate': 1.97393995762765e-05, 'epoch': 0.02}

  7%|▋         | 11/150 [00:41<06:57,  3.00s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:04:30. Total running time: 10min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

  8%|▊         | 12/150 [00:43<06:35,  2.87s/it]
  9%|▊         | 13/150 [00:47<06:59,  3.06s/it]
  9%|▉         | 14/150 [00:49<06:33,  2.89s/it]
 10%|█         | 15/150 [00:51<05:55,  2.63s/it]

(train_sft_tune pid=24517) {'loss': 1.0763, 'grad_norm': 0.20646624267101288, 'learning_rate': 1.9039420867897904e-05, 'epoch': 0.02}

 11%|█         | 16/150 [00:54<06:07,  2.74s/it]
 11%|█▏        | 17/150 [00:58<06:32,  2.95s/it]
 12%|█▏        | 18/150 [01:00<05:57,  2.71s/it]
 13%|█▎        | 19/150 [01:03<06:00,  2.75s/it]
 13%|█▎        | 20/150 [01:05<05:13,  2.41s/it]

(train_sft_tune pid=24517) {'loss': 1.0064, 'grad_norm': 0.2918797731399536, 'learning_rate': 1.8339442159519307e-05, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:07<05:04,  2.36s/it]
 15%|█▍        | 22/150 [01:09<05:03,  2.37s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:05:00. Total running time: 10min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 15%|█▌        | 23/150 [01:12<05:10,  2.45s/it]
 16%|█▌        | 24/150 [01:15<05:27,  2.60s/it]
 17%|█▋        | 25/150 [01:17<05:30,  2.64s/it]

(train_sft_tune pid=24517) {'loss': 0.9313, 'grad_norm': 0.15858027338981628, 'learning_rate': 1.7639463451140703e-05, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:21<05:53,  2.85s/it]
 18%|█▊        | 27/150 [01:23<05:31,  2.70s/it]
 19%|█▊        | 28/150 [01:26<05:41,  2.80s/it]
 19%|█▉        | 29/150 [01:28<05:08,  2.55s/it]
 20%|██        | 30/150 [01:32<05:48,  2.91s/it]

(train_sft_tune pid=24517) {'loss': 1.0837, 'grad_norm': 0.2339136153459549, 'learning_rate': 1.6939484742762106e-05, 'epoch': 0.05}

 21%|██        | 31/150 [01:35<05:52,  2.96s/it]
 21%|██▏       | 32/150 [01:37<05:20,  2.72s/it]
 22%|██▏       | 33/150 [01:40<05:39,  2.90s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:05:31. Total running time: 11min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 23%|██▎       | 34/150 [01:43<05:27,  2.82s/it]
 23%|██▎       | 35/150 [01:45<05:03,  2.64s/it]

(train_sft_tune pid=24517) {'loss': 0.9588, 'grad_norm': 0.21186697483062744, 'learning_rate': 1.6239506034383506e-05, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:48<04:56,  2.60s/it]
 25%|██▍       | 37/150 [01:51<04:58,  2.64s/it]
 25%|██▌       | 38/150 [01:53<04:47,  2.57s/it]
 26%|██▌       | 39/150 [01:56<04:57,  2.68s/it]
 27%|██▋       | 40/150 [01:59<04:57,  2.70s/it]

(train_sft_tune pid=24517) {'loss': 0.8556, 'grad_norm': 0.20610634982585907, 'learning_rate': 1.5539527326004905e-05, 'epoch': 0.06}

 27%|██▋       | 41/150 [02:01<04:57,  2.73s/it]
 28%|██▊       | 42/150 [02:04<04:58,  2.77s/it]
 29%|██▊       | 43/150 [02:06<04:33,  2.56s/it]
 29%|██▉       | 44/150 [02:09<04:38,  2.63s/it]
 30%|███       | 45/150 [02:11<04:18,  2.46s/it]

(train_sft_tune pid=24517) {'loss': 0.9677, 'grad_norm': 0.19875583052635193, 'learning_rate': 1.4839548617626308e-05, 'epoch': 0.07}
Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:06:01. Total running time: 11min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 31%|███       | 46/150 [02:14<04:33,  2.63s/it]
 31%|███▏      | 47/150 [02:17<04:43,  2.75s/it]
 32%|███▏      | 48/150 [02:21<04:55,  2.90s/it]
 33%|███▎      | 49/150 [02:23<04:34,  2.72s/it]
 33%|███▎      | 50/150 [02:26<04:47,  2.88s/it]

(train_sft_tune pid=24517) {'loss': 0.9802, 'grad_norm': 0.2303195744752884, 'learning_rate': 1.4139569909247706e-05, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:30<05:07,  3.11s/it]
 35%|███▍      | 52/150 [02:32<04:48,  2.95s/it]
 35%|███▌      | 53/150 [02:35<04:40,  2.89s/it]
 36%|███▌      | 54/150 [02:38<04:31,  2.83s/it]
 37%|███▋      | 55/150 [02:40<04:11,  2.65s/it]

(train_sft_tune pid=24517) {'loss': 0.8747, 'grad_norm': 0.20754100382328033, 'learning_rate': 1.3439591200869108e-05, 'epoch': 0.09}
Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:06:31. Total running time: 12min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 37%|███▋      | 56/150 [02:43<04:16,  2.73s/it]
 38%|███▊      | 57/150 [02:45<03:53,  2.51s/it]
 39%|███▊      | 58/150 [02:48<03:56,  2.58s/it]
 39%|███▉      | 59/150 [02:50<04:00,  2.64s/it]
 40%|████      | 60/150 [02:53<03:55,  2.62s/it]

(train_sft_tune pid=24517) {'loss': 1.0066, 'grad_norm': 0.2321195900440216, 'learning_rate': 1.273961249249051e-05, 'epoch': 0.1}

 41%|████      | 61/150 [02:56<04:01,  2.72s/it]
 41%|████▏     | 62/150 [03:00<04:26,  3.03s/it]
 42%|████▏     | 63/150 [03:03<04:29,  3.10s/it]
 43%|████▎     | 64/150 [03:07<04:38,  3.24s/it]
 43%|████▎     | 65/150 [03:09<04:08,  2.93s/it]

(train_sft_tune pid=24517) {'loss': 0.8338, 'grad_norm': 0.20804272592067719, 'learning_rate': 1.2039633784111909e-05, 'epoch': 0.1}

 44%|████▍     | 66/150 [03:12<04:07,  2.95s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:07:01. Total running time: 12min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 45%|████▍     | 67/150 [03:14<03:48,  2.75s/it]
 45%|████▌     | 68/150 [03:16<03:30,  2.57s/it]
 46%|████▌     | 69/150 [03:18<03:16,  2.43s/it]
 47%|████▋     | 70/150 [03:22<03:36,  2.71s/it]

(train_sft_tune pid=24517) {'loss': 0.9551, 'grad_norm': 0.19932682812213898, 'learning_rate': 1.133965507573331e-05, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:25<03:47,  2.87s/it]
 48%|████▊     | 72/150 [03:27<03:33,  2.74s/it]
 49%|████▊     | 73/150 [03:30<03:35,  2.80s/it]
 49%|████▉     | 74/150 [03:33<03:28,  2.75s/it]
 50%|█████     | 75/150 [03:36<03:28,  2.77s/it]

(train_sft_tune pid=24517) {'loss': 1.039, 'grad_norm': 0.19334594905376434, 'learning_rate': 1.0639676367354711e-05, 'epoch': 0.12}

 51%|█████     | 76/150 [03:38<03:24,  2.76s/it]
 51%|█████▏    | 77/150 [03:41<03:19,  2.74s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:07:31. Total running time: 13min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 52%|█████▏    | 78/150 [03:43<03:04,  2.57s/it]
 53%|█████▎    | 79/150 [03:46<02:58,  2.52s/it]
 53%|█████▎    | 80/150 [03:48<03:00,  2.58s/it]

(train_sft_tune pid=24517) {'loss': 1.0105, 'grad_norm': 0.28091931343078613, 'learning_rate': 9.939697658976111e-06, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:51<03:04,  2.67s/it]
 55%|█████▍    | 82/150 [03:54<03:04,  2.72s/it]
 55%|█████▌    | 83/150 [03:57<02:58,  2.66s/it]
 56%|█████▌    | 84/150 [03:59<02:49,  2.58s/it]
 57%|█████▋    | 85/150 [04:02<02:54,  2.68s/it]

(train_sft_tune pid=24517) {'loss': 1.049, 'grad_norm': 0.24736376106739044, 'learning_rate': 9.239718950597512e-06, 'epoch': 0.14}

 57%|█████▋    | 86/150 [04:04<02:41,  2.52s/it]
 58%|█████▊    | 87/150 [04:07<02:50,  2.71s/it]
 59%|█████▊    | 88/150 [04:10<02:52,  2.79s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:08:01. Total running time: 13min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 59%|█████▉    | 89/150 [04:14<03:00,  2.95s/it]
 60%|██████    | 90/150 [04:15<02:37,  2.62s/it]

(train_sft_tune pid=24517) {'loss': 1.0399, 'grad_norm': 0.2099483609199524, 'learning_rate': 8.539740242218914e-06, 'epoch': 0.14}

 61%|██████    | 91/150 [04:17<02:25,  2.46s/it]
 61%|██████▏   | 92/150 [04:20<02:26,  2.52s/it]
 62%|██████▏   | 93/150 [04:23<02:24,  2.54s/it]
 63%|██████▎   | 94/150 [04:25<02:18,  2.47s/it]
 63%|██████▎   | 95/150 [04:28<02:22,  2.58s/it]

(train_sft_tune pid=24517) {'loss': 0.8484, 'grad_norm': 0.21526454389095306, 'learning_rate': 7.839761533840313e-06, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:30<02:15,  2.50s/it]
 65%|██████▍   | 97/150 [04:33<02:21,  2.67s/it]
 65%|██████▌   | 98/150 [04:36<02:24,  2.79s/it]
 66%|██████▌   | 99/150 [04:40<02:29,  2.94s/it]
 67%|██████▋   | 100/150 [04:42<02:12,  2.66s/it]

(train_sft_tune pid=24517) {'loss': 0.9406, 'grad_norm': 0.21861688792705536, 'learning_rate': 7.139782825461714e-06, 'epoch': 0.16}
Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:08:31. Total running time: 14min 1s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 67%|██████▋   | 101/150 [04:44<02:06,  2.57s/it]
 68%|██████▊   | 102/150 [04:46<01:59,  2.49s/it]
 69%|██████▊   | 103/150 [04:49<02:01,  2.58s/it]
 69%|██████▉   | 104/150 [04:52<02:01,  2.64s/it]
 70%|███████   | 105/150 [04:54<01:58,  2.64s/it]

(train_sft_tune pid=24517) {'loss': 0.9719, 'grad_norm': 0.1936599463224411, 'learning_rate': 6.439804117083115e-06, 'epoch': 0.17}

 71%|███████   | 106/150 [04:57<01:53,  2.57s/it]
 71%|███████▏  | 107/150 [05:00<01:57,  2.72s/it]
 72%|███████▏  | 108/150 [05:03<02:01,  2.90s/it]
 73%|███████▎  | 109/150 [05:06<01:56,  2.83s/it]
 73%|███████▎  | 110/150 [05:08<01:43,  2.59s/it]

(train_sft_tune pid=24517) {'loss': 0.8927, 'grad_norm': 0.22548808157444, 'learning_rate': 5.739825408704516e-06, 'epoch': 0.18}

 74%|███████▍  | 111/150 [05:11<01:50,  2.82s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:09:01. Total running time: 14min 31s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 75%|███████▍  | 112/150 [05:15<01:52,  2.95s/it]
 75%|███████▌  | 113/150 [05:17<01:40,  2.72s/it]
 76%|███████▌  | 114/150 [05:20<01:40,  2.80s/it]
 77%|███████▋  | 115/150 [05:22<01:31,  2.61s/it]

(train_sft_tune pid=24517) {'loss': 0.9256, 'grad_norm': 0.24849632382392883, 'learning_rate': 5.039846700325915e-06, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:24<01:27,  2.56s/it]
 78%|███████▊  | 117/150 [05:28<01:31,  2.77s/it]
 79%|███████▊  | 118/150 [05:31<01:32,  2.90s/it]
 79%|███████▉  | 119/150 [05:34<01:30,  2.93s/it]
 80%|████████  | 120/150 [05:36<01:22,  2.73s/it]

(train_sft_tune pid=24517) {'loss': 1.1336, 'grad_norm': 0.2458629012107849, 'learning_rate': 4.339867991947317e-06, 'epoch': 0.19}

 81%|████████  | 121/150 [05:40<01:25,  2.94s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:09:31. Total running time: 15min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 81%|████████▏ | 122/150 [05:43<01:25,  3.04s/it]
 82%|████████▏ | 123/150 [05:45<01:18,  2.89s/it]
 83%|████████▎ | 124/150 [05:49<01:18,  3.03s/it]
 83%|████████▎ | 125/150 [05:51<01:12,  2.90s/it]

(train_sft_tune pid=24517) {'loss': 0.8969, 'grad_norm': 0.22501182556152344, 'learning_rate': 3.639889283568717e-06, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:54<01:10,  2.94s/it]
 85%|████████▍ | 127/150 [05:57<01:07,  2.93s/it]
 85%|████████▌ | 128/150 [06:00<01:01,  2.82s/it]
 86%|████████▌ | 129/150 [06:01<00:51,  2.47s/it]
 87%|████████▋ | 130/150 [06:04<00:51,  2.57s/it]

(train_sft_tune pid=24517) {'loss': 0.9, 'grad_norm': 0.22775739431381226, 'learning_rate': 2.9399105751901177e-06, 'epoch': 0.21}

 87%|████████▋ | 131/150 [06:07<00:48,  2.58s/it]
 88%|████████▊ | 132/150 [06:10<00:48,  2.68s/it]
 89%|████████▊ | 133/150 [06:12<00:42,  2.52s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:10:01. Total running time: 15min 32s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 89%|████████▉ | 134/150 [06:16<00:46,  2.89s/it]
 90%|█████████ | 135/150 [06:19<00:42,  2.87s/it]

(train_sft_tune pid=24517) {'loss': 0.921, 'grad_norm': 0.2177751511335373, 'learning_rate': 2.2399318668115182e-06, 'epoch': 0.22}

 91%|█████████ | 136/150 [06:22<00:41,  2.95s/it]
 91%|█████████▏| 137/150 [06:24<00:34,  2.66s/it]
 92%|█████████▏| 138/150 [06:26<00:31,  2.65s/it]
 93%|█████████▎| 139/150 [06:29<00:28,  2.62s/it]
 93%|█████████▎| 140/150 [06:31<00:25,  2.50s/it]

(train_sft_tune pid=24517) {'loss': 0.9931, 'grad_norm': 0.21725893020629883, 'learning_rate': 1.5399531584329187e-06, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:34<00:23,  2.57s/it]
 95%|█████████▍| 142/150 [06:36<00:20,  2.61s/it]
 95%|█████████▌| 143/150 [06:39<00:18,  2.68s/it]

Trial status: 1 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:10:31. Total running time: 16min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_a367bbff   RUNNING      2.02994e-05    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_1ee09412   PENDING      2.60244e-05    16             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 96%|█████████▌| 144/150 [06:43<00:17,  2.85s/it]
 97%|█████████▋| 145/150 [06:45<00:13,  2.76s/it]

(train_sft_tune pid=24517) {'loss': 0.9282, 'grad_norm': 0.22770918905735016, 'learning_rate': 8.399744500543192e-07, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:48<00:10,  2.70s/it]
 98%|█████████▊| 147/150 [06:50<00:08,  2.68s/it]
 99%|█████████▊| 148/150 [06:53<00:05,  2.73s/it]
 99%|█████████▉| 149/150 [06:56<00:02,  2.64s/it]
100%|██████████| 150/150 [06:58<00:00,  2.68s/it]

(train_sft_tune pid=24517) {'loss': 1.0012, 'grad_norm': 0.21284253895282745, 'learning_rate': 1.399957416757199e-07, 'epoch': 0.24}

Trial train_sft_tune_a367bbff completed after 1 iterations at 2025-11-29 16:10:48. Total running time: 16min 19s
+--------------------------------------------------+
| Trial train_sft_tune_a367bbff result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         470.899 |
| time_total_s                             470.899 |
| training_iteration                             1 |
| train_loss                               0.96946 |
+--------------------------------------------------+
(train_sft_tune pid=24517) {'train_runtime': 420.1005, 'train_samples_per_second': 2.856, 'train_steps_per_second': 0.357, 'train_loss': 0.9694574673970541, 'epoch': 0.24}
(train_sft_tune pid=24517) history of tuning  [{'loss': 1.0933, 'grad_norm': 0.23763950169086456, 'learning_rate': 1.6239506034383506e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9688, 'grad_norm': 0.19300755858421326, 'learning_rate': 1.97393995762765e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0763, 'grad_norm': 0.20646624267101288, 'learning_rate': 1.9039420867897904e-05, 'epoch': 0.024, 'step': 15}, {'loss': 1.0064, 'grad_norm': 0.2918797731399536, 'learning_rate': 1.8339442159519307e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.9313, 'grad_norm': 0.15858027338981628, 'learning_rate': 1.7639463451140703e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0837, 'grad_norm': 0.2339136153459549, 'learning_rate': 1.6939484742762106e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9588, 'grad_norm': 0.21186697483062744, 'learning_rate': 1.6239506034383506e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8556, 'grad_norm': 0.20610634982585907, 'learning_rate': 1.5539527326004905e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9677, 'grad_norm': 0.19875583052635193, 'learning_rate': 1.4839548617626308e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9802, 'grad_norm': 0.2303195744752884, 'learning_rate': 1.4139569909247706e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8747, 'grad_norm': 0.20754100382328033, 'learning_rate': 1.3439591200869108e-05, 'epoch': 0.088, 'step': 55}, {'loss': 1.0066, 'grad_norm': 0.2321195900440216, 'learning_rate': 1.273961249249051e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.8338, 'grad_norm': 0.20804272592067719, 'learning_rate': 1.2039633784111909e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.9551, 'grad_norm': 0.19932682812213898, 'learning_rate': 1.133965507573331e-05, 'epoch': 0.112, 'step': 70}, {'loss': 1.039, 'grad_norm': 0.19334594905376434, 'learning_rate': 1.0639676367354711e-05, 'epoch': 0.12, 'step': 75}, {'loss': 1.0105, 'grad_norm': 0.28091931343078613, 'learning_rate': 9.939697658976111e-06, 'epoch': 0.128, 'step': 80}, {'loss': 1.049, 'grad_norm': 0.24736376106739044, 'learning_rate': 9.239718950597512e-06, 'epoch': 0.136, 'step': 85}, {'loss': 1.0399, 'grad_norm': 0.2099483609199524, 'learning_rate': 8.539740242218914e-06, 'epoch': 0.144, 'step': 90}, {'loss': 0.8484, 'grad_norm': 0.21526454389095306, 'learning_rate': 7.839761533840313e-06, 'epoch': 0.152, 'step': 95}, {'loss': 0.9406, 'grad_norm': 0.21861688792705536, 'learning_rate': 7.139782825461714e-06, 'epoch': 0.16, 'step': 100}, {'loss': 0.9719, 'grad_norm': 0.1936599463224411, 'learning_rate': 6.439804117083115e-06, 'epoch': 0.168, 'step': 105}, {'loss': 0.8927, 'grad_norm': 0.22548808157444, 'learning_rate': 5.739825408704516e-06, 'epoch': 0.176, 'step': 110}, {'loss': 0.9256, 'grad_norm': 0.24849632382392883, 'learning_rate': 5.039846700325915e-06, 'epoch': 0.184, 'step': 115}, {'loss': 1.1336, 'grad_norm': 0.2458629012107849, 'learning_rate': 4.339867991947317e-06, 'epoch': 0.192, 'step': 120}, {'loss': 0.8969, 'grad_norm': 0.22501182556152344, 'learning_rate': 3.639889283568717e-06, 'epoch': 0.2, 'step': 125}, {'loss': 0.9, 'grad_norm': 0.22775739431381226, 'learning_rate': 2.9399105751901177e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.921, 'grad_norm': 0.2177751511335373, 'learning_rate': 2.2399318668115182e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9931, 'grad_norm': 0.21725893020629883, 'learning_rate': 1.5399531584329187e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.9282, 'grad_norm': 0.22770918905735016, 'learning_rate': 8.399744500543192e-07, 'epoch': 0.232, 'step': 145}, {'loss': 1.0012, 'grad_norm': 0.21284253895282745, 'learning_rate': 1.399957416757199e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 420.1005, 'train_samples_per_second': 2.856, 'train_steps_per_second': 0.357, 'total_flos': 4944308261511168.0, 'train_loss': 0.9694574673970541, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=24517) Reporting loss: 0.9694574673970541

100%|██████████| 150/150 [07:00<00:00,  2.80s/it]

Trial train_sft_tune_1ee09412 started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_1ee09412 config           |
+------------------------------------------------+
| lora_alpha                                  16 |
| lr                                       3e-05 |
| r                                           16 |
+------------------------------------------------+
(train_sft_tune pid=26717) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:11:01. Total running time: 16min 32s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=26717) 2025-11-29 16:11:03.714357: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=26717) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=26717) E0000 00:00:1764432663.736627   26778 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=26717) E0000 00:00:1764432663.744207   26778 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=26717) W0000 00:00:1764432663.760863   26778 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=26717) W0000 00:00:1764432663.760894   26778 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=26717) W0000 00:00:1764432663.760897   26778 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=26717) W0000 00:00:1764432663.760898   26778 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=26717) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=26717) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=26717)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=26717) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=26717) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=26717)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=26717) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=26717) [2025-11-29 16:11:27,046 E 26717 26754] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:11:31. Total running time: 17min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=26717) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=26717) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=26717) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=26717)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=26717) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=26717) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=26717)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=26717) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:13<33:23, 13.45s/it]
  1%|▏         | 2/150 [00:15<16:47,  6.81s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:12:01. Total running time: 17min 32s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

  2%|▏         | 3/150 [00:18<12:23,  5.06s/it]
  3%|▎         | 4/150 [00:21<10:10,  4.18s/it]

(train_sft_tune pid=26717) {'loss': 1.0932, 'grad_norm': 0.33621808886528015, 'learning_rate': 2.081954470404995e-05, 'epoch': 0.01}

  3%|▎         | 5/150 [00:23<08:21,  3.46s/it]
  4%|▍         | 6/150 [00:26<07:39,  3.19s/it]
  5%|▍         | 7/150 [00:29<07:16,  3.05s/it]
  5%|▌         | 8/150 [00:31<07:04,  2.99s/it]
  6%|▌         | 9/150 [00:34<06:53,  2.93s/it]

(train_sft_tune pid=26717) {'loss': 0.9671, 'grad_norm': 0.270814448595047, 'learning_rate': 2.5306515545440026e-05, 'epoch': 0.02}

  7%|▋         | 10/150 [00:37<06:46,  2.90s/it]
  7%|▋         | 11/150 [00:40<06:51,  2.96s/it]
  8%|▊         | 12/150 [00:43<06:29,  2.82s/it]
  9%|▊         | 13/150 [00:46<06:52,  3.01s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:12:32. Total running time: 18min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

  9%|▉         | 14/150 [00:49<06:27,  2.85s/it]

(train_sft_tune pid=26717) {'loss': 1.0724, 'grad_norm': 0.28848493099212646, 'learning_rate': 2.440912137716201e-05, 'epoch': 0.02}

 10%|█         | 15/150 [00:51<05:50,  2.60s/it]
 11%|█         | 16/150 [00:54<06:03,  2.71s/it]
 11%|█▏        | 17/150 [00:57<06:26,  2.90s/it]
 12%|█▏        | 18/150 [00:59<05:53,  2.68s/it]
 13%|█▎        | 19/150 [01:02<06:00,  2.75s/it]

(train_sft_tune pid=26717) {'loss': 1.0001, 'grad_norm': 0.4061504900455475, 'learning_rate': 2.3511727208883998e-05, 'epoch': 0.03}

 13%|█▎        | 20/150 [01:04<05:12,  2.41s/it]
 14%|█▍        | 21/150 [01:06<05:02,  2.34s/it]
 15%|█▍        | 22/150 [01:08<04:59,  2.34s/it]
 15%|█▌        | 23/150 [01:11<05:05,  2.41s/it]
 16%|█▌        | 24/150 [01:14<05:24,  2.57s/it]

(train_sft_tune pid=26717) {'loss': 0.9254, 'grad_norm': 0.22694145143032074, 'learning_rate': 2.261433304060598e-05, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:16<05:25,  2.61s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:13:02. Total running time: 18min 32s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 17%|█▋        | 26/150 [01:20<05:48,  2.81s/it]
 18%|█▊        | 27/150 [01:22<05:23,  2.63s/it]
 19%|█▊        | 28/150 [01:25<05:35,  2.75s/it]
 19%|█▉        | 29/150 [01:27<05:05,  2.53s/it]

(train_sft_tune pid=26717) {'loss': 1.0756, 'grad_norm': 0.30895620584487915, 'learning_rate': 2.1716938872327966e-05, 'epoch': 0.05}

 20%|██        | 30/150 [01:31<05:44,  2.87s/it]
 21%|██        | 31/150 [01:34<05:46,  2.92s/it]
 21%|██▏       | 32/150 [01:36<05:12,  2.65s/it]
 22%|██▏       | 33/150 [01:39<05:33,  2.85s/it]
 23%|██▎       | 34/150 [01:42<05:23,  2.79s/it]

(train_sft_tune pid=26717) {'loss': 0.9501, 'grad_norm': 0.2917940616607666, 'learning_rate': 2.081954470404995e-05, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:44<05:00,  2.61s/it]
 24%|██▍       | 36/150 [01:46<04:52,  2.56s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:13:32. Total running time: 19min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 25%|██▍       | 37/150 [01:49<04:53,  2.59s/it]
 25%|██▌       | 38/150 [01:51<04:46,  2.55s/it]
 26%|██▌       | 39/150 [01:54<04:56,  2.67s/it]

(train_sft_tune pid=26717) {'loss': 0.8484, 'grad_norm': 0.2977411150932312, 'learning_rate': 1.9922150535771934e-05, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:57<04:55,  2.68s/it]
 27%|██▋       | 41/150 [02:00<04:53,  2.70s/it]
 28%|██▊       | 42/150 [02:02<04:54,  2.73s/it]
 29%|██▊       | 43/150 [02:05<04:33,  2.55s/it]
 29%|██▉       | 44/150 [02:07<04:38,  2.62s/it]

(train_sft_tune pid=26717) {'loss': 0.9605, 'grad_norm': 0.28839707374572754, 'learning_rate': 1.9024756367493922e-05, 'epoch': 0.07}

 30%|███       | 45/150 [02:09<04:16,  2.45s/it]
 31%|███       | 46/150 [02:12<04:30,  2.60s/it]
 31%|███▏      | 47/150 [02:15<04:40,  2.72s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:14:02. Total running time: 19min 32s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 32%|███▏      | 48/150 [02:19<04:52,  2.87s/it]
 33%|███▎      | 49/150 [02:21<04:31,  2.68s/it]

(train_sft_tune pid=26717) {'loss': 0.9711, 'grad_norm': 0.32235172390937805, 'learning_rate': 1.8127362199215903e-05, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:24<04:43,  2.84s/it]
 34%|███▍      | 51/150 [02:28<05:02,  3.06s/it]
 35%|███▍      | 52/150 [02:30<04:47,  2.93s/it]
 35%|███▌      | 53/150 [02:33<04:40,  2.89s/it]
 36%|███▌      | 54/150 [02:36<04:29,  2.81s/it]

(train_sft_tune pid=26717) {'loss': 0.8651, 'grad_norm': 0.2924260199069977, 'learning_rate': 1.722996803093789e-05, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:38<04:07,  2.60s/it]
 37%|███▋      | 56/150 [02:41<04:11,  2.68s/it]
 38%|███▊      | 57/150 [02:43<03:50,  2.48s/it]
 39%|███▊      | 58/150 [02:45<03:56,  2.57s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:14:32. Total running time: 20min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 39%|███▉      | 59/150 [02:48<03:58,  2.62s/it]

(train_sft_tune pid=26717) {'loss': 0.9989, 'grad_norm': 0.3342273533344269, 'learning_rate': 1.6332573862659875e-05, 'epoch': 0.1}

 40%|████      | 60/150 [02:51<03:51,  2.57s/it]
 41%|████      | 61/150 [02:54<03:56,  2.66s/it]
 41%|████▏     | 62/150 [02:57<04:22,  2.99s/it]
 42%|████▏     | 63/150 [03:00<04:25,  3.06s/it]
 43%|████▎     | 64/150 [03:04<04:34,  3.19s/it]

(train_sft_tune pid=26717) {'loss': 0.8253, 'grad_norm': 0.2961249053478241, 'learning_rate': 1.543517969438186e-05, 'epoch': 0.1}

 43%|████▎     | 65/150 [03:06<04:04,  2.87s/it]
 44%|████▍     | 66/150 [03:09<04:04,  2.91s/it]
 45%|████▍     | 67/150 [03:11<03:46,  2.73s/it]
 45%|████▌     | 68/150 [03:14<03:29,  2.56s/it]
 46%|████▌     | 69/150 [03:16<03:14,  2.40s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:15:02. Total running time: 20min 32s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=26717) {'loss': 0.9467, 'grad_norm': 0.2859860956668854, 'learning_rate': 1.4537785526103845e-05, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:19<03:33,  2.67s/it]
 47%|████▋     | 71/150 [03:22<03:44,  2.85s/it]
 48%|████▊     | 72/150 [03:25<03:32,  2.72s/it]
 49%|████▊     | 73/150 [03:27<03:33,  2.77s/it]
 49%|████▉     | 74/150 [03:30<03:24,  2.69s/it]

(train_sft_tune pid=26717) {'loss': 1.0315, 'grad_norm': 0.2780604958534241, 'learning_rate': 1.364039135782583e-05, 'epoch': 0.12}

 50%|█████     | 75/150 [03:33<03:24,  2.72s/it]
 51%|█████     | 76/150 [03:36<03:22,  2.73s/it]
 51%|█████▏    | 77/150 [03:38<03:17,  2.71s/it]
 52%|█████▏    | 78/150 [03:40<03:02,  2.54s/it]
 53%|█████▎    | 79/150 [03:43<02:54,  2.46s/it]

(train_sft_tune pid=26717) {'loss': 1.0024, 'grad_norm': 0.4131588935852051, 'learning_rate': 1.2742997189547813e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:45<02:57,  2.53s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:15:32. Total running time: 21min 2s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 54%|█████▍    | 81/150 [03:48<03:02,  2.64s/it]
 55%|█████▍    | 82/150 [03:51<03:04,  2.72s/it]
 55%|█████▌    | 83/150 [03:54<02:56,  2.64s/it]
 56%|█████▌    | 84/150 [03:56<02:47,  2.53s/it]

(train_sft_tune pid=26717) {'loss': 1.0415, 'grad_norm': 0.35826265811920166, 'learning_rate': 1.1845603021269799e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:59<02:52,  2.65s/it]
 57%|█████▋    | 86/150 [04:01<02:41,  2.52s/it]
 58%|█████▊    | 87/150 [04:04<02:49,  2.70s/it]
 59%|█████▊    | 88/150 [04:07<02:50,  2.76s/it]
 59%|█████▉    | 89/150 [04:11<03:12,  3.16s/it]

(train_sft_tune pid=26717) {'loss': 1.033, 'grad_norm': 0.3063886761665344, 'learning_rate': 1.0948208852991785e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [04:13<02:46,  2.78s/it]
 61%|██████    | 91/150 [04:15<02:32,  2.59s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:16:02. Total running time: 21min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 61%|██████▏   | 92/150 [04:18<02:30,  2.60s/it]
 62%|██████▏   | 93/150 [04:20<02:26,  2.57s/it]
 63%|██████▎   | 94/150 [04:22<02:17,  2.46s/it]
 63%|██████▎   | 95/150 [04:25<02:21,  2.58s/it]
 63%|██████▎   | 95/150 [04:25<02:21,  2.58s/it]

(train_sft_tune pid=26717) {'loss': 0.8404, 'grad_norm': 0.30240124464035034, 'learning_rate': 1.0050814684713769e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:28<02:16,  2.52s/it]
 65%|██████▍   | 97/150 [04:31<02:21,  2.68s/it]
 65%|██████▌   | 98/150 [04:34<02:24,  2.77s/it]
 66%|██████▌   | 99/150 [04:37<02:28,  2.90s/it]

(train_sft_tune pid=26717) {'loss': 0.933, 'grad_norm': 0.3149636685848236, 'learning_rate': 9.153420516435753e-06, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:39<02:11,  2.64s/it]
 67%|██████▋   | 101/150 [04:41<02:05,  2.57s/it]
 68%|██████▊   | 102/150 [04:44<01:59,  2.48s/it]
 69%|██████▊   | 103/150 [04:46<02:00,  2.55s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:16:32. Total running time: 22min 3s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 69%|██████▉   | 104/150 [04:49<01:59,  2.60s/it]

(train_sft_tune pid=26717) {'loss': 0.9642, 'grad_norm': 0.2836885154247284, 'learning_rate': 8.25602634815774e-06, 'epoch': 0.17}

 70%|███████   | 105/150 [04:52<01:57,  2.60s/it]
 71%|███████   | 106/150 [04:54<01:52,  2.55s/it]
 71%|███████▏  | 107/150 [04:57<01:56,  2.70s/it]
 72%|███████▏  | 108/150 [05:00<02:00,  2.86s/it]
 73%|███████▎  | 109/150 [05:03<01:55,  2.81s/it]

(train_sft_tune pid=26717) {'loss': 0.8843, 'grad_norm': 0.3277634382247925, 'learning_rate': 7.358632179879724e-06, 'epoch': 0.18}

 73%|███████▎  | 110/150 [05:05<01:43,  2.59s/it]
 74%|███████▍  | 111/150 [05:09<01:50,  2.82s/it]
 75%|███████▍  | 112/150 [05:12<01:51,  2.94s/it]
 75%|███████▌  | 113/150 [05:14<01:39,  2.68s/it]
 76%|███████▌  | 114/150 [05:17<01:39,  2.77s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:17:02. Total running time: 22min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=26717) {'loss': 0.917, 'grad_norm': 0.35875967144966125, 'learning_rate': 6.4612380116017085e-06, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:19<01:31,  2.61s/it]
 77%|███████▋  | 116/150 [05:21<01:27,  2.56s/it]
 78%|███████▊  | 117/150 [05:25<01:31,  2.76s/it]
 79%|███████▊  | 118/150 [05:28<01:31,  2.87s/it]
 79%|███████▉  | 119/150 [05:31<01:30,  2.92s/it]

(train_sft_tune pid=26717) {'loss': 1.1247, 'grad_norm': 0.35528564453125, 'learning_rate': 5.5638438433236935e-06, 'epoch': 0.19}

 80%|████████  | 120/150 [05:33<01:22,  2.74s/it]
 81%|████████  | 121/150 [05:37<01:24,  2.93s/it]
 81%|████████▏ | 122/150 [05:40<01:24,  3.02s/it]
 82%|████████▏ | 123/150 [05:42<01:17,  2.88s/it]
 83%|████████▎ | 124/150 [05:46<01:18,  3.02s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:17:32. Total running time: 23min 3s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=26717) {'loss': 0.8892, 'grad_norm': 0.3274576663970947, 'learning_rate': 4.666449675045679e-06, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:48<01:12,  2.90s/it]
 84%|████████▍ | 126/150 [05:51<01:09,  2.91s/it]
 85%|████████▍ | 127/150 [05:54<01:06,  2.89s/it]
 85%|████████▌ | 128/150 [05:57<01:01,  2.79s/it]
 86%|████████▌ | 129/150 [05:59<00:52,  2.52s/it]

(train_sft_tune pid=26717) {'loss': 0.8915, 'grad_norm': 0.3222416341304779, 'learning_rate': 3.7690555067676636e-06, 'epoch': 0.21}

 87%|████████▋ | 130/150 [06:01<00:51,  2.60s/it]
 87%|████████▋ | 131/150 [06:04<00:48,  2.57s/it]
 88%|████████▊ | 132/150 [06:07<00:47,  2.66s/it]
 89%|████████▊ | 133/150 [06:09<00:42,  2.51s/it]
 89%|████████▉ | 134/150 [06:13<00:45,  2.87s/it]

(train_sft_tune pid=26717) {'loss': 0.9135, 'grad_norm': 0.3136448264122009, 'learning_rate': 2.8716613384896483e-06, 'epoch': 0.22}

 90%|█████████ | 135/150 [06:15<00:42,  2.83s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:18:02. Total running time: 23min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 91%|█████████ | 136/150 [06:18<00:40,  2.91s/it]
 91%|█████████▏| 137/150 [06:20<00:33,  2.61s/it]
 92%|█████████▏| 138/150 [06:23<00:31,  2.61s/it]
 93%|█████████▎| 139/150 [06:25<00:28,  2.58s/it]

(train_sft_tune pid=26717) {'loss': 0.9867, 'grad_norm': 0.3072841167449951, 'learning_rate': 1.9742671702116333e-06, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:28<00:24,  2.46s/it]
 94%|█████████▍| 141/150 [06:30<00:22,  2.51s/it]
 95%|█████████▍| 142/150 [06:33<00:20,  2.56s/it]
 95%|█████████▌| 143/150 [06:36<00:18,  2.64s/it]
 96%|█████████▌| 144/150 [06:39<00:16,  2.82s/it]

(train_sft_tune pid=26717) {'loss': 0.9201, 'grad_norm': 0.3274863064289093, 'learning_rate': 1.0768730019336182e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:41<00:13,  2.72s/it]
 97%|█████████▋| 146/150 [06:44<00:10,  2.64s/it]
 98%|█████████▊| 147/150 [06:46<00:07,  2.62s/it]

Trial status: 2 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:18:32. Total running time: 24min 3s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1ee09412   RUNNING      2.60244e-05    16             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_e9b87c19   PENDING      3.50943e-05     8             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 99%|█████████▊| 148/150 [06:49<00:05,  2.70s/it]
 99%|█████████▉| 149/150 [06:52<00:02,  2.63s/it]

(train_sft_tune pid=26717) {'loss': 0.9926, 'grad_norm': 0.3072725236415863, 'learning_rate': 1.7947883365560302e-07, 'epoch': 0.24}

100%|██████████| 150/150 [06:55<00:00,  2.66s/it]

Trial train_sft_tune_1ee09412 completed after 1 iterations at 2025-11-29 16:18:40. Total running time: 24min 10s
+--------------------------------------------------+
| Trial train_sft_tune_1ee09412 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         462.288 |
| time_total_s                             462.288 |
| training_iteration                             1 |
| train_loss                               0.96219 |
+--------------------------------------------------+
(train_sft_tune pid=26717) {'train_runtime': 416.0041, 'train_samples_per_second': 2.885, 'train_steps_per_second': 0.361, 'train_loss': 0.9621886920928955, 'epoch': 0.24}
(train_sft_tune pid=26717) history of tuning  [{'loss': 1.0932, 'grad_norm': 0.33621808886528015, 'learning_rate': 2.081954470404995e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9671, 'grad_norm': 0.270814448595047, 'learning_rate': 2.5306515545440026e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0724, 'grad_norm': 0.28848493099212646, 'learning_rate': 2.440912137716201e-05, 'epoch': 0.024, 'step': 15}, {'loss': 1.0001, 'grad_norm': 0.4061504900455475, 'learning_rate': 2.3511727208883998e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.9254, 'grad_norm': 0.22694145143032074, 'learning_rate': 2.261433304060598e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0756, 'grad_norm': 0.30895620584487915, 'learning_rate': 2.1716938872327966e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9501, 'grad_norm': 0.2917940616607666, 'learning_rate': 2.081954470404995e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8484, 'grad_norm': 0.2977411150932312, 'learning_rate': 1.9922150535771934e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9605, 'grad_norm': 0.28839707374572754, 'learning_rate': 1.9024756367493922e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9711, 'grad_norm': 0.32235172390937805, 'learning_rate': 1.8127362199215903e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8651, 'grad_norm': 0.2924260199069977, 'learning_rate': 1.722996803093789e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9989, 'grad_norm': 0.3342273533344269, 'learning_rate': 1.6332573862659875e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.8253, 'grad_norm': 0.2961249053478241, 'learning_rate': 1.543517969438186e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.9467, 'grad_norm': 0.2859860956668854, 'learning_rate': 1.4537785526103845e-05, 'epoch': 0.112, 'step': 70}, {'loss': 1.0315, 'grad_norm': 0.2780604958534241, 'learning_rate': 1.364039135782583e-05, 'epoch': 0.12, 'step': 75}, {'loss': 1.0024, 'grad_norm': 0.4131588935852051, 'learning_rate': 1.2742997189547813e-05, 'epoch': 0.128, 'step': 80}, {'loss': 1.0415, 'grad_norm': 0.35826265811920166, 'learning_rate': 1.1845603021269799e-05, 'epoch': 0.136, 'step': 85}, {'loss': 1.033, 'grad_norm': 0.3063886761665344, 'learning_rate': 1.0948208852991785e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8404, 'grad_norm': 0.30240124464035034, 'learning_rate': 1.0050814684713769e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.933, 'grad_norm': 0.3149636685848236, 'learning_rate': 9.153420516435753e-06, 'epoch': 0.16, 'step': 100}, {'loss': 0.9642, 'grad_norm': 0.2836885154247284, 'learning_rate': 8.25602634815774e-06, 'epoch': 0.168, 'step': 105}, {'loss': 0.8843, 'grad_norm': 0.3277634382247925, 'learning_rate': 7.358632179879724e-06, 'epoch': 0.176, 'step': 110}, {'loss': 0.917, 'grad_norm': 0.35875967144966125, 'learning_rate': 6.4612380116017085e-06, 'epoch': 0.184, 'step': 115}, {'loss': 1.1247, 'grad_norm': 0.35528564453125, 'learning_rate': 5.5638438433236935e-06, 'epoch': 0.192, 'step': 120}, {'loss': 0.8892, 'grad_norm': 0.3274576663970947, 'learning_rate': 4.666449675045679e-06, 'epoch': 0.2, 'step': 125}, {'loss': 0.8915, 'grad_norm': 0.3222416341304779, 'learning_rate': 3.7690555067676636e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.9135, 'grad_norm': 0.3136448264122009, 'learning_rate': 2.8716613384896483e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9867, 'grad_norm': 0.3072841167449951, 'learning_rate': 1.9742671702116333e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.9201, 'grad_norm': 0.3274863064289093, 'learning_rate': 1.0768730019336182e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9926, 'grad_norm': 0.3072725236415863, 'learning_rate': 1.7947883365560302e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 416.0041, 'train_samples_per_second': 2.885, 'train_steps_per_second': 0.361, 'total_flos': 4888333847519232.0, 'train_loss': 0.9621886920928955, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=26717) Reporting loss: 0.9621886920928955

100%|██████████| 150/150 [06:56<00:00,  2.77s/it]

Trial train_sft_tune_e9b87c19 started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_e9b87c19 config           |
+------------------------------------------------+
| lora_alpha                                  16 |
| lr                                       4e-05 |
| r                                            8 |
+------------------------------------------------+
(train_sft_tune pid=28875) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=28875) 2025-11-29 16:18:55.658314: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=28875) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=28875) E0000 00:00:1764433135.682466   28944 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=28875) E0000 00:00:1764433135.689408   28944 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=28875) W0000 00:00:1764433135.706783   28944 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=28875) W0000 00:00:1764433135.706818   28944 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=28875) W0000 00:00:1764433135.706821   28944 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=28875) W0000 00:00:1764433135.706823   28944 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:19:03. Total running time: 24min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=28875) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=28875) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=28875)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=28875) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=28875) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=28875)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=28875) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=28875) [2025-11-29 16:19:19,964 E 28875 28925] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=28875) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=28875) The model is already on multiple devices. Skipping the move to device specified in `args`.

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:19:33. Total running time: 25min 3s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=28875) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=28875)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=28875) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=28875) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=28875)  "-____-"     Trainable parameters = 5,636,096 of 1,241,450,496 (0.45% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=28875) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:13<33:07, 13.34s/it]
  1%|▏         | 2/150 [00:15<16:28,  6.68s/it]
  2%|▏         | 3/150 [00:18<12:03,  4.92s/it]
  3%|▎         | 4/150 [00:20<09:46,  4.02s/it]
  3%|▎         | 5/150 [00:22<07:56,  3.28s/it]
  3%|▎         | 5/150 [00:22<07:56,  3.28s/it]

(train_sft_tune pid=28875) {'loss': 1.0929, 'grad_norm': 0.5091622471809387, 'learning_rate': 2.8075404380856825e-05, 'epoch': 0.01}

  4%|▍         | 6/150 [00:25<07:12,  3.00s/it]
  5%|▍         | 7/150 [00:27<06:45,  2.84s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:20:03. Total running time: 25min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

  5%|▌         | 8/150 [00:30<06:33,  2.77s/it]
  6%|▌         | 9/150 [00:32<06:19,  2.69s/it]
  7%|▋         | 10/150 [00:35<06:07,  2.63s/it]

(train_sft_tune pid=28875) {'loss': 0.9639, 'grad_norm': 0.4109344184398651, 'learning_rate': 3.412613808362769e-05, 'epoch': 0.02}

  7%|▋         | 11/150 [00:38<06:08,  2.65s/it]
  8%|▊         | 12/150 [00:40<05:46,  2.51s/it]
  9%|▊         | 13/150 [00:43<06:05,  2.67s/it]
  9%|▉         | 14/150 [00:45<05:43,  2.53s/it]
 10%|█         | 15/150 [00:47<05:10,  2.30s/it]

(train_sft_tune pid=28875) {'loss': 1.0663, 'grad_norm': 0.4278649389743805, 'learning_rate': 3.2915991343073514e-05, 'epoch': 0.02}

 11%|█         | 16/150 [00:49<05:20,  2.39s/it]
 11%|█▏        | 17/150 [00:52<05:42,  2.58s/it]
 12%|█▏        | 18/150 [00:54<05:14,  2.38s/it]
 13%|█▎        | 19/150 [00:57<05:23,  2.47s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:20:33. Total running time: 26min 3s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 13%|█▎        | 20/150 [00:59<04:43,  2.18s/it]

(train_sft_tune pid=28875) {'loss': 0.991, 'grad_norm': 0.5994589328765869, 'learning_rate': 3.170584460251935e-05, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:01<04:35,  2.13s/it]
 15%|█▍        | 22/150 [01:03<04:34,  2.14s/it]
 15%|█▌        | 23/150 [01:05<04:40,  2.21s/it]
 16%|█▌        | 24/150 [01:08<04:58,  2.37s/it]
 17%|█▋        | 25/150 [01:10<05:05,  2.45s/it]

(train_sft_tune pid=28875) {'loss': 0.9176, 'grad_norm': 0.3491821587085724, 'learning_rate': 3.049569786196517e-05, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:14<05:29,  2.66s/it]
 18%|█▊        | 27/150 [01:16<05:06,  2.49s/it]
 19%|█▊        | 28/150 [01:19<05:17,  2.60s/it]
 19%|█▉        | 29/150 [01:20<04:50,  2.40s/it]
 20%|██        | 30/150 [01:24<05:30,  2.75s/it]

(train_sft_tune pid=28875) {'loss': 1.0648, 'grad_norm': 0.42550474405288696, 'learning_rate': 2.9285551121410998e-05, 'epoch': 0.05}

 21%|██        | 31/150 [01:27<05:33,  2.80s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:21:03. Total running time: 26min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 21%|██▏       | 32/150 [01:29<04:59,  2.54s/it]
 22%|██▏       | 33/150 [01:32<05:16,  2.70s/it]
 23%|██▎       | 34/150 [01:35<05:07,  2.65s/it]
 23%|██▎       | 35/150 [01:37<04:46,  2.49s/it]

(train_sft_tune pid=28875) {'loss': 0.9388, 'grad_norm': 0.43427446484565735, 'learning_rate': 2.8075404380856825e-05, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:39<04:38,  2.45s/it]
 25%|██▍       | 37/150 [01:41<04:38,  2.46s/it]
 25%|██▌       | 38/150 [01:44<04:28,  2.40s/it]
 26%|██▌       | 39/150 [01:46<04:37,  2.50s/it]
 27%|██▋       | 40/150 [01:49<04:38,  2.53s/it]

(train_sft_tune pid=28875) {'loss': 0.8377, 'grad_norm': 0.4394472539424896, 'learning_rate': 2.6865257640302648e-05, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:52<04:35,  2.53s/it]
 28%|██▊       | 42/150 [01:54<04:34,  2.54s/it]
 29%|██▊       | 43/150 [01:56<04:10,  2.34s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:21:33. Total running time: 27min 3s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 29%|██▉       | 44/150 [01:59<04:16,  2.42s/it]
 30%|███       | 45/150 [02:01<04:00,  2.29s/it]

(train_sft_tune pid=28875) {'loss': 0.9503, 'grad_norm': 0.4386971592903137, 'learning_rate': 2.5655110899748478e-05, 'epoch': 0.07}

 31%|███       | 46/150 [02:03<04:12,  2.43s/it]
 31%|███▏      | 47/150 [02:06<04:19,  2.52s/it]
 32%|███▏      | 48/150 [02:09<04:30,  2.65s/it]
 33%|███▎      | 49/150 [02:11<04:10,  2.48s/it]
 33%|███▎      | 50/150 [02:14<04:24,  2.64s/it]

(train_sft_tune pid=28875) {'loss': 0.9608, 'grad_norm': 0.4800989627838135, 'learning_rate': 2.44449641591943e-05, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:18<04:42,  2.86s/it]
 35%|███▍      | 52/150 [02:20<04:25,  2.71s/it]
 35%|███▌      | 53/150 [02:22<04:19,  2.67s/it]
 36%|███▌      | 54/150 [02:25<04:11,  2.62s/it]
 37%|███▋      | 55/150 [02:27<03:56,  2.49s/it]

(train_sft_tune pid=28875) {'loss': 0.8539, 'grad_norm': 0.43243107199668884, 'learning_rate': 2.323481741864013e-05, 'epoch': 0.09}
Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:22:03. Total running time: 27min 33s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 37%|███▋      | 56/150 [02:30<03:59,  2.55s/it]
 38%|███▊      | 57/150 [02:32<03:37,  2.34s/it]
 39%|███▊      | 58/150 [02:34<03:41,  2.41s/it]
 39%|███▉      | 59/150 [02:37<03:44,  2.46s/it]
 40%|████      | 60/150 [02:39<03:39,  2.44s/it]

(train_sft_tune pid=28875) {'loss': 0.9899, 'grad_norm': 0.5246974229812622, 'learning_rate': 2.202467067808596e-05, 'epoch': 0.1}

 41%|████      | 61/150 [02:42<03:45,  2.53s/it]
 41%|████▏     | 62/150 [02:46<04:08,  2.83s/it]
 42%|████▏     | 63/150 [02:49<04:12,  2.90s/it]
 43%|████▎     | 64/150 [02:52<04:20,  3.03s/it]
 43%|████▎     | 65/150 [02:54<03:52,  2.74s/it]

(train_sft_tune pid=28875) {'loss': 0.815, 'grad_norm': 0.44623899459838867, 'learning_rate': 2.0814523937531782e-05, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:57<03:51,  2.76s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:22:33. Total running time: 28min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 45%|████▍     | 67/150 [02:59<03:33,  2.57s/it]
 45%|████▌     | 68/150 [03:01<03:16,  2.40s/it]
 46%|████▌     | 69/150 [03:03<03:02,  2.25s/it]
 47%|████▋     | 70/150 [03:06<03:21,  2.52s/it]

(train_sft_tune pid=28875) {'loss': 0.9364, 'grad_norm': 0.43621399998664856, 'learning_rate': 1.960437719697761e-05, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:09<03:31,  2.68s/it]
 48%|████▊     | 72/150 [03:11<03:19,  2.55s/it]
 49%|████▊     | 73/150 [03:14<03:21,  2.62s/it]
 49%|████▉     | 74/150 [03:16<03:13,  2.55s/it]
 50%|█████     | 75/150 [03:19<03:14,  2.59s/it]

(train_sft_tune pid=28875) {'loss': 1.0224, 'grad_norm': 0.41539573669433594, 'learning_rate': 1.839423045642344e-05, 'epoch': 0.12}

 51%|█████     | 76/150 [03:22<03:10,  2.58s/it]
 51%|█████▏    | 77/150 [03:24<03:06,  2.55s/it]
 52%|█████▏    | 78/150 [03:26<02:51,  2.38s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:23:03. Total running time: 28min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 53%|█████▎    | 79/150 [03:28<02:44,  2.31s/it]
 53%|█████▎    | 80/150 [03:31<02:47,  2.40s/it]

(train_sft_tune pid=28875) {'loss': 0.9931, 'grad_norm': 0.6035523414611816, 'learning_rate': 1.7184083715869262e-05, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:34<02:52,  2.50s/it]
 55%|█████▍    | 82/150 [03:36<02:53,  2.55s/it]
 55%|█████▌    | 83/150 [03:39<02:45,  2.48s/it]
 56%|█████▌    | 84/150 [03:41<02:36,  2.38s/it]
 57%|█████▋    | 85/150 [03:44<02:42,  2.50s/it]

(train_sft_tune pid=28875) {'loss': 1.0322, 'grad_norm': 0.5489156246185303, 'learning_rate': 1.597393697531509e-05, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:46<02:32,  2.38s/it]
 58%|█████▊    | 87/150 [03:49<02:40,  2.55s/it]
 59%|█████▊    | 88/150 [03:51<02:42,  2.61s/it]
 59%|█████▉    | 89/150 [03:54<02:48,  2.76s/it]
 60%|██████    | 90/150 [03:56<02:28,  2.47s/it]

(train_sft_tune pid=28875) {'loss': 1.0254, 'grad_norm': 0.46759384870529175, 'learning_rate': 1.4763790234760916e-05, 'epoch': 0.14}
Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:23:33. Total running time: 29min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 61%|██████    | 91/150 [03:58<02:18,  2.36s/it]
 61%|██████▏   | 92/150 [04:01<02:19,  2.41s/it]
 62%|██████▏   | 93/150 [04:03<02:17,  2.41s/it]
 63%|██████▎   | 94/150 [04:05<02:09,  2.32s/it]
 63%|██████▎   | 95/150 [04:08<02:13,  2.43s/it]

(train_sft_tune pid=28875) {'loss': 0.8318, 'grad_norm': 0.4417476952075958, 'learning_rate': 1.3553643494206743e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:10<02:09,  2.39s/it]
 65%|██████▍   | 97/150 [04:13<02:14,  2.54s/it]
 65%|██████▌   | 98/150 [04:16<02:17,  2.64s/it]
 66%|██████▌   | 99/150 [04:19<02:21,  2.77s/it]
 67%|██████▋   | 100/150 [04:21<02:05,  2.52s/it]

(train_sft_tune pid=28875) {'loss': 0.9245, 'grad_norm': 0.46493861079216003, 'learning_rate': 1.2343496753652568e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:23<02:00,  2.46s/it]
 68%|██████▊   | 102/150 [04:26<01:53,  2.37s/it]
 69%|██████▊   | 103/150 [04:28<01:54,  2.45s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:24:03. Total running time: 29min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 69%|██████▉   | 104/150 [04:31<01:54,  2.49s/it]
 70%|███████   | 105/150 [04:33<01:51,  2.49s/it]

(train_sft_tune pid=28875) {'loss': 0.9554, 'grad_norm': 0.429649293422699, 'learning_rate': 1.1133350013098396e-05, 'epoch': 0.17}

 71%|███████   | 106/150 [04:36<01:47,  2.45s/it]
 71%|███████▏  | 107/150 [04:39<01:51,  2.60s/it]
 72%|███████▏  | 108/150 [04:42<01:55,  2.75s/it]
 73%|███████▎  | 109/150 [04:44<01:50,  2.69s/it]
 73%|███████▎  | 110/150 [04:46<01:38,  2.46s/it]

(train_sft_tune pid=28875) {'loss': 0.8742, 'grad_norm': 0.49644675850868225, 'learning_rate': 9.923203272544223e-06, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:49<01:44,  2.68s/it]
 75%|███████▍  | 112/150 [04:52<01:45,  2.78s/it]
 75%|███████▌  | 113/150 [04:54<01:34,  2.55s/it]
 76%|███████▌  | 114/150 [04:57<01:34,  2.62s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:24:33. Total running time: 30min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 77%|███████▋  | 115/150 [04:59<01:26,  2.46s/it]

(train_sft_tune pid=28875) {'loss': 0.907, 'grad_norm': 0.5447911620140076, 'learning_rate': 8.713056531990048e-06, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:02<01:23,  2.46s/it]
 78%|███████▊  | 117/150 [05:05<01:27,  2.65s/it]
 79%|███████▊  | 118/150 [05:08<01:28,  2.75s/it]
 79%|███████▉  | 119/150 [05:11<01:26,  2.78s/it]
 80%|████████  | 120/150 [05:13<01:18,  2.62s/it]

(train_sft_tune pid=28875) {'loss': 1.1144, 'grad_norm': 0.5355522036552429, 'learning_rate': 7.502909791435876e-06, 'epoch': 0.19}

 81%|████████  | 121/150 [05:16<01:21,  2.80s/it]
 81%|████████▏ | 122/150 [05:19<01:20,  2.87s/it]
 82%|████████▏ | 123/150 [05:22<01:13,  2.74s/it]
 83%|████████▎ | 124/150 [05:25<01:14,  2.87s/it]
 83%|████████▎ | 125/150 [05:27<01:09,  2.77s/it]

(train_sft_tune pid=28875) {'loss': 0.8804, 'grad_norm': 0.4842964708805084, 'learning_rate': 6.292763050881702e-06, 'epoch': 0.2}
Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:25:03. Total running time: 30min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 84%|████████▍ | 126/150 [05:30<01:06,  2.79s/it]
 85%|████████▍ | 127/150 [05:33<01:03,  2.76s/it]
 85%|████████▌ | 128/150 [05:35<00:58,  2.66s/it]
 86%|████████▌ | 129/150 [05:37<00:49,  2.34s/it]
 87%|████████▋ | 130/150 [05:40<00:48,  2.44s/it]

(train_sft_tune pid=28875) {'loss': 0.8832, 'grad_norm': 0.4740906357765198, 'learning_rate': 5.0826163103275285e-06, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:42<00:46,  2.46s/it]
 88%|████████▊ | 132/150 [05:45<00:45,  2.54s/it]
 89%|████████▊ | 133/150 [05:47<00:40,  2.38s/it]
 89%|████████▉ | 134/150 [05:50<00:43,  2.73s/it]
 90%|█████████ | 135/150 [05:53<00:40,  2.72s/it]

(train_sft_tune pid=28875) {'loss': 0.905, 'grad_norm': 0.47047102451324463, 'learning_rate': 3.872469569773355e-06, 'epoch': 0.22}

 91%|█████████ | 136/150 [05:56<00:39,  2.80s/it]
 91%|█████████▏| 137/150 [05:58<00:32,  2.52s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:25:34. Total running time: 31min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 92%|█████████▏| 138/150 [06:00<00:30,  2.50s/it]
 93%|█████████▎| 139/150 [06:03<00:27,  2.47s/it]
 93%|█████████▎| 140/150 [06:05<00:23,  2.37s/it]

(train_sft_tune pid=28875) {'loss': 0.9798, 'grad_norm': 0.4549700915813446, 'learning_rate': 2.6623228292191817e-06, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:07<00:21,  2.43s/it]
 95%|█████████▍| 142/150 [06:10<00:19,  2.48s/it]
 95%|█████████▌| 143/150 [06:13<00:17,  2.53s/it]
 96%|█████████▌| 144/150 [06:16<00:16,  2.69s/it]
 97%|█████████▋| 145/150 [06:18<00:13,  2.61s/it]

(train_sft_tune pid=28875) {'loss': 0.9111, 'grad_norm': 0.489604651927948, 'learning_rate': 1.452176088665008e-06, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:21<00:10,  2.56s/it]
 98%|█████████▊| 147/150 [06:23<00:07,  2.52s/it]
 99%|█████████▊| 148/150 [06:26<00:05,  2.59s/it]
 99%|█████████▉| 149/150 [06:28<00:02,  2.51s/it]

Trial status: 3 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:26:04. Total running time: 31min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_e9b87c19   RUNNING      3.50943e-05     8             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_f628069f   PENDING      7.2761e-05     16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

100%|██████████| 150/150 [06:31<00:00,  2.56s/it]

(train_sft_tune pid=28875) {'loss': 0.983, 'grad_norm': 0.45026302337646484, 'learning_rate': 2.420293481108347e-07, 'epoch': 0.24}

100%|██████████| 150/150 [06:32<00:00,  2.62s/it]

(train_sft_tune pid=28875) {'train_runtime': 392.3903, 'train_samples_per_second': 3.058, 'train_steps_per_second': 0.382, 'train_loss': 0.9534026463826497, 'epoch': 0.24}
(train_sft_tune pid=28875) history of tuning  [{'loss': 1.0929, 'grad_norm': 0.5091622471809387, 'learning_rate': 2.8075404380856825e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9639, 'grad_norm': 0.4109344184398651, 'learning_rate': 3.412613808362769e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0663, 'grad_norm': 0.4278649389743805, 'learning_rate': 3.2915991343073514e-05, 'epoch': 0.024, 'step': 15}, {'loss': 0.991, 'grad_norm': 0.5994589328765869, 'learning_rate': 3.170584460251935e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.9176, 'grad_norm': 0.3491821587085724, 'learning_rate': 3.049569786196517e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0648, 'grad_norm': 0.42550474405288696, 'learning_rate': 2.9285551121410998e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9388, 'grad_norm': 0.43427446484565735, 'learning_rate': 2.8075404380856825e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8377, 'grad_norm': 0.4394472539424896, 'learning_rate': 2.6865257640302648e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9503, 'grad_norm': 0.4386971592903137, 'learning_rate': 2.5655110899748478e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9608, 'grad_norm': 0.4800989627838135, 'learning_rate': 2.44449641591943e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8539, 'grad_norm': 0.43243107199668884, 'learning_rate': 2.323481741864013e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9899, 'grad_norm': 0.5246974229812622, 'learning_rate': 2.202467067808596e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.815, 'grad_norm': 0.44623899459838867, 'learning_rate': 2.0814523937531782e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.9364, 'grad_norm': 0.43621399998664856, 'learning_rate': 1.960437719697761e-05, 'epoch': 0.112, 'step': 70}, {'loss': 1.0224, 'grad_norm': 0.41539573669433594, 'learning_rate': 1.839423045642344e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9931, 'grad_norm': 0.6035523414611816, 'learning_rate': 1.7184083715869262e-05, 'epoch': 0.128, 'step': 80}, {'loss': 1.0322, 'grad_norm': 0.5489156246185303, 'learning_rate': 1.597393697531509e-05, 'epoch': 0.136, 'step': 85}, {'loss': 1.0254, 'grad_norm': 0.46759384870529175, 'learning_rate': 1.4763790234760916e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8318, 'grad_norm': 0.4417476952075958, 'learning_rate': 1.3553643494206743e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.9245, 'grad_norm': 0.46493861079216003, 'learning_rate': 1.2343496753652568e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9554, 'grad_norm': 0.429649293422699, 'learning_rate': 1.1133350013098396e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8742, 'grad_norm': 0.49644675850868225, 'learning_rate': 9.923203272544223e-06, 'epoch': 0.176, 'step': 110}, {'loss': 0.907, 'grad_norm': 0.5447911620140076, 'learning_rate': 8.713056531990048e-06, 'epoch': 0.184, 'step': 115}, {'loss': 1.1144, 'grad_norm': 0.5355522036552429, 'learning_rate': 7.502909791435876e-06, 'epoch': 0.192, 'step': 120}, {'loss': 0.8804, 'grad_norm': 0.4842964708805084, 'learning_rate': 6.292763050881702e-06, 'epoch': 0.2, 'step': 125}, {'loss': 0.8832, 'grad_norm': 0.4740906357765198, 'learning_rate': 5.0826163103275285e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.905, 'grad_norm': 0.47047102451324463, 'learning_rate': 3.872469569773355e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9798, 'grad_norm': 0.4549700915813446, 'learning_rate': 2.6623228292191817e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.9111, 'grad_norm': 0.489604651927948, 'learning_rate': 1.452176088665008e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.983, 'grad_norm': 0.45026302337646484, 'learning_rate': 2.420293481108347e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 392.3903, 'train_samples_per_second': 3.058, 'train_steps_per_second': 0.382, 'total_flos': 4860346640523264.0, 'train_loss': 0.9534026463826497, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=28875) Reporting loss: 0.9534026463826497

Trial train_sft_tune_e9b87c19 completed after 1 iterations at 2025-11-29 16:26:07. Total running time: 31min 37s
+--------------------------------------------------+
| Trial train_sft_tune_e9b87c19 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         436.332 |
| time_total_s                             436.332 |
| training_iteration                             1 |
| train_loss                                0.9534 |
+--------------------------------------------------+

Trial train_sft_tune_f628069f started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_f628069f config           |
+------------------------------------------------+
| lora_alpha                                  32 |
| lr                                       7e-05 |
| r                                           16 |
+------------------------------------------------+
(train_sft_tune pid=30932) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=30932) 2025-11-29 16:26:22.147270: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=30932) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=30932) E0000 00:00:1764433582.170401   30992 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=30932) E0000 00:00:1764433582.177132   30992 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=30932) W0000 00:00:1764433582.193909   30992 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=30932) W0000 00:00:1764433582.193948   30992 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=30932) W0000 00:00:1764433582.193951   30992 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=30932) W0000 00:00:1764433582.193953   30992 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:26:34. Total running time: 32min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=30932) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=30932) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=30932)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=30932) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=30932) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=30932)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=30932) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=30932) [2025-11-29 16:26:45,455 E 30932 30971] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=30932) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=30932) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=30932) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=30932)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=30932) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=30932) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=30932)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=30932) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:27:04. Total running time: 32min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:13<33:10, 13.36s/it]
  1%|▏         | 2/150 [00:15<16:29,  6.68s/it]
  2%|▏         | 3/150 [00:18<11:58,  4.89s/it]
  3%|▎         | 4/150 [00:20<09:42,  3.99s/it]
  3%|▎         | 5/150 [00:22<07:56,  3.29s/it]

(train_sft_tune pid=30932) {'loss': 1.09, 'grad_norm': 0.6373386979103088, 'learning_rate': 5.820878833336036e-05, 'epoch': 0.01}

  4%|▍         | 6/150 [00:25<07:17,  3.04s/it]
  5%|▍         | 7/150 [00:27<06:49,  2.86s/it]
  5%|▌         | 8/150 [00:30<06:32,  2.76s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:27:34. Total running time: 33min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  6%|▌         | 9/150 [00:32<06:16,  2.67s/it]
  7%|▋         | 10/150 [00:35<06:10,  2.65s/it]

(train_sft_tune pid=30932) {'loss': 0.9414, 'grad_norm': 0.5156688094139099, 'learning_rate': 7.075378581899835e-05, 'epoch': 0.02}

  7%|▋         | 11/150 [00:38<06:13,  2.69s/it]
  8%|▊         | 12/150 [00:40<05:49,  2.53s/it]
  9%|▊         | 13/150 [00:43<06:04,  2.66s/it]
  9%|▉         | 14/150 [00:45<05:40,  2.51s/it]
 10%|█         | 15/150 [00:47<05:13,  2.32s/it]

(train_sft_tune pid=30932) {'loss': 1.0348, 'grad_norm': 0.509214460849762, 'learning_rate': 6.824478632187075e-05, 'epoch': 0.02}

 11%|█         | 16/150 [00:50<05:24,  2.42s/it]
 11%|█▏        | 17/150 [00:53<05:44,  2.59s/it]
 12%|█▏        | 18/150 [00:54<05:14,  2.38s/it]
 13%|█▎        | 19/150 [00:57<05:20,  2.44s/it]
 13%|█▎        | 20/150 [00:59<04:40,  2.16s/it]

(train_sft_tune pid=30932) {'loss': 0.9551, 'grad_norm': 0.6892575621604919, 'learning_rate': 6.573578682474316e-05, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:01<04:35,  2.13s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:28:04. Total running time: 33min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 15%|█▍        | 22/150 [01:03<04:36,  2.16s/it]
 15%|█▌        | 23/150 [01:05<04:42,  2.23s/it]
 16%|█▌        | 24/150 [01:08<04:58,  2.37s/it]
 17%|█▋        | 25/150 [01:10<05:01,  2.41s/it]

(train_sft_tune pid=30932) {'loss': 0.8859, 'grad_norm': 0.4255257248878479, 'learning_rate': 6.322678732761556e-05, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:14<05:26,  2.63s/it]
 18%|█▊        | 27/150 [01:16<05:05,  2.49s/it]
 19%|█▊        | 28/150 [01:19<05:15,  2.59s/it]
 19%|█▉        | 29/150 [01:20<04:46,  2.37s/it]
 20%|██        | 30/150 [01:24<05:25,  2.71s/it]

(train_sft_tune pid=30932) {'loss': 1.0293, 'grad_norm': 0.527380108833313, 'learning_rate': 6.0717787830487955e-05, 'epoch': 0.05}

 21%|██        | 31/150 [01:27<05:28,  2.76s/it]
 21%|██▏       | 32/150 [01:29<04:59,  2.53s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:28:34. Total running time: 34min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 22%|██▏       | 33/150 [01:32<05:16,  2.71s/it]
 23%|██▎       | 34/150 [01:34<05:06,  2.64s/it]
 23%|██▎       | 35/150 [01:36<04:45,  2.48s/it]

(train_sft_tune pid=30932) {'loss': 0.9088, 'grad_norm': 0.5402133464813232, 'learning_rate': 5.820878833336036e-05, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:39<04:40,  2.46s/it]
 25%|██▍       | 37/150 [01:41<04:42,  2.50s/it]
 25%|██▌       | 38/150 [01:44<04:32,  2.43s/it]
 26%|██▌       | 39/150 [01:46<04:39,  2.52s/it]
 27%|██▋       | 40/150 [01:49<04:38,  2.53s/it]

(train_sft_tune pid=30932) {'loss': 0.8065, 'grad_norm': 0.5211477875709534, 'learning_rate': 5.5699788836232754e-05, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:52<04:37,  2.55s/it]
 28%|██▊       | 42/150 [01:54<04:38,  2.58s/it]
 29%|██▊       | 43/150 [01:56<04:14,  2.38s/it]
 29%|██▉       | 44/150 [01:59<04:19,  2.45s/it]
 30%|███       | 45/150 [02:01<03:59,  2.28s/it]

(train_sft_tune pid=30932) {'loss': 0.9142, 'grad_norm': 0.5381515026092529, 'learning_rate': 5.319078933910515e-05, 'epoch': 0.07}
Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:29:04. Total running time: 34min 34s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 31%|███       | 46/150 [02:03<04:12,  2.43s/it]
 31%|███▏      | 47/150 [02:06<04:21,  2.54s/it]
 32%|███▏      | 48/150 [02:09<04:32,  2.67s/it]
 33%|███▎      | 49/150 [02:11<04:11,  2.49s/it]
 33%|███▎      | 50/150 [02:14<04:22,  2.63s/it]

(train_sft_tune pid=30932) {'loss': 0.9348, 'grad_norm': 0.5299551486968994, 'learning_rate': 5.0681789841977546e-05, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:18<04:41,  2.84s/it]
 35%|███▍      | 52/150 [02:20<04:27,  2.73s/it]
 35%|███▌      | 53/150 [02:23<04:20,  2.68s/it]
 36%|███▌      | 54/150 [02:25<04:12,  2.63s/it]
 37%|███▋      | 55/150 [02:27<03:52,  2.44s/it]

(train_sft_tune pid=30932) {'loss': 0.8271, 'grad_norm': 0.53386390209198, 'learning_rate': 4.817279034484995e-05, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:30<03:57,  2.52s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:29:34. Total running time: 35min 4s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 38%|███▊      | 57/150 [02:32<03:38,  2.35s/it]
 39%|███▊      | 58/150 [02:34<03:43,  2.42s/it]
 39%|███▉      | 59/150 [02:37<03:45,  2.48s/it]
 40%|████      | 60/150 [02:39<03:39,  2.44s/it]

(train_sft_tune pid=30932) {'loss': 0.9598, 'grad_norm': 0.6328838467597961, 'learning_rate': 4.566379084772235e-05, 'epoch': 0.1}

 41%|████      | 61/150 [02:42<03:43,  2.52s/it]
 41%|████▏     | 62/150 [02:46<04:08,  2.82s/it]
 42%|████▏     | 63/150 [02:49<04:11,  2.89s/it]
 43%|████▎     | 64/150 [02:52<04:19,  3.02s/it]
 43%|████▎     | 65/150 [02:54<03:51,  2.72s/it]

(train_sft_tune pid=30932) {'loss': 0.7893, 'grad_norm': 0.52370285987854, 'learning_rate': 4.315479135059474e-05, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:57<03:52,  2.76s/it]
 45%|████▍     | 67/150 [02:59<03:35,  2.60s/it]
 45%|████▌     | 68/150 [03:01<03:18,  2.42s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:30:04. Total running time: 35min 35s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 46%|████▌     | 69/150 [03:03<03:04,  2.28s/it]
 47%|████▋     | 70/150 [03:06<03:22,  2.53s/it]

(train_sft_tune pid=30932) {'loss': 0.9087, 'grad_norm': 0.5156027674674988, 'learning_rate': 4.0645791853467143e-05, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:09<03:33,  2.70s/it]
 48%|████▊     | 72/150 [03:12<03:22,  2.60s/it]
 49%|████▊     | 73/150 [03:14<03:23,  2.64s/it]
 49%|████▉     | 74/150 [03:17<03:13,  2.55s/it]
 50%|█████     | 75/150 [03:19<03:12,  2.57s/it]

(train_sft_tune pid=30932) {'loss': 1.0012, 'grad_norm': 0.48431000113487244, 'learning_rate': 3.8136792356339546e-05, 'epoch': 0.12}

 51%|█████     | 76/150 [03:22<03:10,  2.58s/it]
 51%|█████▏    | 77/150 [03:24<03:08,  2.58s/it]
 52%|█████▏    | 78/150 [03:26<02:53,  2.41s/it]
 53%|█████▎    | 79/150 [03:29<02:46,  2.34s/it]
 53%|█████▎    | 80/150 [03:31<02:48,  2.41s/it]

(train_sft_tune pid=30932) {'loss': 0.9683, 'grad_norm': 0.7240557074546814, 'learning_rate': 3.562779285921194e-05, 'epoch': 0.13}
Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:30:34. Total running time: 36min 5s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 54%|█████▍    | 81/150 [03:34<02:51,  2.48s/it]
 55%|█████▍    | 82/150 [03:37<02:54,  2.56s/it]
 55%|█████▌    | 83/150 [03:39<02:47,  2.51s/it]
 56%|█████▌    | 84/150 [03:41<02:38,  2.40s/it]
 57%|█████▋    | 85/150 [03:44<02:43,  2.51s/it]

(train_sft_tune pid=30932) {'loss': 1.0061, 'grad_norm': 0.6677917838096619, 'learning_rate': 3.311879336208434e-05, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:46<02:31,  2.37s/it]
 58%|█████▊    | 87/150 [03:49<02:40,  2.55s/it]
 59%|█████▊    | 88/150 [03:52<02:42,  2.62s/it]
 59%|█████▉    | 89/150 [03:55<02:48,  2.77s/it]
 60%|██████    | 90/150 [03:57<02:27,  2.45s/it]

(train_sft_tune pid=30932) {'loss': 1.0059, 'grad_norm': 0.5612753033638, 'learning_rate': 3.060979386495674e-05, 'epoch': 0.14}

 61%|██████    | 91/150 [03:59<02:16,  2.31s/it]
 61%|██████▏   | 92/150 [04:01<02:18,  2.39s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:31:04. Total running time: 36min 35s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 62%|██████▏   | 93/150 [04:04<02:18,  2.43s/it]
 63%|██████▎   | 94/150 [04:06<02:10,  2.34s/it]
 63%|██████▎   | 95/150 [04:08<02:14,  2.44s/it]

(train_sft_tune pid=30932) {'loss': 0.8101, 'grad_norm': 0.4902043044567108, 'learning_rate': 2.8100794367829137e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:11<02:08,  2.37s/it]
 65%|██████▍   | 97/150 [04:14<02:14,  2.53s/it]
 65%|██████▌   | 98/150 [04:16<02:17,  2.65s/it]
 66%|██████▌   | 99/150 [04:20<02:21,  2.78s/it]
 67%|██████▋   | 100/150 [04:21<02:05,  2.52s/it]

(train_sft_tune pid=30932) {'loss': 0.9038, 'grad_norm': 0.546373188495636, 'learning_rate': 2.5591794870701533e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:24<01:59,  2.45s/it]
 68%|██████▊   | 102/150 [04:26<01:53,  2.37s/it]
 69%|██████▊   | 103/150 [04:29<01:55,  2.46s/it]
 69%|██████▉   | 104/150 [04:31<01:55,  2.50s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:31:34. Total running time: 37min 5s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 70%|███████   | 105/150 [04:34<01:52,  2.50s/it]

(train_sft_tune pid=30932) {'loss': 0.934, 'grad_norm': 0.5001214146614075, 'learning_rate': 2.3082795373573935e-05, 'epoch': 0.17}

 71%|███████   | 106/150 [04:36<01:47,  2.44s/it]
 71%|███████▏  | 107/150 [04:39<01:51,  2.58s/it]
 72%|███████▏  | 108/150 [04:42<01:55,  2.75s/it]
 73%|███████▎  | 109/150 [04:45<01:50,  2.69s/it]
 73%|███████▎  | 110/150 [04:47<01:38,  2.46s/it]

(train_sft_tune pid=30932) {'loss': 0.8474, 'grad_norm': 0.5920054912567139, 'learning_rate': 2.057379587644633e-05, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:50<01:44,  2.67s/it]
 75%|███████▍  | 112/150 [04:53<01:46,  2.79s/it]
 75%|███████▌  | 113/150 [04:55<01:35,  2.59s/it]
 76%|███████▌  | 114/150 [04:58<01:35,  2.66s/it]
 77%|███████▋  | 115/150 [05:00<01:26,  2.48s/it]

(train_sft_tune pid=30932) {'loss': 0.8787, 'grad_norm': 0.656803548336029, 'learning_rate': 1.806479637931873e-05, 'epoch': 0.18}
Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:32:04. Total running time: 37min 35s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 77%|███████▋  | 116/150 [05:02<01:23,  2.45s/it]
 78%|███████▊  | 117/150 [05:05<01:26,  2.64s/it]
 79%|███████▊  | 118/150 [05:08<01:28,  2.75s/it]
 79%|███████▉  | 119/150 [05:11<01:26,  2.78s/it]
 80%|████████  | 120/150 [05:13<01:18,  2.60s/it]

(train_sft_tune pid=30932) {'loss': 1.0881, 'grad_norm': 0.6020211577415466, 'learning_rate': 1.555579688219113e-05, 'epoch': 0.19}

 81%|████████  | 121/150 [05:16<01:20,  2.78s/it]
 81%|████████▏ | 122/150 [05:20<01:20,  2.88s/it]
 82%|████████▏ | 123/150 [05:22<01:14,  2.75s/it]
 83%|████████▎ | 124/150 [05:25<01:14,  2.88s/it]
 83%|████████▎ | 125/150 [05:28<01:08,  2.75s/it]

(train_sft_tune pid=30932) {'loss': 0.8591, 'grad_norm': 0.530328631401062, 'learning_rate': 1.3046797385063528e-05, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:31<01:06,  2.79s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:32:34. Total running time: 38min 5s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 85%|████████▍ | 127/150 [05:33<01:04,  2.78s/it]
 85%|████████▌ | 128/150 [05:36<00:59,  2.69s/it]
 86%|████████▌ | 129/150 [05:37<00:49,  2.36s/it]
 87%|████████▋ | 130/150 [05:40<00:49,  2.46s/it]

(train_sft_tune pid=30932) {'loss': 0.8606, 'grad_norm': 0.5267955660820007, 'learning_rate': 1.0537797887935927e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:42<00:46,  2.44s/it]
 88%|████████▊ | 132/150 [05:45<00:45,  2.55s/it]
 89%|████████▊ | 133/150 [05:47<00:41,  2.42s/it]
 89%|████████▉ | 134/150 [05:51<00:44,  2.77s/it]
 90%|█████████ | 135/150 [05:54<00:41,  2.74s/it]

(train_sft_tune pid=30932) {'loss': 0.8874, 'grad_norm': 0.5628255009651184, 'learning_rate': 8.028798390808325e-06, 'epoch': 0.22}

 91%|█████████ | 136/150 [05:57<00:39,  2.82s/it]
 91%|█████████▏| 137/150 [05:59<00:33,  2.58s/it]
 92%|█████████▏| 138/150 [06:01<00:30,  2.57s/it]

Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:33:05. Total running time: 38min 35s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 93%|█████████▎| 139/150 [06:04<00:27,  2.52s/it]
 93%|█████████▎| 140/150 [06:06<00:24,  2.40s/it]

(train_sft_tune pid=30932) {'loss': 0.9607, 'grad_norm': 0.5406239032745361, 'learning_rate': 5.519798893680723e-06, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:08<00:22,  2.46s/it]
 95%|█████████▍| 142/150 [06:11<00:20,  2.51s/it]
 95%|█████████▌| 143/150 [06:14<00:18,  2.58s/it]
 96%|█████████▌| 144/150 [06:17<00:16,  2.74s/it]
 97%|█████████▋| 145/150 [06:19<00:13,  2.64s/it]

(train_sft_tune pid=30932) {'loss': 0.8899, 'grad_norm': 0.5317929983139038, 'learning_rate': 3.010799396553122e-06, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:22<00:10,  2.56s/it]
 98%|█████████▊| 147/150 [06:24<00:07,  2.56s/it]
 99%|█████████▊| 148/150 [06:27<00:05,  2.64s/it]
 99%|█████████▉| 149/150 [06:29<00:02,  2.54s/it]
100%|██████████| 150/150 [06:32<00:00,  2.57s/it]

(train_sft_tune pid=30932) {'loss': 0.9552, 'grad_norm': 0.5141841769218445, 'learning_rate': 5.017998994255203e-07, 'epoch': 0.24}
Trial status: 4 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:33:35. Total running time: 39min 5s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 3e6a0a4a with train_loss=0.9325727272033691 and params={'lr': 5.6184813910899204e-05, 'r': 32, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f628069f   RUNNING      7.2761e-05     16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_bad7439a   PENDING      0.0001356      32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

Trial train_sft_tune_f628069f completed after 1 iterations at 2025-11-29 16:33:35. Total running time: 39min 6s
+--------------------------------------------------+
| Trial train_sft_tune_f628069f result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         439.088 |
| time_total_s                             439.088 |
| training_iteration                             1 |
| train_loss                               0.92806 |
+--------------------------------------------------+
(train_sft_tune pid=30932) {'train_runtime': 393.3331, 'train_samples_per_second': 3.051, 'train_steps_per_second': 0.381, 'train_loss': 0.9280647850036621, 'epoch': 0.24}
(train_sft_tune pid=30932) history of tuning  [{'loss': 1.09, 'grad_norm': 0.6373386979103088, 'learning_rate': 5.820878833336036e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9414, 'grad_norm': 0.5156688094139099, 'learning_rate': 7.075378581899835e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0348, 'grad_norm': 0.509214460849762, 'learning_rate': 6.824478632187075e-05, 'epoch': 0.024, 'step': 15}, {'loss': 0.9551, 'grad_norm': 0.6892575621604919, 'learning_rate': 6.573578682474316e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.8859, 'grad_norm': 0.4255257248878479, 'learning_rate': 6.322678732761556e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0293, 'grad_norm': 0.527380108833313, 'learning_rate': 6.0717787830487955e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9088, 'grad_norm': 0.5402133464813232, 'learning_rate': 5.820878833336036e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8065, 'grad_norm': 0.5211477875709534, 'learning_rate': 5.5699788836232754e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9142, 'grad_norm': 0.5381515026092529, 'learning_rate': 5.319078933910515e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9348, 'grad_norm': 0.5299551486968994, 'learning_rate': 5.0681789841977546e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8271, 'grad_norm': 0.53386390209198, 'learning_rate': 4.817279034484995e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9598, 'grad_norm': 0.6328838467597961, 'learning_rate': 4.566379084772235e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.7893, 'grad_norm': 0.52370285987854, 'learning_rate': 4.315479135059474e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.9087, 'grad_norm': 0.5156027674674988, 'learning_rate': 4.0645791853467143e-05, 'epoch': 0.112, 'step': 70}, {'loss': 1.0012, 'grad_norm': 0.48431000113487244, 'learning_rate': 3.8136792356339546e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9683, 'grad_norm': 0.7240557074546814, 'learning_rate': 3.562779285921194e-05, 'epoch': 0.128, 'step': 80}, {'loss': 1.0061, 'grad_norm': 0.6677917838096619, 'learning_rate': 3.311879336208434e-05, 'epoch': 0.136, 'step': 85}, {'loss': 1.0059, 'grad_norm': 0.5612753033638, 'learning_rate': 3.060979386495674e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8101, 'grad_norm': 0.4902043044567108, 'learning_rate': 2.8100794367829137e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.9038, 'grad_norm': 0.546373188495636, 'learning_rate': 2.5591794870701533e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.934, 'grad_norm': 0.5001214146614075, 'learning_rate': 2.3082795373573935e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8474, 'grad_norm': 0.5920054912567139, 'learning_rate': 2.057379587644633e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8787, 'grad_norm': 0.656803548336029, 'learning_rate': 1.806479637931873e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0881, 'grad_norm': 0.6020211577415466, 'learning_rate': 1.555579688219113e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8591, 'grad_norm': 0.530328631401062, 'learning_rate': 1.3046797385063528e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8606, 'grad_norm': 0.5267955660820007, 'learning_rate': 1.0537797887935927e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8874, 'grad_norm': 0.5628255009651184, 'learning_rate': 8.028798390808325e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9607, 'grad_norm': 0.5406239032745361, 'learning_rate': 5.519798893680723e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.8899, 'grad_norm': 0.5317929983139038, 'learning_rate': 3.010799396553122e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9552, 'grad_norm': 0.5141841769218445, 'learning_rate': 5.017998994255203e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 393.3331, 'train_samples_per_second': 3.051, 'train_steps_per_second': 0.381, 'total_flos': 4888333847519232.0, 'train_loss': 0.9280647850036621, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=30932) Reporting loss: 0.9280647850036621

100%|██████████| 150/150 [06:33<00:00,  2.62s/it]

Trial train_sft_tune_bad7439a started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_bad7439a config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00014 |
| r                                             32 |
+--------------------------------------------------+
(train_sft_tune pid=32993) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=32993) 2025-11-29 16:33:50.421966: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=32993) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=32993) E0000 00:00:1764434030.444455   33053 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=32993) E0000 00:00:1764434030.451500   33053 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=32993) W0000 00:00:1764434030.471202   33053 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=32993) W0000 00:00:1764434030.471245   33053 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=32993) W0000 00:00:1764434030.471247   33053 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=32993) W0000 00:00:1764434030.471249   33053 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:34:05. Total running time: 39min 35s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=32993) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=32993) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=32993)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=32993) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=32993) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=32993)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=32993) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=32993) [2025-11-29 16:34:14,517 E 32993 33035] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=32993) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=32993) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=32993) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=32993)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=32993) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=32993) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=32993)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=32993) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:34:35. Total running time: 40min 5s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:12<30:15, 12.18s/it]
  1%|▏         | 2/150 [00:14<15:24,  6.24s/it]
  2%|▏         | 3/150 [00:16<11:21,  4.64s/it]
  3%|▎         | 4/150 [00:19<09:18,  3.82s/it]
  3%|▎         | 5/150 [00:21<07:36,  3.15s/it]

(train_sft_tune pid=32993) {'loss': 1.0808, 'grad_norm': 0.7531550526618958, 'learning_rate': 0.00010847983910880855, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:02,  2.93s/it]
  5%|▍         | 7/150 [00:26<06:41,  2.81s/it]
  5%|▌         | 8/150 [00:29<06:27,  2.73s/it]
  6%|▌         | 9/150 [00:31<06:13,  2.65s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:35:05. Total running time: 40min 35s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  7%|▋         | 10/150 [00:34<06:05,  2.61s/it]

(train_sft_tune pid=32993) {'loss': 0.9123, 'grad_norm': 0.5921828746795654, 'learning_rate': 0.00013185911477881038, 'epoch': 0.02}

  7%|▋         | 11/150 [00:36<06:07,  2.65s/it]
  8%|▊         | 12/150 [00:39<05:49,  2.53s/it]
  9%|▊         | 13/150 [00:42<06:07,  2.68s/it]
  9%|▉         | 14/150 [00:44<05:44,  2.53s/it]
 10%|█         | 15/150 [00:46<05:13,  2.32s/it]

(train_sft_tune pid=32993) {'loss': 1.0061, 'grad_norm': 0.6930614113807678, 'learning_rate': 0.00012718325964481002, 'epoch': 0.02}

 11%|█         | 16/150 [00:48<05:23,  2.42s/it]
 11%|█▏        | 17/150 [00:51<05:46,  2.61s/it]
 12%|█▏        | 18/150 [00:53<05:22,  2.44s/it]
 13%|█▎        | 19/150 [00:56<05:27,  2.50s/it]
 13%|█▎        | 20/150 [00:58<04:46,  2.20s/it]

(train_sft_tune pid=32993) {'loss': 0.9331, 'grad_norm': 0.8356968760490417, 'learning_rate': 0.00012250740451080964, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:00<04:39,  2.17s/it]
 15%|█▍        | 22/150 [01:02<04:38,  2.18s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:35:35. Total running time: 41min 5s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 15%|█▌        | 23/150 [01:04<04:45,  2.25s/it]
 16%|█▌        | 24/150 [01:07<05:03,  2.41s/it]
 17%|█▋        | 25/150 [01:10<05:07,  2.46s/it]

(train_sft_tune pid=32993) {'loss': 0.8662, 'grad_norm': 0.5356580018997192, 'learning_rate': 0.00011783154937680927, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:13<05:30,  2.66s/it]
 18%|█▊        | 27/150 [01:15<05:08,  2.51s/it]
 19%|█▊        | 28/150 [01:18<05:20,  2.63s/it]
 19%|█▉        | 29/150 [01:20<04:53,  2.42s/it]
 20%|██        | 30/150 [01:23<05:32,  2.77s/it]

(train_sft_tune pid=32993) {'loss': 1.011, 'grad_norm': 0.5435776114463806, 'learning_rate': 0.00011315569424280891, 'epoch': 0.05}

 21%|██        | 31/150 [01:26<05:35,  2.82s/it]
 21%|██▏       | 32/150 [01:28<05:03,  2.57s/it]
 22%|██▏       | 33/150 [01:31<05:22,  2.75s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:36:05. Total running time: 41min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 23%|██▎       | 34/150 [01:34<05:11,  2.69s/it]
 23%|██▎       | 35/150 [01:36<04:49,  2.51s/it]

(train_sft_tune pid=32993) {'loss': 0.8961, 'grad_norm': 0.6149797439575195, 'learning_rate': 0.00010847983910880855, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:38<04:42,  2.48s/it]
 25%|██▍       | 37/150 [01:41<04:43,  2.51s/it]
 25%|██▌       | 38/150 [01:43<04:37,  2.48s/it]
 26%|██▌       | 39/150 [01:46<04:46,  2.58s/it]
 27%|██▋       | 40/150 [01:49<04:44,  2.59s/it]

(train_sft_tune pid=32993) {'loss': 0.7893, 'grad_norm': 0.615458607673645, 'learning_rate': 0.00010380398397480816, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:52<04:42,  2.59s/it]
 28%|██▊       | 42/150 [01:54<04:41,  2.61s/it]
 29%|██▊       | 43/150 [01:56<04:20,  2.43s/it]
 29%|██▉       | 44/150 [01:59<04:25,  2.51s/it]
 30%|███       | 45/150 [02:01<04:04,  2.33s/it]

(train_sft_tune pid=32993) {'loss': 0.8981, 'grad_norm': 0.6120821237564087, 'learning_rate': 9.91281288408078e-05, 'epoch': 0.07}
Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:36:35. Total running time: 42min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 31%|███       | 46/150 [02:04<04:18,  2.48s/it]
 31%|███▏      | 47/150 [02:06<04:25,  2.58s/it]
 32%|███▏      | 48/150 [02:09<04:37,  2.72s/it]
 33%|███▎      | 49/150 [02:12<04:19,  2.57s/it]
 33%|███▎      | 50/150 [02:15<04:29,  2.69s/it]

(train_sft_tune pid=32993) {'loss': 0.9259, 'grad_norm': 0.5673463344573975, 'learning_rate': 9.445227370680743e-05, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:18<04:46,  2.90s/it]
 35%|███▍      | 52/150 [02:20<04:30,  2.76s/it]
 35%|███▌      | 53/150 [02:23<04:26,  2.74s/it]
 36%|███▌      | 54/150 [02:26<04:17,  2.68s/it]
 37%|███▋      | 55/150 [02:28<03:55,  2.48s/it]

(train_sft_tune pid=32993) {'loss': 0.8136, 'grad_norm': 0.6031177639961243, 'learning_rate': 8.977641857280707e-05, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:30<03:59,  2.55s/it]
 38%|███▊      | 57/150 [02:32<03:38,  2.35s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:37:05. Total running time: 42min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 39%|███▊      | 58/150 [02:35<03:46,  2.46s/it]
 39%|███▉      | 59/150 [02:38<03:52,  2.56s/it]
 40%|████      | 60/150 [02:40<03:44,  2.50s/it]

(train_sft_tune pid=32993) {'loss': 0.9445, 'grad_norm': 0.7045859694480896, 'learning_rate': 8.51005634388067e-05, 'epoch': 0.1}

 41%|████      | 61/150 [02:43<03:50,  2.58s/it]
 41%|████▏     | 62/150 [02:47<04:13,  2.88s/it]
 42%|████▏     | 63/150 [02:50<04:16,  2.95s/it]
 43%|████▎     | 64/150 [02:53<04:24,  3.07s/it]
 43%|████▎     | 65/150 [02:55<03:54,  2.76s/it]

(train_sft_tune pid=32993) {'loss': 0.776, 'grad_norm': 0.5765944123268127, 'learning_rate': 8.042470830480633e-05, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:58<03:54,  2.79s/it]
 45%|████▍     | 67/150 [03:00<03:37,  2.62s/it]
 45%|████▌     | 68/150 [03:02<03:23,  2.48s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:37:35. Total running time: 43min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 46%|████▌     | 69/150 [03:04<03:07,  2.32s/it]
 47%|████▋     | 70/150 [03:07<03:26,  2.58s/it]

(train_sft_tune pid=32993) {'loss': 0.8938, 'grad_norm': 0.5475544929504395, 'learning_rate': 7.574885317080597e-05, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:10<03:35,  2.73s/it]
 48%|████▊     | 72/150 [03:13<03:23,  2.61s/it]
 49%|████▊     | 73/150 [03:16<03:25,  2.67s/it]
 49%|████▉     | 74/150 [03:18<03:16,  2.59s/it]
 50%|█████     | 75/150 [03:21<03:15,  2.61s/it]

(train_sft_tune pid=32993) {'loss': 0.9935, 'grad_norm': 0.5332158207893372, 'learning_rate': 7.10729980368056e-05, 'epoch': 0.12}

 51%|█████     | 76/150 [03:23<03:13,  2.61s/it]
 51%|█████▏    | 77/150 [03:26<03:09,  2.60s/it]
 52%|█████▏    | 78/150 [03:28<02:56,  2.45s/it]
 53%|█████▎    | 79/150 [03:30<02:49,  2.38s/it]
 53%|█████▎    | 80/150 [03:33<02:50,  2.44s/it]

(train_sft_tune pid=32993) {'loss': 0.9554, 'grad_norm': 0.7809261083602905, 'learning_rate': 6.639714290280523e-05, 'epoch': 0.13}
Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:38:05. Total running time: 43min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 54%|█████▍    | 81/150 [03:35<02:54,  2.53s/it]
 55%|█████▍    | 82/150 [03:38<02:55,  2.59s/it]
 55%|█████▌    | 83/150 [03:41<02:50,  2.54s/it]
 56%|█████▌    | 84/150 [03:43<02:41,  2.45s/it]
 57%|█████▋    | 85/150 [03:46<02:46,  2.56s/it]

(train_sft_tune pid=32993) {'loss': 0.9904, 'grad_norm': 0.6971901655197144, 'learning_rate': 6.172128776880487e-05, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:48<02:34,  2.41s/it]
 58%|█████▊    | 87/150 [03:51<02:43,  2.59s/it]
 59%|█████▊    | 88/150 [03:54<02:45,  2.68s/it]
 59%|█████▉    | 89/150 [03:57<02:52,  2.83s/it]
 60%|██████    | 90/150 [03:59<02:30,  2.51s/it]

(train_sft_tune pid=32993) {'loss': 0.9961, 'grad_norm': 0.6014179587364197, 'learning_rate': 5.7045432634804494e-05, 'epoch': 0.14}

 61%|██████    | 91/150 [04:01<02:19,  2.36s/it]
 61%|██████▏   | 92/150 [04:03<02:20,  2.42s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:38:35. Total running time: 44min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 62%|██████▏   | 93/150 [04:06<02:19,  2.45s/it]
 63%|██████▎   | 94/150 [04:08<02:13,  2.38s/it]
 63%|██████▎   | 95/150 [04:11<02:16,  2.48s/it]

(train_sft_tune pid=32993) {'loss': 0.7996, 'grad_norm': 0.507145881652832, 'learning_rate': 5.236957750080412e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:13<02:10,  2.41s/it]
 65%|██████▍   | 97/150 [04:16<02:16,  2.57s/it]
 65%|██████▌   | 98/150 [04:19<02:19,  2.68s/it]
 66%|██████▌   | 99/150 [04:22<02:24,  2.83s/it]
 67%|██████▋   | 100/150 [04:24<02:07,  2.55s/it]

(train_sft_tune pid=32993) {'loss': 0.8944, 'grad_norm': 0.5604210495948792, 'learning_rate': 4.769372236680375e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:26<02:01,  2.48s/it]
 68%|██████▊   | 102/150 [04:28<01:54,  2.39s/it]
 69%|██████▊   | 103/150 [04:31<01:56,  2.48s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:39:05. Total running time: 44min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 69%|██████▉   | 104/150 [04:34<01:56,  2.54s/it]
 70%|███████   | 105/150 [04:36<01:53,  2.53s/it]

(train_sft_tune pid=32993) {'loss': 0.9231, 'grad_norm': 0.5129208564758301, 'learning_rate': 4.301786723280339e-05, 'epoch': 0.17}

 71%|███████   | 106/150 [04:39<01:48,  2.46s/it]
 71%|███████▏  | 107/150 [04:41<01:51,  2.60s/it]
 72%|███████▏  | 108/150 [04:45<01:56,  2.77s/it]
 73%|███████▎  | 109/150 [04:47<01:51,  2.73s/it]
 73%|███████▎  | 110/150 [04:49<01:40,  2.51s/it]

(train_sft_tune pid=32993) {'loss': 0.8348, 'grad_norm': 0.6200331449508667, 'learning_rate': 3.834201209880302e-05, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:52<01:46,  2.72s/it]
 75%|███████▍  | 112/150 [04:56<01:47,  2.84s/it]
 75%|███████▌  | 113/150 [04:58<01:37,  2.64s/it]
 76%|███████▌  | 114/150 [05:01<01:37,  2.71s/it]
 77%|███████▋  | 115/150 [05:03<01:28,  2.53s/it]

(train_sft_tune pid=32993) {'loss': 0.8618, 'grad_norm': 0.6768903136253357, 'learning_rate': 3.366615696480265e-05, 'epoch': 0.18}
Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:39:35. Total running time: 45min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 77%|███████▋  | 116/150 [05:05<01:24,  2.49s/it]
 78%|███████▊  | 117/150 [05:08<01:28,  2.67s/it]
 79%|███████▊  | 118/150 [05:11<01:29,  2.80s/it]
 79%|███████▉  | 119/150 [05:14<01:27,  2.83s/it]
 80%|████████  | 120/150 [05:16<01:19,  2.64s/it]

(train_sft_tune pid=32993) {'loss': 1.0742, 'grad_norm': 0.6167656183242798, 'learning_rate': 2.8990301830802283e-05, 'epoch': 0.19}

 81%|████████  | 121/150 [05:20<01:21,  2.83s/it]
 81%|████████▏ | 122/150 [05:23<01:21,  2.92s/it]
 82%|████████▏ | 123/150 [05:25<01:15,  2.79s/it]
 83%|████████▎ | 124/150 [05:29<01:15,  2.92s/it]
 83%|████████▎ | 125/150 [05:31<01:09,  2.80s/it]

(train_sft_tune pid=32993) {'loss': 0.8478, 'grad_norm': 0.5468034148216248, 'learning_rate': 2.4314446696801915e-05, 'epoch': 0.2}
Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:40:06. Total running time: 45min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 84%|████████▍ | 126/150 [05:34<01:07,  2.82s/it]
 85%|████████▍ | 127/150 [05:37<01:04,  2.82s/it]
 85%|████████▌ | 128/150 [05:39<00:59,  2.73s/it]
 86%|████████▌ | 129/150 [05:41<00:50,  2.39s/it]
 87%|████████▋ | 130/150 [05:44<00:49,  2.49s/it]

(train_sft_tune pid=32993) {'loss': 0.8484, 'grad_norm': 0.5528503060340881, 'learning_rate': 1.963859156280155e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:46<00:47,  2.48s/it]
 88%|████████▊ | 132/150 [05:49<00:46,  2.60s/it]
 89%|████████▊ | 133/150 [05:51<00:41,  2.46s/it]
 89%|████████▉ | 134/150 [05:55<00:45,  2.84s/it]
 90%|█████████ | 135/150 [05:58<00:42,  2.83s/it]

(train_sft_tune pid=32993) {'loss': 0.875, 'grad_norm': 0.5754672288894653, 'learning_rate': 1.4962736428801178e-05, 'epoch': 0.22}

 91%|█████████ | 136/150 [06:01<00:41,  2.94s/it]
 91%|█████████▏| 137/150 [06:03<00:35,  2.69s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:40:36. Total running time: 46min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 92%|█████████▏| 138/150 [06:06<00:32,  2.70s/it]
 93%|█████████▎| 139/150 [06:08<00:29,  2.68s/it]
 93%|█████████▎| 140/150 [06:11<00:25,  2.56s/it]

(train_sft_tune pid=32993) {'loss': 0.9473, 'grad_norm': 0.5656006336212158, 'learning_rate': 1.028688129480081e-05, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:13<00:23,  2.63s/it]
 95%|█████████▍| 142/150 [06:16<00:21,  2.69s/it]
 95%|█████████▌| 143/150 [06:19<00:19,  2.75s/it]
 96%|█████████▌| 144/150 [06:22<00:17,  2.93s/it]
 97%|█████████▋| 145/150 [06:25<00:14,  2.82s/it]

(train_sft_tune pid=32993) {'loss': 0.8779, 'grad_norm': 0.5661571025848389, 'learning_rate': 5.611026160800442e-06, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:28<00:10,  2.75s/it]
 98%|█████████▊| 147/150 [06:30<00:08,  2.72s/it]
 99%|█████████▊| 148/150 [06:33<00:05,  2.78s/it]

Trial status: 5 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:41:06. Total running time: 46min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f628069f with train_loss=0.9280647850036621 and params={'lr': 7.276098541670044e-05, 'r': 16, 'lora_alpha': 32}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_bad7439a   RUNNING      0.0001356      32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_6193e7f8   PENDING      1.4578e-05     16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 99%|█████████▉| 149/150 [06:36<00:02,  2.67s/it]
100%|██████████| 150/150 [06:38<00:00,  2.70s/it]

(train_sft_tune pid=32993) {'loss': 0.9373, 'grad_norm': 0.5448716878890991, 'learning_rate': 9.351710268000736e-07, 'epoch': 0.24}

100%|██████████| 150/150 [06:40<00:00,  2.67s/it]

(train_sft_tune pid=32993) {'train_runtime': 400.0367, 'train_samples_per_second': 3.0, 'train_steps_per_second': 0.375, 'train_loss': 0.9134614070256551, 'epoch': 0.24}

Trial train_sft_tune_bad7439a completed after 1 iterations at 2025-11-29 16:41:12. Total running time: 46min 42s
+--------------------------------------------------+
| Trial train_sft_tune_bad7439a result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         446.411 |
| time_total_s                             446.411 |
| training_iteration                             1 |
| train_loss                               0.91346 |
+--------------------------------------------------+
(train_sft_tune pid=32993) history of tuning  [{'loss': 1.0808, 'grad_norm': 0.7531550526618958, 'learning_rate': 0.00010847983910880855, 'epoch': 0.008, 'step': 5}, {'loss': 0.9123, 'grad_norm': 0.5921828746795654, 'learning_rate': 0.00013185911477881038, 'epoch': 0.016, 'step': 10}, {'loss': 1.0061, 'grad_norm': 0.6930614113807678, 'learning_rate': 0.00012718325964481002, 'epoch': 0.024, 'step': 15}, {'loss': 0.9331, 'grad_norm': 0.8356968760490417, 'learning_rate': 0.00012250740451080964, 'epoch': 0.032, 'step': 20}, {'loss': 0.8662, 'grad_norm': 0.5356580018997192, 'learning_rate': 0.00011783154937680927, 'epoch': 0.04, 'step': 25}, {'loss': 1.011, 'grad_norm': 0.5435776114463806, 'learning_rate': 0.00011315569424280891, 'epoch': 0.048, 'step': 30}, {'loss': 0.8961, 'grad_norm': 0.6149797439575195, 'learning_rate': 0.00010847983910880855, 'epoch': 0.056, 'step': 35}, {'loss': 0.7893, 'grad_norm': 0.615458607673645, 'learning_rate': 0.00010380398397480816, 'epoch': 0.064, 'step': 40}, {'loss': 0.8981, 'grad_norm': 0.6120821237564087, 'learning_rate': 9.91281288408078e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9259, 'grad_norm': 0.5673463344573975, 'learning_rate': 9.445227370680743e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8136, 'grad_norm': 0.6031177639961243, 'learning_rate': 8.977641857280707e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9445, 'grad_norm': 0.7045859694480896, 'learning_rate': 8.51005634388067e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.776, 'grad_norm': 0.5765944123268127, 'learning_rate': 8.042470830480633e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.8938, 'grad_norm': 0.5475544929504395, 'learning_rate': 7.574885317080597e-05, 'epoch': 0.112, 'step': 70}, {'loss': 0.9935, 'grad_norm': 0.5332158207893372, 'learning_rate': 7.10729980368056e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9554, 'grad_norm': 0.7809261083602905, 'learning_rate': 6.639714290280523e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.9904, 'grad_norm': 0.6971901655197144, 'learning_rate': 6.172128776880487e-05, 'epoch': 0.136, 'step': 85}, {'loss': 0.9961, 'grad_norm': 0.6014179587364197, 'learning_rate': 5.7045432634804494e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.7996, 'grad_norm': 0.507145881652832, 'learning_rate': 5.236957750080412e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8944, 'grad_norm': 0.5604210495948792, 'learning_rate': 4.769372236680375e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9231, 'grad_norm': 0.5129208564758301, 'learning_rate': 4.301786723280339e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8348, 'grad_norm': 0.6200331449508667, 'learning_rate': 3.834201209880302e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8618, 'grad_norm': 0.6768903136253357, 'learning_rate': 3.366615696480265e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0742, 'grad_norm': 0.6167656183242798, 'learning_rate': 2.8990301830802283e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8478, 'grad_norm': 0.5468034148216248, 'learning_rate': 2.4314446696801915e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8484, 'grad_norm': 0.5528503060340881, 'learning_rate': 1.963859156280155e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.875, 'grad_norm': 0.5754672288894653, 'learning_rate': 1.4962736428801178e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9473, 'grad_norm': 0.5656006336212158, 'learning_rate': 1.028688129480081e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8779, 'grad_norm': 0.5661571025848389, 'learning_rate': 5.611026160800442e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9373, 'grad_norm': 0.5448716878890991, 'learning_rate': 9.351710268000736e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 400.0367, 'train_samples_per_second': 3.0, 'train_steps_per_second': 0.375, 'total_flos': 4944308261511168.0, 'train_loss': 0.9134614070256551, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=32993) Reporting loss: 0.9134614070256551

Trial train_sft_tune_6193e7f8 started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_6193e7f8 config           |
+------------------------------------------------+
| lora_alpha                                  64 |
| lr                                       1e-05 |
| r                                           16 |
+------------------------------------------------+
(train_sft_tune pid=35085) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=35085) 2025-11-29 16:41:27.097070: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=35085) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=35085) E0000 00:00:1764434487.132946   35143 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=35085) E0000 00:00:1764434487.144120   35143 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=35085) W0000 00:00:1764434487.169866   35143 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=35085) W0000 00:00:1764434487.169908   35143 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=35085) W0000 00:00:1764434487.169912   35143 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=35085) W0000 00:00:1764434487.169914   35143 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:41:36. Total running time: 47min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=35085) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=35085) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=35085)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=35085) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=35085) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=35085)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=35085) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=35085) [2025-11-29 16:41:50,413 E 35085 35124] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=35085) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=35085) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=35085) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=35085)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=35085) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=35085) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=35085)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:42:06. Total running time: 47min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=35085) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:12<30:10, 12.15s/it]
  1%|▏         | 2/150 [00:14<15:27,  6.27s/it]
  2%|▏         | 3/150 [00:17<11:38,  4.75s/it]
  3%|▎         | 4/150 [00:20<09:40,  3.98s/it]
  3%|▎         | 5/150 [00:22<08:01,  3.32s/it]

(train_sft_tune pid=35085) {'loss': 1.0924, 'grad_norm': 1.3184741735458374, 'learning_rate': 1.1662410984641912e-05, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:30,  3.13s/it]
  5%|▍         | 7/150 [00:27<07:08,  3.00s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:42:36. Total running time: 48min 6s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

  5%|▌         | 8/150 [00:30<06:59,  2.96s/it]
  6%|▌         | 9/150 [00:33<06:47,  2.89s/it]
  7%|▋         | 10/150 [00:36<06:43,  2.88s/it]

(train_sft_tune pid=35085) {'loss': 0.9597, 'grad_norm': 1.0093135833740234, 'learning_rate': 1.4175861627883703e-05, 'epoch': 0.02}

  7%|▋         | 11/150 [00:39<06:48,  2.94s/it]
  8%|▊         | 12/150 [00:41<06:24,  2.79s/it]
  9%|▊         | 13/150 [00:44<06:41,  2.93s/it]
  9%|▉         | 14/150 [00:47<06:14,  2.76s/it]
 10%|█         | 15/150 [00:49<05:41,  2.53s/it]

(train_sft_tune pid=35085) {'loss': 1.0599, 'grad_norm': 0.9991586804389954, 'learning_rate': 1.3673171499235346e-05, 'epoch': 0.02}

 11%|█         | 16/150 [00:52<05:52,  2.63s/it]
 11%|█▏        | 17/150 [00:55<06:12,  2.80s/it]
 12%|█▏        | 18/150 [00:57<05:38,  2.57s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:43:06. Total running time: 48min 36s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 13%|█▎        | 19/150 [01:00<05:43,  2.62s/it]
 13%|█▎        | 20/150 [01:01<05:02,  2.33s/it]

(train_sft_tune pid=35085) {'loss': 0.9842, 'grad_norm': 1.3578966856002808, 'learning_rate': 1.3170481370586987e-05, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:04<04:57,  2.30s/it]
 15%|█▍        | 22/150 [01:06<04:54,  2.30s/it]
 15%|█▌        | 23/150 [01:08<04:59,  2.36s/it]
 16%|█▌        | 24/150 [01:11<05:17,  2.52s/it]
 17%|█▋        | 25/150 [01:14<05:21,  2.57s/it]

(train_sft_tune pid=35085) {'loss': 0.9133, 'grad_norm': 0.82823246717453, 'learning_rate': 1.2667791241938629e-05, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:17<05:46,  2.79s/it]
 18%|█▊        | 27/150 [01:19<05:22,  2.62s/it]
 19%|█▊        | 28/150 [01:22<05:33,  2.73s/it]
 19%|█▉        | 29/150 [01:24<05:02,  2.50s/it]
 20%|██        | 30/150 [01:28<05:46,  2.89s/it]

(train_sft_tune pid=35085) {'loss': 1.06, 'grad_norm': 0.911141574382782, 'learning_rate': 1.2165101113290271e-05, 'epoch': 0.05}
Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:43:36. Total running time: 49min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 21%|██        | 31/150 [01:31<05:51,  2.95s/it]
 21%|██▏       | 32/150 [01:33<05:17,  2.69s/it]
 22%|██▏       | 33/150 [01:37<05:37,  2.88s/it]
 23%|██▎       | 34/150 [01:39<05:26,  2.82s/it]
 23%|██▎       | 35/150 [01:42<05:07,  2.67s/it]

(train_sft_tune pid=35085) {'loss': 0.9355, 'grad_norm': 0.9670218825340271, 'learning_rate': 1.1662410984641912e-05, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:44<05:00,  2.64s/it]
 25%|██▍       | 37/150 [01:47<05:00,  2.66s/it]
 25%|██▌       | 38/150 [01:49<04:49,  2.58s/it]
 26%|██▌       | 39/150 [01:52<04:59,  2.70s/it]
 27%|██▋       | 40/150 [01:55<05:01,  2.74s/it]

(train_sft_tune pid=35085) {'loss': 0.8334, 'grad_norm': 0.9320001006126404, 'learning_rate': 1.1159720855993554e-05, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:58<04:59,  2.75s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:44:06. Total running time: 49min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 28%|██▊       | 42/150 [02:01<04:58,  2.76s/it]
 29%|██▊       | 43/150 [02:03<04:32,  2.54s/it]
 29%|██▉       | 44/150 [02:06<04:37,  2.61s/it]
 30%|███       | 45/150 [02:08<04:19,  2.47s/it]
 30%|███       | 45/150 [02:08<04:19,  2.47s/it]

(train_sft_tune pid=35085) {'loss': 0.9471, 'grad_norm': 0.9674147963523865, 'learning_rate': 1.0657030727345196e-05, 'epoch': 0.07}

 31%|███       | 46/150 [02:11<04:31,  2.61s/it]
 31%|███▏      | 47/150 [02:14<04:40,  2.72s/it]
 32%|███▏      | 48/150 [02:17<04:51,  2.85s/it]
 33%|███▎      | 49/150 [02:19<04:29,  2.67s/it]
 33%|███▎      | 50/150 [02:22<04:42,  2.82s/it]

(train_sft_tune pid=35085) {'loss': 0.9596, 'grad_norm': 0.9792876243591309, 'learning_rate': 1.0154340598696838e-05, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:26<05:01,  3.04s/it]
 35%|███▍      | 52/150 [02:28<04:42,  2.89s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:44:36. Total running time: 50min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 35%|███▌      | 53/150 [02:31<04:35,  2.84s/it]
 36%|███▌      | 54/150 [02:34<04:28,  2.80s/it]
 37%|███▋      | 55/150 [02:36<04:07,  2.60s/it]

(train_sft_tune pid=35085) {'loss': 0.8526, 'grad_norm': 0.9435152411460876, 'learning_rate': 9.651650470048479e-06, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:39<04:10,  2.67s/it]
 38%|███▊      | 57/150 [02:41<03:48,  2.45s/it]
 39%|███▊      | 58/150 [02:43<03:52,  2.53s/it]
 39%|███▉      | 59/150 [02:46<03:56,  2.60s/it]
 40%|████      | 60/150 [02:49<03:52,  2.58s/it]

(train_sft_tune pid=35085) {'loss': 0.9883, 'grad_norm': 1.1335753202438354, 'learning_rate': 9.148960341400121e-06, 'epoch': 0.1}

 41%|████      | 61/150 [02:51<03:57,  2.67s/it]
 41%|████▏     | 62/150 [02:55<04:22,  2.98s/it]
 42%|████▏     | 63/150 [02:58<04:25,  3.05s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:45:06. Total running time: 50min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 43%|████▎     | 64/150 [03:02<04:34,  3.19s/it]
 43%|████▎     | 65/150 [03:04<04:03,  2.86s/it]

(train_sft_tune pid=35085) {'loss': 0.8143, 'grad_norm': 0.9452593922615051, 'learning_rate': 8.646270212751763e-06, 'epoch': 0.1}

 44%|████▍     | 66/150 [03:07<04:02,  2.89s/it]
 45%|████▍     | 67/150 [03:09<03:44,  2.70s/it]
 45%|████▌     | 68/150 [03:11<03:28,  2.54s/it]
 46%|████▌     | 69/150 [03:13<03:14,  2.40s/it]
 47%|████▋     | 70/150 [03:17<03:33,  2.67s/it]

(train_sft_tune pid=35085) {'loss': 0.9357, 'grad_norm': 0.9154446721076965, 'learning_rate': 8.143580084103404e-06, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:20<03:44,  2.85s/it]
 48%|████▊     | 72/150 [03:22<03:31,  2.71s/it]
 49%|████▊     | 73/150 [03:25<03:33,  2.78s/it]
 49%|████▉     | 74/150 [03:28<03:24,  2.69s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:45:36. Total running time: 51min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 50%|█████     | 75/150 [03:31<03:23,  2.72s/it]

(train_sft_tune pid=35085) {'loss': 1.0221, 'grad_norm': 0.8610120415687561, 'learning_rate': 7.640889955455046e-06, 'epoch': 0.12}

 51%|█████     | 76/150 [03:33<03:20,  2.71s/it]
 51%|█████▏    | 77/150 [03:36<03:16,  2.69s/it]
 52%|█████▏    | 78/150 [03:38<03:02,  2.53s/it]
 53%|█████▎    | 79/150 [03:40<02:54,  2.46s/it]
 53%|█████▎    | 80/150 [03:43<02:56,  2.53s/it]

(train_sft_tune pid=35085) {'loss': 0.9922, 'grad_norm': 1.2896531820297241, 'learning_rate': 7.138199826806688e-06, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:46<03:00,  2.61s/it]
 55%|█████▍    | 82/150 [03:49<03:01,  2.67s/it]
 55%|█████▌    | 83/150 [03:51<02:55,  2.62s/it]
 56%|█████▌    | 84/150 [03:54<02:48,  2.55s/it]
 57%|█████▋    | 85/150 [03:57<02:52,  2.66s/it]

(train_sft_tune pid=35085) {'loss': 1.0315, 'grad_norm': 1.1337248086929321, 'learning_rate': 6.63550969815833e-06, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:59<02:40,  2.51s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:46:06. Total running time: 51min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 58%|█████▊    | 87/150 [04:02<02:48,  2.68s/it]
 59%|█████▊    | 88/150 [04:05<02:50,  2.76s/it]
 59%|█████▉    | 89/150 [04:08<02:57,  2.91s/it]
 60%|██████    | 90/150 [04:10<02:34,  2.58s/it]

(train_sft_tune pid=35085) {'loss': 1.025, 'grad_norm': 0.9478867650032043, 'learning_rate': 6.1328195695099716e-06, 'epoch': 0.14}

 61%|██████    | 91/150 [04:12<02:22,  2.42s/it]
 61%|██████▏   | 92/150 [04:14<02:23,  2.47s/it]
 62%|██████▏   | 93/150 [04:17<02:23,  2.51s/it]
 63%|██████▎   | 94/150 [04:19<02:15,  2.42s/it]
 63%|██████▎   | 95/150 [04:22<02:19,  2.53s/it]

(train_sft_tune pid=35085) {'loss': 0.8318, 'grad_norm': 0.8872599601745605, 'learning_rate': 5.630129440861613e-06, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:24<02:12,  2.45s/it]
 65%|██████▍   | 97/150 [04:27<02:18,  2.62s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:46:37. Total running time: 52min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 65%|██████▌   | 98/150 [04:30<02:21,  2.73s/it]
 66%|██████▌   | 99/150 [04:33<02:26,  2.87s/it]
 67%|██████▋   | 100/150 [04:35<02:09,  2.59s/it]

(train_sft_tune pid=35085) {'loss': 0.9244, 'grad_norm': 0.9600462317466736, 'learning_rate': 5.127439312213255e-06, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:38<02:02,  2.51s/it]
 68%|██████▊   | 102/150 [04:40<01:55,  2.42s/it]
 69%|██████▊   | 103/150 [04:43<01:58,  2.52s/it]
 69%|██████▉   | 104/150 [04:45<01:57,  2.56s/it]
 70%|███████   | 105/150 [04:48<01:54,  2.55s/it]

(train_sft_tune pid=35085) {'loss': 0.9555, 'grad_norm': 0.8847124576568604, 'learning_rate': 4.624749183564897e-06, 'epoch': 0.17}

 71%|███████   | 106/150 [04:50<01:49,  2.49s/it]
 71%|███████▏  | 107/150 [04:53<01:53,  2.63s/it]
 72%|███████▏  | 108/150 [04:56<01:57,  2.80s/it]
 73%|███████▎  | 109/150 [04:59<01:52,  2.75s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:47:07. Total running time: 52min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 73%|███████▎  | 110/150 [05:01<01:40,  2.51s/it]

(train_sft_tune pid=35085) {'loss': 0.8745, 'grad_norm': 1.0244698524475098, 'learning_rate': 4.1220590549165386e-06, 'epoch': 0.18}

 74%|███████▍  | 111/150 [05:04<01:46,  2.73s/it]
 75%|███████▍  | 112/150 [05:07<01:48,  2.85s/it]
 75%|███████▌  | 113/150 [05:09<01:37,  2.64s/it]
 76%|███████▌  | 114/150 [05:12<01:37,  2.70s/it]
 77%|███████▋  | 115/150 [05:14<01:28,  2.52s/it]

(train_sft_tune pid=35085) {'loss': 0.9071, 'grad_norm': 1.1296133995056152, 'learning_rate': 3.6193689262681797e-06, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:17<01:24,  2.48s/it]
 78%|███████▊  | 117/150 [05:20<01:28,  2.68s/it]
 79%|███████▊  | 118/150 [05:23<01:29,  2.80s/it]
 79%|███████▉  | 119/150 [05:26<01:27,  2.83s/it]
 80%|████████  | 120/150 [05:28<01:19,  2.64s/it]

(train_sft_tune pid=35085) {'loss': 1.1151, 'grad_norm': 1.0862970352172852, 'learning_rate': 3.1166787976198217e-06, 'epoch': 0.19}
Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:47:37. Total running time: 53min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 81%|████████  | 121/150 [05:31<01:22,  2.83s/it]
 81%|████████▏ | 122/150 [05:35<01:22,  2.95s/it]
 82%|████████▏ | 123/150 [05:37<01:15,  2.81s/it]
 83%|████████▎ | 124/150 [05:40<01:16,  2.93s/it]
 83%|████████▎ | 125/150 [05:43<01:10,  2.82s/it]

(train_sft_tune pid=35085) {'loss': 0.8805, 'grad_norm': 0.9707982540130615, 'learning_rate': 2.613988668971463e-06, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:46<01:08,  2.84s/it]
 85%|████████▍ | 127/150 [05:49<01:05,  2.85s/it]
 85%|████████▌ | 128/150 [05:51<01:00,  2.74s/it]
 86%|████████▌ | 129/150 [05:53<00:50,  2.42s/it]
 87%|████████▋ | 130/150 [05:56<00:50,  2.50s/it]

(train_sft_tune pid=35085) {'loss': 0.8833, 'grad_norm': 0.961113691329956, 'learning_rate': 2.111298540323105e-06, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:58<00:47,  2.49s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:48:07. Total running time: 53min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 88%|████████▊ | 132/150 [06:01<00:46,  2.60s/it]
 89%|████████▊ | 133/150 [06:03<00:41,  2.45s/it]
 89%|████████▉ | 134/150 [06:07<00:44,  2.80s/it]
 90%|█████████ | 135/150 [06:09<00:41,  2.76s/it]

(train_sft_tune pid=35085) {'loss': 0.9055, 'grad_norm': 0.9431411027908325, 'learning_rate': 1.6086084116747465e-06, 'epoch': 0.22}

 91%|█████████ | 136/150 [06:12<00:39,  2.85s/it]
 91%|█████████▏| 137/150 [06:14<00:33,  2.59s/it]
 92%|█████████▏| 138/150 [06:17<00:30,  2.58s/it]
 93%|█████████▎| 139/150 [06:19<00:27,  2.54s/it]
 93%|█████████▎| 140/150 [06:21<00:24,  2.42s/it]

(train_sft_tune pid=35085) {'loss': 0.9795, 'grad_norm': 0.9312751293182373, 'learning_rate': 1.1059182830263883e-06, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:24<00:22,  2.47s/it]
 95%|█████████▍| 142/150 [06:27<00:20,  2.52s/it]
 95%|█████████▌| 143/150 [06:29<00:18,  2.58s/it]

Trial status: 6 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:48:37. Total running time: 54min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_6193e7f8   RUNNING      1.4578e-05     16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_df75121a   PENDING      4.54764e-05    16             32                                            |
+--------------------------------------------------------------------------------------------------------------------+

 96%|█████████▌| 144/150 [06:32<00:16,  2.74s/it]
 97%|█████████▋| 145/150 [06:35<00:13,  2.65s/it]

(train_sft_tune pid=35085) {'loss': 0.9114, 'grad_norm': 0.9650323987007141, 'learning_rate': 6.032281543780299e-07, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:37<00:10,  2.58s/it]
 98%|█████████▊| 147/150 [06:40<00:07,  2.58s/it]
 99%|█████████▊| 148/150 [06:43<00:05,  2.64s/it]
 99%|█████████▉| 149/150 [06:45<00:02,  2.55s/it]
100%|██████████| 150/150 [06:48<00:00,  2.58s/it]

(train_sft_tune pid=35085) {'loss': 0.9833, 'grad_norm': 0.9254371523857117, 'learning_rate': 1.0053802572967166e-07, 'epoch': 0.24}

Trial train_sft_tune_6193e7f8 completed after 1 iterations at 2025-11-29 16:48:55. Total running time: 54min 26s
+--------------------------------------------------+
| Trial train_sft_tune_6193e7f8 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         454.236 |
| time_total_s                             454.236 |
| training_iteration                             1 |
| train_loss                               0.95196 |
+--------------------------------------------------+
(train_sft_tune pid=35085) {'train_runtime': 409.0359, 'train_samples_per_second': 2.934, 'train_steps_per_second': 0.367, 'train_loss': 0.951955410639445, 'epoch': 0.24}
(train_sft_tune pid=35085) history of tuning  [{'loss': 1.0924, 'grad_norm': 1.3184741735458374, 'learning_rate': 1.1662410984641912e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9597, 'grad_norm': 1.0093135833740234, 'learning_rate': 1.4175861627883703e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0599, 'grad_norm': 0.9991586804389954, 'learning_rate': 1.3673171499235346e-05, 'epoch': 0.024, 'step': 15}, {'loss': 0.9842, 'grad_norm': 1.3578966856002808, 'learning_rate': 1.3170481370586987e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.9133, 'grad_norm': 0.82823246717453, 'learning_rate': 1.2667791241938629e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.06, 'grad_norm': 0.911141574382782, 'learning_rate': 1.2165101113290271e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9355, 'grad_norm': 0.9670218825340271, 'learning_rate': 1.1662410984641912e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8334, 'grad_norm': 0.9320001006126404, 'learning_rate': 1.1159720855993554e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9471, 'grad_norm': 0.9674147963523865, 'learning_rate': 1.0657030727345196e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9596, 'grad_norm': 0.9792876243591309, 'learning_rate': 1.0154340598696838e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8526, 'grad_norm': 0.9435152411460876, 'learning_rate': 9.651650470048479e-06, 'epoch': 0.088, 'step': 55}, {'loss': 0.9883, 'grad_norm': 1.1335753202438354, 'learning_rate': 9.148960341400121e-06, 'epoch': 0.096, 'step': 60}, {'loss': 0.8143, 'grad_norm': 0.9452593922615051, 'learning_rate': 8.646270212751763e-06, 'epoch': 0.104, 'step': 65}, {'loss': 0.9357, 'grad_norm': 0.9154446721076965, 'learning_rate': 8.143580084103404e-06, 'epoch': 0.112, 'step': 70}, {'loss': 1.0221, 'grad_norm': 0.8610120415687561, 'learning_rate': 7.640889955455046e-06, 'epoch': 0.12, 'step': 75}, {'loss': 0.9922, 'grad_norm': 1.2896531820297241, 'learning_rate': 7.138199826806688e-06, 'epoch': 0.128, 'step': 80}, {'loss': 1.0315, 'grad_norm': 1.1337248086929321, 'learning_rate': 6.63550969815833e-06, 'epoch': 0.136, 'step': 85}, {'loss': 1.025, 'grad_norm': 0.9478867650032043, 'learning_rate': 6.1328195695099716e-06, 'epoch': 0.144, 'step': 90}, {'loss': 0.8318, 'grad_norm': 0.8872599601745605, 'learning_rate': 5.630129440861613e-06, 'epoch': 0.152, 'step': 95}, {'loss': 0.9244, 'grad_norm': 0.9600462317466736, 'learning_rate': 5.127439312213255e-06, 'epoch': 0.16, 'step': 100}, {'loss': 0.9555, 'grad_norm': 0.8847124576568604, 'learning_rate': 4.624749183564897e-06, 'epoch': 0.168, 'step': 105}, {'loss': 0.8745, 'grad_norm': 1.0244698524475098, 'learning_rate': 4.1220590549165386e-06, 'epoch': 0.176, 'step': 110}, {'loss': 0.9071, 'grad_norm': 1.1296133995056152, 'learning_rate': 3.6193689262681797e-06, 'epoch': 0.184, 'step': 115}, {'loss': 1.1151, 'grad_norm': 1.0862970352172852, 'learning_rate': 3.1166787976198217e-06, 'epoch': 0.192, 'step': 120}, {'loss': 0.8805, 'grad_norm': 0.9707982540130615, 'learning_rate': 2.613988668971463e-06, 'epoch': 0.2, 'step': 125}, {'loss': 0.8833, 'grad_norm': 0.961113691329956, 'learning_rate': 2.111298540323105e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.9055, 'grad_norm': 0.9431411027908325, 'learning_rate': 1.6086084116747465e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9795, 'grad_norm': 0.9312751293182373, 'learning_rate': 1.1059182830263883e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.9114, 'grad_norm': 0.9650323987007141, 'learning_rate': 6.032281543780299e-07, 'epoch': 0.232, 'step': 145}, {'loss': 0.9833, 'grad_norm': 0.9254371523857117, 'learning_rate': 1.0053802572967166e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 409.0359, 'train_samples_per_second': 2.934, 'train_steps_per_second': 0.367, 'total_flos': 4888333847519232.0, 'train_loss': 0.951955410639445, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=35085) Reporting loss: 0.951955410639445

100%|██████████| 150/150 [06:49<00:00,  2.73s/it]

Trial train_sft_tune_df75121a started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_df75121a config           |
+------------------------------------------------+
| lora_alpha                                  32 |
| lr                                       5e-05 |
| r                                           16 |
+------------------------------------------------+

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:49:07. Total running time: 54min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=37213) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=37213) 2025-11-29 16:49:10.596841: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=37213) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=37213) E0000 00:00:1764434950.619130   37274 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=37213) E0000 00:00:1764434950.625972   37274 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=37213) W0000 00:00:1764434950.643611   37274 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=37213) W0000 00:00:1764434950.643647   37274 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=37213) W0000 00:00:1764434950.643650   37274 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=37213) W0000 00:00:1764434950.643652   37274 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=37213) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=37213) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=37213)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=37213) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=37213) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=37213)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=37213) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=37213) [2025-11-29 16:49:34,663 E 37213 37256] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:49:37. Total running time: 55min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=37213) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=37213) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=37213) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=37213)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=37213) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=37213) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=37213)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=37213) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:12<31:29, 12.68s/it]
  1%|▏         | 2/150 [00:14<16:01,  6.50s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:50:07. Total running time: 55min 37s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  2%|▏         | 3/150 [00:17<11:40,  4.77s/it]
  3%|▎         | 4/150 [00:20<09:28,  3.90s/it]
  3%|▎         | 5/150 [00:22<07:42,  3.19s/it]

(train_sft_tune pid=37213) {'loss': 1.0915, 'grad_norm': 0.6526359915733337, 'learning_rate': 3.6381080977831357e-05, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:01,  2.93s/it]
  5%|▍         | 7/150 [00:27<06:40,  2.80s/it]
  5%|▌         | 8/150 [00:29<06:25,  2.72s/it]
  6%|▌         | 9/150 [00:31<06:10,  2.62s/it]
  7%|▋         | 10/150 [00:34<06:00,  2.58s/it]

(train_sft_tune pid=37213) {'loss': 0.9517, 'grad_norm': 0.5122365355491638, 'learning_rate': 4.422183118857087e-05, 'epoch': 0.02}

  7%|▋         | 11/150 [00:37<06:02,  2.61s/it]
  8%|▊         | 12/150 [00:39<05:44,  2.49s/it]
  9%|▊         | 13/150 [00:42<06:01,  2.64s/it]
  9%|▉         | 14/150 [00:44<05:39,  2.50s/it]
 10%|█         | 15/150 [00:46<05:08,  2.29s/it]

(train_sft_tune pid=37213) {'loss': 1.0469, 'grad_norm': 0.5077704787254333, 'learning_rate': 4.265368114642296e-05, 'epoch': 0.02}
Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:50:37. Total running time: 56min 7s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 11%|█         | 16/150 [00:48<05:18,  2.38s/it]
 11%|█▏        | 17/150 [00:51<05:41,  2.57s/it]
 12%|█▏        | 18/150 [00:53<05:16,  2.40s/it]
 13%|█▎        | 19/150 [00:56<05:21,  2.46s/it]
 13%|█▎        | 20/150 [00:57<04:41,  2.17s/it]

(train_sft_tune pid=37213) {'loss': 0.9686, 'grad_norm': 0.6832707524299622, 'learning_rate': 4.1085531104275065e-05, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:00<04:34,  2.13s/it]
 15%|█▍        | 22/150 [01:02<04:33,  2.13s/it]
 15%|█▌        | 23/150 [01:04<04:40,  2.21s/it]
 16%|█▌        | 24/150 [01:07<04:58,  2.37s/it]
 17%|█▋        | 25/150 [01:09<05:03,  2.43s/it]

(train_sft_tune pid=37213) {'loss': 0.8988, 'grad_norm': 0.4327300190925598, 'learning_rate': 3.951738106212716e-05, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:12<05:27,  2.64s/it]
 18%|█▊        | 27/150 [01:15<05:05,  2.48s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:51:07. Total running time: 56min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 19%|█▊        | 28/150 [01:17<05:16,  2.60s/it]
 19%|█▉        | 29/150 [01:19<04:50,  2.40s/it]
 20%|██        | 30/150 [01:23<05:28,  2.73s/it]

(train_sft_tune pid=37213) {'loss': 1.0409, 'grad_norm': 0.5210758447647095, 'learning_rate': 3.7949231019979255e-05, 'epoch': 0.05}

 21%|██        | 31/150 [01:26<05:31,  2.79s/it]
 21%|██▏       | 32/150 [01:28<04:59,  2.54s/it]
 22%|██▏       | 33/150 [01:31<05:18,  2.72s/it]
 23%|██▎       | 34/150 [01:33<05:09,  2.66s/it]
 23%|██▎       | 35/150 [01:36<04:47,  2.50s/it]

(train_sft_tune pid=37213) {'loss': 0.9194, 'grad_norm': 0.5550289154052734, 'learning_rate': 3.6381080977831357e-05, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:38<04:40,  2.46s/it]
 25%|██▍       | 37/150 [01:40<04:40,  2.49s/it]
 25%|██▌       | 38/150 [01:43<04:31,  2.43s/it]
 26%|██▌       | 39/150 [01:46<04:41,  2.53s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:51:37. Total running time: 57min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 27%|██▋       | 40/150 [01:48<04:40,  2.55s/it]

(train_sft_tune pid=37213) {'loss': 0.8157, 'grad_norm': 0.5193595886230469, 'learning_rate': 3.481293093568345e-05, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:51<04:38,  2.55s/it]
 28%|██▊       | 42/150 [01:53<04:38,  2.58s/it]
 29%|██▊       | 43/150 [01:55<04:14,  2.38s/it]
 29%|██▉       | 44/150 [01:58<04:21,  2.47s/it]
 30%|███       | 45/150 [02:00<04:01,  2.30s/it]

(train_sft_tune pid=37213) {'loss': 0.9276, 'grad_norm': 0.5533820986747742, 'learning_rate': 3.3244780893535547e-05, 'epoch': 0.07}

 31%|███       | 46/150 [02:03<04:11,  2.42s/it]
 31%|███▏      | 47/150 [02:05<04:20,  2.53s/it]
 32%|███▏      | 48/150 [02:08<04:31,  2.66s/it]
 33%|███▎      | 49/150 [02:11<04:15,  2.53s/it]
 33%|███▎      | 50/150 [02:13<04:26,  2.66s/it]

(train_sft_tune pid=37213) {'loss': 0.9428, 'grad_norm': 0.5476590991020203, 'learning_rate': 3.167663085138764e-05, 'epoch': 0.08}
Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:52:07. Total running time: 57min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 34%|███▍      | 51/150 [02:17<04:43,  2.87s/it]
 35%|███▍      | 52/150 [02:19<04:26,  2.72s/it]
 35%|███▌      | 53/150 [02:22<04:20,  2.68s/it]
 36%|███▌      | 54/150 [02:24<04:14,  2.65s/it]
 37%|███▋      | 55/150 [02:26<03:53,  2.46s/it]

(train_sft_tune pid=37213) {'loss': 0.8365, 'grad_norm': 0.5413466095924377, 'learning_rate': 3.010848080923974e-05, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:29<03:57,  2.53s/it]
 38%|███▊      | 57/150 [02:31<03:36,  2.33s/it]
 39%|███▊      | 58/150 [02:34<03:40,  2.40s/it]
 39%|███▉      | 59/150 [02:36<03:46,  2.48s/it]
 40%|████      | 60/150 [02:39<03:41,  2.47s/it]

(train_sft_tune pid=37213) {'loss': 0.9704, 'grad_norm': 0.6392175555229187, 'learning_rate': 2.854033076709184e-05, 'epoch': 0.1}

 41%|████      | 61/150 [02:41<03:46,  2.55s/it]
 41%|████▏     | 62/150 [02:45<04:09,  2.84s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:52:37. Total running time: 58min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 42%|████▏     | 63/150 [02:48<04:13,  2.91s/it]
 43%|████▎     | 64/150 [02:51<04:21,  3.04s/it]
 43%|████▎     | 65/150 [02:53<03:52,  2.74s/it]

(train_sft_tune pid=37213) {'loss': 0.7982, 'grad_norm': 0.5366675853729248, 'learning_rate': 2.6972180724943933e-05, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:56<03:52,  2.77s/it]
 45%|████▍     | 67/150 [02:58<03:34,  2.58s/it]
 45%|████▌     | 68/150 [03:00<03:18,  2.43s/it]
 46%|████▌     | 69/150 [03:02<03:07,  2.31s/it]
 47%|████▋     | 70/150 [03:06<03:25,  2.57s/it]

(train_sft_tune pid=37213) {'loss': 0.9184, 'grad_norm': 0.5275888442993164, 'learning_rate': 2.5404030682796032e-05, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:09<03:34,  2.72s/it]
 48%|████▊     | 72/150 [03:11<03:21,  2.59s/it]
 49%|████▊     | 73/150 [03:14<03:23,  2.65s/it]
 49%|████▉     | 74/150 [03:16<03:15,  2.57s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:53:07. Total running time: 58min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 50%|█████     | 75/150 [03:19<03:14,  2.59s/it]

(train_sft_tune pid=37213) {'loss': 1.0078, 'grad_norm': 0.4979163706302643, 'learning_rate': 2.383588064064813e-05, 'epoch': 0.12}

 51%|█████     | 76/150 [03:21<03:11,  2.59s/it]
 51%|█████▏    | 77/150 [03:24<03:06,  2.56s/it]
 52%|█████▏    | 78/150 [03:26<02:53,  2.41s/it]
 53%|█████▎    | 79/150 [03:28<02:48,  2.37s/it]
 53%|█████▎    | 80/150 [03:31<02:50,  2.44s/it]

(train_sft_tune pid=37213) {'loss': 0.977, 'grad_norm': 0.7412441968917847, 'learning_rate': 2.2267730598500222e-05, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:33<02:53,  2.51s/it]
 55%|█████▍    | 82/150 [03:36<02:54,  2.56s/it]
 55%|█████▌    | 83/150 [03:38<02:47,  2.50s/it]
 56%|█████▌    | 84/150 [03:41<02:40,  2.43s/it]
 57%|█████▋    | 85/150 [03:44<02:45,  2.55s/it]

(train_sft_tune pid=37213) {'loss': 1.0153, 'grad_norm': 0.6821607351303101, 'learning_rate': 2.0699580556352324e-05, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:46<02:33,  2.39s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:53:37. Total running time: 59min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 58%|█████▊    | 87/150 [03:49<02:41,  2.56s/it]
 59%|█████▊    | 88/150 [03:51<02:42,  2.62s/it]
 59%|█████▉    | 89/150 [03:54<02:49,  2.77s/it]
 60%|██████    | 90/150 [03:56<02:27,  2.46s/it]

(train_sft_tune pid=37213) {'loss': 1.0119, 'grad_norm': 0.5697472095489502, 'learning_rate': 1.913143051420442e-05, 'epoch': 0.14}

 61%|██████    | 91/150 [03:58<02:16,  2.32s/it]
 61%|██████▏   | 92/150 [04:01<02:17,  2.38s/it]
 62%|██████▏   | 93/150 [04:03<02:15,  2.38s/it]
 63%|██████▎   | 94/150 [04:05<02:09,  2.32s/it]
 63%|██████▎   | 95/150 [04:08<02:14,  2.45s/it]

(train_sft_tune pid=37213) {'loss': 0.8167, 'grad_norm': 0.507361888885498, 'learning_rate': 1.7563280472056514e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:10<02:08,  2.37s/it]
 65%|██████▍   | 97/150 [04:13<02:13,  2.52s/it]
 65%|██████▌   | 98/150 [04:16<02:16,  2.63s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:54:07. Total running time: 59min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 66%|██████▌   | 99/150 [04:19<02:21,  2.77s/it]
 67%|██████▋   | 100/150 [04:21<02:06,  2.53s/it]

(train_sft_tune pid=37213) {'loss': 0.9104, 'grad_norm': 0.5609763264656067, 'learning_rate': 1.5995130429908612e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:23<02:00,  2.45s/it]
 68%|██████▊   | 102/150 [04:25<01:53,  2.37s/it]
 69%|██████▊   | 103/150 [04:28<01:54,  2.44s/it]
 69%|██████▉   | 104/150 [04:31<01:55,  2.51s/it]
 70%|███████   | 105/150 [04:33<01:53,  2.52s/it]

(train_sft_tune pid=37213) {'loss': 0.941, 'grad_norm': 0.5179095268249512, 'learning_rate': 1.442698038776071e-05, 'epoch': 0.17}

 71%|███████   | 106/150 [04:36<01:48,  2.46s/it]
 71%|███████▏  | 107/150 [04:38<01:51,  2.60s/it]
 72%|███████▏  | 108/150 [04:42<01:55,  2.75s/it]
 73%|███████▎  | 109/150 [04:44<01:50,  2.70s/it]
 73%|███████▎  | 110/150 [04:46<01:39,  2.50s/it]

(train_sft_tune pid=37213) {'loss': 0.8563, 'grad_norm': 0.603768527507782, 'learning_rate': 1.2858830345612805e-05, 'epoch': 0.18}
Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:54:38. Total running time: 1hr 0min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 74%|███████▍  | 111/150 [04:49<01:45,  2.70s/it]
 75%|███████▍  | 112/150 [04:52<01:46,  2.81s/it]
 75%|███████▌  | 113/150 [04:54<01:35,  2.57s/it]
 76%|███████▌  | 114/150 [04:57<01:35,  2.65s/it]
 77%|███████▋  | 115/150 [04:59<01:27,  2.51s/it]

(train_sft_tune pid=37213) {'loss': 0.8885, 'grad_norm': 0.6704658269882202, 'learning_rate': 1.1290680303464902e-05, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:02<01:23,  2.46s/it]
 78%|███████▊  | 117/150 [05:05<01:27,  2.64s/it]
 79%|███████▊  | 118/150 [05:08<01:28,  2.75s/it]
 79%|███████▉  | 119/150 [05:11<01:26,  2.81s/it]
 80%|████████  | 120/150 [05:13<01:18,  2.63s/it]

(train_sft_tune pid=37213) {'loss': 1.0969, 'grad_norm': 0.6360414624214172, 'learning_rate': 9.722530261317e-06, 'epoch': 0.19}

 81%|████████  | 121/150 [05:16<01:21,  2.80s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:55:08. Total running time: 1hr 0min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 81%|████████▏ | 122/150 [05:19<01:20,  2.88s/it]
 82%|████████▏ | 123/150 [05:22<01:14,  2.75s/it]
 83%|████████▎ | 124/150 [05:25<01:15,  2.89s/it]
 83%|████████▎ | 125/150 [05:27<01:09,  2.76s/it]

(train_sft_tune pid=37213) {'loss': 0.8659, 'grad_norm': 0.555664598941803, 'learning_rate': 8.154380219169095e-06, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:30<01:06,  2.78s/it]
 85%|████████▍ | 127/150 [05:33<01:03,  2.76s/it]
 85%|████████▌ | 128/150 [05:35<00:58,  2.67s/it]
 86%|████████▌ | 129/150 [05:37<00:50,  2.39s/it]
 87%|████████▋ | 130/150 [05:40<00:49,  2.49s/it]

(train_sft_tune pid=37213) {'loss': 0.8682, 'grad_norm': 0.5500710606575012, 'learning_rate': 6.586230177021194e-06, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:42<00:46,  2.47s/it]
 88%|████████▊ | 132/150 [05:45<00:45,  2.55s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:55:38. Total running time: 1hr 1min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 89%|████████▊ | 133/150 [05:47<00:40,  2.39s/it]
 89%|████████▉ | 134/150 [05:51<00:43,  2.75s/it]
 90%|█████████ | 135/150 [05:53<00:40,  2.72s/it]

(train_sft_tune pid=37213) {'loss': 0.8931, 'grad_norm': 0.566796600818634, 'learning_rate': 5.01808013487329e-06, 'epoch': 0.22}

 91%|█████████ | 136/150 [05:56<00:38,  2.79s/it]
 91%|█████████▏| 137/150 [05:58<00:32,  2.51s/it]
 92%|█████████▏| 138/150 [06:01<00:30,  2.52s/it]
 93%|█████████▎| 139/150 [06:03<00:27,  2.52s/it]
 93%|█████████▎| 140/150 [06:05<00:24,  2.41s/it]

(train_sft_tune pid=37213) {'loss': 0.9672, 'grad_norm': 0.5504554510116577, 'learning_rate': 3.449930092725387e-06, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:08<00:22,  2.46s/it]
 95%|█████████▍| 142/150 [06:10<00:19,  2.49s/it]
 95%|█████████▌| 143/150 [06:13<00:17,  2.55s/it]
 96%|█████████▌| 144/150 [06:16<00:16,  2.72s/it]

Trial status: 7 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:56:08. Total running time: 1hr 1min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_df75121a   RUNNING      4.54764e-05    16             32                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_ef9c592d   PENDING      1.26719e-05    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 97%|█████████▋| 145/150 [06:19<00:13,  2.62s/it]

(train_sft_tune pid=37213) {'loss': 0.897, 'grad_norm': 0.5573516488075256, 'learning_rate': 1.8817800505774837e-06, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:21<00:10,  2.54s/it]
 98%|█████████▊| 147/150 [06:23<00:07,  2.52s/it]
 99%|█████████▊| 148/150 [06:26<00:05,  2.58s/it]
 99%|█████████▉| 149/150 [06:29<00:02,  2.53s/it]
100%|██████████| 150/150 [06:31<00:00,  2.58s/it]

(train_sft_tune pid=37213) {'loss': 0.9652, 'grad_norm': 0.5299330353736877, 'learning_rate': 3.136300084295806e-07, 'epoch': 0.24}

100%|██████████| 150/150 [06:32<00:00,  2.62s/it]

(train_sft_tune pid=37213) {'train_runtime': 393.0042, 'train_samples_per_second': 3.053, 'train_steps_per_second': 0.382, 'train_loss': 0.9368585173288981, 'epoch': 0.24}
(train_sft_tune pid=37213) history of tuning  [{'loss': 1.0915, 'grad_norm': 0.6526359915733337, 'learning_rate': 3.6381080977831357e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9517, 'grad_norm': 0.5122365355491638, 'learning_rate': 4.422183118857087e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0469, 'grad_norm': 0.5077704787254333, 'learning_rate': 4.265368114642296e-05, 'epoch': 0.024, 'step': 15}, {'loss': 0.9686, 'grad_norm': 0.6832707524299622, 'learning_rate': 4.1085531104275065e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.8988, 'grad_norm': 0.4327300190925598, 'learning_rate': 3.951738106212716e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0409, 'grad_norm': 0.5210758447647095, 'learning_rate': 3.7949231019979255e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9194, 'grad_norm': 0.5550289154052734, 'learning_rate': 3.6381080977831357e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.8157, 'grad_norm': 0.5193595886230469, 'learning_rate': 3.481293093568345e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.9276, 'grad_norm': 0.5533820986747742, 'learning_rate': 3.3244780893535547e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9428, 'grad_norm': 0.5476590991020203, 'learning_rate': 3.167663085138764e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8365, 'grad_norm': 0.5413466095924377, 'learning_rate': 3.010848080923974e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9704, 'grad_norm': 0.6392175555229187, 'learning_rate': 2.854033076709184e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.7982, 'grad_norm': 0.5366675853729248, 'learning_rate': 2.6972180724943933e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.9184, 'grad_norm': 0.5275888442993164, 'learning_rate': 2.5404030682796032e-05, 'epoch': 0.112, 'step': 70}, {'loss': 1.0078, 'grad_norm': 0.4979163706302643, 'learning_rate': 2.383588064064813e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.977, 'grad_norm': 0.7412441968917847, 'learning_rate': 2.2267730598500222e-05, 'epoch': 0.128, 'step': 80}, {'loss': 1.0153, 'grad_norm': 0.6821607351303101, 'learning_rate': 2.0699580556352324e-05, 'epoch': 0.136, 'step': 85}, {'loss': 1.0119, 'grad_norm': 0.5697472095489502, 'learning_rate': 1.913143051420442e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8167, 'grad_norm': 0.507361888885498, 'learning_rate': 1.7563280472056514e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.9104, 'grad_norm': 0.5609763264656067, 'learning_rate': 1.5995130429908612e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.941, 'grad_norm': 0.5179095268249512, 'learning_rate': 1.442698038776071e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8563, 'grad_norm': 0.603768527507782, 'learning_rate': 1.2858830345612805e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8885, 'grad_norm': 0.6704658269882202, 'learning_rate': 1.1290680303464902e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0969, 'grad_norm': 0.6360414624214172, 'learning_rate': 9.722530261317e-06, 'epoch': 0.192, 'step': 120}, {'loss': 0.8659, 'grad_norm': 0.555664598941803, 'learning_rate': 8.154380219169095e-06, 'epoch': 0.2, 'step': 125}, {'loss': 0.8682, 'grad_norm': 0.5500710606575012, 'learning_rate': 6.586230177021194e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.8931, 'grad_norm': 0.566796600818634, 'learning_rate': 5.01808013487329e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9672, 'grad_norm': 0.5504554510116577, 'learning_rate': 3.449930092725387e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.897, 'grad_norm': 0.5573516488075256, 'learning_rate': 1.8817800505774837e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9652, 'grad_norm': 0.5299330353736877, 'learning_rate': 3.136300084295806e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 393.0042, 'train_samples_per_second': 3.053, 'train_steps_per_second': 0.382, 'total_flos': 4888333847519232.0, 'train_loss': 0.9368585173288981, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=37213) Reporting loss: 0.9368585173288981

Trial train_sft_tune_df75121a completed after 1 iterations at 2025-11-29 16:56:24. Total running time: 1hr 1min 54s
+--------------------------------------------------+
| Trial train_sft_tune_df75121a result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         438.256 |
| time_total_s                             438.256 |
| training_iteration                             1 |
| train_loss                               0.93686 |
+--------------------------------------------------+

Trial train_sft_tune_ef9c592d started with configuration:
+------------------------------------------------+
| Trial train_sft_tune_ef9c592d config           |
+------------------------------------------------+
| lora_alpha                                  64 |
| lr                                       1e-05 |
| r                                           16 |
+------------------------------------------------+
(train_sft_tune pid=39270) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:56:38. Total running time: 1hr 2min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=39270) 2025-11-29 16:56:39.409490: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=39270) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=39270) E0000 00:00:1764435399.442327   39339 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=39270) E0000 00:00:1764435399.449023   39339 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=39270) W0000 00:00:1764435399.468129   39339 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=39270) W0000 00:00:1764435399.468163   39339 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=39270) W0000 00:00:1764435399.468165   39339 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=39270) W0000 00:00:1764435399.468167   39339 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=39270) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=39270) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=39270)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=39270) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=39270) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=39270)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=39270) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=39270) [2025-11-29 16:57:03,581 E 39270 39317] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:57:08. Total running time: 1hr 2min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=39270) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=39270) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=39270) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=39270)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=39270) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=39270) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=39270)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=39270) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:13<32:54, 13.25s/it]
  1%|▏         | 2/150 [00:15<16:22,  6.64s/it]
  2%|▏         | 3/150 [00:17<11:51,  4.84s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:57:38. Total running time: 1hr 3min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  3%|▎         | 4/150 [00:20<09:37,  3.95s/it]
  3%|▎         | 5/150 [00:22<07:47,  3.22s/it]

(train_sft_tune pid=39270) {'loss': 1.0926, 'grad_norm': 1.3234810829162598, 'learning_rate': 1.0137528225755963e-05, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:04,  2.95s/it]
  5%|▍         | 7/150 [00:27<06:37,  2.78s/it]
  5%|▌         | 8/150 [00:29<06:22,  2.69s/it]
  6%|▌         | 9/150 [00:32<06:13,  2.65s/it]
  7%|▋         | 10/150 [00:34<06:03,  2.60s/it]

(train_sft_tune pid=39270) {'loss': 0.9615, 'grad_norm': 1.0162451267242432, 'learning_rate': 1.2322340343375781e-05, 'epoch': 0.02}

  7%|▋         | 11/150 [00:37<06:03,  2.62s/it]
  8%|▊         | 12/150 [00:39<05:42,  2.48s/it]
  9%|▊         | 13/150 [00:42<05:59,  2.63s/it]
  9%|▉         | 14/150 [00:44<05:41,  2.51s/it]
 10%|█         | 15/150 [00:46<05:12,  2.31s/it]

(train_sft_tune pid=39270) {'loss': 1.0629, 'grad_norm': 1.01313316822052, 'learning_rate': 1.1885377919851818e-05, 'epoch': 0.02}

 11%|█         | 16/150 [00:49<05:21,  2.40s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:58:08. Total running time: 1hr 3min 38s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 11%|█▏        | 17/150 [00:52<05:42,  2.57s/it]
 12%|█▏        | 18/150 [00:54<05:11,  2.36s/it]
 13%|█▎        | 19/150 [00:56<05:20,  2.45s/it]
 13%|█▎        | 20/150 [00:58<04:47,  2.21s/it]

(train_sft_tune pid=39270) {'loss': 0.9882, 'grad_norm': 1.3769569396972656, 'learning_rate': 1.1448415496327854e-05, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:00<04:39,  2.17s/it]
 15%|█▍        | 22/150 [01:02<04:36,  2.16s/it]
 15%|█▌        | 23/150 [01:05<04:42,  2.22s/it]
 16%|█▌        | 24/150 [01:07<04:57,  2.36s/it]
 17%|█▋        | 25/150 [01:10<05:02,  2.42s/it]

(train_sft_tune pid=39270) {'loss': 0.9164, 'grad_norm': 0.8266986608505249, 'learning_rate': 1.1011453072803889e-05, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:13<05:26,  2.63s/it]
 18%|█▊        | 27/150 [01:15<05:04,  2.47s/it]
 19%|█▊        | 28/150 [01:18<05:14,  2.58s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:58:38. Total running time: 1hr 4min 8s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 19%|█▉        | 29/150 [01:20<04:46,  2.37s/it]
 20%|██        | 30/150 [01:23<05:26,  2.72s/it]

(train_sft_tune pid=39270) {'loss': 1.0646, 'grad_norm': 0.9323044419288635, 'learning_rate': 1.0574490649279925e-05, 'epoch': 0.05}

 21%|██        | 31/150 [01:26<05:31,  2.78s/it]
 21%|██▏       | 32/150 [01:28<04:59,  2.54s/it]
 22%|██▏       | 33/150 [01:31<05:17,  2.71s/it]
 23%|██▎       | 34/150 [01:34<05:07,  2.65s/it]
 23%|██▎       | 35/150 [01:36<04:50,  2.52s/it]

(train_sft_tune pid=39270) {'loss': 0.9399, 'grad_norm': 0.9731032252311707, 'learning_rate': 1.0137528225755963e-05, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:38<04:43,  2.49s/it]
 25%|██▍       | 37/150 [01:41<04:42,  2.50s/it]
 25%|██▌       | 38/150 [01:43<04:32,  2.43s/it]
 26%|██▌       | 39/150 [01:46<04:40,  2.53s/it]
 27%|██▋       | 40/150 [01:49<04:40,  2.55s/it]

(train_sft_tune pid=39270) {'loss': 0.838, 'grad_norm': 0.9466841220855713, 'learning_rate': 9.700565802231998e-06, 'epoch': 0.06}
Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:59:08. Total running time: 1hr 4min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 27%|██▋       | 41/150 [01:51<04:40,  2.57s/it]
 28%|██▊       | 42/150 [01:54<04:39,  2.59s/it]
 29%|██▊       | 43/150 [01:56<04:15,  2.38s/it]
 29%|██▉       | 44/150 [01:58<04:19,  2.45s/it]
 30%|███       | 45/150 [02:00<04:01,  2.30s/it]

(train_sft_tune pid=39270) {'loss': 0.9511, 'grad_norm': 0.9600830674171448, 'learning_rate': 9.263603378708035e-06, 'epoch': 0.07}

 31%|███       | 46/150 [02:03<04:16,  2.47s/it]
 31%|███▏      | 47/150 [02:06<04:24,  2.57s/it]
 32%|███▏      | 48/150 [02:09<04:35,  2.70s/it]
 33%|███▎      | 49/150 [02:11<04:13,  2.51s/it]
 33%|███▎      | 50/150 [02:14<04:25,  2.65s/it]

(train_sft_tune pid=39270) {'loss': 0.9633, 'grad_norm': 0.9797455072402954, 'learning_rate': 8.82664095518407e-06, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:17<04:43,  2.86s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 16:59:38. Total running time: 1hr 5min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 35%|███▍      | 52/150 [02:20<04:26,  2.72s/it]
 35%|███▌      | 53/150 [02:22<04:18,  2.67s/it]
 36%|███▌      | 54/150 [02:25<04:11,  2.62s/it]
 37%|███▋      | 55/150 [02:27<03:55,  2.48s/it]

(train_sft_tune pid=39270) {'loss': 0.8567, 'grad_norm': 0.9409347772598267, 'learning_rate': 8.389678531660106e-06, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:30<04:00,  2.56s/it]
 38%|███▊      | 57/150 [02:32<03:38,  2.35s/it]
 39%|███▊      | 58/150 [02:34<03:42,  2.42s/it]
 39%|███▉      | 59/150 [02:37<03:45,  2.48s/it]
 40%|████      | 60/150 [02:39<03:39,  2.44s/it]

(train_sft_tune pid=39270) {'loss': 0.992, 'grad_norm': 1.1246224641799927, 'learning_rate': 7.952716108136142e-06, 'epoch': 0.1}

 41%|████      | 61/150 [02:42<03:47,  2.55s/it]
 41%|████▏     | 62/150 [02:46<04:11,  2.86s/it]
 42%|████▏     | 63/150 [02:49<04:13,  2.92s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:00:08. Total running time: 1hr 5min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 43%|████▎     | 64/150 [02:52<04:21,  3.04s/it]
 43%|████▎     | 65/150 [02:54<03:53,  2.75s/it]

(train_sft_tune pid=39270) {'loss': 0.8183, 'grad_norm': 0.9431872963905334, 'learning_rate': 7.515753684612178e-06, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:57<03:52,  2.77s/it]
 45%|████▍     | 67/150 [02:59<03:34,  2.58s/it]
 45%|████▌     | 68/150 [03:01<03:17,  2.41s/it]
 46%|████▌     | 69/150 [03:03<03:03,  2.27s/it]
 47%|████▋     | 70/150 [03:06<03:22,  2.53s/it]

(train_sft_tune pid=39270) {'loss': 0.9397, 'grad_norm': 0.9104006886482239, 'learning_rate': 7.078791261088215e-06, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:09<03:33,  2.70s/it]
 48%|████▊     | 72/150 [03:11<03:20,  2.57s/it]
 49%|████▊     | 73/150 [03:14<03:21,  2.62s/it]
 49%|████▉     | 74/150 [03:16<03:12,  2.54s/it]
 50%|█████     | 75/150 [03:19<03:12,  2.57s/it]

(train_sft_tune pid=39270) {'loss': 1.0257, 'grad_norm': 0.8584834337234497, 'learning_rate': 6.641828837564252e-06, 'epoch': 0.12}
Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:00:38. Total running time: 1hr 6min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 51%|█████     | 76/150 [03:22<03:11,  2.58s/it]
 51%|█████▏    | 77/150 [03:24<03:06,  2.55s/it]
 52%|█████▏    | 78/150 [03:26<02:52,  2.39s/it]
 53%|█████▎    | 79/150 [03:28<02:45,  2.33s/it]
 53%|█████▎    | 80/150 [03:31<02:48,  2.40s/it]

(train_sft_tune pid=39270) {'loss': 0.9962, 'grad_norm': 1.2959891557693481, 'learning_rate': 6.204866414040287e-06, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:34<02:53,  2.51s/it]
 55%|█████▍    | 82/150 [03:36<02:54,  2.57s/it]
 55%|█████▌    | 83/150 [03:39<02:46,  2.49s/it]
 56%|█████▌    | 84/150 [03:41<02:37,  2.39s/it]
 57%|█████▋    | 85/150 [03:44<02:42,  2.50s/it]

(train_sft_tune pid=39270) {'loss': 1.0353, 'grad_norm': 1.1253238916397095, 'learning_rate': 5.767903990516324e-06, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:46<02:32,  2.39s/it]
 58%|█████▊    | 87/150 [03:49<02:42,  2.58s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:01:08. Total running time: 1hr 6min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 59%|█████▊    | 88/150 [03:52<02:43,  2.64s/it]
 59%|█████▉    | 89/150 [03:55<02:49,  2.78s/it]
 60%|██████    | 90/150 [03:56<02:27,  2.47s/it]

(train_sft_tune pid=39270) {'loss': 1.0281, 'grad_norm': 0.9408210515975952, 'learning_rate': 5.3309415669923595e-06, 'epoch': 0.14}

 61%|██████    | 91/150 [03:59<02:18,  2.35s/it]
 61%|██████▏   | 92/150 [04:01<02:19,  2.41s/it]
 62%|██████▏   | 93/150 [04:03<02:17,  2.41s/it]
 63%|██████▎   | 94/150 [04:06<02:10,  2.32s/it]
 63%|██████▎   | 95/150 [04:08<02:13,  2.44s/it]

(train_sft_tune pid=39270) {'loss': 0.8354, 'grad_norm': 0.8881773948669434, 'learning_rate': 4.893979143468395e-06, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:11<02:08,  2.37s/it]
 65%|██████▍   | 97/150 [04:13<02:15,  2.55s/it]
 65%|██████▌   | 98/150 [04:16<02:17,  2.64s/it]
 66%|██████▌   | 99/150 [04:19<02:21,  2.77s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:01:38. Total running time: 1hr 7min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 67%|██████▋   | 100/150 [04:21<02:05,  2.51s/it]

(train_sft_tune pid=39270) {'loss': 0.9279, 'grad_norm': 0.9591174125671387, 'learning_rate': 4.457016719944432e-06, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:24<01:59,  2.45s/it]
 68%|██████▊   | 102/150 [04:26<01:54,  2.38s/it]
 69%|██████▊   | 103/150 [04:28<01:55,  2.45s/it]
 69%|██████▉   | 104/150 [04:31<01:54,  2.49s/it]
 70%|███████   | 105/150 [04:34<01:51,  2.49s/it]

(train_sft_tune pid=39270) {'loss': 0.9592, 'grad_norm': 0.8782027959823608, 'learning_rate': 4.020054296420468e-06, 'epoch': 0.17}

 71%|███████   | 106/150 [04:36<01:46,  2.43s/it]
 71%|███████▏  | 107/150 [04:39<01:51,  2.59s/it]
 72%|███████▏  | 108/150 [04:42<01:55,  2.74s/it]
 73%|███████▎  | 109/150 [04:44<01:50,  2.68s/it]
 73%|███████▎  | 110/150 [04:46<01:38,  2.47s/it]

(train_sft_tune pid=39270) {'loss': 0.8787, 'grad_norm': 1.017762541770935, 'learning_rate': 3.583091872896504e-06, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:50<01:44,  2.69s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:02:09. Total running time: 1hr 7min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 75%|███████▍  | 112/150 [04:53<01:46,  2.80s/it]
 75%|███████▌  | 113/150 [04:55<01:34,  2.57s/it]
 76%|███████▌  | 114/150 [04:57<01:35,  2.64s/it]
 77%|███████▋  | 115/150 [05:00<01:26,  2.47s/it]

(train_sft_tune pid=39270) {'loss': 0.9113, 'grad_norm': 1.1216005086898804, 'learning_rate': 3.1461294493725397e-06, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:02<01:23,  2.45s/it]
 78%|███████▊  | 117/150 [05:05<01:27,  2.65s/it]
 79%|███████▊  | 118/150 [05:08<01:28,  2.77s/it]
 79%|███████▉  | 119/150 [05:11<01:26,  2.79s/it]
 80%|████████  | 120/150 [05:13<01:18,  2.61s/it]

(train_sft_tune pid=39270) {'loss': 1.1194, 'grad_norm': 1.078948974609375, 'learning_rate': 2.709167025848576e-06, 'epoch': 0.19}

 81%|████████  | 121/150 [05:16<01:21,  2.81s/it]
 81%|████████▏ | 122/150 [05:20<01:21,  2.90s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:02:39. Total running time: 1hr 8min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 82%|████████▏ | 123/150 [05:22<01:14,  2.76s/it]
 83%|████████▎ | 124/150 [05:25<01:15,  2.89s/it]
 83%|████████▎ | 125/150 [05:28<01:09,  2.78s/it]

(train_sft_tune pid=39270) {'loss': 0.8841, 'grad_norm': 0.9698523879051208, 'learning_rate': 2.2722046023246122e-06, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:31<01:07,  2.81s/it]
 85%|████████▍ | 127/150 [05:33<01:04,  2.78s/it]
 85%|████████▌ | 128/150 [05:36<00:59,  2.68s/it]
 86%|████████▌ | 129/150 [05:37<00:49,  2.37s/it]
 87%|████████▋ | 130/150 [05:40<00:49,  2.46s/it]

(train_sft_tune pid=39270) {'loss': 0.8869, 'grad_norm': 0.9617202281951904, 'learning_rate': 1.8352421788006485e-06, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:43<00:46,  2.46s/it]
 88%|████████▊ | 132/150 [05:45<00:46,  2.56s/it]
 89%|████████▊ | 133/150 [05:47<00:40,  2.41s/it]

Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:03:09. Total running time: 1hr 8min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 89%|████████▉ | 134/150 [05:51<00:44,  2.75s/it]
 90%|█████████ | 135/150 [05:54<00:40,  2.73s/it]

(train_sft_tune pid=39270) {'loss': 0.9088, 'grad_norm': 0.9393609762191772, 'learning_rate': 1.3982797552766843e-06, 'epoch': 0.22}

 91%|█████████ | 136/150 [05:57<00:39,  2.81s/it]
 91%|█████████▏| 137/150 [05:58<00:32,  2.53s/it]
 92%|█████████▏| 138/150 [06:01<00:30,  2.52s/it]
 93%|█████████▎| 139/150 [06:03<00:27,  2.49s/it]
 93%|█████████▎| 140/150 [06:06<00:23,  2.39s/it]

(train_sft_tune pid=39270) {'loss': 0.9824, 'grad_norm': 0.93082594871521, 'learning_rate': 9.613173317527206e-07, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:08<00:22,  2.46s/it]
 95%|█████████▍| 142/150 [06:11<00:20,  2.51s/it]
 95%|█████████▌| 143/150 [06:13<00:17,  2.57s/it]
 96%|█████████▌| 144/150 [06:17<00:16,  2.73s/it]
 97%|█████████▋| 145/150 [06:19<00:13,  2.64s/it]

(train_sft_tune pid=39270) {'loss': 0.9151, 'grad_norm': 0.9635312557220459, 'learning_rate': 5.243549082287566e-07, 'epoch': 0.23}
Trial status: 8 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:03:39. Total running time: 1hr 9min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_ef9c592d   RUNNING      1.26719e-05    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_f6d5bc07   PENDING      0.000158739    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 97%|█████████▋| 146/150 [06:22<00:10,  2.60s/it]
 98%|█████████▊| 147/150 [06:24<00:07,  2.56s/it]
 99%|█████████▊| 148/150 [06:27<00:05,  2.61s/it]
 99%|█████████▉| 149/150 [06:29<00:02,  2.52s/it]
100%|██████████| 150/150 [06:32<00:00,  2.55s/it]

(train_sft_tune pid=39270) {'loss': 0.9874, 'grad_norm': 0.9263652563095093, 'learning_rate': 8.739248470479277e-08, 'epoch': 0.24}

Trial train_sft_tune_ef9c592d completed after 1 iterations at 2025-11-29 17:03:51. Total running time: 1hr 9min 22s
+--------------------------------------------------+
| Trial train_sft_tune_ef9c592d result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         436.884 |
| time_total_s                             436.884 |
| training_iteration                             1 |
| train_loss                               0.95557 |
+--------------------------------------------------+
(train_sft_tune pid=39270) {'train_runtime': 393.3075, 'train_samples_per_second': 3.051, 'train_steps_per_second': 0.381, 'train_loss': 0.9555704625447591, 'epoch': 0.24}
(train_sft_tune pid=39270) history of tuning  [{'loss': 1.0926, 'grad_norm': 1.3234810829162598, 'learning_rate': 1.0137528225755963e-05, 'epoch': 0.008, 'step': 5}, {'loss': 0.9615, 'grad_norm': 1.0162451267242432, 'learning_rate': 1.2322340343375781e-05, 'epoch': 0.016, 'step': 10}, {'loss': 1.0629, 'grad_norm': 1.01313316822052, 'learning_rate': 1.1885377919851818e-05, 'epoch': 0.024, 'step': 15}, {'loss': 0.9882, 'grad_norm': 1.3769569396972656, 'learning_rate': 1.1448415496327854e-05, 'epoch': 0.032, 'step': 20}, {'loss': 0.9164, 'grad_norm': 0.8266986608505249, 'learning_rate': 1.1011453072803889e-05, 'epoch': 0.04, 'step': 25}, {'loss': 1.0646, 'grad_norm': 0.9323044419288635, 'learning_rate': 1.0574490649279925e-05, 'epoch': 0.048, 'step': 30}, {'loss': 0.9399, 'grad_norm': 0.9731032252311707, 'learning_rate': 1.0137528225755963e-05, 'epoch': 0.056, 'step': 35}, {'loss': 0.838, 'grad_norm': 0.9466841220855713, 'learning_rate': 9.700565802231998e-06, 'epoch': 0.064, 'step': 40}, {'loss': 0.9511, 'grad_norm': 0.9600830674171448, 'learning_rate': 9.263603378708035e-06, 'epoch': 0.072, 'step': 45}, {'loss': 0.9633, 'grad_norm': 0.9797455072402954, 'learning_rate': 8.82664095518407e-06, 'epoch': 0.08, 'step': 50}, {'loss': 0.8567, 'grad_norm': 0.9409347772598267, 'learning_rate': 8.389678531660106e-06, 'epoch': 0.088, 'step': 55}, {'loss': 0.992, 'grad_norm': 1.1246224641799927, 'learning_rate': 7.952716108136142e-06, 'epoch': 0.096, 'step': 60}, {'loss': 0.8183, 'grad_norm': 0.9431872963905334, 'learning_rate': 7.515753684612178e-06, 'epoch': 0.104, 'step': 65}, {'loss': 0.9397, 'grad_norm': 0.9104006886482239, 'learning_rate': 7.078791261088215e-06, 'epoch': 0.112, 'step': 70}, {'loss': 1.0257, 'grad_norm': 0.8584834337234497, 'learning_rate': 6.641828837564252e-06, 'epoch': 0.12, 'step': 75}, {'loss': 0.9962, 'grad_norm': 1.2959891557693481, 'learning_rate': 6.204866414040287e-06, 'epoch': 0.128, 'step': 80}, {'loss': 1.0353, 'grad_norm': 1.1253238916397095, 'learning_rate': 5.767903990516324e-06, 'epoch': 0.136, 'step': 85}, {'loss': 1.0281, 'grad_norm': 0.9408210515975952, 'learning_rate': 5.3309415669923595e-06, 'epoch': 0.144, 'step': 90}, {'loss': 0.8354, 'grad_norm': 0.8881773948669434, 'learning_rate': 4.893979143468395e-06, 'epoch': 0.152, 'step': 95}, {'loss': 0.9279, 'grad_norm': 0.9591174125671387, 'learning_rate': 4.457016719944432e-06, 'epoch': 0.16, 'step': 100}, {'loss': 0.9592, 'grad_norm': 0.8782027959823608, 'learning_rate': 4.020054296420468e-06, 'epoch': 0.168, 'step': 105}, {'loss': 0.8787, 'grad_norm': 1.017762541770935, 'learning_rate': 3.583091872896504e-06, 'epoch': 0.176, 'step': 110}, {'loss': 0.9113, 'grad_norm': 1.1216005086898804, 'learning_rate': 3.1461294493725397e-06, 'epoch': 0.184, 'step': 115}, {'loss': 1.1194, 'grad_norm': 1.078948974609375, 'learning_rate': 2.709167025848576e-06, 'epoch': 0.192, 'step': 120}, {'loss': 0.8841, 'grad_norm': 0.9698523879051208, 'learning_rate': 2.2722046023246122e-06, 'epoch': 0.2, 'step': 125}, {'loss': 0.8869, 'grad_norm': 0.9617202281951904, 'learning_rate': 1.8352421788006485e-06, 'epoch': 0.208, 'step': 130}, {'loss': 0.9088, 'grad_norm': 0.9393609762191772, 'learning_rate': 1.3982797552766843e-06, 'epoch': 0.216, 'step': 135}, {'loss': 0.9824, 'grad_norm': 0.93082594871521, 'learning_rate': 9.613173317527206e-07, 'epoch': 0.224, 'step': 140}, {'loss': 0.9151, 'grad_norm': 0.9635312557220459, 'learning_rate': 5.243549082287566e-07, 'epoch': 0.232, 'step': 145}, {'loss': 0.9874, 'grad_norm': 0.9263652563095093, 'learning_rate': 8.739248470479277e-08, 'epoch': 0.24, 'step': 150}, {'train_runtime': 393.3075, 'train_samples_per_second': 3.051, 'train_steps_per_second': 0.381, 'total_flos': 4888333847519232.0, 'train_loss': 0.9555704625447591, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=39270) Reporting loss: 0.9555704625447591

100%|██████████| 150/150 [06:33<00:00,  2.62s/it]

Trial train_sft_tune_f6d5bc07 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_f6d5bc07 config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00016 |
| r                                             16 |
+--------------------------------------------------+
(train_sft_tune pid=41307) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=41307) 2025-11-29 17:04:06.439767: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=41307) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=41307) E0000 00:00:1764435846.484702   41364 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=41307) E0000 00:00:1764435846.497024   41364 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=41307) W0000 00:00:1764435846.526218   41364 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=41307) W0000 00:00:1764435846.526265   41364 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=41307) W0000 00:00:1764435846.526269   41364 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=41307) W0000 00:00:1764435846.526272   41364 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:04:09. Total running time: 1hr 9min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=41307) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=41307) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=41307)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=41307) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=41307) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=41307)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=41307) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=41307) [2025-11-29 17:04:29,988 E 41307 41344] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=41307) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:04:39. Total running time: 1hr 10min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=41307) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=41307) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=41307)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=41307) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=41307) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=41307)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=41307) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:12<30:28, 12.27s/it]
  1%|▏         | 2/150 [00:14<15:23,  6.24s/it]
  2%|▏         | 3/150 [00:16<11:19,  4.62s/it]
  3%|▎         | 4/150 [00:19<09:15,  3.81s/it]

(train_sft_tune pid=41307) {'loss': 1.0791, 'grad_norm': 1.0293103456497192, 'learning_rate': 0.00012699099974277186, 'epoch': 0.01}

  3%|▎         | 5/150 [00:21<07:34,  3.13s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:05:09. Total running time: 1hr 10min 39s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

  4%|▍         | 6/150 [00:23<06:59,  2.91s/it]
  5%|▍         | 7/150 [00:26<06:37,  2.78s/it]
  5%|▌         | 8/150 [00:28<06:21,  2.69s/it]
  6%|▌         | 9/150 [00:31<06:08,  2.61s/it]

(train_sft_tune pid=41307) {'loss': 0.9085, 'grad_norm': 0.7875751852989197, 'learning_rate': 0.00015435974968733474, 'epoch': 0.02}

  7%|▋         | 10/150 [00:33<06:00,  2.58s/it]
  7%|▋         | 11/150 [00:36<06:03,  2.61s/it]
  8%|▊         | 12/150 [00:38<05:44,  2.49s/it]
  9%|▊         | 13/150 [00:41<06:01,  2.64s/it]
  9%|▉         | 14/150 [00:43<05:40,  2.50s/it]

(train_sft_tune pid=41307) {'loss': 1.0039, 'grad_norm': 0.9596777558326721, 'learning_rate': 0.00014888599969842218, 'epoch': 0.02}

 10%|█         | 15/150 [00:45<05:09,  2.29s/it]
 11%|█         | 16/150 [00:48<05:20,  2.39s/it]
 11%|█▏        | 17/150 [00:51<05:43,  2.58s/it]
 12%|█▏        | 18/150 [00:53<05:12,  2.37s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:05:39. Total running time: 1hr 11min 9s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 13%|█▎        | 19/150 [00:55<05:19,  2.44s/it]

(train_sft_tune pid=41307) {'loss': 0.9292, 'grad_norm': 1.1341583728790283, 'learning_rate': 0.0001434122497095096, 'epoch': 0.03}

 13%|█▎        | 20/150 [00:57<04:39,  2.15s/it]
 14%|█▍        | 21/150 [00:59<04:32,  2.11s/it]
 15%|█▍        | 22/150 [01:01<04:33,  2.13s/it]
 15%|█▌        | 23/150 [01:04<04:41,  2.22s/it]
 16%|█▌        | 24/150 [01:06<04:57,  2.36s/it]

(train_sft_tune pid=41307) {'loss': 0.8652, 'grad_norm': 0.7635369300842285, 'learning_rate': 0.000137938499720597, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:09<05:01,  2.41s/it]
 17%|█▋        | 26/150 [01:12<05:25,  2.62s/it]
 18%|█▊        | 27/150 [01:14<05:07,  2.50s/it]
 19%|█▊        | 28/150 [01:17<05:18,  2.61s/it]
 19%|█▉        | 29/150 [01:19<04:48,  2.38s/it]

(train_sft_tune pid=41307) {'loss': 1.0085, 'grad_norm': 0.7693275809288025, 'learning_rate': 0.00013246474973168445, 'epoch': 0.05}

 20%|██        | 30/150 [01:22<05:27,  2.73s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:06:09. Total running time: 1hr 11min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 21%|██        | 31/150 [01:25<05:30,  2.78s/it]
 21%|██▏       | 32/150 [01:27<05:01,  2.55s/it]
 22%|██▏       | 33/150 [01:30<05:19,  2.73s/it]
 23%|██▎       | 34/150 [01:33<05:08,  2.66s/it]

(train_sft_tune pid=41307) {'loss': 0.8968, 'grad_norm': 0.8615941405296326, 'learning_rate': 0.00012699099974277186, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:35<04:46,  2.49s/it]
 24%|██▍       | 36/150 [01:37<04:39,  2.45s/it]
 25%|██▍       | 37/150 [01:40<04:42,  2.50s/it]
 25%|██▌       | 38/150 [01:42<04:35,  2.46s/it]
 26%|██▌       | 39/150 [01:45<04:42,  2.55s/it]

(train_sft_tune pid=41307) {'loss': 0.7876, 'grad_norm': 0.8689572811126709, 'learning_rate': 0.00012151724975385927, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:48<04:41,  2.56s/it]
 27%|██▋       | 41/150 [01:50<04:39,  2.56s/it]
 28%|██▊       | 42/150 [01:53<04:39,  2.59s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:06:39. Total running time: 1hr 12min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 29%|██▊       | 43/150 [01:55<04:18,  2.42s/it]
 29%|██▉       | 44/150 [01:58<04:42,  2.66s/it]

(train_sft_tune pid=41307) {'loss': 0.8968, 'grad_norm': 0.8466201424598694, 'learning_rate': 0.0001160434997649467, 'epoch': 0.07}

 30%|███       | 45/150 [02:00<04:15,  2.44s/it]
 31%|███       | 46/150 [02:03<04:23,  2.54s/it]
 31%|███▏      | 47/150 [02:06<04:29,  2.62s/it]
 32%|███▏      | 48/150 [02:09<04:39,  2.74s/it]
 33%|███▎      | 49/150 [02:11<04:18,  2.56s/it]

(train_sft_tune pid=41307) {'loss': 0.9265, 'grad_norm': 0.7894248962402344, 'learning_rate': 0.00011056974977603411, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:14<04:26,  2.67s/it]
 34%|███▍      | 51/150 [02:17<04:43,  2.87s/it]
 35%|███▍      | 52/150 [02:19<04:27,  2.73s/it]
 35%|███▌      | 53/150 [02:22<04:21,  2.70s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:07:09. Total running time: 1hr 12min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 36%|███▌      | 54/150 [02:25<04:13,  2.64s/it]

(train_sft_tune pid=41307) {'loss': 0.8131, 'grad_norm': 0.8508226871490479, 'learning_rate': 0.00010509599978712154, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:27<03:52,  2.45s/it]
 37%|███▋      | 56/150 [02:29<03:56,  2.51s/it]
 38%|███▊      | 57/150 [02:31<03:36,  2.33s/it]
 39%|███▊      | 58/150 [02:34<03:41,  2.41s/it]
 39%|███▉      | 59/150 [02:36<03:44,  2.46s/it]

(train_sft_tune pid=41307) {'loss': 0.9433, 'grad_norm': 0.9803476333618164, 'learning_rate': 9.962224979820896e-05, 'epoch': 0.1}

 40%|████      | 60/150 [02:39<03:38,  2.43s/it]
 41%|████      | 61/150 [02:41<03:43,  2.51s/it]
 41%|████▏     | 62/150 [02:45<04:07,  2.81s/it]
 42%|████▏     | 63/150 [02:48<04:11,  2.89s/it]
 43%|████▎     | 64/150 [02:51<04:19,  3.02s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:07:39. Total running time: 1hr 13min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=41307) {'loss': 0.775, 'grad_norm': 0.7936156988143921, 'learning_rate': 9.414849980929637e-05, 'epoch': 0.1}

 43%|████▎     | 65/150 [02:53<03:51,  2.72s/it]
 44%|████▍     | 66/150 [02:56<03:51,  2.76s/it]
 45%|████▍     | 67/150 [02:58<03:37,  2.62s/it]
 45%|████▌     | 68/150 [03:00<03:20,  2.45s/it]
 46%|████▌     | 69/150 [03:02<03:05,  2.29s/it]

(train_sft_tune pid=41307) {'loss': 0.8942, 'grad_norm': 0.7501825094223022, 'learning_rate': 8.86747498203838e-05, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:06<03:23,  2.54s/it]
 47%|████▋     | 71/150 [03:09<03:33,  2.70s/it]
 48%|████▊     | 72/150 [03:11<03:22,  2.60s/it]
 49%|████▊     | 73/150 [03:14<03:24,  2.65s/it]
 49%|████▉     | 74/150 [03:16<03:14,  2.56s/it]

(train_sft_tune pid=41307) {'loss': 0.9934, 'grad_norm': 0.7356411814689636, 'learning_rate': 8.320099983147123e-05, 'epoch': 0.12}

 50%|█████     | 75/150 [03:19<03:13,  2.58s/it]
 51%|█████     | 76/150 [03:21<03:11,  2.58s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:08:09. Total running time: 1hr 13min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 51%|█████▏    | 77/150 [03:24<03:07,  2.57s/it]
 52%|█████▏    | 78/150 [03:26<02:53,  2.42s/it]
 53%|█████▎    | 79/150 [03:28<02:46,  2.34s/it]

(train_sft_tune pid=41307) {'loss': 0.9536, 'grad_norm': 1.0775481462478638, 'learning_rate': 7.772724984255864e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:31<02:48,  2.40s/it]
 54%|█████▍    | 81/150 [03:33<02:51,  2.49s/it]
 55%|█████▍    | 82/150 [03:36<02:53,  2.55s/it]
 55%|█████▌    | 83/150 [03:38<02:47,  2.49s/it]
 56%|█████▌    | 84/150 [03:41<02:37,  2.39s/it]

(train_sft_tune pid=41307) {'loss': 0.9882, 'grad_norm': 0.9597605466842651, 'learning_rate': 7.225349985364606e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:43<02:42,  2.51s/it]
 57%|█████▋    | 86/150 [03:45<02:30,  2.36s/it]
 58%|█████▊    | 87/150 [03:48<02:39,  2.54s/it]
 59%|█████▊    | 88/150 [03:51<02:42,  2.61s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:08:39. Total running time: 1hr 14min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 59%|█████▉    | 89/150 [03:54<02:48,  2.77s/it]

(train_sft_tune pid=41307) {'loss': 0.9954, 'grad_norm': 0.8357112407684326, 'learning_rate': 6.677974986473348e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [03:56<02:27,  2.45s/it]
 61%|██████    | 91/150 [03:58<02:16,  2.31s/it]
 61%|██████▏   | 92/150 [04:00<02:17,  2.37s/it]
 62%|██████▏   | 93/150 [04:03<02:17,  2.41s/it]
 63%|██████▎   | 94/150 [04:05<02:10,  2.33s/it]

(train_sft_tune pid=41307) {'loss': 0.7999, 'grad_norm': 0.6981964707374573, 'learning_rate': 6.13059998758209e-05, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:08<02:14,  2.44s/it]
 64%|██████▍   | 96/150 [04:10<02:07,  2.37s/it]
 65%|██████▍   | 97/150 [04:13<02:13,  2.53s/it]
 65%|██████▌   | 98/150 [04:16<02:17,  2.64s/it]
 66%|██████▌   | 99/150 [04:19<02:21,  2.77s/it]

(train_sft_tune pid=41307) {'loss': 0.8927, 'grad_norm': 0.7667824029922485, 'learning_rate': 5.5832249886908315e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:21<02:05,  2.51s/it]
 67%|██████▋   | 101/150 [04:23<01:59,  2.43s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:09:09. Total running time: 1hr 14min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 68%|██████▊   | 102/150 [04:25<01:52,  2.35s/it]
 69%|██████▊   | 103/150 [04:28<01:54,  2.44s/it]
 69%|██████▉   | 104/150 [04:30<01:54,  2.49s/it]

(train_sft_tune pid=41307) {'loss': 0.9222, 'grad_norm': 0.7139136791229248, 'learning_rate': 5.035849989799574e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:33<01:51,  2.48s/it]
 71%|███████   | 106/150 [04:35<01:46,  2.42s/it]
 71%|███████▏  | 107/150 [04:38<01:50,  2.56s/it]
 72%|███████▏  | 108/150 [04:41<01:54,  2.73s/it]
 73%|███████▎  | 109/150 [04:44<01:50,  2.69s/it]

(train_sft_tune pid=41307) {'loss': 0.8339, 'grad_norm': 0.8552203178405762, 'learning_rate': 4.488474990908316e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [04:46<01:38,  2.47s/it]
 74%|███████▍  | 111/150 [04:49<01:44,  2.69s/it]
 75%|███████▍  | 112/150 [04:52<01:46,  2.81s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:09:40. Total running time: 1hr 15min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 75%|███████▌  | 113/150 [04:54<01:37,  2.63s/it]
 76%|███████▌  | 114/150 [04:57<01:37,  2.71s/it]

(train_sft_tune pid=41307) {'loss': 0.8595, 'grad_norm': 0.9273313879966736, 'learning_rate': 3.941099992017058e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [04:59<01:28,  2.53s/it]
 77%|███████▋  | 116/150 [05:02<01:25,  2.51s/it]
 78%|███████▊  | 117/150 [05:05<01:29,  2.73s/it]
 79%|███████▊  | 118/150 [05:08<01:32,  2.89s/it]
 79%|███████▉  | 119/150 [05:11<01:31,  2.96s/it]

(train_sft_tune pid=41307) {'loss': 1.0741, 'grad_norm': 0.8562014698982239, 'learning_rate': 3.3937249931258e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:14<01:23,  2.77s/it]
 81%|████████  | 121/150 [05:17<01:26,  2.99s/it]
 81%|████████▏ | 122/150 [05:21<01:27,  3.11s/it]
 82%|████████▏ | 123/150 [05:23<01:19,  2.96s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:10:10. Total running time: 1hr 15min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 83%|████████▎ | 124/150 [05:27<01:20,  3.09s/it]

(train_sft_tune pid=41307) {'loss': 0.8486, 'grad_norm': 0.760073184967041, 'learning_rate': 2.8463499942345418e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:29<01:13,  2.95s/it]
 84%|████████▍ | 126/150 [05:32<01:11,  2.97s/it]
 85%|████████▍ | 127/150 [05:35<01:07,  2.94s/it]
 85%|████████▌ | 128/150 [05:38<01:02,  2.82s/it]
 86%|████████▌ | 129/150 [05:39<00:51,  2.47s/it]

(train_sft_tune pid=41307) {'loss': 0.8463, 'grad_norm': 0.7628359198570251, 'learning_rate': 2.2989749953432837e-05, 'epoch': 0.21}

 87%|████████▋ | 130/150 [05:42<00:51,  2.56s/it]
 87%|████████▋ | 131/150 [05:44<00:48,  2.54s/it]
 88%|████████▊ | 132/150 [05:47<00:47,  2.64s/it]
 89%|████████▊ | 133/150 [05:49<00:41,  2.47s/it]
 89%|████████▉ | 134/150 [05:53<00:45,  2.82s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:10:40. Total running time: 1hr 16min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=41307) {'loss': 0.8751, 'grad_norm': 0.7938733696937561, 'learning_rate': 1.7515999964520256e-05, 'epoch': 0.22}

 90%|█████████ | 135/150 [05:56<00:41,  2.78s/it]
 91%|█████████ | 136/150 [05:59<00:39,  2.86s/it]
 91%|█████████▏| 137/150 [06:01<00:33,  2.58s/it]
 92%|█████████▏| 138/150 [06:03<00:30,  2.57s/it]
 93%|█████████▎| 139/150 [06:06<00:27,  2.53s/it]

(train_sft_tune pid=41307) {'loss': 0.9476, 'grad_norm': 0.7714327573776245, 'learning_rate': 1.2042249975607677e-05, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:08<00:24,  2.41s/it]
 94%|█████████▍| 141/150 [06:10<00:22,  2.46s/it]
 95%|█████████▍| 142/150 [06:13<00:20,  2.53s/it]
 95%|█████████▌| 143/150 [06:16<00:18,  2.58s/it]
 96%|█████████▌| 144/150 [06:19<00:16,  2.75s/it]

(train_sft_tune pid=41307) {'loss': 0.8776, 'grad_norm': 0.7858572602272034, 'learning_rate': 6.568499986695096e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:21<00:13,  2.65s/it]

Trial status: 9 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:11:10. Total running time: 1hr 16min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: bad7439a with train_loss=0.9134614070256551 and params={'lr': 0.00013559979888601068, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_f6d5bc07   RUNNING      0.000158739    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_53da69d4   PENDING      0.000179674    32             16                                            |
+--------------------------------------------------------------------------------------------------------------------+

 97%|█████████▋| 146/150 [06:24<00:10,  2.60s/it]
 98%|█████████▊| 147/150 [06:26<00:07,  2.58s/it]
 99%|█████████▊| 148/150 [06:29<00:05,  2.65s/it]
 99%|█████████▉| 149/150 [06:32<00:02,  2.57s/it]

(train_sft_tune pid=41307) {'loss': 0.9359, 'grad_norm': 0.7520708441734314, 'learning_rate': 1.094749997782516e-06, 'epoch': 0.24}

100%|██████████| 150/150 [06:34<00:00,  2.61s/it]

(train_sft_tune pid=41307) {'train_runtime': 395.7088, 'train_samples_per_second': 3.033, 'train_steps_per_second': 0.379, 'train_loss': 0.9123824580510458, 'epoch': 0.24}
(train_sft_tune pid=41307) history of tuning  [{'loss': 1.0791, 'grad_norm': 1.0293103456497192, 'learning_rate': 0.00012699099974277186, 'epoch': 0.008, 'step': 5}, {'loss': 0.9085, 'grad_norm': 0.7875751852989197, 'learning_rate': 0.00015435974968733474, 'epoch': 0.016, 'step': 10}, {'loss': 1.0039, 'grad_norm': 0.9596777558326721, 'learning_rate': 0.00014888599969842218, 'epoch': 0.024, 'step': 15}, {'loss': 0.9292, 'grad_norm': 1.1341583728790283, 'learning_rate': 0.0001434122497095096, 'epoch': 0.032, 'step': 20}, {'loss': 0.8652, 'grad_norm': 0.7635369300842285, 'learning_rate': 0.000137938499720597, 'epoch': 0.04, 'step': 25}, {'loss': 1.0085, 'grad_norm': 0.7693275809288025, 'learning_rate': 0.00013246474973168445, 'epoch': 0.048, 'step': 30}, {'loss': 0.8968, 'grad_norm': 0.8615941405296326, 'learning_rate': 0.00012699099974277186, 'epoch': 0.056, 'step': 35}, {'loss': 0.7876, 'grad_norm': 0.8689572811126709, 'learning_rate': 0.00012151724975385927, 'epoch': 0.064, 'step': 40}, {'loss': 0.8968, 'grad_norm': 0.8466201424598694, 'learning_rate': 0.0001160434997649467, 'epoch': 0.072, 'step': 45}, {'loss': 0.9265, 'grad_norm': 0.7894248962402344, 'learning_rate': 0.00011056974977603411, 'epoch': 0.08, 'step': 50}, {'loss': 0.8131, 'grad_norm': 0.8508226871490479, 'learning_rate': 0.00010509599978712154, 'epoch': 0.088, 'step': 55}, {'loss': 0.9433, 'grad_norm': 0.9803476333618164, 'learning_rate': 9.962224979820896e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.775, 'grad_norm': 0.7936156988143921, 'learning_rate': 9.414849980929637e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.8942, 'grad_norm': 0.7501825094223022, 'learning_rate': 8.86747498203838e-05, 'epoch': 0.112, 'step': 70}, {'loss': 0.9934, 'grad_norm': 0.7356411814689636, 'learning_rate': 8.320099983147123e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9536, 'grad_norm': 1.0775481462478638, 'learning_rate': 7.772724984255864e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.9882, 'grad_norm': 0.9597605466842651, 'learning_rate': 7.225349985364606e-05, 'epoch': 0.136, 'step': 85}, {'loss': 0.9954, 'grad_norm': 0.8357112407684326, 'learning_rate': 6.677974986473348e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.7999, 'grad_norm': 0.6981964707374573, 'learning_rate': 6.13059998758209e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8927, 'grad_norm': 0.7667824029922485, 'learning_rate': 5.5832249886908315e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9222, 'grad_norm': 0.7139136791229248, 'learning_rate': 5.035849989799574e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8339, 'grad_norm': 0.8552203178405762, 'learning_rate': 4.488474990908316e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8595, 'grad_norm': 0.9273313879966736, 'learning_rate': 3.941099992017058e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0741, 'grad_norm': 0.8562014698982239, 'learning_rate': 3.3937249931258e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8486, 'grad_norm': 0.760073184967041, 'learning_rate': 2.8463499942345418e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8463, 'grad_norm': 0.7628359198570251, 'learning_rate': 2.2989749953432837e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8751, 'grad_norm': 0.7938733696937561, 'learning_rate': 1.7515999964520256e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9476, 'grad_norm': 0.7714327573776245, 'learning_rate': 1.2042249975607677e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8776, 'grad_norm': 0.7858572602272034, 'learning_rate': 6.568499986695096e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9359, 'grad_norm': 0.7520708441734314, 'learning_rate': 1.094749997782516e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 395.7088, 'train_samples_per_second': 3.033, 'train_steps_per_second': 0.379, 'total_flos': 4888333847519232.0, 'train_loss': 0.9123824580510458, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=41307) Reporting loss: 0.9123824580510458

Trial train_sft_tune_f6d5bc07 completed after 1 iterations at 2025-11-29 17:11:21. Total running time: 1hr 16min 52s
+--------------------------------------------------+
| Trial train_sft_tune_f6d5bc07 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         440.693 |
| time_total_s                             440.693 |
| training_iteration                             1 |
| train_loss                               0.91238 |
+--------------------------------------------------+

100%|██████████| 150/150 [06:35<00:00,  2.64s/it]

Trial train_sft_tune_53da69d4 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_53da69d4 config             |
+--------------------------------------------------+
| lora_alpha                                    16 |
| lr                                       0.00018 |
| r                                             32 |
+--------------------------------------------------+
(train_sft_tune pid=43300) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=43300) 2025-11-29 17:11:36.569460: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=43300) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=43300) E0000 00:00:1764436296.611700   43356 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=43300) E0000 00:00:1764436296.622651   43356 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=43300) W0000 00:00:1764436296.656462   43356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=43300) W0000 00:00:1764436296.656511   43356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=43300) W0000 00:00:1764436296.656514   43356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=43300) W0000 00:00:1764436296.656518   43356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:11:40. Total running time: 1hr 17min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=43300) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=43300) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=43300)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=43300) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=43300) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=43300)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=43300) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=43300) [2025-11-29 17:12:00,355 E 43300 43338] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=43300) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:12:10. Total running time: 1hr 17min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=43300) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=43300) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=43300)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=43300) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=43300) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=43300)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=43300) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:12<31:10, 12.56s/it]
  1%|▏         | 2/150 [00:14<15:48,  6.41s/it]
  2%|▏         | 3/150 [00:17<11:43,  4.79s/it]
  3%|▎         | 4/150 [00:20<09:37,  3.95s/it]

(train_sft_tune pid=43300) {'loss': 1.0889, 'grad_norm': 0.23334290087223053, 'learning_rate': 0.00014373900136446056, 'epoch': 0.01}

  3%|▎         | 5/150 [00:22<07:57,  3.29s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:12:40. Total running time: 1hr 18min 10s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  4%|▍         | 6/150 [00:24<07:23,  3.08s/it]
  5%|▍         | 7/150 [00:27<06:55,  2.90s/it]
  5%|▌         | 8/150 [00:30<06:38,  2.80s/it]
  6%|▌         | 9/150 [00:32<06:22,  2.71s/it]

(train_sft_tune pid=43300) {'loss': 0.9328, 'grad_norm': 0.20978665351867676, 'learning_rate': 0.00017471723441714603, 'epoch': 0.02}

  7%|▋         | 10/150 [00:35<06:14,  2.68s/it]
  7%|▋         | 11/150 [00:38<06:18,  2.72s/it]
  8%|▊         | 12/150 [00:40<05:53,  2.56s/it]
  9%|▊         | 13/150 [00:43<06:11,  2.71s/it]
  9%|▉         | 14/150 [00:45<05:48,  2.56s/it]

(train_sft_tune pid=43300) {'loss': 1.023, 'grad_norm': 0.19947712123394012, 'learning_rate': 0.00016852158780660892, 'epoch': 0.02}

 10%|█         | 15/150 [00:47<05:16,  2.34s/it]
 11%|█         | 16/150 [00:50<05:29,  2.46s/it]
 11%|█▏        | 17/150 [00:53<05:51,  2.64s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:13:10. Total running time: 1hr 18min 40s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 12%|█▏        | 18/150 [00:55<05:20,  2.43s/it]
 13%|█▎        | 19/150 [00:57<05:26,  2.50s/it]

(train_sft_tune pid=43300) {'loss': 0.946, 'grad_norm': 0.3243914544582367, 'learning_rate': 0.00016232594119607185, 'epoch': 0.03}

 13%|█▎        | 20/150 [00:59<04:45,  2.20s/it]
 14%|█▍        | 21/150 [01:01<04:41,  2.18s/it]
 15%|█▍        | 22/150 [01:03<04:44,  2.22s/it]
 15%|█▌        | 23/150 [01:06<04:50,  2.29s/it]
 16%|█▌        | 24/150 [01:08<05:06,  2.44s/it]

(train_sft_tune pid=43300) {'loss': 0.8759, 'grad_norm': 0.17892445623874664, 'learning_rate': 0.00015613029458553474, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:11<05:11,  2.49s/it]
 17%|█▋        | 26/150 [01:14<05:36,  2.71s/it]
 18%|█▊        | 27/150 [01:17<05:16,  2.57s/it]
 19%|█▊        | 28/150 [01:19<05:25,  2.67s/it]
 19%|█▉        | 29/150 [01:21<04:55,  2.45s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:13:40. Total running time: 1hr 19min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=43300) {'loss': 1.019, 'grad_norm': 0.1980839967727661, 'learning_rate': 0.00014993464797499766, 'epoch': 0.05}

 20%|██        | 30/150 [01:25<05:35,  2.79s/it]
 21%|██        | 31/150 [01:28<05:39,  2.85s/it]
 21%|██▏       | 32/150 [01:30<05:09,  2.62s/it]
 22%|██▏       | 33/150 [01:33<05:26,  2.79s/it]
 23%|██▎       | 34/150 [01:36<05:14,  2.71s/it]

(train_sft_tune pid=43300) {'loss': 0.9015, 'grad_norm': 0.21245798468589783, 'learning_rate': 0.00014373900136446056, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:38<04:51,  2.54s/it]
 24%|██▍       | 36/150 [01:40<04:46,  2.51s/it]
 25%|██▍       | 37/150 [01:43<04:46,  2.54s/it]
 25%|██▌       | 38/150 [01:45<04:36,  2.47s/it]
 26%|██▌       | 39/150 [01:48<04:45,  2.57s/it]

(train_sft_tune pid=43300) {'loss': 0.7986, 'grad_norm': 0.2211657613515854, 'learning_rate': 0.00013754335475392346, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:51<04:44,  2.58s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:14:10. Total running time: 1hr 19min 41s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 27%|██▋       | 41/150 [01:53<04:44,  2.61s/it]
 28%|██▊       | 42/150 [01:56<04:44,  2.64s/it]
 29%|██▊       | 43/150 [01:58<04:19,  2.43s/it]
 29%|██▉       | 44/150 [02:01<04:23,  2.48s/it]

(train_sft_tune pid=43300) {'loss': 0.9053, 'grad_norm': 0.21754470467567444, 'learning_rate': 0.00013134770814338638, 'epoch': 0.07}

 30%|███       | 45/150 [02:02<04:02,  2.31s/it]
 31%|███       | 46/150 [02:05<04:15,  2.46s/it]
 31%|███▏      | 47/150 [02:08<04:25,  2.58s/it]
 32%|███▏      | 48/150 [02:11<04:36,  2.71s/it]
 33%|███▎      | 49/150 [02:13<04:16,  2.53s/it]

(train_sft_tune pid=43300) {'loss': 0.9302, 'grad_norm': 0.2134866565465927, 'learning_rate': 0.00012515206153284927, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:16<04:26,  2.67s/it]
 34%|███▍      | 51/150 [02:20<04:46,  2.89s/it]
 35%|███▍      | 52/150 [02:22<04:31,  2.77s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:14:40. Total running time: 1hr 20min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 35%|███▌      | 53/150 [02:25<04:24,  2.73s/it]
 36%|███▌      | 54/150 [02:27<04:16,  2.67s/it]

(train_sft_tune pid=43300) {'loss': 0.8198, 'grad_norm': 0.22063186764717102, 'learning_rate': 0.00011895641492231218, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:29<03:55,  2.48s/it]
 37%|███▋      | 56/150 [02:32<04:00,  2.56s/it]
 38%|███▊      | 57/150 [02:34<03:41,  2.38s/it]
 39%|███▊      | 58/150 [02:37<03:45,  2.45s/it]
 39%|███▉      | 59/150 [02:39<03:47,  2.50s/it]

(train_sft_tune pid=43300) {'loss': 0.9512, 'grad_norm': 0.2562682628631592, 'learning_rate': 0.0001127607683117751, 'epoch': 0.1}

 40%|████      | 60/150 [02:42<03:42,  2.48s/it]
 41%|████      | 61/150 [02:45<03:49,  2.58s/it]
 41%|████▏     | 62/150 [02:48<04:14,  2.89s/it]
 42%|████▏     | 63/150 [02:51<04:17,  2.96s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:15:10. Total running time: 1hr 20min 41s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 43%|████▎     | 64/150 [02:55<04:25,  3.09s/it]

(train_sft_tune pid=43300) {'loss': 0.7826, 'grad_norm': 0.20716267824172974, 'learning_rate': 0.00010656512170123799, 'epoch': 0.1}

 43%|████▎     | 65/150 [02:57<03:57,  2.80s/it]
 44%|████▍     | 66/150 [03:00<03:58,  2.84s/it]
 45%|████▍     | 67/150 [03:02<03:39,  2.65s/it]
 45%|████▌     | 68/150 [03:04<03:22,  2.46s/it]
 46%|████▌     | 69/150 [03:06<03:07,  2.31s/it]

(train_sft_tune pid=43300) {'loss': 0.9003, 'grad_norm': 0.20409846305847168, 'learning_rate': 0.00010036947509070091, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:09<03:26,  2.58s/it]
 47%|████▋     | 71/150 [03:12<03:38,  2.76s/it]
 48%|████▊     | 72/150 [03:15<03:25,  2.63s/it]
 49%|████▊     | 73/150 [03:17<03:26,  2.68s/it]
 49%|████▉     | 74/150 [03:20<03:17,  2.60s/it]

(train_sft_tune pid=43300) {'loss': 0.9969, 'grad_norm': 0.19312623143196106, 'learning_rate': 9.417382848016382e-05, 'epoch': 0.12}

 50%|█████     | 75/150 [03:23<03:17,  2.63s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:15:40. Total running time: 1hr 21min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 51%|█████     | 76/150 [03:25<03:16,  2.65s/it]
 51%|█████▏    | 77/150 [03:28<03:11,  2.62s/it]
 52%|█████▏    | 78/150 [03:30<02:56,  2.45s/it]
 53%|█████▎    | 79/150 [03:32<02:48,  2.37s/it]

(train_sft_tune pid=43300) {'loss': 0.9619, 'grad_norm': 0.284930944442749, 'learning_rate': 8.797818186962672e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:35<02:50,  2.43s/it]
 54%|█████▍    | 81/150 [03:37<02:55,  2.54s/it]
 55%|█████▍    | 82/150 [03:40<02:58,  2.62s/it]
 55%|█████▌    | 83/150 [03:43<02:50,  2.54s/it]
 56%|█████▌    | 84/150 [03:45<02:40,  2.44s/it]

(train_sft_tune pid=43300) {'loss': 0.9984, 'grad_norm': 0.2624940276145935, 'learning_rate': 8.178253525908964e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:48<02:45,  2.55s/it]
 57%|█████▋    | 86/150 [03:50<02:34,  2.41s/it]
 58%|█████▊    | 87/150 [03:53<02:43,  2.60s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:16:10. Total running time: 1hr 21min 41s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 59%|█████▊    | 88/150 [03:55<02:44,  2.66s/it]
 59%|█████▉    | 89/150 [03:59<02:51,  2.81s/it]

(train_sft_tune pid=43300) {'loss': 1.0008, 'grad_norm': 0.2278735339641571, 'learning_rate': 7.558688864855253e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [04:00<02:29,  2.49s/it]
 61%|██████    | 91/150 [04:02<02:19,  2.36s/it]
 61%|██████▏   | 92/150 [04:05<02:20,  2.43s/it]
 62%|██████▏   | 93/150 [04:07<02:18,  2.43s/it]
 63%|██████▎   | 94/150 [04:10<02:11,  2.35s/it]

(train_sft_tune pid=43300) {'loss': 0.8041, 'grad_norm': 0.19204272329807281, 'learning_rate': 6.939124203801544e-05, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:12<02:15,  2.46s/it]
 64%|██████▍   | 96/150 [04:15<02:09,  2.40s/it]
 65%|██████▍   | 97/150 [04:18<02:16,  2.58s/it]
 65%|██████▌   | 98/150 [04:20<02:18,  2.67s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:16:41. Total running time: 1hr 22min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 66%|██████▌   | 99/150 [04:24<02:23,  2.81s/it]

(train_sft_tune pid=43300) {'loss': 0.8986, 'grad_norm': 0.21344535052776337, 'learning_rate': 6.319559542747835e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:26<02:07,  2.54s/it]
 67%|██████▋   | 101/150 [04:28<02:01,  2.48s/it]
 68%|██████▊   | 102/150 [04:30<01:55,  2.41s/it]
 69%|██████▊   | 103/150 [04:33<01:56,  2.49s/it]
 69%|██████▉   | 104/150 [04:35<01:56,  2.53s/it]

(train_sft_tune pid=43300) {'loss': 0.9279, 'grad_norm': 0.1915910691022873, 'learning_rate': 5.699994881694126e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:38<01:53,  2.52s/it]
 71%|███████   | 106/150 [04:40<01:48,  2.46s/it]
 71%|███████▏  | 107/150 [04:43<01:53,  2.63s/it]
 72%|███████▏  | 108/150 [04:46<01:56,  2.78s/it]
 73%|███████▎  | 109/150 [04:49<01:51,  2.72s/it]

(train_sft_tune pid=43300) {'loss': 0.8403, 'grad_norm': 0.24009786546230316, 'learning_rate': 5.0804302206404165e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [04:51<01:39,  2.49s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:17:11. Total running time: 1hr 22min 41s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 74%|███████▍  | 111/150 [04:54<01:45,  2.71s/it]
 75%|███████▍  | 112/150 [04:57<01:47,  2.84s/it]
 75%|███████▌  | 113/150 [04:59<01:36,  2.60s/it]
 76%|███████▌  | 114/150 [05:02<01:36,  2.67s/it]

(train_sft_tune pid=43300) {'loss': 0.8698, 'grad_norm': 0.25878220796585083, 'learning_rate': 4.460865559586707e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:04<01:27,  2.50s/it]
 77%|███████▋  | 116/150 [05:07<01:24,  2.48s/it]
 78%|███████▊  | 117/150 [05:10<01:28,  2.67s/it]
 79%|███████▊  | 118/150 [05:13<01:29,  2.79s/it]
 79%|███████▉  | 119/150 [05:16<01:27,  2.82s/it]

(train_sft_tune pid=43300) {'loss': 1.0805, 'grad_norm': 0.23234058916568756, 'learning_rate': 3.8413008985329976e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:18<01:19,  2.64s/it]
 81%|████████  | 121/150 [05:21<01:22,  2.83s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:17:41. Total running time: 1hr 23min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 81%|████████▏ | 122/150 [05:24<01:21,  2.92s/it]
 82%|████████▏ | 123/150 [05:27<01:15,  2.78s/it]
 83%|████████▎ | 124/150 [05:30<01:15,  2.91s/it]

(train_sft_tune pid=43300) {'loss': 0.8533, 'grad_norm': 0.20349809527397156, 'learning_rate': 3.2217362374792886e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:33<01:10,  2.81s/it]
 84%|████████▍ | 126/150 [05:36<01:08,  2.84s/it]
 85%|████████▍ | 127/150 [05:38<01:04,  2.81s/it]
 85%|████████▌ | 128/150 [05:41<00:59,  2.71s/it]
 86%|████████▌ | 129/150 [05:42<00:50,  2.39s/it]

(train_sft_tune pid=43300) {'loss': 0.8539, 'grad_norm': 0.20532113313674927, 'learning_rate': 2.6021715764255795e-05, 'epoch': 0.21}

 87%|████████▋ | 130/150 [05:45<00:49,  2.49s/it]
 87%|████████▋ | 131/150 [05:48<00:47,  2.49s/it]
 88%|████████▊ | 132/150 [05:50<00:46,  2.58s/it]
 89%|████████▊ | 133/150 [05:52<00:41,  2.43s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:18:11. Total running time: 1hr 23min 41s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 89%|████████▉ | 134/150 [05:56<00:44,  2.79s/it]

(train_sft_tune pid=43300) {'loss': 0.8808, 'grad_norm': 0.2311025857925415, 'learning_rate': 1.9826069153718697e-05, 'epoch': 0.22}

 90%|█████████ | 135/150 [05:59<00:41,  2.76s/it]
 91%|█████████ | 136/150 [06:02<00:39,  2.84s/it]
 91%|█████████▏| 137/150 [06:04<00:33,  2.55s/it]
 92%|█████████▏| 138/150 [06:06<00:30,  2.54s/it]
 93%|█████████▎| 139/150 [06:09<00:27,  2.50s/it]

(train_sft_tune pid=43300) {'loss': 0.954, 'grad_norm': 0.21985064446926117, 'learning_rate': 1.3630422543181605e-05, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:11<00:23,  2.39s/it]
 94%|█████████▍| 141/150 [06:13<00:22,  2.47s/it]
 95%|█████████▍| 142/150 [06:16<00:20,  2.50s/it]
 95%|█████████▌| 143/150 [06:19<00:17,  2.56s/it]
 96%|█████████▌| 144/150 [06:22<00:16,  2.73s/it]

Trial status: 10 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:18:41. Total running time: 1hr 24min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_53da69d4   RUNNING      0.000179674    32             16                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_d33d8ede   PENDING      0.000407619     8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=43300) {'loss': 0.8836, 'grad_norm': 0.21496878564357758, 'learning_rate': 7.4347759326445115e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:24<00:13,  2.65s/it]
 97%|█████████▋| 146/150 [06:27<00:10,  2.59s/it]
 98%|█████████▊| 147/150 [06:29<00:07,  2.57s/it]
 99%|█████████▊| 148/150 [06:32<00:05,  2.63s/it]
 99%|█████████▉| 149/150 [06:34<00:02,  2.54s/it]

(train_sft_tune pid=43300) {'loss': 0.9458, 'grad_norm': 0.20065070688724518, 'learning_rate': 1.2391293221074186e-06, 'epoch': 0.24}

100%|██████████| 150/150 [06:37<00:00,  2.59s/it]

Trial train_sft_tune_53da69d4 completed after 1 iterations at 2025-11-29 17:18:55. Total running time: 1hr 24min 26s
+--------------------------------------------------+
| Trial train_sft_tune_53da69d4 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         444.349 |
| time_total_s                             444.349 |
| training_iteration                             1 |
| train_loss                               0.92086 |
+--------------------------------------------------+
(train_sft_tune pid=43300) {'train_runtime': 398.8404, 'train_samples_per_second': 3.009, 'train_steps_per_second': 0.376, 'train_loss': 0.9208558019002279, 'epoch': 0.24}
(train_sft_tune pid=43300) history of tuning  [{'loss': 1.0889, 'grad_norm': 0.23334290087223053, 'learning_rate': 0.00014373900136446056, 'epoch': 0.008, 'step': 5}, {'loss': 0.9328, 'grad_norm': 0.20978665351867676, 'learning_rate': 0.00017471723441714603, 'epoch': 0.016, 'step': 10}, {'loss': 1.023, 'grad_norm': 0.19947712123394012, 'learning_rate': 0.00016852158780660892, 'epoch': 0.024, 'step': 15}, {'loss': 0.946, 'grad_norm': 0.3243914544582367, 'learning_rate': 0.00016232594119607185, 'epoch': 0.032, 'step': 20}, {'loss': 0.8759, 'grad_norm': 0.17892445623874664, 'learning_rate': 0.00015613029458553474, 'epoch': 0.04, 'step': 25}, {'loss': 1.019, 'grad_norm': 0.1980839967727661, 'learning_rate': 0.00014993464797499766, 'epoch': 0.048, 'step': 30}, {'loss': 0.9015, 'grad_norm': 0.21245798468589783, 'learning_rate': 0.00014373900136446056, 'epoch': 0.056, 'step': 35}, {'loss': 0.7986, 'grad_norm': 0.2211657613515854, 'learning_rate': 0.00013754335475392346, 'epoch': 0.064, 'step': 40}, {'loss': 0.9053, 'grad_norm': 0.21754470467567444, 'learning_rate': 0.00013134770814338638, 'epoch': 0.072, 'step': 45}, {'loss': 0.9302, 'grad_norm': 0.2134866565465927, 'learning_rate': 0.00012515206153284927, 'epoch': 0.08, 'step': 50}, {'loss': 0.8198, 'grad_norm': 0.22063186764717102, 'learning_rate': 0.00011895641492231218, 'epoch': 0.088, 'step': 55}, {'loss': 0.9512, 'grad_norm': 0.2562682628631592, 'learning_rate': 0.0001127607683117751, 'epoch': 0.096, 'step': 60}, {'loss': 0.7826, 'grad_norm': 0.20716267824172974, 'learning_rate': 0.00010656512170123799, 'epoch': 0.104, 'step': 65}, {'loss': 0.9003, 'grad_norm': 0.20409846305847168, 'learning_rate': 0.00010036947509070091, 'epoch': 0.112, 'step': 70}, {'loss': 0.9969, 'grad_norm': 0.19312623143196106, 'learning_rate': 9.417382848016382e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9619, 'grad_norm': 0.284930944442749, 'learning_rate': 8.797818186962672e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.9984, 'grad_norm': 0.2624940276145935, 'learning_rate': 8.178253525908964e-05, 'epoch': 0.136, 'step': 85}, {'loss': 1.0008, 'grad_norm': 0.2278735339641571, 'learning_rate': 7.558688864855253e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8041, 'grad_norm': 0.19204272329807281, 'learning_rate': 6.939124203801544e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8986, 'grad_norm': 0.21344535052776337, 'learning_rate': 6.319559542747835e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9279, 'grad_norm': 0.1915910691022873, 'learning_rate': 5.699994881694126e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8403, 'grad_norm': 0.24009786546230316, 'learning_rate': 5.0804302206404165e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8698, 'grad_norm': 0.25878220796585083, 'learning_rate': 4.460865559586707e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0805, 'grad_norm': 0.23234058916568756, 'learning_rate': 3.8413008985329976e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8533, 'grad_norm': 0.20349809527397156, 'learning_rate': 3.2217362374792886e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8539, 'grad_norm': 0.20532113313674927, 'learning_rate': 2.6021715764255795e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8808, 'grad_norm': 0.2311025857925415, 'learning_rate': 1.9826069153718697e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.954, 'grad_norm': 0.21985064446926117, 'learning_rate': 1.3630422543181605e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8836, 'grad_norm': 0.21496878564357758, 'learning_rate': 7.4347759326445115e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9458, 'grad_norm': 0.20065070688724518, 'learning_rate': 1.2391293221074186e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 398.8404, 'train_samples_per_second': 3.009, 'train_steps_per_second': 0.376, 'total_flos': 4944308261511168.0, 'train_loss': 0.9208558019002279, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=43300) Reporting loss: 0.9208558019002279

100%|██████████| 150/150 [06:38<00:00,  2.66s/it]

Trial train_sft_tune_d33d8ede started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_d33d8ede config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00041 |
| r                                              8 |
+--------------------------------------------------+
(train_sft_tune pid=45299) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=45299) 2025-11-29 17:19:11.111652: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=45299) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=45299) E0000 00:00:1764436751.139680   45356 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=45299) E0000 00:00:1764436751.146462   45356 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=45299) W0000 00:00:1764436751.163264   45356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=45299) W0000 00:00:1764436751.163303   45356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=45299) W0000 00:00:1764436751.163306   45356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=45299) W0000 00:00:1764436751.163308   45356 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:19:11. Total running time: 1hr 24min 41s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=45299) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=45299) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=45299)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=45299) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=45299) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=45299)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=45299) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=45299) [2025-11-29 17:19:34,438 E 45299 45337] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:19:41. Total running time: 1hr 25min 11s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=45299) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=45299) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=45299) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=45299)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=45299) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=45299) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=45299)  "-____-"     Trainable parameters = 5,636,096 of 1,241,450,496 (0.45% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=45299) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:13<32:32, 13.10s/it]
  1%|▏         | 2/150 [00:15<16:11,  6.57s/it]
  2%|▏         | 3/150 [00:17<11:45,  4.80s/it]
  3%|▎         | 4/150 [00:20<09:29,  3.90s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:20:11. Total running time: 1hr 25min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  3%|▎         | 5/150 [00:22<07:49,  3.24s/it]

(train_sft_tune pid=45299) {'loss': 1.0698, 'grad_norm': 1.6210365295410156, 'learning_rate': 0.00032609497897358847, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:09,  2.98s/it]
  5%|▍         | 7/150 [00:27<06:41,  2.80s/it]
  5%|▌         | 8/150 [00:29<06:24,  2.71s/it]
  6%|▌         | 9/150 [00:32<06:09,  2.62s/it]
  7%|▋         | 10/150 [00:34<06:01,  2.58s/it]

(train_sft_tune pid=45299) {'loss': 0.8936, 'grad_norm': 1.2224524021148682, 'learning_rate': 0.0003963740692696204, 'epoch': 0.02}

  7%|▋         | 11/150 [00:37<06:04,  2.62s/it]
  8%|▊         | 12/150 [00:39<05:41,  2.48s/it]
  9%|▊         | 13/150 [00:42<05:59,  2.62s/it]
  9%|▉         | 14/150 [00:44<05:37,  2.48s/it]
 10%|█         | 15/150 [00:46<05:05,  2.26s/it]

(train_sft_tune pid=45299) {'loss': 1.0015, 'grad_norm': 1.32182776927948, 'learning_rate': 0.000382318251210414, 'epoch': 0.02}

 11%|█         | 16/150 [00:49<05:17,  2.37s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:20:41. Total running time: 1hr 26min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 11%|█▏        | 17/150 [00:52<05:40,  2.56s/it]
 12%|█▏        | 18/150 [00:53<05:11,  2.36s/it]
 13%|█▎        | 19/150 [00:56<05:17,  2.43s/it]
 13%|█▎        | 20/150 [00:58<04:37,  2.14s/it]

(train_sft_tune pid=45299) {'loss': 0.932, 'grad_norm': 1.5813697576522827, 'learning_rate': 0.0003682624331512076, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:00<04:31,  2.11s/it]
 15%|█▍        | 22/150 [01:02<04:33,  2.14s/it]
 15%|█▌        | 23/150 [01:04<04:41,  2.22s/it]
 16%|█▌        | 24/150 [01:07<04:56,  2.36s/it]
 17%|█▋        | 25/150 [01:09<05:01,  2.41s/it]

(train_sft_tune pid=45299) {'loss': 0.8696, 'grad_norm': 0.9875711798667908, 'learning_rate': 0.00035420661509200123, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:12<05:24,  2.62s/it]
 18%|█▊        | 27/150 [01:15<05:06,  2.49s/it]
 19%|█▊        | 28/150 [01:17<05:16,  2.59s/it]
 19%|█▉        | 29/150 [01:19<04:46,  2.37s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:21:11. Total running time: 1hr 26min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 20%|██        | 30/150 [01:23<05:25,  2.71s/it]

(train_sft_tune pid=45299) {'loss': 1.0141, 'grad_norm': 1.1712521314620972, 'learning_rate': 0.00034015079703279485, 'epoch': 0.05}

 21%|██        | 31/150 [01:26<05:28,  2.76s/it]
 21%|██▏       | 32/150 [01:28<04:58,  2.53s/it]
 22%|██▏       | 33/150 [01:31<05:17,  2.71s/it]
 23%|██▎       | 34/150 [01:33<05:06,  2.65s/it]
 23%|██▎       | 35/150 [01:35<04:45,  2.48s/it]

(train_sft_tune pid=45299) {'loss': 0.9012, 'grad_norm': 1.1878232955932617, 'learning_rate': 0.00032609497897358847, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:38<04:37,  2.44s/it]
 25%|██▍       | 37/150 [01:40<04:40,  2.48s/it]
 25%|██▌       | 38/150 [01:43<04:34,  2.45s/it]
 26%|██▌       | 39/150 [01:45<04:41,  2.53s/it]
 27%|██▋       | 40/150 [01:48<04:39,  2.54s/it]

(train_sft_tune pid=45299) {'loss': 0.79, 'grad_norm': 1.3488677740097046, 'learning_rate': 0.00031203916091438204, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:51<04:37,  2.54s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:21:41. Total running time: 1hr 27min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 28%|██▊       | 42/150 [01:53<04:38,  2.58s/it]
 29%|██▊       | 43/150 [01:55<04:17,  2.41s/it]
 29%|██▉       | 44/150 [01:58<04:20,  2.46s/it]
 30%|███       | 45/150 [02:00<04:00,  2.29s/it]

(train_sft_tune pid=45299) {'loss': 0.9012, 'grad_norm': 1.1933400630950928, 'learning_rate': 0.00029798334285517566, 'epoch': 0.07}

 31%|███       | 46/150 [02:03<04:13,  2.43s/it]
 31%|███▏      | 47/150 [02:05<04:22,  2.55s/it]
 32%|███▏      | 48/150 [02:08<04:35,  2.70s/it]
 33%|███▎      | 49/150 [02:10<04:14,  2.52s/it]
 33%|███▎      | 50/150 [02:13<04:26,  2.66s/it]

(train_sft_tune pid=45299) {'loss': 0.9355, 'grad_norm': 1.043503999710083, 'learning_rate': 0.0002839275247959692, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:17<04:43,  2.86s/it]
 35%|███▍      | 52/150 [02:19<04:27,  2.73s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:22:11. Total running time: 1hr 27min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 35%|███▌      | 53/150 [02:22<04:22,  2.71s/it]
 36%|███▌      | 54/150 [02:24<04:14,  2.65s/it]
 37%|███▋      | 55/150 [02:26<03:52,  2.45s/it]

(train_sft_tune pid=45299) {'loss': 0.8196, 'grad_norm': 1.2222000360488892, 'learning_rate': 0.00026987170673676284, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:29<03:56,  2.52s/it]
 38%|███▊      | 57/150 [02:31<03:36,  2.33s/it]
 39%|███▊      | 58/150 [02:34<03:43,  2.43s/it]
 39%|███▉      | 59/150 [02:36<03:45,  2.48s/it]
 40%|████      | 60/150 [02:39<03:44,  2.50s/it]

(train_sft_tune pid=45299) {'loss': 0.9561, 'grad_norm': 1.4296318292617798, 'learning_rate': 0.00025581588867755646, 'epoch': 0.1}

 41%|████      | 61/150 [02:41<03:48,  2.57s/it]
 41%|████▏     | 62/150 [02:45<04:11,  2.86s/it]
 42%|████▏     | 63/150 [02:48<04:14,  2.93s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:22:41. Total running time: 1hr 28min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 43%|████▎     | 64/150 [02:51<04:21,  3.04s/it]
 43%|████▎     | 65/150 [02:53<03:52,  2.73s/it]

(train_sft_tune pid=45299) {'loss': 0.7845, 'grad_norm': 1.1908822059631348, 'learning_rate': 0.00024176007061835002, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:56<03:51,  2.76s/it]
 45%|████▍     | 67/150 [02:59<03:36,  2.61s/it]
 45%|████▌     | 68/150 [03:01<03:20,  2.44s/it]
 46%|████▌     | 69/150 [03:02<03:04,  2.28s/it]
 47%|████▋     | 70/150 [03:06<03:22,  2.53s/it]

(train_sft_tune pid=45299) {'loss': 0.9036, 'grad_norm': 1.0537197589874268, 'learning_rate': 0.00022770425255914364, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:09<03:32,  2.69s/it]
 48%|████▊     | 72/150 [03:11<03:21,  2.58s/it]
 49%|████▊     | 73/150 [03:14<03:23,  2.64s/it]
 49%|████▉     | 74/150 [03:16<03:14,  2.55s/it]
 50%|█████     | 75/150 [03:19<03:13,  2.58s/it]

(train_sft_tune pid=45299) {'loss': 0.998, 'grad_norm': 1.0083982944488525, 'learning_rate': 0.00021364843449993726, 'epoch': 0.12}
Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:23:11. Total running time: 1hr 28min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 51%|█████     | 76/150 [03:21<03:10,  2.57s/it]
 51%|█████▏    | 77/150 [03:24<03:08,  2.58s/it]
 52%|█████▏    | 78/150 [03:26<02:54,  2.42s/it]
 53%|█████▎    | 79/150 [03:28<02:46,  2.34s/it]
 53%|█████▎    | 80/150 [03:31<02:48,  2.40s/it]

(train_sft_tune pid=45299) {'loss': 0.9682, 'grad_norm': 1.5290271043777466, 'learning_rate': 0.00019959261644073085, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:33<02:51,  2.48s/it]
 55%|█████▍    | 82/150 [03:36<02:54,  2.56s/it]
 55%|█████▌    | 83/150 [03:38<02:46,  2.49s/it]
 56%|█████▌    | 84/150 [03:41<02:37,  2.39s/it]
 57%|█████▋    | 85/150 [03:43<02:42,  2.50s/it]

(train_sft_tune pid=45299) {'loss': 1.0012, 'grad_norm': 1.2788819074630737, 'learning_rate': 0.00018553679838152447, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:45<02:30,  2.36s/it]
 58%|█████▊    | 87/150 [03:48<02:39,  2.54s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:23:42. Total running time: 1hr 29min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 59%|█████▊    | 88/150 [03:51<02:42,  2.62s/it]
 59%|█████▉    | 89/150 [03:54<02:48,  2.77s/it]
 60%|██████    | 90/150 [03:56<02:27,  2.46s/it]

(train_sft_tune pid=45299) {'loss': 1.0053, 'grad_norm': 1.2879043817520142, 'learning_rate': 0.00017148098032231806, 'epoch': 0.14}

 61%|██████    | 91/150 [03:58<02:16,  2.31s/it]
 61%|██████▏   | 92/150 [04:00<02:18,  2.38s/it]
 62%|██████▏   | 93/150 [04:03<02:17,  2.41s/it]
 63%|██████▎   | 94/150 [04:05<02:10,  2.33s/it]
 63%|██████▎   | 95/150 [04:08<02:14,  2.44s/it]

(train_sft_tune pid=45299) {'loss': 0.8095, 'grad_norm': 0.9309933185577393, 'learning_rate': 0.00015742516226311166, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:10<02:07,  2.37s/it]
 65%|██████▍   | 97/150 [04:13<02:14,  2.53s/it]
 65%|██████▌   | 98/150 [04:16<02:16,  2.63s/it]
 66%|██████▌   | 99/150 [04:19<02:21,  2.77s/it]
 67%|██████▋   | 100/150 [04:21<02:05,  2.50s/it]

(train_sft_tune pid=45299) {'loss': 0.9043, 'grad_norm': 1.051042914390564, 'learning_rate': 0.00014336934420390525, 'epoch': 0.16}
Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:24:12. Total running time: 1hr 29min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 67%|██████▋   | 101/150 [04:23<01:59,  2.44s/it]
 68%|██████▊   | 102/150 [04:25<01:53,  2.36s/it]
 69%|██████▊   | 103/150 [04:28<01:55,  2.46s/it]
 69%|██████▉   | 104/150 [04:30<01:55,  2.50s/it]
 70%|███████   | 105/150 [04:33<01:52,  2.49s/it]

(train_sft_tune pid=45299) {'loss': 0.9275, 'grad_norm': 0.9876271486282349, 'learning_rate': 0.00012931352614469887, 'epoch': 0.17}

 71%|███████   | 106/150 [04:35<01:46,  2.42s/it]
 71%|███████▏  | 107/150 [04:38<01:50,  2.57s/it]
 72%|███████▏  | 108/150 [04:41<01:55,  2.74s/it]
 73%|███████▎  | 109/150 [04:44<01:49,  2.68s/it]
 73%|███████▎  | 110/150 [04:46<01:38,  2.46s/it]

(train_sft_tune pid=45299) {'loss': 0.8405, 'grad_norm': 1.2033132314682007, 'learning_rate': 0.00011525770808549246, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:49<01:44,  2.67s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:24:42. Total running time: 1hr 30min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 75%|███████▍  | 112/150 [04:52<01:46,  2.79s/it]
 75%|███████▌  | 113/150 [04:54<01:35,  2.59s/it]
 76%|███████▌  | 114/150 [04:57<01:35,  2.66s/it]
 77%|███████▋  | 115/150 [04:59<01:26,  2.48s/it]

(train_sft_tune pid=45299) {'loss': 0.8635, 'grad_norm': 1.324117660522461, 'learning_rate': 0.00010120189002628607, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:01<01:23,  2.45s/it]
 78%|███████▊  | 117/150 [05:04<01:26,  2.64s/it]
 79%|███████▊  | 118/150 [05:07<01:28,  2.75s/it]
 79%|███████▉  | 119/150 [05:10<01:25,  2.77s/it]
 80%|████████  | 120/150 [05:12<01:17,  2.59s/it]

(train_sft_tune pid=45299) {'loss': 1.0859, 'grad_norm': 1.272504448890686, 'learning_rate': 8.714607196707967e-05, 'epoch': 0.19}

 81%|████████  | 121/150 [05:16<01:20,  2.77s/it]
 81%|████████▏ | 122/150 [05:19<01:20,  2.87s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:25:12. Total running time: 1hr 30min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 82%|████████▏ | 123/150 [05:21<01:13,  2.74s/it]
 83%|████████▎ | 124/150 [05:24<01:14,  2.87s/it]
 83%|████████▎ | 125/150 [05:27<01:08,  2.76s/it]

(train_sft_tune pid=45299) {'loss': 0.8543, 'grad_norm': 1.0498095750808716, 'learning_rate': 7.309025390787326e-05, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:30<01:07,  2.80s/it]
 85%|████████▍ | 127/150 [05:33<01:04,  2.79s/it]
 85%|████████▌ | 128/150 [05:35<00:59,  2.69s/it]
 86%|████████▌ | 129/150 [05:37<00:49,  2.36s/it]
 87%|████████▋ | 130/150 [05:39<00:49,  2.46s/it]

(train_sft_tune pid=45299) {'loss': 0.8522, 'grad_norm': 1.1726435422897339, 'learning_rate': 5.9034435848666875e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:42<00:46,  2.45s/it]
 88%|████████▊ | 132/150 [05:44<00:45,  2.55s/it]
 89%|████████▊ | 133/150 [05:46<00:40,  2.39s/it]
 89%|████████▉ | 134/150 [05:50<00:43,  2.74s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:25:42. Total running time: 1hr 31min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 90%|█████████ | 135/150 [05:53<00:40,  2.71s/it]

(train_sft_tune pid=45299) {'loss': 0.8802, 'grad_norm': 1.0612040758132935, 'learning_rate': 4.497861778946047e-05, 'epoch': 0.22}

 91%|█████████ | 136/150 [05:56<00:39,  2.80s/it]
 91%|█████████▏| 137/150 [05:58<00:32,  2.53s/it]
 92%|█████████▏| 138/150 [06:00<00:30,  2.52s/it]
 93%|█████████▎| 139/150 [06:02<00:27,  2.48s/it]
 93%|█████████▎| 140/150 [06:05<00:23,  2.37s/it]

(train_sft_tune pid=45299) {'loss': 0.9539, 'grad_norm': 1.1171345710754395, 'learning_rate': 3.092279973025407e-05, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:07<00:21,  2.43s/it]
 95%|█████████▍| 142/150 [06:10<00:19,  2.49s/it]
 95%|█████████▌| 143/150 [06:12<00:17,  2.54s/it]
 96%|█████████▌| 144/150 [06:16<00:16,  2.71s/it]
 97%|█████████▋| 145/150 [06:18<00:13,  2.61s/it]

(train_sft_tune pid=45299) {'loss': 0.8842, 'grad_norm': 1.1889991760253906, 'learning_rate': 1.6866981671047678e-05, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:20<00:10,  2.55s/it]

Trial status: 11 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:26:12. Total running time: 1hr 31min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d33d8ede   RUNNING      0.000407619     8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_5ba5374a   PENDING      0.0004791       8             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 98%|█████████▊| 147/150 [06:23<00:07,  2.54s/it]
 99%|█████████▊| 148/150 [06:26<00:05,  2.60s/it]
 99%|█████████▉| 149/150 [06:28<00:02,  2.50s/it]
100%|██████████| 150/150 [06:31<00:00,  2.54s/it]

(train_sft_tune pid=45299) {'loss': 0.943, 'grad_norm': 1.0518184900283813, 'learning_rate': 2.8111636118412796e-06, 'epoch': 0.24}

100%|██████████| 150/150 [06:31<00:00,  2.61s/it]

(train_sft_tune pid=45299) {'train_runtime': 391.8865, 'train_samples_per_second': 3.062, 'train_steps_per_second': 0.383, 'train_loss': 0.9181313927968343, 'epoch': 0.24}

Trial train_sft_tune_d33d8ede completed after 1 iterations at 2025-11-29 17:26:22. Total running time: 1hr 31min 52s
+--------------------------------------------------+
| Trial train_sft_tune_d33d8ede result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         436.761 |
| time_total_s                             436.761 |
| training_iteration                             1 |
| train_loss                               0.91813 |
+--------------------------------------------------+
(train_sft_tune pid=45299) history of tuning  [{'loss': 1.0698, 'grad_norm': 1.6210365295410156, 'learning_rate': 0.00032609497897358847, 'epoch': 0.008, 'step': 5}, {'loss': 0.8936, 'grad_norm': 1.2224524021148682, 'learning_rate': 0.0003963740692696204, 'epoch': 0.016, 'step': 10}, {'loss': 1.0015, 'grad_norm': 1.32182776927948, 'learning_rate': 0.000382318251210414, 'epoch': 0.024, 'step': 15}, {'loss': 0.932, 'grad_norm': 1.5813697576522827, 'learning_rate': 0.0003682624331512076, 'epoch': 0.032, 'step': 20}, {'loss': 0.8696, 'grad_norm': 0.9875711798667908, 'learning_rate': 0.00035420661509200123, 'epoch': 0.04, 'step': 25}, {'loss': 1.0141, 'grad_norm': 1.1712521314620972, 'learning_rate': 0.00034015079703279485, 'epoch': 0.048, 'step': 30}, {'loss': 0.9012, 'grad_norm': 1.1878232955932617, 'learning_rate': 0.00032609497897358847, 'epoch': 0.056, 'step': 35}, {'loss': 0.79, 'grad_norm': 1.3488677740097046, 'learning_rate': 0.00031203916091438204, 'epoch': 0.064, 'step': 40}, {'loss': 0.9012, 'grad_norm': 1.1933400630950928, 'learning_rate': 0.00029798334285517566, 'epoch': 0.072, 'step': 45}, {'loss': 0.9355, 'grad_norm': 1.043503999710083, 'learning_rate': 0.0002839275247959692, 'epoch': 0.08, 'step': 50}, {'loss': 0.8196, 'grad_norm': 1.2222000360488892, 'learning_rate': 0.00026987170673676284, 'epoch': 0.088, 'step': 55}, {'loss': 0.9561, 'grad_norm': 1.4296318292617798, 'learning_rate': 0.00025581588867755646, 'epoch': 0.096, 'step': 60}, {'loss': 0.7845, 'grad_norm': 1.1908822059631348, 'learning_rate': 0.00024176007061835002, 'epoch': 0.104, 'step': 65}, {'loss': 0.9036, 'grad_norm': 1.0537197589874268, 'learning_rate': 0.00022770425255914364, 'epoch': 0.112, 'step': 70}, {'loss': 0.998, 'grad_norm': 1.0083982944488525, 'learning_rate': 0.00021364843449993726, 'epoch': 0.12, 'step': 75}, {'loss': 0.9682, 'grad_norm': 1.5290271043777466, 'learning_rate': 0.00019959261644073085, 'epoch': 0.128, 'step': 80}, {'loss': 1.0012, 'grad_norm': 1.2788819074630737, 'learning_rate': 0.00018553679838152447, 'epoch': 0.136, 'step': 85}, {'loss': 1.0053, 'grad_norm': 1.2879043817520142, 'learning_rate': 0.00017148098032231806, 'epoch': 0.144, 'step': 90}, {'loss': 0.8095, 'grad_norm': 0.9309933185577393, 'learning_rate': 0.00015742516226311166, 'epoch': 0.152, 'step': 95}, {'loss': 0.9043, 'grad_norm': 1.051042914390564, 'learning_rate': 0.00014336934420390525, 'epoch': 0.16, 'step': 100}, {'loss': 0.9275, 'grad_norm': 0.9876271486282349, 'learning_rate': 0.00012931352614469887, 'epoch': 0.168, 'step': 105}, {'loss': 0.8405, 'grad_norm': 1.2033132314682007, 'learning_rate': 0.00011525770808549246, 'epoch': 0.176, 'step': 110}, {'loss': 0.8635, 'grad_norm': 1.324117660522461, 'learning_rate': 0.00010120189002628607, 'epoch': 0.184, 'step': 115}, {'loss': 1.0859, 'grad_norm': 1.272504448890686, 'learning_rate': 8.714607196707967e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8543, 'grad_norm': 1.0498095750808716, 'learning_rate': 7.309025390787326e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8522, 'grad_norm': 1.1726435422897339, 'learning_rate': 5.9034435848666875e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8802, 'grad_norm': 1.0612040758132935, 'learning_rate': 4.497861778946047e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9539, 'grad_norm': 1.1171345710754395, 'learning_rate': 3.092279973025407e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8842, 'grad_norm': 1.1889991760253906, 'learning_rate': 1.6866981671047678e-05, 'epoch': 0.232, 'step': 145}, {'loss': 0.943, 'grad_norm': 1.0518184900283813, 'learning_rate': 2.8111636118412796e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 391.8865, 'train_samples_per_second': 3.062, 'train_steps_per_second': 0.383, 'total_flos': 4860346640523264.0, 'train_loss': 0.9181313927968343, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=45299) Reporting loss: 0.9181313927968343

Trial train_sft_tune_5ba5374a started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_5ba5374a config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00048 |
| r                                              8 |
+--------------------------------------------------+
(train_sft_tune pid=47272) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=47272) 2025-11-29 17:26:36.797826: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=47272) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=47272) E0000 00:00:1764437196.825815   47328 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=47272) E0000 00:00:1764437196.838733   47328 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=47272) W0000 00:00:1764437196.871482   47328 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=47272) W0000 00:00:1764437196.871525   47328 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=47272) W0000 00:00:1764437196.871529   47328 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=47272) W0000 00:00:1764437196.871532   47328 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:26:42. Total running time: 1hr 32min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=47272) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=47272) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=47272)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=47272) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=47272) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=47272)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=47272) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=47272) [2025-11-29 17:27:01,016 E 47272 47310] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=47272) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:27:12. Total running time: 1hr 32min 42s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=47272) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=47272) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=47272)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=47272) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=47272) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=47272)  "-____-"     Trainable parameters = 5,636,096 of 1,241,450,496 (0.45% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=47272) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:11<29:23, 11.84s/it]
  1%|▏         | 2/150 [00:13<15:00,  6.09s/it]
  2%|▏         | 3/150 [00:16<11:06,  4.54s/it]
  3%|▎         | 4/150 [00:19<09:07,  3.75s/it]
  3%|▎         | 5/150 [00:21<07:28,  3.09s/it]

(train_sft_tune pid=47272) {'loss': 1.0687, 'grad_norm': 1.6162619590759277, 'learning_rate': 0.00038328003941867563, 'epoch': 0.01}

  4%|▍         | 6/150 [00:23<06:53,  2.87s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:27:42. Total running time: 1hr 33min 12s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  5%|▍         | 7/150 [00:26<06:32,  2.75s/it]
  5%|▌         | 8/150 [00:28<06:19,  2.68s/it]
  6%|▌         | 9/150 [00:30<06:07,  2.61s/it]
  7%|▋         | 10/150 [00:33<05:59,  2.57s/it]

(train_sft_tune pid=47272) {'loss': 0.8922, 'grad_norm': 1.2029731273651123, 'learning_rate': 0.0004658834961899419, 'epoch': 0.02}

  7%|▋         | 11/150 [00:36<06:02,  2.61s/it]
  8%|▊         | 12/150 [00:38<05:44,  2.50s/it]
  9%|▊         | 13/150 [00:41<06:01,  2.64s/it]
  9%|▉         | 14/150 [00:43<05:38,  2.49s/it]
 10%|█         | 15/150 [00:45<05:06,  2.27s/it]

(train_sft_tune pid=47272) {'loss': 1.0028, 'grad_norm': 1.3101884126663208, 'learning_rate': 0.0004493628048356886, 'epoch': 0.02}

 11%|█         | 16/150 [00:47<05:19,  2.38s/it]
 11%|█▏        | 17/150 [00:50<05:42,  2.58s/it]
 12%|█▏        | 18/150 [00:52<05:12,  2.37s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:28:12. Total running time: 1hr 33min 43s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 13%|█▎        | 19/150 [00:55<05:19,  2.44s/it]
 13%|█▎        | 20/150 [00:56<04:39,  2.15s/it]

(train_sft_tune pid=47272) {'loss': 0.9351, 'grad_norm': 1.5492786169052124, 'learning_rate': 0.0004328421134814354, 'epoch': 0.03}

 14%|█▍        | 21/150 [00:58<04:32,  2.11s/it]
 15%|█▍        | 22/150 [01:01<04:32,  2.13s/it]
 15%|█▌        | 23/150 [01:03<04:41,  2.22s/it]
 16%|█▌        | 24/150 [01:06<04:57,  2.36s/it]
 17%|█▋        | 25/150 [01:08<05:02,  2.42s/it]

(train_sft_tune pid=47272) {'loss': 0.8739, 'grad_norm': 0.9768109917640686, 'learning_rate': 0.0004163214221271821, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:11<05:25,  2.62s/it]
 18%|█▊        | 27/150 [01:14<05:07,  2.50s/it]
 19%|█▊        | 28/150 [01:16<05:17,  2.60s/it]
 19%|█▉        | 29/150 [01:18<04:47,  2.38s/it]
 20%|██        | 30/150 [01:22<05:25,  2.72s/it]

(train_sft_tune pid=47272) {'loss': 1.0206, 'grad_norm': 1.1527581214904785, 'learning_rate': 0.0003998007307729289, 'epoch': 0.05}

 21%|██        | 31/150 [01:25<05:29,  2.77s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:28:42. Total running time: 1hr 34min 13s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 21%|██▏       | 32/150 [01:27<04:59,  2.54s/it]
 22%|██▏       | 33/150 [01:30<05:18,  2.72s/it]
 23%|██▎       | 34/150 [01:32<05:07,  2.65s/it]
 23%|██▎       | 35/150 [01:34<04:44,  2.48s/it]

(train_sft_tune pid=47272) {'loss': 0.9063, 'grad_norm': 1.2298141717910767, 'learning_rate': 0.00038328003941867563, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:37<04:38,  2.44s/it]
 25%|██▍       | 37/150 [01:39<04:41,  2.49s/it]
 25%|██▌       | 38/150 [01:42<04:34,  2.45s/it]
 26%|██▌       | 39/150 [01:44<04:41,  2.53s/it]
 27%|██▋       | 40/150 [01:47<04:40,  2.55s/it]

(train_sft_tune pid=47272) {'loss': 0.7941, 'grad_norm': 1.6255152225494385, 'learning_rate': 0.0003667593480644223, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:50<04:37,  2.55s/it]
 28%|██▊       | 42/150 [01:52<04:38,  2.58s/it]
 29%|██▊       | 43/150 [01:54<04:16,  2.39s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:29:12. Total running time: 1hr 34min 43s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 29%|██▉       | 44/150 [01:57<04:20,  2.45s/it]
 30%|███       | 45/150 [01:59<04:00,  2.29s/it]

(train_sft_tune pid=47272) {'loss': 0.9062, 'grad_norm': 1.2395178079605103, 'learning_rate': 0.0003502386567101691, 'epoch': 0.07}

 31%|███       | 46/150 [02:01<04:12,  2.43s/it]
 31%|███▏      | 47/150 [02:04<04:22,  2.55s/it]
 32%|███▏      | 48/150 [02:07<04:34,  2.69s/it]
 33%|███▎      | 49/150 [02:09<04:14,  2.52s/it]
 33%|███▎      | 50/150 [02:12<04:26,  2.66s/it]

(train_sft_tune pid=47272) {'loss': 0.9412, 'grad_norm': 1.099489450454712, 'learning_rate': 0.0003337179653559158, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:16<04:44,  2.88s/it]
 35%|███▍      | 52/150 [02:18<04:30,  2.76s/it]
 35%|███▌      | 53/150 [02:21<04:24,  2.72s/it]
 36%|███▌      | 54/150 [02:23<04:14,  2.65s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:29:42. Total running time: 1hr 35min 13s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 37%|███▋      | 55/150 [02:25<03:53,  2.46s/it]

(train_sft_tune pid=47272) {'loss': 0.827, 'grad_norm': 1.2886182069778442, 'learning_rate': 0.0003171972740016626, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:28<03:57,  2.53s/it]
 38%|███▊      | 57/150 [02:30<03:37,  2.33s/it]
 39%|███▊      | 58/150 [02:33<03:41,  2.41s/it]
 39%|███▉      | 59/150 [02:35<03:44,  2.46s/it]
 40%|████      | 60/150 [02:37<03:38,  2.42s/it]

(train_sft_tune pid=47272) {'loss': 0.9626, 'grad_norm': 1.497041940689087, 'learning_rate': 0.0003006765826474093, 'epoch': 0.1}

 41%|████      | 61/150 [02:40<03:43,  2.51s/it]
 41%|████▏     | 62/150 [02:44<04:08,  2.83s/it]
 42%|████▏     | 63/150 [02:47<04:12,  2.90s/it]
 43%|████▎     | 64/150 [02:50<04:19,  3.02s/it]
 43%|████▎     | 65/150 [02:52<03:51,  2.72s/it]

(train_sft_tune pid=47272) {'loss': 0.7919, 'grad_norm': 1.2713899612426758, 'learning_rate': 0.00028415589129315605, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:55<03:52,  2.77s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:30:12. Total running time: 1hr 35min 43s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 45%|████▍     | 67/150 [02:57<03:37,  2.61s/it]
 45%|████▌     | 68/150 [02:59<03:20,  2.44s/it]
 46%|████▌     | 69/150 [03:01<03:05,  2.29s/it]
 47%|████▋     | 70/150 [03:04<03:23,  2.54s/it]

(train_sft_tune pid=47272) {'loss': 0.9104, 'grad_norm': 1.1069625616073608, 'learning_rate': 0.0002676351999389028, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:07<03:33,  2.70s/it]
 48%|████▊     | 72/150 [03:10<03:23,  2.61s/it]
 49%|████▊     | 73/150 [03:13<03:23,  2.64s/it]
 49%|████▉     | 74/150 [03:15<03:14,  2.56s/it]
 50%|█████     | 75/150 [03:18<03:13,  2.58s/it]

(train_sft_tune pid=47272) {'loss': 1.0039, 'grad_norm': 1.0359419584274292, 'learning_rate': 0.0002511145085846496, 'epoch': 0.12}

 51%|█████     | 76/150 [03:20<03:11,  2.58s/it]
 51%|█████▏    | 77/150 [03:23<03:08,  2.58s/it]
 52%|█████▏    | 78/150 [03:25<02:53,  2.42s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:30:43. Total running time: 1hr 36min 13s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 53%|█████▎    | 79/150 [03:27<02:46,  2.34s/it]
 53%|█████▎    | 80/150 [03:29<02:48,  2.41s/it]

(train_sft_tune pid=47272) {'loss': 0.9747, 'grad_norm': 1.553617000579834, 'learning_rate': 0.00023459381723039627, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:32<02:51,  2.48s/it]
 55%|█████▍    | 82/150 [03:35<02:53,  2.55s/it]
 55%|█████▌    | 83/150 [03:37<02:47,  2.50s/it]
 56%|█████▌    | 84/150 [03:39<02:37,  2.39s/it]
 57%|█████▋    | 85/150 [03:42<02:42,  2.50s/it]

(train_sft_tune pid=47272) {'loss': 1.0077, 'grad_norm': 1.3139469623565674, 'learning_rate': 0.00021807312587614303, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:44<02:30,  2.36s/it]
 58%|█████▊    | 87/150 [03:47<02:39,  2.54s/it]
 59%|█████▊    | 88/150 [03:50<02:41,  2.61s/it]
 59%|█████▉    | 89/150 [03:53<02:48,  2.76s/it]
 60%|██████    | 90/150 [03:55<02:27,  2.45s/it]

(train_sft_tune pid=47272) {'loss': 1.0111, 'grad_norm': 1.3173537254333496, 'learning_rate': 0.00020155243452188977, 'epoch': 0.14}
Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:31:13. Total running time: 1hr 36min 43s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 61%|██████    | 91/150 [03:57<02:16,  2.31s/it]
 61%|██████▏   | 92/150 [03:59<02:18,  2.39s/it]
 62%|██████▏   | 93/150 [04:02<02:17,  2.42s/it]
 63%|██████▎   | 94/150 [04:04<02:10,  2.33s/it]
 63%|██████▎   | 95/150 [04:07<02:14,  2.44s/it]

(train_sft_tune pid=47272) {'loss': 0.8166, 'grad_norm': 0.9585609436035156, 'learning_rate': 0.0001850317431676365, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:09<02:07,  2.37s/it]
 65%|██████▍   | 97/150 [04:12<02:14,  2.53s/it]
 65%|██████▌   | 98/150 [04:15<02:16,  2.63s/it]
 66%|██████▌   | 99/150 [04:18<02:21,  2.77s/it]
 67%|██████▋   | 100/150 [04:20<02:05,  2.50s/it]

(train_sft_tune pid=47272) {'loss': 0.9106, 'grad_norm': 1.0832890272140503, 'learning_rate': 0.00016851105181338324, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:22<01:59,  2.43s/it]
 68%|██████▊   | 102/150 [04:24<01:53,  2.37s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:31:43. Total running time: 1hr 37min 13s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 69%|██████▊   | 103/150 [04:27<01:55,  2.46s/it]
 69%|██████▉   | 104/150 [04:29<01:54,  2.50s/it]
 70%|███████   | 105/150 [04:32<01:52,  2.49s/it]
 70%|███████   | 105/150 [04:32<01:52,  2.49s/it]

(train_sft_tune pid=47272) {'loss': 0.9327, 'grad_norm': 1.0185366868972778, 'learning_rate': 0.00015199036045913, 'epoch': 0.17}

 71%|███████   | 106/150 [04:34<01:46,  2.43s/it]
 71%|███████▏  | 107/150 [04:37<01:50,  2.58s/it]
 72%|███████▏  | 108/150 [04:40<01:55,  2.74s/it]
 73%|███████▎  | 109/150 [04:43<01:49,  2.67s/it]
 73%|███████▎  | 110/150 [04:45<01:38,  2.45s/it]

(train_sft_tune pid=47272) {'loss': 0.8453, 'grad_norm': 1.2425920963287354, 'learning_rate': 0.00013546966910487672, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:48<01:44,  2.67s/it]
 75%|███████▍  | 112/150 [04:51<01:45,  2.78s/it]
 75%|███████▌  | 113/150 [04:53<01:35,  2.58s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:32:13. Total running time: 1hr 37min 43s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 76%|███████▌  | 114/150 [04:56<01:35,  2.65s/it]
 77%|███████▋  | 115/150 [04:58<01:26,  2.47s/it]

(train_sft_tune pid=47272) {'loss': 0.8669, 'grad_norm': 1.409043312072754, 'learning_rate': 0.00011894897775062347, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:00<01:22,  2.44s/it]
 78%|███████▊  | 117/150 [05:03<01:26,  2.63s/it]
 79%|███████▊  | 118/150 [05:06<01:27,  2.75s/it]
 79%|███████▉  | 119/150 [05:09<01:26,  2.78s/it]
 80%|████████  | 120/150 [05:11<01:17,  2.59s/it]

(train_sft_tune pid=47272) {'loss': 1.0907, 'grad_norm': 1.3244205713272095, 'learning_rate': 0.0001024282863963702, 'epoch': 0.19}

 81%|████████  | 121/150 [05:14<01:20,  2.79s/it]
 81%|████████▏ | 122/150 [05:18<01:20,  2.88s/it]
 82%|████████▏ | 123/150 [05:20<01:14,  2.74s/it]
 83%|████████▎ | 124/150 [05:23<01:14,  2.87s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:32:43. Total running time: 1hr 38min 13s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=47272) {'loss': 0.8593, 'grad_norm': 1.1088588237762451, 'learning_rate': 8.590759504211694e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:26<01:08,  2.75s/it]
 84%|████████▍ | 126/150 [05:28<01:06,  2.77s/it]
 85%|████████▍ | 127/150 [05:31<01:03,  2.77s/it]
 85%|████████▌ | 128/150 [05:34<00:58,  2.67s/it]
 86%|████████▌ | 129/150 [05:35<00:49,  2.35s/it]
 87%|████████▋ | 130/150 [05:38<00:48,  2.45s/it]

(train_sft_tune pid=47272) {'loss': 0.8561, 'grad_norm': 1.2050660848617554, 'learning_rate': 6.938690368786369e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:40<00:46,  2.44s/it]
 88%|████████▊ | 132/150 [05:43<00:45,  2.55s/it]
 89%|████████▊ | 133/150 [05:45<00:40,  2.40s/it]
 89%|████████▉ | 134/150 [05:49<00:43,  2.75s/it]
 90%|█████████ | 135/150 [05:51<00:40,  2.71s/it]

(train_sft_tune pid=47272) {'loss': 0.8852, 'grad_norm': 1.0892430543899536, 'learning_rate': 5.286621233361043e-05, 'epoch': 0.22}

 91%|█████████ | 136/150 [05:54<00:39,  2.80s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:33:13. Total running time: 1hr 38min 43s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 91%|█████████▏| 137/150 [05:56<00:32,  2.53s/it]
 92%|█████████▏| 138/150 [05:59<00:30,  2.53s/it]
 93%|█████████▎| 139/150 [06:01<00:27,  2.49s/it]
 93%|█████████▎| 140/150 [06:03<00:23,  2.37s/it]

(train_sft_tune pid=47272) {'loss': 0.9571, 'grad_norm': 1.1300443410873413, 'learning_rate': 3.634552097935717e-05, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:06<00:21,  2.43s/it]
 95%|█████████▍| 142/150 [06:09<00:19,  2.50s/it]
 95%|█████████▌| 143/150 [06:11<00:17,  2.55s/it]
 96%|█████████▌| 144/150 [06:14<00:16,  2.71s/it]
 97%|█████████▋| 145/150 [06:17<00:13,  2.61s/it]

(train_sft_tune pid=47272) {'loss': 0.8889, 'grad_norm': 1.231716513633728, 'learning_rate': 1.982482962510391e-05, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:19<00:10,  2.55s/it]
 98%|█████████▊| 147/150 [06:22<00:07,  2.54s/it]
 99%|█████████▊| 148/150 [06:24<00:05,  2.60s/it]

Trial status: 12 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:33:43. Total running time: 1hr 39min 13s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_5ba5374a   RUNNING      0.0004791       8             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_eebd3616   PENDING      0.000125219    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 99%|█████████▉| 149/150 [06:27<00:02,  2.51s/it]
100%|██████████| 150/150 [06:29<00:00,  2.54s/it]

(train_sft_tune pid=47272) {'loss': 0.9469, 'grad_norm': 1.085383653640747, 'learning_rate': 3.304138270850652e-06, 'epoch': 0.24}

Trial train_sft_tune_5ba5374a completed after 1 iterations at 2025-11-29 17:33:48. Total running time: 1hr 39min 18s
+--------------------------------------------------+
| Trial train_sft_tune_5ba5374a result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         435.813 |
| time_total_s                             435.813 |
| training_iteration                             1 |
| train_loss                               0.92289 |
+--------------------------------------------------+
(train_sft_tune pid=47272) {'train_runtime': 390.6138, 'train_samples_per_second': 3.072, 'train_steps_per_second': 0.384, 'train_loss': 0.9228893645604451, 'epoch': 0.24}
(train_sft_tune pid=47272) history of tuning  [{'loss': 1.0687, 'grad_norm': 1.6162619590759277, 'learning_rate': 0.00038328003941867563, 'epoch': 0.008, 'step': 5}, {'loss': 0.8922, 'grad_norm': 1.2029731273651123, 'learning_rate': 0.0004658834961899419, 'epoch': 0.016, 'step': 10}, {'loss': 1.0028, 'grad_norm': 1.3101884126663208, 'learning_rate': 0.0004493628048356886, 'epoch': 0.024, 'step': 15}, {'loss': 0.9351, 'grad_norm': 1.5492786169052124, 'learning_rate': 0.0004328421134814354, 'epoch': 0.032, 'step': 20}, {'loss': 0.8739, 'grad_norm': 0.9768109917640686, 'learning_rate': 0.0004163214221271821, 'epoch': 0.04, 'step': 25}, {'loss': 1.0206, 'grad_norm': 1.1527581214904785, 'learning_rate': 0.0003998007307729289, 'epoch': 0.048, 'step': 30}, {'loss': 0.9063, 'grad_norm': 1.2298141717910767, 'learning_rate': 0.00038328003941867563, 'epoch': 0.056, 'step': 35}, {'loss': 0.7941, 'grad_norm': 1.6255152225494385, 'learning_rate': 0.0003667593480644223, 'epoch': 0.064, 'step': 40}, {'loss': 0.9062, 'grad_norm': 1.2395178079605103, 'learning_rate': 0.0003502386567101691, 'epoch': 0.072, 'step': 45}, {'loss': 0.9412, 'grad_norm': 1.099489450454712, 'learning_rate': 0.0003337179653559158, 'epoch': 0.08, 'step': 50}, {'loss': 0.827, 'grad_norm': 1.2886182069778442, 'learning_rate': 0.0003171972740016626, 'epoch': 0.088, 'step': 55}, {'loss': 0.9626, 'grad_norm': 1.497041940689087, 'learning_rate': 0.0003006765826474093, 'epoch': 0.096, 'step': 60}, {'loss': 0.7919, 'grad_norm': 1.2713899612426758, 'learning_rate': 0.00028415589129315605, 'epoch': 0.104, 'step': 65}, {'loss': 0.9104, 'grad_norm': 1.1069625616073608, 'learning_rate': 0.0002676351999389028, 'epoch': 0.112, 'step': 70}, {'loss': 1.0039, 'grad_norm': 1.0359419584274292, 'learning_rate': 0.0002511145085846496, 'epoch': 0.12, 'step': 75}, {'loss': 0.9747, 'grad_norm': 1.553617000579834, 'learning_rate': 0.00023459381723039627, 'epoch': 0.128, 'step': 80}, {'loss': 1.0077, 'grad_norm': 1.3139469623565674, 'learning_rate': 0.00021807312587614303, 'epoch': 0.136, 'step': 85}, {'loss': 1.0111, 'grad_norm': 1.3173537254333496, 'learning_rate': 0.00020155243452188977, 'epoch': 0.144, 'step': 90}, {'loss': 0.8166, 'grad_norm': 0.9585609436035156, 'learning_rate': 0.0001850317431676365, 'epoch': 0.152, 'step': 95}, {'loss': 0.9106, 'grad_norm': 1.0832890272140503, 'learning_rate': 0.00016851105181338324, 'epoch': 0.16, 'step': 100}, {'loss': 0.9327, 'grad_norm': 1.0185366868972778, 'learning_rate': 0.00015199036045913, 'epoch': 0.168, 'step': 105}, {'loss': 0.8453, 'grad_norm': 1.2425920963287354, 'learning_rate': 0.00013546966910487672, 'epoch': 0.176, 'step': 110}, {'loss': 0.8669, 'grad_norm': 1.409043312072754, 'learning_rate': 0.00011894897775062347, 'epoch': 0.184, 'step': 115}, {'loss': 1.0907, 'grad_norm': 1.3244205713272095, 'learning_rate': 0.0001024282863963702, 'epoch': 0.192, 'step': 120}, {'loss': 0.8593, 'grad_norm': 1.1088588237762451, 'learning_rate': 8.590759504211694e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8561, 'grad_norm': 1.2050660848617554, 'learning_rate': 6.938690368786369e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8852, 'grad_norm': 1.0892430543899536, 'learning_rate': 5.286621233361043e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9571, 'grad_norm': 1.1300443410873413, 'learning_rate': 3.634552097935717e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8889, 'grad_norm': 1.231716513633728, 'learning_rate': 1.982482962510391e-05, 'epoch': 0.232, 'step': 145}, {'loss': 0.9469, 'grad_norm': 1.085383653640747, 'learning_rate': 3.304138270850652e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 390.6138, 'train_samples_per_second': 3.072, 'train_steps_per_second': 0.384, 'total_flos': 4860346640523264.0, 'train_loss': 0.9228893645604451, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=47272) Reporting loss: 0.9228893645604451

100%|██████████| 150/150 [06:30<00:00,  2.60s/it]

Trial train_sft_tune_eebd3616 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_eebd3616 config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00013 |
| r                                             32 |
+--------------------------------------------------+
(train_sft_tune pid=49234) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=49234) 2025-11-29 17:34:02.119644: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=49234) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=49234) E0000 00:00:1764437642.142860   49290 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=49234) E0000 00:00:1764437642.149959   49290 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=49234) W0000 00:00:1764437642.167479   49290 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=49234) W0000 00:00:1764437642.167507   49290 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=49234) W0000 00:00:1764437642.167510   49290 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=49234) W0000 00:00:1764437642.167512   49290 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:34:13. Total running time: 1hr 39min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=49234) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=49234) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=49234)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=49234) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=49234) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=49234)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=49234) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=49234) [2025-11-29 17:34:26,437 E 49234 49271] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=49234) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=49234) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=49234) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=49234)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=49234) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=49234) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=49234)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=49234) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:34:43. Total running time: 1hr 40min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:12<30:03, 12.11s/it]
  1%|▏         | 2/150 [00:14<15:17,  6.20s/it]
  2%|▏         | 3/150 [00:16<11:18,  4.62s/it]
  3%|▎         | 4/150 [00:19<09:16,  3.81s/it]

(train_sft_tune pid=49234) {'loss': 1.0816, 'grad_norm': 0.7633291482925415, 'learning_rate': 0.00010017540551666286, 'epoch': 0.01}

  3%|▎         | 5/150 [00:21<07:35,  3.14s/it]
  4%|▍         | 6/150 [00:23<06:58,  2.91s/it]
  5%|▍         | 7/150 [00:26<06:38,  2.79s/it]
  5%|▌         | 8/150 [00:28<06:24,  2.71s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:35:13. Total running time: 1hr 40min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  6%|▌         | 9/150 [00:31<06:11,  2.63s/it]

(train_sft_tune pid=49234) {'loss': 0.9142, 'grad_norm': 0.6076091527938843, 'learning_rate': 0.00012176493256766778, 'epoch': 0.02}

  7%|▋         | 10/150 [00:33<06:02,  2.59s/it]
  7%|▋         | 11/150 [00:36<06:06,  2.63s/it]
  8%|▊         | 12/150 [00:38<05:47,  2.52s/it]
  9%|▊         | 13/150 [00:41<06:04,  2.66s/it]
  9%|▉         | 14/150 [00:44<05:42,  2.52s/it]

(train_sft_tune pid=49234) {'loss': 1.007, 'grad_norm': 0.6912737488746643, 'learning_rate': 0.00011744702715746679, 'epoch': 0.02}

 10%|█         | 15/150 [00:45<05:10,  2.30s/it]
 11%|█         | 16/150 [00:48<05:22,  2.41s/it]
 11%|█▏        | 17/150 [00:51<05:45,  2.60s/it]
 12%|█▏        | 18/150 [00:53<05:15,  2.39s/it]
 13%|█▎        | 19/150 [00:56<05:22,  2.46s/it]

(train_sft_tune pid=49234) {'loss': 0.9348, 'grad_norm': 0.8511788249015808, 'learning_rate': 0.00011312912174726581, 'epoch': 0.03}

 13%|█▎        | 20/150 [00:57<04:42,  2.17s/it]
 14%|█▍        | 21/150 [00:59<04:35,  2.14s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:35:43. Total running time: 1hr 41min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 15%|█▍        | 22/150 [01:01<04:37,  2.17s/it]
 15%|█▌        | 23/150 [01:04<04:45,  2.25s/it]
 16%|█▌        | 24/150 [01:07<05:01,  2.40s/it]

(train_sft_tune pid=49234) {'loss': 0.8667, 'grad_norm': 0.5334112644195557, 'learning_rate': 0.00010881121633706481, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:09<05:06,  2.45s/it]
 17%|█▋        | 26/150 [01:12<05:29,  2.66s/it]
 18%|█▊        | 27/150 [01:15<05:11,  2.53s/it]
 19%|█▊        | 28/150 [01:17<05:21,  2.64s/it]
 19%|█▉        | 29/150 [01:19<04:51,  2.41s/it]

(train_sft_tune pid=49234) {'loss': 1.0119, 'grad_norm': 0.5499404668807983, 'learning_rate': 0.00010449331092686384, 'epoch': 0.05}

 20%|██        | 30/150 [01:23<05:30,  2.75s/it]
 21%|██        | 31/150 [01:26<05:34,  2.81s/it]
 21%|██▏       | 32/150 [01:28<05:04,  2.58s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:36:13. Total running time: 1hr 41min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 22%|██▏       | 33/150 [01:31<05:23,  2.76s/it]
 23%|██▎       | 34/150 [01:34<05:12,  2.69s/it]

(train_sft_tune pid=49234) {'loss': 0.8965, 'grad_norm': 0.6174235343933105, 'learning_rate': 0.00010017540551666286, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:36<04:50,  2.52s/it]
 24%|██▍       | 36/150 [01:38<04:42,  2.47s/it]
 25%|██▍       | 37/150 [01:41<04:44,  2.52s/it]
 25%|██▌       | 38/150 [01:43<04:35,  2.46s/it]
 26%|██▌       | 39/150 [01:46<04:44,  2.56s/it]

(train_sft_tune pid=49234) {'loss': 0.7902, 'grad_norm': 0.614843487739563, 'learning_rate': 9.585750010646186e-05, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:48<04:42,  2.57s/it]
 27%|██▋       | 41/150 [01:51<04:41,  2.58s/it]
 28%|██▊       | 42/150 [01:54<04:43,  2.63s/it]
 29%|██▊       | 43/150 [01:56<04:20,  2.43s/it]
 29%|██▉       | 44/150 [01:58<04:24,  2.49s/it]

(train_sft_tune pid=49234) {'loss': 0.8989, 'grad_norm': 0.617906928062439, 'learning_rate': 9.153959469626088e-05, 'epoch': 0.07}
Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:36:43. Total running time: 1hr 42min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 30%|███       | 45/150 [02:00<04:03,  2.32s/it]
 31%|███       | 46/150 [02:03<04:16,  2.47s/it]
 31%|███▏      | 47/150 [02:06<04:29,  2.61s/it]
 32%|███▏      | 48/150 [02:09<04:40,  2.75s/it]
 33%|███▎      | 49/150 [02:11<04:18,  2.56s/it]

(train_sft_tune pid=49234) {'loss': 0.9264, 'grad_norm': 0.5734530687332153, 'learning_rate': 8.72216892860599e-05, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:14<04:30,  2.71s/it]
 34%|███▍      | 51/150 [02:18<04:49,  2.92s/it]
 35%|███▍      | 52/150 [02:20<04:33,  2.79s/it]
 35%|███▌      | 53/150 [02:23<04:24,  2.73s/it]
 36%|███▌      | 54/150 [02:25<04:16,  2.67s/it]

(train_sft_tune pid=49234) {'loss': 0.8141, 'grad_norm': 0.6046827435493469, 'learning_rate': 8.29037838758589e-05, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:27<03:55,  2.47s/it]
 37%|███▋      | 56/150 [02:30<03:59,  2.55s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:37:14. Total running time: 1hr 42min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 38%|███▊      | 57/150 [02:32<03:44,  2.41s/it]
 39%|███▊      | 58/150 [02:35<03:47,  2.47s/it]
 39%|███▉      | 59/150 [02:37<03:49,  2.53s/it]

(train_sft_tune pid=49234) {'loss': 0.9453, 'grad_norm': 0.7091051340103149, 'learning_rate': 7.858587846565793e-05, 'epoch': 0.1}

 40%|████      | 60/150 [02:40<03:43,  2.48s/it]
 41%|████      | 61/150 [02:43<03:49,  2.58s/it]
 41%|████▏     | 62/150 [02:46<04:16,  2.91s/it]
 42%|████▏     | 63/150 [02:49<04:21,  3.00s/it]
 43%|████▎     | 64/150 [02:53<04:31,  3.15s/it]

(train_sft_tune pid=49234) {'loss': 0.7769, 'grad_norm': 0.5822945833206177, 'learning_rate': 7.426797305545694e-05, 'epoch': 0.1}

 43%|████▎     | 65/150 [02:55<04:02,  2.85s/it]
 44%|████▍     | 66/150 [02:58<04:05,  2.92s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:37:44. Total running time: 1hr 43min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 45%|████▍     | 67/150 [03:01<03:47,  2.74s/it]
 45%|████▌     | 68/150 [03:03<03:32,  2.59s/it]
 46%|████▌     | 69/150 [03:05<03:18,  2.45s/it]

(train_sft_tune pid=49234) {'loss': 0.8946, 'grad_norm': 0.5551198720932007, 'learning_rate': 6.995006764525595e-05, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:08<03:40,  2.76s/it]
 47%|████▋     | 71/150 [03:12<03:54,  2.97s/it]
 48%|████▊     | 72/150 [03:14<03:41,  2.84s/it]
 49%|████▊     | 73/150 [03:17<03:42,  2.89s/it]
 49%|████▉     | 74/150 [03:20<03:31,  2.79s/it]

(train_sft_tune pid=49234) {'loss': 0.9939, 'grad_norm': 0.5392911434173584, 'learning_rate': 6.563216223505498e-05, 'epoch': 0.12}

 50%|█████     | 75/150 [03:23<03:32,  2.83s/it]
 51%|█████     | 76/150 [03:26<03:27,  2.81s/it]
 51%|█████▏    | 77/150 [03:28<03:21,  2.76s/it]
 52%|█████▏    | 78/150 [03:30<03:05,  2.57s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:38:14. Total running time: 1hr 43min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 53%|█████▎    | 79/150 [03:33<02:56,  2.48s/it]

(train_sft_tune pid=49234) {'loss': 0.9562, 'grad_norm': 0.7924289703369141, 'learning_rate': 6.131425682485399e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:35<02:59,  2.56s/it]
 54%|█████▍    | 81/150 [03:38<03:01,  2.63s/it]
 55%|█████▍    | 82/150 [03:41<03:01,  2.67s/it]
 55%|█████▌    | 83/150 [03:43<02:52,  2.58s/it]
 56%|█████▌    | 84/150 [03:45<02:42,  2.46s/it]

(train_sft_tune pid=49234) {'loss': 0.9915, 'grad_norm': 0.7065389156341553, 'learning_rate': 5.699635141465301e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:48<02:48,  2.59s/it]
 57%|█████▋    | 86/150 [03:50<02:35,  2.44s/it]
 58%|█████▊    | 87/150 [03:53<02:44,  2.61s/it]
 59%|█████▊    | 88/150 [03:56<02:45,  2.67s/it]
 59%|█████▉    | 89/150 [03:59<02:52,  2.83s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:38:44. Total running time: 1hr 44min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=49234) {'loss': 0.9968, 'grad_norm': 0.6052343249320984, 'learning_rate': 5.267844600445202e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [04:01<02:34,  2.57s/it]
 61%|██████    | 91/150 [04:03<02:21,  2.41s/it]
 61%|██████▏   | 92/150 [04:06<02:22,  2.46s/it]
 62%|██████▏   | 93/150 [04:09<02:20,  2.46s/it]
 63%|██████▎   | 94/150 [04:11<02:12,  2.37s/it]

(train_sft_tune pid=49234) {'loss': 0.8, 'grad_norm': 0.5132319331169128, 'learning_rate': 4.836054059425103e-05, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:13<02:17,  2.50s/it]
 64%|██████▍   | 96/150 [04:16<02:11,  2.44s/it]
 65%|██████▍   | 97/150 [04:19<02:17,  2.60s/it]
 65%|██████▌   | 98/150 [04:22<02:20,  2.71s/it]
 66%|██████▌   | 99/150 [04:25<02:26,  2.87s/it]

(train_sft_tune pid=49234) {'loss': 0.8949, 'grad_norm': 0.5678762197494507, 'learning_rate': 4.404263518405005e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:27<02:10,  2.61s/it]
 67%|██████▋   | 101/150 [04:29<02:04,  2.54s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:39:14. Total running time: 1hr 44min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 68%|██████▊   | 102/150 [04:32<01:57,  2.46s/it]
 69%|██████▊   | 103/150 [04:34<01:59,  2.54s/it]
 69%|██████▉   | 104/150 [04:37<02:00,  2.61s/it]

(train_sft_tune pid=49234) {'loss': 0.9237, 'grad_norm': 0.5195145010948181, 'learning_rate': 3.9724729773849065e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:40<01:57,  2.62s/it]
 71%|███████   | 106/150 [04:42<01:52,  2.55s/it]
 71%|███████▏  | 107/150 [04:45<01:56,  2.70s/it]
 72%|███████▏  | 108/150 [04:48<02:00,  2.88s/it]
 73%|███████▎  | 109/150 [04:51<01:55,  2.83s/it]

(train_sft_tune pid=49234) {'loss': 0.8355, 'grad_norm': 0.6271134614944458, 'learning_rate': 3.540682436364808e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [04:53<01:44,  2.61s/it]
 74%|███████▍  | 111/150 [04:57<01:50,  2.84s/it]
 75%|███████▍  | 112/150 [05:00<01:52,  2.96s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:39:44. Total running time: 1hr 45min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 75%|███████▌  | 113/150 [05:02<01:40,  2.72s/it]
 76%|███████▌  | 114/150 [05:05<01:41,  2.83s/it]

(train_sft_tune pid=49234) {'loss': 0.8629, 'grad_norm': 0.6869121193885803, 'learning_rate': 3.1088918953447095e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:07<01:32,  2.64s/it]
 77%|███████▋  | 116/150 [05:10<01:28,  2.60s/it]
 78%|███████▊  | 117/150 [05:13<01:32,  2.80s/it]
 79%|███████▊  | 118/150 [05:16<01:33,  2.93s/it]
 79%|███████▉  | 119/150 [05:19<01:32,  2.97s/it]

(train_sft_tune pid=49234) {'loss': 1.075, 'grad_norm': 0.6253347396850586, 'learning_rate': 2.677101354324611e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:22<01:22,  2.77s/it]
 81%|████████  | 121/150 [05:25<01:26,  2.97s/it]
 81%|████████▏ | 122/150 [05:28<01:25,  3.07s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:40:14. Total running time: 1hr 45min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 82%|████████▏ | 123/150 [05:31<01:19,  2.93s/it]
 83%|████████▎ | 124/150 [05:34<01:19,  3.06s/it]

(train_sft_tune pid=49234) {'loss': 0.8486, 'grad_norm': 0.5539865493774414, 'learning_rate': 2.245310813304512e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:37<01:13,  2.93s/it]
 84%|████████▍ | 126/150 [05:40<01:10,  2.95s/it]
 85%|████████▍ | 127/150 [05:43<01:07,  2.94s/it]
 85%|████████▌ | 128/150 [05:46<01:02,  2.83s/it]
 86%|████████▌ | 129/150 [05:47<00:52,  2.48s/it]

(train_sft_tune pid=49234) {'loss': 0.8492, 'grad_norm': 0.5610573887825012, 'learning_rate': 1.813520272284414e-05, 'epoch': 0.21}

 87%|████████▋ | 130/150 [05:50<00:51,  2.58s/it]
 87%|████████▋ | 131/150 [05:53<00:48,  2.56s/it]
 88%|████████▊ | 132/150 [05:55<00:48,  2.67s/it]
 89%|████████▊ | 133/150 [05:58<00:42,  2.51s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:40:44. Total running time: 1hr 46min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 89%|████████▉ | 134/150 [06:01<00:46,  2.89s/it]

(train_sft_tune pid=49234) {'loss': 0.8758, 'grad_norm': 0.5828552842140198, 'learning_rate': 1.3817297312643152e-05, 'epoch': 0.22}

 90%|█████████ | 135/150 [06:04<00:42,  2.85s/it]
 91%|█████████ | 136/150 [06:07<00:41,  2.94s/it]
 91%|█████████▏| 137/150 [06:09<00:34,  2.66s/it]
 92%|█████████▏| 138/150 [06:12<00:31,  2.65s/it]
 93%|█████████▎| 139/150 [06:14<00:28,  2.61s/it]

(train_sft_tune pid=49234) {'loss': 0.9482, 'grad_norm': 0.5748524069786072, 'learning_rate': 9.499391902442166e-06, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:17<00:24,  2.49s/it]
 94%|█████████▍| 141/150 [06:19<00:23,  2.56s/it]
 95%|█████████▍| 142/150 [06:22<00:20,  2.61s/it]
 95%|█████████▌| 143/150 [06:25<00:18,  2.67s/it]
 96%|█████████▌| 144/150 [06:28<00:17,  2.84s/it]

(train_sft_tune pid=49234) {'loss': 0.8785, 'grad_norm': 0.5703625679016113, 'learning_rate': 5.181486492241182e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:31<00:13,  2.74s/it]

Trial status: 13 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:41:14. Total running time: 1hr 46min 44s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_eebd3616   RUNNING      0.000125219    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_dab9ed39   PENDING      0.000126527    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 97%|█████████▋| 146/150 [06:33<00:10,  2.69s/it]
 98%|█████████▊| 147/150 [06:36<00:07,  2.65s/it]
 99%|█████████▊| 148/150 [06:39<00:05,  2.72s/it]
 99%|█████████▉| 149/150 [06:41<00:02,  2.63s/it]

(train_sft_tune pid=49234) {'loss': 0.9384, 'grad_norm': 0.5510336756706238, 'learning_rate': 8.63581082040197e-07, 'epoch': 0.24}

100%|██████████| 150/150 [06:44<00:00,  2.67s/it]

Trial train_sft_tune_eebd3616 completed after 1 iterations at 2025-11-29 17:41:28. Total running time: 1hr 46min 59s
+--------------------------------------------------+
| Trial train_sft_tune_eebd3616 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         451.151 |
| time_total_s                             451.151 |
| training_iteration                             1 |
| train_loss                               0.91428 |
+--------------------------------------------------+
(train_sft_tune pid=49234) {'train_runtime': 405.6092, 'train_samples_per_second': 2.959, 'train_steps_per_second': 0.37, 'train_loss': 0.914280489285787, 'epoch': 0.24}
(train_sft_tune pid=49234) history of tuning  [{'loss': 1.0816, 'grad_norm': 0.7633291482925415, 'learning_rate': 0.00010017540551666286, 'epoch': 0.008, 'step': 5}, {'loss': 0.9142, 'grad_norm': 0.6076091527938843, 'learning_rate': 0.00012176493256766778, 'epoch': 0.016, 'step': 10}, {'loss': 1.007, 'grad_norm': 0.6912737488746643, 'learning_rate': 0.00011744702715746679, 'epoch': 0.024, 'step': 15}, {'loss': 0.9348, 'grad_norm': 0.8511788249015808, 'learning_rate': 0.00011312912174726581, 'epoch': 0.032, 'step': 20}, {'loss': 0.8667, 'grad_norm': 0.5334112644195557, 'learning_rate': 0.00010881121633706481, 'epoch': 0.04, 'step': 25}, {'loss': 1.0119, 'grad_norm': 0.5499404668807983, 'learning_rate': 0.00010449331092686384, 'epoch': 0.048, 'step': 30}, {'loss': 0.8965, 'grad_norm': 0.6174235343933105, 'learning_rate': 0.00010017540551666286, 'epoch': 0.056, 'step': 35}, {'loss': 0.7902, 'grad_norm': 0.614843487739563, 'learning_rate': 9.585750010646186e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.8989, 'grad_norm': 0.617906928062439, 'learning_rate': 9.153959469626088e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9264, 'grad_norm': 0.5734530687332153, 'learning_rate': 8.72216892860599e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8141, 'grad_norm': 0.6046827435493469, 'learning_rate': 8.29037838758589e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9453, 'grad_norm': 0.7091051340103149, 'learning_rate': 7.858587846565793e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.7769, 'grad_norm': 0.5822945833206177, 'learning_rate': 7.426797305545694e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.8946, 'grad_norm': 0.5551198720932007, 'learning_rate': 6.995006764525595e-05, 'epoch': 0.112, 'step': 70}, {'loss': 0.9939, 'grad_norm': 0.5392911434173584, 'learning_rate': 6.563216223505498e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9562, 'grad_norm': 0.7924289703369141, 'learning_rate': 6.131425682485399e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.9915, 'grad_norm': 0.7065389156341553, 'learning_rate': 5.699635141465301e-05, 'epoch': 0.136, 'step': 85}, {'loss': 0.9968, 'grad_norm': 0.6052343249320984, 'learning_rate': 5.267844600445202e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8, 'grad_norm': 0.5132319331169128, 'learning_rate': 4.836054059425103e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8949, 'grad_norm': 0.5678762197494507, 'learning_rate': 4.404263518405005e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9237, 'grad_norm': 0.5195145010948181, 'learning_rate': 3.9724729773849065e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8355, 'grad_norm': 0.6271134614944458, 'learning_rate': 3.540682436364808e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8629, 'grad_norm': 0.6869121193885803, 'learning_rate': 3.1088918953447095e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.075, 'grad_norm': 0.6253347396850586, 'learning_rate': 2.677101354324611e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8486, 'grad_norm': 0.5539865493774414, 'learning_rate': 2.245310813304512e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8492, 'grad_norm': 0.5610573887825012, 'learning_rate': 1.813520272284414e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8758, 'grad_norm': 0.5828552842140198, 'learning_rate': 1.3817297312643152e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9482, 'grad_norm': 0.5748524069786072, 'learning_rate': 9.499391902442166e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.8785, 'grad_norm': 0.5703625679016113, 'learning_rate': 5.181486492241182e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9384, 'grad_norm': 0.5510336756706238, 'learning_rate': 8.63581082040197e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 405.6092, 'train_samples_per_second': 2.959, 'train_steps_per_second': 0.37, 'total_flos': 4944308261511168.0, 'train_loss': 0.914280489285787, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=49234) Reporting loss: 0.914280489285787

100%|██████████| 150/150 [06:45<00:00,  2.70s/it]

Trial train_sft_tune_dab9ed39 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_dab9ed39 config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00013 |
| r                                             32 |
+--------------------------------------------------+
(train_sft_tune pid=51257) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=51257) 2025-11-29 17:41:43.561789: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=51257) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=51257) E0000 00:00:1764438103.584336   51314 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=51257) E0000 00:00:1764438103.591104   51314 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=51257) W0000 00:00:1764438103.608375   51314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=51257) W0000 00:00:1764438103.608412   51314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=51257) W0000 00:00:1764438103.608414   51314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=51257) W0000 00:00:1764438103.608416   51314 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:41:44. Total running time: 1hr 47min 14s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=51257) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=51257) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=51257)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=51257) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=51257) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=51257)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=51257) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=51257) [2025-11-29 17:42:07,115 E 51257 51295] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:42:14. Total running time: 1hr 47min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=51257) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=51257) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=51257) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=51257)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=51257) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=51257) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=51257)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=51257) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:13<33:56, 13.66s/it]
  1%|▏         | 2/150 [00:15<16:51,  6.83s/it]
  2%|▏         | 3/150 [00:18<12:10,  4.97s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:42:44. Total running time: 1hr 48min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  3%|▎         | 4/150 [00:21<09:50,  4.04s/it]
  3%|▎         | 5/150 [00:23<08:02,  3.33s/it]

(train_sft_tune pid=51257) {'loss': 1.0815, 'grad_norm': 0.7621669173240662, 'learning_rate': 0.00010122156074022368, 'epoch': 0.01}

  4%|▍         | 6/150 [00:25<07:16,  3.03s/it]
  5%|▍         | 7/150 [00:28<06:48,  2.85s/it]
  5%|▌         | 8/150 [00:30<06:31,  2.76s/it]
  6%|▌         | 9/150 [00:33<06:19,  2.69s/it]
  7%|▋         | 10/150 [00:35<06:13,  2.67s/it]

(train_sft_tune pid=51257) {'loss': 0.9139, 'grad_norm': 0.6054676175117493, 'learning_rate': 0.00012303655227906496, 'epoch': 0.02}

  7%|▋         | 11/150 [00:38<06:12,  2.68s/it]
  8%|▊         | 12/150 [00:40<05:49,  2.54s/it]
  9%|▊         | 13/150 [00:43<06:07,  2.68s/it]
  9%|▉         | 14/150 [00:45<05:46,  2.55s/it]
 10%|█         | 15/150 [00:47<05:20,  2.37s/it]

(train_sft_tune pid=51257) {'loss': 1.0069, 'grad_norm': 0.6916328072547913, 'learning_rate': 0.00011867355397129671, 'epoch': 0.02}

 11%|█         | 16/150 [00:50<05:31,  2.47s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:43:14. Total running time: 1hr 48min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 11%|█▏        | 17/150 [00:53<05:52,  2.65s/it]
 12%|█▏        | 18/150 [00:55<05:20,  2.43s/it]
 13%|█▎        | 19/150 [00:58<05:26,  2.50s/it]
 13%|█▎        | 20/150 [00:59<04:54,  2.26s/it]

(train_sft_tune pid=51257) {'loss': 0.9346, 'grad_norm': 0.8495272994041443, 'learning_rate': 0.00011431055566352846, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:02<04:48,  2.24s/it]
 15%|█▍        | 22/150 [01:04<04:46,  2.24s/it]
 15%|█▌        | 23/150 [01:06<04:50,  2.29s/it]
 16%|█▌        | 24/150 [01:09<05:06,  2.43s/it]
 17%|█▋        | 25/150 [01:12<05:11,  2.49s/it]

(train_sft_tune pid=51257) {'loss': 0.8666, 'grad_norm': 0.5336423516273499, 'learning_rate': 0.00010994755735576019, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:15<05:35,  2.70s/it]
 18%|█▊        | 27/150 [01:17<05:11,  2.54s/it]
 19%|█▊        | 28/150 [01:20<05:22,  2.64s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:43:44. Total running time: 1hr 49min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 19%|█▉        | 29/150 [01:22<04:51,  2.41s/it]
 20%|██        | 30/150 [01:25<05:32,  2.77s/it]

(train_sft_tune pid=51257) {'loss': 1.0118, 'grad_norm': 0.5489776730537415, 'learning_rate': 0.00010558455904799194, 'epoch': 0.05}

 21%|██        | 31/150 [01:28<05:36,  2.83s/it]
 21%|██▏       | 32/150 [01:30<05:05,  2.59s/it]
 22%|██▏       | 33/150 [01:34<05:23,  2.77s/it]
 23%|██▎       | 34/150 [01:36<05:13,  2.70s/it]
 23%|██▎       | 35/150 [01:38<04:54,  2.56s/it]

(train_sft_tune pid=51257) {'loss': 0.8964, 'grad_norm': 0.6171854734420776, 'learning_rate': 0.00010122156074022368, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:41<04:47,  2.53s/it]
 25%|██▍       | 37/150 [01:43<04:46,  2.54s/it]
 25%|██▌       | 38/150 [01:46<04:36,  2.47s/it]
 26%|██▌       | 39/150 [01:48<04:45,  2.57s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:44:14. Total running time: 1hr 49min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 27%|██▋       | 40/150 [01:51<04:46,  2.60s/it]

(train_sft_tune pid=51257) {'loss': 0.7901, 'grad_norm': 0.6149877309799194, 'learning_rate': 9.68585624324554e-05, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:54<04:44,  2.61s/it]
 28%|██▊       | 42/150 [01:56<04:43,  2.63s/it]
 29%|██▊       | 43/150 [01:58<04:20,  2.43s/it]
 29%|██▉       | 44/150 [02:01<04:24,  2.50s/it]
 30%|███       | 45/150 [02:03<04:06,  2.35s/it]

(train_sft_tune pid=51257) {'loss': 0.8987, 'grad_norm': 0.6170118451118469, 'learning_rate': 9.249556412468715e-05, 'epoch': 0.07}

 31%|███       | 46/150 [02:06<04:21,  2.51s/it]
 31%|███▏      | 47/150 [02:09<04:29,  2.61s/it]
 32%|███▏      | 48/150 [02:12<04:39,  2.74s/it]
 33%|███▎      | 49/150 [02:14<04:17,  2.55s/it]
 33%|███▎      | 50/150 [02:17<04:30,  2.70s/it]

(train_sft_tune pid=51257) {'loss': 0.9262, 'grad_norm': 0.5726306438446045, 'learning_rate': 8.813256581691887e-05, 'epoch': 0.08}
Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:44:44. Total running time: 1hr 50min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 34%|███▍      | 51/150 [02:20<04:48,  2.92s/it]
 35%|███▍      | 52/150 [02:23<04:32,  2.78s/it]
 35%|███▌      | 53/150 [02:26<04:24,  2.72s/it]
 36%|███▌      | 54/150 [02:28<04:17,  2.68s/it]

 37%|███▋      | 55/150 [02:30<03:59,  2.52s/it]

(train_sft_tune pid=51257) {'loss': 0.8141, 'grad_norm': 0.6044875979423523, 'learning_rate': 8.376956750915063e-05, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:33<04:02,  2.58s/it]
 38%|███▊      | 57/150 [02:35<03:40,  2.37s/it]
 39%|███▊      | 58/150 [02:37<03:45,  2.45s/it]
 39%|███▉      | 59/150 [02:40<03:47,  2.50s/it]
 40%|████      | 60/150 [02:43<03:44,  2.49s/it]

(train_sft_tune pid=51257) {'loss': 0.9452, 'grad_norm': 0.7087476849555969, 'learning_rate': 7.940656920138236e-05, 'epoch': 0.1}

 41%|████      | 61/150 [02:45<03:49,  2.58s/it]
 41%|████▏     | 62/150 [02:49<04:13,  2.88s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:45:14. Total running time: 1hr 50min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 42%|████▏     | 63/150 [02:52<04:16,  2.95s/it]
 43%|████▎     | 64/150 [02:55<04:25,  3.09s/it]
 43%|████▎     | 65/150 [02:58<03:56,  2.78s/it]

(train_sft_tune pid=51257) {'loss': 0.7768, 'grad_norm': 0.5816706418991089, 'learning_rate': 7.50435708936141e-05, 'epoch': 0.1}

 44%|████▍     | 66/150 [03:00<03:55,  2.80s/it]
 45%|████▍     | 67/150 [03:03<03:37,  2.62s/it]
 45%|████▌     | 68/150 [03:05<03:20,  2.45s/it]
 46%|████▌     | 69/150 [03:07<03:08,  2.33s/it]
 47%|████▋     | 70/150 [03:10<03:27,  2.59s/it]

(train_sft_tune pid=51257) {'loss': 0.8945, 'grad_norm': 0.5541176199913025, 'learning_rate': 7.068057258584584e-05, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:13<03:36,  2.75s/it]
 48%|████▊     | 72/150 [03:15<03:23,  2.61s/it]
 49%|████▊     | 73/150 [03:18<03:25,  2.67s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:45:45. Total running time: 1hr 51min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 49%|████▉     | 74/150 [03:21<03:19,  2.62s/it]
 50%|█████     | 75/150 [03:23<03:18,  2.65s/it]

(train_sft_tune pid=51257) {'loss': 0.9939, 'grad_norm': 0.5382978916168213, 'learning_rate': 6.631757427807759e-05, 'epoch': 0.12}

 51%|█████     | 76/150 [03:26<03:15,  2.64s/it]
 51%|█████▏    | 77/150 [03:28<03:10,  2.61s/it]
 52%|█████▏    | 78/150 [03:31<03:15,  2.72s/it]
 53%|█████▎    | 79/150 [03:34<03:03,  2.58s/it]
 53%|█████▎    | 80/150 [03:36<03:00,  2.58s/it]

(train_sft_tune pid=51257) {'loss': 0.9561, 'grad_norm': 0.7910987138748169, 'learning_rate': 6.195457597030931e-05, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:39<03:00,  2.62s/it]
 55%|█████▍    | 82/150 [03:42<03:00,  2.65s/it]
 55%|█████▌    | 83/150 [03:44<02:52,  2.57s/it]
 56%|█████▌    | 84/150 [03:46<02:44,  2.50s/it]
 57%|█████▋    | 85/150 [03:49<02:48,  2.60s/it]

(train_sft_tune pid=51257) {'loss': 0.9914, 'grad_norm': 0.7052956223487854, 'learning_rate': 5.7591577662541056e-05, 'epoch': 0.14}
Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:46:15. Total running time: 1hr 51min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 57%|█████▋    | 86/150 [03:51<02:35,  2.44s/it]
 58%|█████▊    | 87/150 [03:54<02:44,  2.61s/it]
 59%|█████▊    | 88/150 [03:57<02:46,  2.68s/it]
 59%|█████▉    | 89/150 [04:00<02:53,  2.84s/it]
 60%|██████    | 90/150 [04:02<02:30,  2.52s/it]

(train_sft_tune pid=51257) {'loss': 0.9967, 'grad_norm': 0.6048508286476135, 'learning_rate': 5.3228579354772794e-05, 'epoch': 0.14}

 61%|██████    | 91/150 [04:04<02:19,  2.36s/it]
 61%|██████▏   | 92/150 [04:07<02:20,  2.42s/it]
 62%|██████▏   | 93/150 [04:09<02:19,  2.44s/it]
 63%|██████▎   | 94/150 [04:12<02:14,  2.39s/it]
 63%|██████▎   | 95/150 [04:14<02:17,  2.50s/it]

(train_sft_tune pid=51257) {'loss': 0.8, 'grad_norm': 0.5124039053916931, 'learning_rate': 4.886558104700453e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:17<02:11,  2.43s/it]
 65%|██████▍   | 97/150 [04:19<02:17,  2.59s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:46:45. Total running time: 1hr 52min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 65%|██████▌   | 98/150 [04:22<02:19,  2.68s/it]
 66%|██████▌   | 99/150 [04:26<02:24,  2.84s/it]
 67%|██████▋   | 100/150 [04:28<02:08,  2.57s/it]

(train_sft_tune pid=51257) {'loss': 0.8948, 'grad_norm': 0.566940188407898, 'learning_rate': 4.450258273923627e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:30<02:02,  2.49s/it]
 68%|██████▊   | 102/150 [04:32<01:55,  2.40s/it]
 69%|██████▊   | 103/150 [04:35<01:57,  2.49s/it]
 69%|██████▉   | 104/150 [04:37<01:57,  2.55s/it]
 70%|███████   | 105/150 [04:40<01:54,  2.54s/it]

(train_sft_tune pid=51257) {'loss': 0.9237, 'grad_norm': 0.5186281800270081, 'learning_rate': 4.013958443146801e-05, 'epoch': 0.17}

 71%|███████   | 106/150 [04:42<01:48,  2.47s/it]
 71%|███████▏  | 107/150 [04:45<01:52,  2.61s/it]
 72%|███████▏  | 108/150 [04:48<01:56,  2.78s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:47:15. Total running time: 1hr 52min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 73%|███████▎  | 109/150 [04:51<01:52,  2.74s/it]
 73%|███████▎  | 110/150 [04:53<01:40,  2.50s/it]

(train_sft_tune pid=51257) {'loss': 0.8355, 'grad_norm': 0.6263107061386108, 'learning_rate': 3.5776586123699744e-05, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:56<01:45,  2.72s/it]
 75%|███████▍  | 112/150 [04:59<01:47,  2.84s/it]
 75%|███████▌  | 113/150 [05:01<01:36,  2.61s/it]
 76%|███████▌  | 114/150 [05:04<01:36,  2.69s/it]
 77%|███████▋  | 115/150 [05:06<01:27,  2.51s/it]

(train_sft_tune pid=51257) {'loss': 0.8627, 'grad_norm': 0.6857587099075317, 'learning_rate': 3.141358781593148e-05, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:09<01:24,  2.48s/it]
 78%|███████▊  | 117/150 [05:12<01:28,  2.67s/it]
 79%|███████▊  | 118/150 [05:15<01:29,  2.80s/it]
 79%|███████▉  | 119/150 [05:18<01:27,  2.83s/it]
 80%|████████  | 120/150 [05:20<01:19,  2.64s/it]

(train_sft_tune pid=51257) {'loss': 1.0749, 'grad_norm': 0.6242572069168091, 'learning_rate': 2.7050589508163222e-05, 'epoch': 0.19}
Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:47:45. Total running time: 1hr 53min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 81%|████████  | 121/150 [05:23<01:21,  2.82s/it]
 81%|████████▏ | 122/150 [05:26<01:21,  2.92s/it]
 82%|████████▏ | 123/150 [05:29<01:15,  2.80s/it]
 83%|████████▎ | 124/150 [05:32<01:16,  2.92s/it]
 83%|████████▎ | 125/150 [05:35<01:10,  2.81s/it]

(train_sft_tune pid=51257) {'loss': 0.8485, 'grad_norm': 0.5529601573944092, 'learning_rate': 2.268759120039496e-05, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:38<01:07,  2.83s/it]
 85%|████████▍ | 127/150 [05:40<01:04,  2.82s/it]
 85%|████████▌ | 128/150 [05:43<01:00,  2.73s/it]
 86%|████████▌ | 129/150 [05:45<00:50,  2.40s/it]
 87%|████████▋ | 130/150 [05:47<00:49,  2.49s/it]

(train_sft_tune pid=51257) {'loss': 0.849, 'grad_norm': 0.5599597692489624, 'learning_rate': 1.83245928926267e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:50<00:46,  2.47s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:48:15. Total running time: 1hr 53min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 88%|████████▊ | 132/150 [05:53<00:46,  2.59s/it]
 89%|████████▊ | 133/150 [05:55<00:41,  2.44s/it]
 89%|████████▉ | 134/150 [05:58<00:44,  2.80s/it]
 90%|█████████ | 135/150 [06:01<00:41,  2.76s/it]

(train_sft_tune pid=51257) {'loss': 0.8756, 'grad_norm': 0.5818164944648743, 'learning_rate': 1.3961594584858438e-05, 'epoch': 0.22}

 91%|█████████ | 136/150 [06:04<00:39,  2.84s/it]
 91%|█████████▏| 137/150 [06:06<00:33,  2.58s/it]
 92%|█████████▏| 138/150 [06:09<00:31,  2.59s/it]
 93%|█████████▎| 139/150 [06:11<00:27,  2.54s/it]
 93%|█████████▎| 140/150 [06:13<00:24,  2.42s/it]

(train_sft_tune pid=51257) {'loss': 0.9481, 'grad_norm': 0.5737020373344421, 'learning_rate': 9.598596277090175e-06, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:16<00:22,  2.48s/it]
 95%|█████████▍| 142/150 [06:18<00:20,  2.53s/it]

Trial status: 14 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:48:45. Total running time: 1hr 54min 15s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_dab9ed39   RUNNING      0.000126527    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_9d59f08d   PENDING      0.000190782    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 95%|█████████▌| 143/150 [06:21<00:18,  2.60s/it]
 96%|█████████▌| 144/150 [06:24<00:16,  2.77s/it]
 97%|█████████▋| 145/150 [06:27<00:13,  2.67s/it]

(train_sft_tune pid=51257) {'loss': 0.8785, 'grad_norm': 0.5699051022529602, 'learning_rate': 5.235597969321914e-06, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:29<00:10,  2.61s/it]
 98%|█████████▊| 147/150 [06:32<00:07,  2.60s/it]
 99%|█████████▊| 148/150 [06:35<00:05,  2.66s/it]
 99%|█████████▉| 149/150 [06:37<00:02,  2.57s/it]
100%|██████████| 150/150 [06:40<00:00,  2.61s/it]

(train_sft_tune pid=51257) {'loss': 0.9382, 'grad_norm': 0.550272524356842, 'learning_rate': 8.725996615536523e-07, 'epoch': 0.24}

Trial train_sft_tune_dab9ed39 completed after 1 iterations at 2025-11-29 17:49:05. Total running time: 1hr 54min 35s
+--------------------------------------------------+
| Trial train_sft_tune_dab9ed39 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                          446.89 |
| time_total_s                              446.89 |
| training_iteration                             1 |
| train_loss                               0.91417 |
+--------------------------------------------------+
(train_sft_tune pid=51257) {'train_runtime': 401.2045, 'train_samples_per_second': 2.991, 'train_steps_per_second': 0.374, 'train_loss': 0.9141735680898031, 'epoch': 0.24}
(train_sft_tune pid=51257) history of tuning  [{'loss': 1.0815, 'grad_norm': 0.7621669173240662, 'learning_rate': 0.00010122156074022368, 'epoch': 0.008, 'step': 5}, {'loss': 0.9139, 'grad_norm': 0.6054676175117493, 'learning_rate': 0.00012303655227906496, 'epoch': 0.016, 'step': 10}, {'loss': 1.0069, 'grad_norm': 0.6916328072547913, 'learning_rate': 0.00011867355397129671, 'epoch': 0.024, 'step': 15}, {'loss': 0.9346, 'grad_norm': 0.8495272994041443, 'learning_rate': 0.00011431055566352846, 'epoch': 0.032, 'step': 20}, {'loss': 0.8666, 'grad_norm': 0.5336423516273499, 'learning_rate': 0.00010994755735576019, 'epoch': 0.04, 'step': 25}, {'loss': 1.0118, 'grad_norm': 0.5489776730537415, 'learning_rate': 0.00010558455904799194, 'epoch': 0.048, 'step': 30}, {'loss': 0.8964, 'grad_norm': 0.6171854734420776, 'learning_rate': 0.00010122156074022368, 'epoch': 0.056, 'step': 35}, {'loss': 0.7901, 'grad_norm': 0.6149877309799194, 'learning_rate': 9.68585624324554e-05, 'epoch': 0.064, 'step': 40}, {'loss': 0.8987, 'grad_norm': 0.6170118451118469, 'learning_rate': 9.249556412468715e-05, 'epoch': 0.072, 'step': 45}, {'loss': 0.9262, 'grad_norm': 0.5726306438446045, 'learning_rate': 8.813256581691887e-05, 'epoch': 0.08, 'step': 50}, {'loss': 0.8141, 'grad_norm': 0.6044875979423523, 'learning_rate': 8.376956750915063e-05, 'epoch': 0.088, 'step': 55}, {'loss': 0.9452, 'grad_norm': 0.7087476849555969, 'learning_rate': 7.940656920138236e-05, 'epoch': 0.096, 'step': 60}, {'loss': 0.7768, 'grad_norm': 0.5816706418991089, 'learning_rate': 7.50435708936141e-05, 'epoch': 0.104, 'step': 65}, {'loss': 0.8945, 'grad_norm': 0.5541176199913025, 'learning_rate': 7.068057258584584e-05, 'epoch': 0.112, 'step': 70}, {'loss': 0.9939, 'grad_norm': 0.5382978916168213, 'learning_rate': 6.631757427807759e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.9561, 'grad_norm': 0.7910987138748169, 'learning_rate': 6.195457597030931e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.9914, 'grad_norm': 0.7052956223487854, 'learning_rate': 5.7591577662541056e-05, 'epoch': 0.136, 'step': 85}, {'loss': 0.9967, 'grad_norm': 0.6048508286476135, 'learning_rate': 5.3228579354772794e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.8, 'grad_norm': 0.5124039053916931, 'learning_rate': 4.886558104700453e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8948, 'grad_norm': 0.566940188407898, 'learning_rate': 4.450258273923627e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9237, 'grad_norm': 0.5186281800270081, 'learning_rate': 4.013958443146801e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8355, 'grad_norm': 0.6263107061386108, 'learning_rate': 3.5776586123699744e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8627, 'grad_norm': 0.6857587099075317, 'learning_rate': 3.141358781593148e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0749, 'grad_norm': 0.6242572069168091, 'learning_rate': 2.7050589508163222e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8485, 'grad_norm': 0.5529601573944092, 'learning_rate': 2.268759120039496e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.849, 'grad_norm': 0.5599597692489624, 'learning_rate': 1.83245928926267e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8756, 'grad_norm': 0.5818164944648743, 'learning_rate': 1.3961594584858438e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9481, 'grad_norm': 0.5737020373344421, 'learning_rate': 9.598596277090175e-06, 'epoch': 0.224, 'step': 140}, {'loss': 0.8785, 'grad_norm': 0.5699051022529602, 'learning_rate': 5.235597969321914e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9382, 'grad_norm': 0.550272524356842, 'learning_rate': 8.725996615536523e-07, 'epoch': 0.24, 'step': 150}, {'train_runtime': 401.2045, 'train_samples_per_second': 2.991, 'train_steps_per_second': 0.374, 'total_flos': 4944308261511168.0, 'train_loss': 0.9141735680898031, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=51257) Reporting loss: 0.9141735680898031

100%|██████████| 150/150 [06:41<00:00,  2.67s/it]

Trial train_sft_tune_9d59f08d started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_9d59f08d config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00019 |
| r                                             32 |
+--------------------------------------------------+

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:49:15. Total running time: 1hr 54min 45s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=53266) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=53266) 2025-11-29 17:49:19.465475: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=53266) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=53266) E0000 00:00:1764438559.493466   53327 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=53266) E0000 00:00:1764438559.500386   53327 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=53266) W0000 00:00:1764438559.517937   53327 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=53266) W0000 00:00:1764438559.517972   53327 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=53266) W0000 00:00:1764438559.517975   53327 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=53266) W0000 00:00:1764438559.517977   53327 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=53266) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=53266) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=53266)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=53266) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=53266) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=53266)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=53266) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=53266) [2025-11-29 17:49:43,885 E 53266 53303] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:49:45. Total running time: 1hr 55min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=53266) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=53266) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=53266) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=53266)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=53266) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=53266) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=53266)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=53266) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:12<30:09, 12.15s/it]
  1%|▏         | 2/150 [00:14<15:19,  6.21s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:50:15. Total running time: 1hr 55min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  2%|▏         | 3/150 [00:16<11:21,  4.63s/it]
  3%|▎         | 4/150 [00:19<09:18,  3.82s/it]

(train_sft_tune pid=53266) {'loss': 1.0772, 'grad_norm': 0.7156462073326111, 'learning_rate': 0.00015262550285015896, 'epoch': 0.01}

  3%|▎         | 5/150 [00:21<07:37,  3.15s/it]
  4%|▍         | 6/150 [00:23<07:00,  2.92s/it]
  5%|▍         | 7/150 [00:26<06:39,  2.79s/it]
  5%|▌         | 8/150 [00:29<06:25,  2.71s/it]
  6%|▌         | 9/150 [00:31<06:11,  2.64s/it]

(train_sft_tune pid=53266) {'loss': 0.9046, 'grad_norm': 0.5606908798217773, 'learning_rate': 0.00018551893018855525, 'epoch': 0.02}

  7%|▋         | 10/150 [00:34<06:04,  2.60s/it]
  7%|▋         | 11/150 [00:36<06:09,  2.66s/it]
  8%|▊         | 12/150 [00:39<05:49,  2.53s/it]
  9%|▊         | 13/150 [00:42<06:05,  2.67s/it]
  9%|▉         | 14/150 [00:44<05:43,  2.52s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:50:45. Total running time: 1hr 56min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=53266) {'loss': 1.0028, 'grad_norm': 0.6732004880905151, 'learning_rate': 0.000178940244720876, 'epoch': 0.02}

 10%|█         | 15/150 [00:46<05:10,  2.30s/it]
 11%|█         | 16/150 [00:48<05:24,  2.42s/it]
 11%|█▏        | 17/150 [00:51<05:47,  2.61s/it]
 12%|█▏        | 18/150 [00:53<05:17,  2.40s/it]
 13%|█▎        | 19/150 [00:56<05:24,  2.47s/it]

(train_sft_tune pid=53266) {'loss': 0.9275, 'grad_norm': 0.7878870964050293, 'learning_rate': 0.00017236155925319673, 'epoch': 0.03}

 13%|█▎        | 20/150 [00:57<04:43,  2.18s/it]
 14%|█▍        | 21/150 [00:59<04:36,  2.14s/it]
 15%|█▍        | 22/150 [01:02<04:38,  2.18s/it]
 15%|█▌        | 23/150 [01:04<04:48,  2.27s/it]
 16%|█▌        | 24/150 [01:07<05:03,  2.41s/it]

(train_sft_tune pid=53266) {'loss': 0.8642, 'grad_norm': 0.548893928527832, 'learning_rate': 0.00016578287378551744, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:09<05:08,  2.47s/it]
 17%|█▋        | 26/150 [01:13<05:33,  2.69s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:51:15. Total running time: 1hr 56min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 18%|█▊        | 27/150 [01:15<05:13,  2.55s/it]
 19%|█▊        | 28/150 [01:18<05:23,  2.65s/it]
 19%|█▉        | 29/150 [01:20<04:53,  2.43s/it]

(train_sft_tune pid=53266) {'loss': 1.0072, 'grad_norm': 0.5405575633049011, 'learning_rate': 0.0001592041883178382, 'epoch': 0.05}

 20%|██        | 30/150 [01:23<05:33,  2.78s/it]
 21%|██        | 31/150 [01:26<05:38,  2.84s/it]
 21%|██▏       | 32/150 [01:28<05:07,  2.60s/it]
 22%|██▏       | 33/150 [01:32<05:25,  2.78s/it]
 23%|██▎       | 34/150 [01:34<05:13,  2.70s/it]

(train_sft_tune pid=53266) {'loss': 0.8946, 'grad_norm': 0.598756730556488, 'learning_rate': 0.00015262550285015896, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:36<04:50,  2.53s/it]
 24%|██▍       | 36/150 [01:39<04:44,  2.49s/it]
 25%|██▍       | 37/150 [01:41<04:47,  2.54s/it]
 25%|██▌       | 38/150 [01:44<04:36,  2.47s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:51:45. Total running time: 1hr 57min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 26%|██▌       | 39/150 [01:46<04:44,  2.57s/it]

(train_sft_tune pid=53266) {'loss': 0.7866, 'grad_norm': 0.6255586743354797, 'learning_rate': 0.00014604681738247967, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:49<04:44,  2.58s/it]
 27%|██▋       | 41/150 [01:52<04:42,  2.59s/it]
 28%|██▊       | 42/150 [01:54<04:42,  2.62s/it]
 29%|██▊       | 43/150 [01:56<04:17,  2.41s/it]
 29%|██▉       | 44/150 [01:59<04:22,  2.48s/it]

(train_sft_tune pid=53266) {'loss': 0.8949, 'grad_norm': 0.6057253479957581, 'learning_rate': 0.0001394681319148004, 'epoch': 0.07}

 30%|███       | 45/150 [02:01<04:02,  2.31s/it]
 31%|███       | 46/150 [02:04<04:16,  2.47s/it]
 31%|███▏      | 47/150 [02:06<04:26,  2.59s/it]
 32%|███▏      | 48/150 [02:09<04:38,  2.73s/it]
 33%|███▎      | 49/150 [02:12<04:17,  2.55s/it]

(train_sft_tune pid=53266) {'loss': 0.9255, 'grad_norm': 0.555653989315033, 'learning_rate': 0.00013288944644712113, 'epoch': 0.08}
Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:52:15. Total running time: 1hr 57min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 33%|███▎      | 50/150 [02:15<04:29,  2.69s/it]
 34%|███▍      | 51/150 [02:18<04:49,  2.92s/it]
 35%|███▍      | 52/150 [02:21<04:32,  2.78s/it]
 35%|███▌      | 53/150 [02:23<04:24,  2.73s/it]
 36%|███▌      | 54/150 [02:26<04:16,  2.67s/it]

(train_sft_tune pid=53266) {'loss': 0.8117, 'grad_norm': 0.6133427023887634, 'learning_rate': 0.00012631076097944187, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:28<03:55,  2.48s/it]
 37%|███▋      | 56/150 [02:30<04:00,  2.56s/it]
 38%|███▊      | 57/150 [02:32<03:41,  2.38s/it]
 39%|███▊      | 58/150 [02:35<03:45,  2.45s/it]
 39%|███▉      | 59/150 [02:38<03:48,  2.51s/it]

(train_sft_tune pid=53266) {'loss': 0.9414, 'grad_norm': 0.6907379031181335, 'learning_rate': 0.00011973207551176261, 'epoch': 0.1}

 40%|████      | 60/150 [02:40<03:41,  2.47s/it]
 41%|████      | 61/150 [02:43<03:48,  2.57s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:52:45. Total running time: 1hr 58min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 41%|████▏     | 62/150 [02:46<04:12,  2.87s/it]
 42%|████▏     | 63/150 [02:50<04:15,  2.94s/it]
 43%|████▎     | 64/150 [02:53<04:23,  3.06s/it]

(train_sft_tune pid=53266) {'loss': 0.7723, 'grad_norm': 0.5514310598373413, 'learning_rate': 0.00011315339004408334, 'epoch': 0.1}

 43%|████▎     | 65/150 [02:55<03:54,  2.76s/it]
 44%|████▍     | 66/150 [02:58<03:54,  2.79s/it]
 45%|████▍     | 67/150 [03:00<03:36,  2.61s/it]
 45%|████▌     | 68/150 [03:02<03:20,  2.45s/it]
 46%|████▌     | 69/150 [03:04<03:06,  2.30s/it]

(train_sft_tune pid=53266) {'loss': 0.891, 'grad_norm': 0.5201959609985352, 'learning_rate': 0.00010657470457640408, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:07<03:24,  2.56s/it]
 47%|████▋     | 71/150 [03:10<03:36,  2.74s/it]
 48%|████▊     | 72/150 [03:13<03:23,  2.61s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:53:15. Total running time: 1hr 58min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 49%|████▊     | 73/150 [03:15<03:25,  2.67s/it]
 49%|████▉     | 74/150 [03:18<03:16,  2.59s/it]

(train_sft_tune pid=53266) {'loss': 0.9912, 'grad_norm': 0.5131025910377502, 'learning_rate': 9.999601910872483e-05, 'epoch': 0.12}

 50%|█████     | 75/150 [03:21<03:16,  2.62s/it]
 51%|█████     | 76/150 [03:23<03:15,  2.65s/it]
 51%|█████▏    | 77/150 [03:26<03:10,  2.61s/it]
 52%|█████▏    | 78/150 [03:28<02:56,  2.45s/it]
 53%|█████▎    | 79/150 [03:30<02:48,  2.38s/it]

(train_sft_tune pid=53266) {'loss': 0.952, 'grad_norm': 0.7413825392723083, 'learning_rate': 9.341733364104555e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:33<02:51,  2.45s/it]
 54%|█████▍    | 81/150 [03:36<02:56,  2.56s/it]
 55%|█████▍    | 82/150 [03:38<02:57,  2.61s/it]
 55%|█████▌    | 83/150 [03:41<02:49,  2.53s/it]
 56%|█████▌    | 84/150 [03:43<02:40,  2.43s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:53:46. Total running time: 1hr 59min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=53266) {'loss': 0.9865, 'grad_norm': 0.6674237847328186, 'learning_rate': 8.68386481733663e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:46<02:45,  2.55s/it]
 57%|█████▋    | 86/150 [03:48<02:36,  2.44s/it]
 58%|█████▊    | 87/150 [03:51<02:44,  2.62s/it]
 59%|█████▊    | 88/150 [03:54<02:45,  2.67s/it]
 59%|█████▉    | 89/150 [03:57<02:52,  2.83s/it]

(train_sft_tune pid=53266) {'loss': 0.9939, 'grad_norm': 0.6009345054626465, 'learning_rate': 8.025996270568702e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [03:59<02:31,  2.53s/it]
 61%|██████    | 91/150 [04:01<02:21,  2.41s/it]
 61%|██████▏   | 92/150 [04:03<02:22,  2.46s/it]
 62%|██████▏   | 93/150 [04:06<02:19,  2.45s/it]
 63%|██████▎   | 94/150 [04:08<02:12,  2.36s/it]

(train_sft_tune pid=53266) {'loss': 0.7984, 'grad_norm': 0.48597005009651184, 'learning_rate': 7.368127723800777e-05, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:11<02:15,  2.46s/it]
 64%|██████▍   | 96/150 [04:13<02:11,  2.43s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:54:16. Total running time: 1hr 59min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 65%|██████▍   | 97/150 [04:16<02:17,  2.60s/it]
 65%|██████▌   | 98/150 [04:19<02:19,  2.69s/it]
 66%|██████▌   | 99/150 [04:22<02:23,  2.82s/it]

(train_sft_tune pid=53266) {'loss': 0.8931, 'grad_norm': 0.5322408676147461, 'learning_rate': 6.71025917703285e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:24<02:07,  2.56s/it]
 67%|██████▋   | 101/150 [04:26<02:03,  2.51s/it]
 68%|██████▊   | 102/150 [04:29<01:55,  2.42s/it]
 69%|██████▊   | 103/150 [04:31<01:56,  2.48s/it]
 69%|██████▉   | 104/150 [04:34<01:56,  2.53s/it]

(train_sft_tune pid=53266) {'loss': 0.9214, 'grad_norm': 0.4899670481681824, 'learning_rate': 6.052390630264924e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:36<01:53,  2.53s/it]
 71%|███████   | 106/150 [04:39<01:50,  2.51s/it]
 71%|███████▏  | 107/150 [04:42<01:53,  2.64s/it]
 72%|███████▏  | 108/150 [04:45<01:57,  2.79s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:54:46. Total running time: 2hr 0min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 73%|███████▎  | 109/150 [04:47<01:51,  2.73s/it]

(train_sft_tune pid=53266) {'loss': 0.8327, 'grad_norm': 0.5923108458518982, 'learning_rate': 5.394522083496997e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [04:49<01:40,  2.51s/it]
 74%|███████▍  | 111/150 [04:53<01:46,  2.73s/it]
 75%|███████▍  | 112/150 [04:56<01:47,  2.83s/it]
 75%|███████▌  | 113/150 [04:58<01:36,  2.60s/it]
 76%|███████▌  | 114/150 [05:01<01:36,  2.67s/it]

(train_sft_tune pid=53266) {'loss': 0.8584, 'grad_norm': 0.6430292129516602, 'learning_rate': 4.73665353672907e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:03<01:27,  2.51s/it]
 77%|███████▋  | 116/150 [05:05<01:24,  2.49s/it]
 78%|███████▊  | 117/150 [05:08<01:28,  2.67s/it]
 79%|███████▊  | 118/150 [05:11<01:29,  2.79s/it]
 79%|███████▉  | 119/150 [05:14<01:27,  2.83s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:55:16. Total running time: 2hr 0min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=53266) {'loss': 1.0714, 'grad_norm': 0.5863268375396729, 'learning_rate': 4.0787849899611443e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:17<01:19,  2.67s/it]
 81%|████████  | 121/150 [05:20<01:22,  2.86s/it]
 81%|████████▏ | 122/150 [05:23<01:22,  2.94s/it]
 82%|████████▏ | 123/150 [05:26<01:15,  2.80s/it]
 83%|████████▎ | 124/150 [05:29<01:16,  2.94s/it]

(train_sft_tune pid=53266) {'loss': 0.8458, 'grad_norm': 0.5240222811698914, 'learning_rate': 3.420916443193217e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:31<01:10,  2.83s/it]
 84%|████████▍ | 126/150 [05:34<01:08,  2.85s/it]
 85%|████████▍ | 127/150 [05:37<01:04,  2.82s/it]
 85%|████████▌ | 128/150 [05:40<00:59,  2.73s/it]
 86%|████████▌ | 129/150 [05:41<00:51,  2.44s/it]

(train_sft_tune pid=53266) {'loss': 0.846, 'grad_norm': 0.5315230488777161, 'learning_rate': 2.7630478964252914e-05, 'epoch': 0.21}

 87%|████████▋ | 130/150 [05:44<00:50,  2.53s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:55:46. Total running time: 2hr 1min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 87%|████████▋ | 131/150 [05:46<00:47,  2.50s/it]
 88%|████████▊ | 132/150 [05:49<00:46,  2.59s/it]
 89%|████████▊ | 133/150 [05:51<00:41,  2.44s/it]
 89%|████████▉ | 134/150 [05:55<00:44,  2.80s/it]

(train_sft_tune pid=53266) {'loss': 0.873, 'grad_norm': 0.5502493977546692, 'learning_rate': 2.1051793496573646e-05, 'epoch': 0.22}

 90%|█████████ | 135/150 [05:58<00:41,  2.78s/it]
 91%|█████████ | 136/150 [06:01<00:39,  2.85s/it]
 91%|█████████▏| 137/150 [06:03<00:33,  2.56s/it]
 92%|█████████▏| 138/150 [06:05<00:30,  2.56s/it]
 93%|█████████▎| 139/150 [06:08<00:28,  2.56s/it]

(train_sft_tune pid=53266) {'loss': 0.9442, 'grad_norm': 0.5428464412689209, 'learning_rate': 1.4473108028894382e-05, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:10<00:24,  2.45s/it]
 94%|█████████▍| 141/150 [06:13<00:22,  2.50s/it]

Trial status: 15 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:56:16. Total running time: 2hr 1min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: f6d5bc07 with train_loss=0.9123824580510458 and params={'lr': 0.00015873874967846482, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_9d59f08d   RUNNING      0.000190782    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 95%|█████████▍| 142/150 [06:15<00:20,  2.53s/it]
 95%|█████████▌| 143/150 [06:18<00:18,  2.59s/it]
 96%|█████████▌| 144/150 [06:21<00:16,  2.77s/it]

(train_sft_tune pid=53266) {'loss': 0.8754, 'grad_norm': 0.5561320185661316, 'learning_rate': 7.894422561215117e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:23<00:13,  2.67s/it]
 97%|█████████▋| 146/150 [06:26<00:10,  2.59s/it]
 98%|█████████▊| 147/150 [06:28<00:07,  2.57s/it]
 99%|█████████▊| 148/150 [06:31<00:05,  2.64s/it]
 99%|█████████▉| 149/150 [06:34<00:02,  2.58s/it]

(train_sft_tune pid=53266) {'loss': 0.9334, 'grad_norm': 0.5249659419059753, 'learning_rate': 1.3157370935358529e-06, 'epoch': 0.24}

100%|██████████| 150/150 [06:36<00:00,  2.62s/it]

Trial train_sft_tune_9d59f08d completed after 1 iterations at 2025-11-29 17:56:38. Total running time: 2hr 2min 8s
+--------------------------------------------------+
| Trial train_sft_tune_9d59f08d result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                          443.46 |
| time_total_s                              443.46 |
| training_iteration                             1 |
| train_loss                               0.91061 |
+--------------------------------------------------+
(train_sft_tune pid=53266) {'train_runtime': 397.9431, 'train_samples_per_second': 3.016, 'train_steps_per_second': 0.377, 'train_loss': 0.9106097141901652, 'epoch': 0.24}
(train_sft_tune pid=53266) history of tuning  [{'loss': 1.0772, 'grad_norm': 0.7156462073326111, 'learning_rate': 0.00015262550285015896, 'epoch': 0.008, 'step': 5}, {'loss': 0.9046, 'grad_norm': 0.5606908798217773, 'learning_rate': 0.00018551893018855525, 'epoch': 0.016, 'step': 10}, {'loss': 1.0028, 'grad_norm': 0.6732004880905151, 'learning_rate': 0.000178940244720876, 'epoch': 0.024, 'step': 15}, {'loss': 0.9275, 'grad_norm': 0.7878870964050293, 'learning_rate': 0.00017236155925319673, 'epoch': 0.032, 'step': 20}, {'loss': 0.8642, 'grad_norm': 0.548893928527832, 'learning_rate': 0.00016578287378551744, 'epoch': 0.04, 'step': 25}, {'loss': 1.0072, 'grad_norm': 0.5405575633049011, 'learning_rate': 0.0001592041883178382, 'epoch': 0.048, 'step': 30}, {'loss': 0.8946, 'grad_norm': 0.598756730556488, 'learning_rate': 0.00015262550285015896, 'epoch': 0.056, 'step': 35}, {'loss': 0.7866, 'grad_norm': 0.6255586743354797, 'learning_rate': 0.00014604681738247967, 'epoch': 0.064, 'step': 40}, {'loss': 0.8949, 'grad_norm': 0.6057253479957581, 'learning_rate': 0.0001394681319148004, 'epoch': 0.072, 'step': 45}, {'loss': 0.9255, 'grad_norm': 0.555653989315033, 'learning_rate': 0.00013288944644712113, 'epoch': 0.08, 'step': 50}, {'loss': 0.8117, 'grad_norm': 0.6133427023887634, 'learning_rate': 0.00012631076097944187, 'epoch': 0.088, 'step': 55}, {'loss': 0.9414, 'grad_norm': 0.6907379031181335, 'learning_rate': 0.00011973207551176261, 'epoch': 0.096, 'step': 60}, {'loss': 0.7723, 'grad_norm': 0.5514310598373413, 'learning_rate': 0.00011315339004408334, 'epoch': 0.104, 'step': 65}, {'loss': 0.891, 'grad_norm': 0.5201959609985352, 'learning_rate': 0.00010657470457640408, 'epoch': 0.112, 'step': 70}, {'loss': 0.9912, 'grad_norm': 0.5131025910377502, 'learning_rate': 9.999601910872483e-05, 'epoch': 0.12, 'step': 75}, {'loss': 0.952, 'grad_norm': 0.7413825392723083, 'learning_rate': 9.341733364104555e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.9865, 'grad_norm': 0.6674237847328186, 'learning_rate': 8.68386481733663e-05, 'epoch': 0.136, 'step': 85}, {'loss': 0.9939, 'grad_norm': 0.6009345054626465, 'learning_rate': 8.025996270568702e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.7984, 'grad_norm': 0.48597005009651184, 'learning_rate': 7.368127723800777e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8931, 'grad_norm': 0.5322408676147461, 'learning_rate': 6.71025917703285e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9214, 'grad_norm': 0.4899670481681824, 'learning_rate': 6.052390630264924e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8327, 'grad_norm': 0.5923108458518982, 'learning_rate': 5.394522083496997e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8584, 'grad_norm': 0.6430292129516602, 'learning_rate': 4.73665353672907e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0714, 'grad_norm': 0.5863268375396729, 'learning_rate': 4.0787849899611443e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8458, 'grad_norm': 0.5240222811698914, 'learning_rate': 3.420916443193217e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.846, 'grad_norm': 0.5315230488777161, 'learning_rate': 2.7630478964252914e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.873, 'grad_norm': 0.5502493977546692, 'learning_rate': 2.1051793496573646e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9442, 'grad_norm': 0.5428464412689209, 'learning_rate': 1.4473108028894382e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8754, 'grad_norm': 0.5561320185661316, 'learning_rate': 7.894422561215117e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9334, 'grad_norm': 0.5249659419059753, 'learning_rate': 1.3157370935358529e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 397.9431, 'train_samples_per_second': 3.016, 'train_steps_per_second': 0.377, 'total_flos': 4944308261511168.0, 'train_loss': 0.9106097141901652, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=53266) Reporting loss: 0.9106097141901652

100%|██████████| 150/150 [06:37<00:00,  2.65s/it]

Trial status: 16 TERMINATED | 1 PENDING
Current time: 2025-11-29 17:56:46. Total running time: 2hr 2min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   PENDING      0.000196317    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

Trial train_sft_tune_03394dc9 started with configuration:
+-------------------------------------------------+
| Trial train_sft_tune_03394dc9 config            |
+-------------------------------------------------+
| lora_alpha                                   64 |
| lr                                       0.0002 |
| r                                            16 |
+-------------------------------------------------+
(train_sft_tune pid=55261) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=55261) 2025-11-29 17:56:53.853866: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=55261) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=55261) E0000 00:00:1764439013.878292   55321 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=55261) E0000 00:00:1764439013.890670   55321 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=55261) W0000 00:00:1764439013.911999   55321 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=55261) W0000 00:00:1764439013.912043   55321 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=55261) W0000 00:00:1764439013.912046   55321 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=55261) W0000 00:00:1764439013.912048   55321 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=55261) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=55261) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=55261)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=55261) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=55261) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=55261)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=55261) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:57:16. Total running time: 2hr 2min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=55261) [2025-11-29 17:57:17,894 E 55261 55302] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=55261) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=55261) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=55261) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=55261)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=55261) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=55261) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=55261)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=55261) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:57:46. Total running time: 2hr 3min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:12<31:55, 12.86s/it]
  1%|▏         | 2/150 [00:14<16:04,  6.52s/it]
  2%|▏         | 3/150 [00:17<11:48,  4.82s/it]
  3%|▎         | 4/150 [00:20<09:33,  3.93s/it]

(train_sft_tune pid=55261) {'loss': 1.0767, 'grad_norm': 1.001434564590454, 'learning_rate': 0.00015705377497046916, 'epoch': 0.01}

  3%|▎         | 5/150 [00:22<07:44,  3.21s/it]
  4%|▍         | 6/150 [00:24<07:02,  2.93s/it]
  5%|▍         | 7/150 [00:27<06:39,  2.79s/it]
  5%|▌         | 8/150 [00:29<06:26,  2.72s/it]
  6%|▌         | 9/150 [00:32<06:10,  2.63s/it]

(train_sft_tune pid=55261) {'loss': 0.9038, 'grad_norm': 0.7887026071548462, 'learning_rate': 0.00019090157130031163, 'epoch': 0.02}

  7%|▋         | 10/150 [00:34<06:01,  2.58s/it]
  7%|▋         | 11/150 [00:37<06:03,  2.62s/it]
  8%|▊         | 12/150 [00:39<05:42,  2.48s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:58:16. Total running time: 2hr 3min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  9%|▊         | 13/150 [00:42<06:02,  2.64s/it]
  9%|▉         | 14/150 [00:44<05:40,  2.50s/it]

(train_sft_tune pid=55261) {'loss': 1.0017, 'grad_norm': 0.9322093725204468, 'learning_rate': 0.00018413201203434313, 'epoch': 0.02}

 10%|█         | 15/150 [00:46<05:08,  2.29s/it]
 11%|█         | 16/150 [00:49<05:19,  2.38s/it]
 11%|█▏        | 17/150 [00:52<05:42,  2.57s/it]
 12%|█▏        | 18/150 [00:54<05:16,  2.40s/it]
 13%|█▎        | 19/150 [00:56<05:23,  2.47s/it]

(train_sft_tune pid=55261) {'loss': 0.9265, 'grad_norm': 1.101630449295044, 'learning_rate': 0.00017736245276837463, 'epoch': 0.03}

 13%|█▎        | 20/150 [00:58<04:42,  2.17s/it]
 14%|█▍        | 21/150 [01:00<04:35,  2.13s/it]
 15%|█▍        | 22/150 [01:02<04:34,  2.14s/it]
 15%|█▌        | 23/150 [01:04<04:41,  2.22s/it]
 16%|█▌        | 24/150 [01:07<05:00,  2.39s/it]

(train_sft_tune pid=55261) {'loss': 0.8634, 'grad_norm': 0.7721512317657471, 'learning_rate': 0.00017059289350240613, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:10<05:04,  2.44s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:58:46. Total running time: 2hr 4min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 17%|█▋        | 26/150 [01:13<05:27,  2.64s/it]
 18%|█▊        | 27/150 [01:15<05:05,  2.49s/it]
 19%|█▊        | 28/150 [01:18<05:16,  2.60s/it]
 19%|█▉        | 29/150 [01:20<04:54,  2.44s/it]

(train_sft_tune pid=55261) {'loss': 1.007, 'grad_norm': 0.7720519304275513, 'learning_rate': 0.00016382333423643763, 'epoch': 0.05}

 20%|██        | 30/150 [01:23<05:31,  2.76s/it]
 21%|██        | 31/150 [01:26<05:33,  2.80s/it]
 21%|██▏       | 32/150 [01:28<05:01,  2.55s/it]
 22%|██▏       | 33/150 [01:31<05:19,  2.73s/it]
 23%|██▎       | 34/150 [01:34<05:10,  2.67s/it]

(train_sft_tune pid=55261) {'loss': 0.8954, 'grad_norm': 0.8438665270805359, 'learning_rate': 0.00015705377497046916, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:36<04:48,  2.51s/it]
 24%|██▍       | 36/150 [01:38<04:41,  2.47s/it]
 25%|██▍       | 37/150 [01:41<04:41,  2.49s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:59:16. Total running time: 2hr 4min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 25%|██▌       | 38/150 [01:43<04:33,  2.44s/it]
 26%|██▌       | 39/150 [01:46<04:42,  2.55s/it]

(train_sft_tune pid=55261) {'loss': 0.7868, 'grad_norm': 0.8794001340866089, 'learning_rate': 0.00015028421570450063, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:49<04:41,  2.56s/it]
 27%|██▋       | 41/150 [01:51<04:39,  2.56s/it]
 28%|██▊       | 42/150 [01:54<04:39,  2.59s/it]
 29%|██▊       | 43/150 [01:56<04:17,  2.40s/it]
 29%|██▉       | 44/150 [01:58<04:22,  2.48s/it]

(train_sft_tune pid=55261) {'loss': 0.8955, 'grad_norm': 0.8511478304862976, 'learning_rate': 0.00014351465643853216, 'epoch': 0.07}

 30%|███       | 45/150 [02:00<04:02,  2.31s/it]
 31%|███       | 46/150 [02:03<04:15,  2.46s/it]
 31%|███▏      | 47/150 [02:06<04:24,  2.56s/it]
 32%|███▏      | 48/150 [02:09<04:36,  2.71s/it]
 33%|███▎      | 49/150 [02:11<04:17,  2.55s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 17:59:46. Total running time: 2hr 5min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=55261) {'loss': 0.9266, 'grad_norm': 0.7750667333602905, 'learning_rate': 0.00013674509717256364, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:14<04:28,  2.68s/it]
 34%|███▍      | 51/150 [02:18<04:46,  2.90s/it]
 35%|███▍      | 52/150 [02:20<04:30,  2.76s/it]
 35%|███▌      | 53/150 [02:23<04:24,  2.72s/it]
 36%|███▌      | 54/150 [02:25<04:17,  2.68s/it]

(train_sft_tune pid=55261) {'loss': 0.8124, 'grad_norm': 0.8506602048873901, 'learning_rate': 0.00012997553790659516, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:27<03:55,  2.48s/it]
 37%|███▋      | 56/150 [02:30<04:00,  2.56s/it]
 38%|███▊      | 57/150 [02:32<03:38,  2.35s/it]
 39%|███▊      | 58/150 [02:35<03:44,  2.44s/it]
 39%|███▉      | 59/150 [02:37<03:50,  2.53s/it]

(train_sft_tune pid=55261) {'loss': 0.9418, 'grad_norm': 0.9682239890098572, 'learning_rate': 0.00012320597864062666, 'epoch': 0.1}

 40%|████      | 60/150 [02:40<03:43,  2.48s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:00:16. Total running time: 2hr 5min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 41%|████      | 61/150 [02:42<03:47,  2.56s/it]
 41%|████▏     | 62/150 [02:46<04:12,  2.86s/it]
 42%|████▏     | 63/150 [02:49<04:15,  2.94s/it]
 43%|████▎     | 64/150 [02:52<04:21,  3.05s/it]

(train_sft_tune pid=55261) {'loss': 0.773, 'grad_norm': 0.7735145688056946, 'learning_rate': 0.00011643641937465815, 'epoch': 0.1}

 43%|████▎     | 65/150 [02:54<03:53,  2.74s/it]
 44%|████▍     | 66/150 [02:57<03:52,  2.77s/it]
 45%|████▍     | 67/150 [02:59<03:35,  2.60s/it]
 45%|████▌     | 68/150 [03:02<03:21,  2.46s/it]
 46%|████▌     | 69/150 [03:03<03:06,  2.30s/it]

(train_sft_tune pid=55261) {'loss': 0.8929, 'grad_norm': 0.7298997640609741, 'learning_rate': 0.00010966686010868966, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:07<03:23,  2.54s/it]
 47%|████▋     | 71/150 [03:10<03:33,  2.70s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:00:46. Total running time: 2hr 6min 16s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 48%|████▊     | 72/150 [03:12<03:21,  2.58s/it]
 49%|████▊     | 73/150 [03:15<03:23,  2.64s/it]
 49%|████▉     | 74/150 [03:17<03:14,  2.56s/it]

(train_sft_tune pid=55261) {'loss': 0.9928, 'grad_norm': 0.7190122008323669, 'learning_rate': 0.00010289730084272118, 'epoch': 0.12}

 50%|█████     | 75/150 [03:20<03:14,  2.59s/it]
 51%|█████     | 76/150 [03:22<03:11,  2.59s/it]
 51%|█████▏    | 77/150 [03:25<03:07,  2.57s/it]
 52%|█████▏    | 78/150 [03:27<02:55,  2.44s/it]
 53%|█████▎    | 79/150 [03:29<02:48,  2.37s/it]

(train_sft_tune pid=55261) {'loss': 0.9523, 'grad_norm': 1.0524590015411377, 'learning_rate': 9.612774157675267e-05, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:32<02:49,  2.43s/it]
 54%|█████▍    | 81/150 [03:34<02:53,  2.51s/it]
 55%|█████▍    | 82/150 [03:37<02:54,  2.57s/it]
 55%|█████▌    | 83/150 [03:40<02:49,  2.53s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:01:16. Total running time: 2hr 6min 46s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 56%|█████▌    | 84/150 [03:42<02:40,  2.43s/it]

(train_sft_tune pid=55261) {'loss': 0.986, 'grad_norm': 0.9351544380187988, 'learning_rate': 8.935818231078417e-05, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:45<02:44,  2.53s/it]
 57%|█████▋    | 86/150 [03:47<02:32,  2.38s/it]
 58%|█████▊    | 87/150 [03:50<02:40,  2.55s/it]
 59%|█████▊    | 88/150 [03:52<02:43,  2.64s/it]
 59%|█████▉    | 89/150 [03:56<02:50,  2.79s/it]

(train_sft_tune pid=55261) {'loss': 0.9944, 'grad_norm': 0.8332004547119141, 'learning_rate': 8.258862304481567e-05, 'epoch': 0.14}

 60%|██████    | 90/150 [03:57<02:28,  2.48s/it]
 61%|██████    | 91/150 [03:59<02:17,  2.34s/it]
 61%|██████▏   | 92/150 [04:02<02:19,  2.40s/it]
 62%|██████▏   | 93/150 [04:04<02:18,  2.43s/it]
 63%|██████▎   | 94/150 [04:07<02:12,  2.36s/it]

(train_sft_tune pid=55261) {'loss': 0.7999, 'grad_norm': 0.6815103888511658, 'learning_rate': 7.581906377884717e-05, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:09<02:15,  2.46s/it]
 64%|██████▍   | 96/150 [04:11<02:08,  2.39s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:01:46. Total running time: 2hr 7min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 65%|██████▍   | 97/150 [04:14<02:15,  2.55s/it]
 65%|██████▌   | 98/150 [04:17<02:17,  2.65s/it]
 66%|██████▌   | 99/150 [04:20<02:22,  2.79s/it]

(train_sft_tune pid=55261) {'loss': 0.8923, 'grad_norm': 0.743851900100708, 'learning_rate': 6.904950451287867e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:22<02:06,  2.53s/it]
 67%|██████▋   | 101/150 [04:25<02:00,  2.45s/it]
 68%|██████▊   | 102/150 [04:27<01:53,  2.37s/it]
 69%|██████▊   | 103/150 [04:29<01:55,  2.47s/it]
 69%|██████▉   | 104/150 [04:32<01:55,  2.51s/it]

(train_sft_tune pid=55261) {'loss': 0.9217, 'grad_norm': 0.695155680179596, 'learning_rate': 6.227994524691018e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:35<01:52,  2.51s/it]
 71%|███████   | 106/150 [04:37<01:47,  2.44s/it]
 71%|███████▏  | 107/150 [04:40<01:50,  2.58s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:02:16. Total running time: 2hr 7min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 72%|███████▏  | 108/150 [04:43<01:55,  2.75s/it]
 73%|███████▎  | 109/150 [04:46<01:50,  2.70s/it]

(train_sft_tune pid=55261) {'loss': 0.8328, 'grad_norm': 0.8324121832847595, 'learning_rate': 5.551038598094168e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [04:47<01:39,  2.48s/it]
 74%|███████▍  | 111/150 [04:51<01:44,  2.69s/it]
 75%|███████▍  | 112/150 [04:54<01:46,  2.81s/it]
 75%|███████▌  | 113/150 [04:56<01:36,  2.62s/it]
 76%|███████▌  | 114/150 [04:59<01:36,  2.68s/it]

(train_sft_tune pid=55261) {'loss': 0.8577, 'grad_norm': 0.9073755145072937, 'learning_rate': 4.874082671497318e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:01<01:27,  2.50s/it]
 77%|███████▋  | 116/150 [05:03<01:24,  2.47s/it]
 78%|███████▊  | 117/150 [05:06<01:27,  2.66s/it]
 79%|███████▊  | 118/150 [05:09<01:28,  2.78s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:02:46. Total running time: 2hr 8min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 79%|███████▉  | 119/150 [05:12<01:26,  2.81s/it]

(train_sft_tune pid=55261) {'loss': 1.0728, 'grad_norm': 0.839188277721405, 'learning_rate': 4.197126744900469e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:14<01:18,  2.62s/it]
 81%|████████  | 121/150 [05:18<01:21,  2.80s/it]
 81%|████████▏ | 122/150 [05:21<01:21,  2.91s/it]
 82%|████████▏ | 123/150 [05:23<01:14,  2.77s/it]
 83%|████████▎ | 124/150 [05:26<01:15,  2.90s/it]

(train_sft_tune pid=55261) {'loss': 0.8481, 'grad_norm': 0.7452049255371094, 'learning_rate': 3.5201708183036184e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:29<01:09,  2.78s/it]
 84%|████████▍ | 126/150 [05:32<01:07,  2.80s/it]
 85%|████████▍ | 127/150 [05:35<01:04,  2.80s/it]
 85%|████████▌ | 128/150 [05:37<00:59,  2.69s/it]
 86%|████████▌ | 129/150 [05:39<00:49,  2.37s/it]

(train_sft_tune pid=55261) {'loss': 0.8451, 'grad_norm': 0.7526001930236816, 'learning_rate': 2.843214891706769e-05, 'epoch': 0.21}
Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:03:16. Total running time: 2hr 8min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 87%|████████▋ | 130/150 [05:41<00:49,  2.46s/it]
 87%|████████▋ | 131/150 [05:44<00:46,  2.45s/it]
 88%|████████▊ | 132/150 [05:47<00:46,  2.56s/it]
 89%|████████▊ | 133/150 [05:49<00:41,  2.42s/it]
 89%|████████▉ | 134/150 [05:52<00:44,  2.77s/it]

(train_sft_tune pid=55261) {'loss': 0.8741, 'grad_norm': 0.7760483026504517, 'learning_rate': 2.166258965109919e-05, 'epoch': 0.22}

 90%|█████████ | 135/150 [05:55<00:41,  2.74s/it]
 91%|█████████ | 136/150 [05:58<00:39,  2.83s/it]
 91%|█████████▏| 137/150 [06:00<00:33,  2.57s/it]
 92%|█████████▏| 138/150 [06:02<00:30,  2.55s/it]
 93%|█████████▎| 139/150 [06:05<00:27,  2.51s/it]

(train_sft_tune pid=55261) {'loss': 0.9465, 'grad_norm': 0.7568925619125366, 'learning_rate': 1.4893030385130694e-05, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:07<00:23,  2.40s/it]
 94%|█████████▍| 141/150 [06:10<00:22,  2.46s/it]

Trial status: 16 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:03:46. Total running time: 2hr 9min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_03394dc9   RUNNING      0.000196317    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 95%|█████████▍| 142/150 [06:12<00:20,  2.52s/it]
 95%|█████████▌| 143/150 [06:15<00:17,  2.57s/it]
 96%|█████████▌| 144/150 [06:18<00:16,  2.73s/it]

(train_sft_tune pid=55261) {'loss': 0.8768, 'grad_norm': 0.7815085649490356, 'learning_rate': 8.123471119162198e-06, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:20<00:13,  2.64s/it]
 97%|█████████▋| 146/150 [06:23<00:10,  2.58s/it]
 98%|█████████▊| 147/150 [06:25<00:07,  2.56s/it]
 99%|█████████▊| 148/150 [06:28<00:05,  2.62s/it]
 99%|█████████▉| 149/150 [06:31<00:02,  2.53s/it]

(train_sft_tune pid=55261) {'loss': 0.9341, 'grad_norm': 0.7367031574249268, 'learning_rate': 1.3539118531936995e-06, 'epoch': 0.24}

100%|██████████| 150/150 [06:33<00:00,  2.57s/it]

Trial train_sft_tune_03394dc9 completed after 1 iterations at 2025-11-29 18:04:09. Total running time: 2hr 9min 39s
+--------------------------------------------------+
| Trial train_sft_tune_03394dc9 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         440.069 |
| time_total_s                             440.069 |
| training_iteration                             1 |
| train_loss                               0.91104 |
+--------------------------------------------------+
(train_sft_tune pid=55261) {'train_runtime': 394.6366, 'train_samples_per_second': 3.041, 'train_steps_per_second': 0.38, 'train_loss': 0.9110364341735839, 'epoch': 0.24}
(train_sft_tune pid=55261) history of tuning  [{'loss': 1.0767, 'grad_norm': 1.001434564590454, 'learning_rate': 0.00015705377497046916, 'epoch': 0.008, 'step': 5}, {'loss': 0.9038, 'grad_norm': 0.7887026071548462, 'learning_rate': 0.00019090157130031163, 'epoch': 0.016, 'step': 10}, {'loss': 1.0017, 'grad_norm': 0.9322093725204468, 'learning_rate': 0.00018413201203434313, 'epoch': 0.024, 'step': 15}, {'loss': 0.9265, 'grad_norm': 1.101630449295044, 'learning_rate': 0.00017736245276837463, 'epoch': 0.032, 'step': 20}, {'loss': 0.8634, 'grad_norm': 0.7721512317657471, 'learning_rate': 0.00017059289350240613, 'epoch': 0.04, 'step': 25}, {'loss': 1.007, 'grad_norm': 0.7720519304275513, 'learning_rate': 0.00016382333423643763, 'epoch': 0.048, 'step': 30}, {'loss': 0.8954, 'grad_norm': 0.8438665270805359, 'learning_rate': 0.00015705377497046916, 'epoch': 0.056, 'step': 35}, {'loss': 0.7868, 'grad_norm': 0.8794001340866089, 'learning_rate': 0.00015028421570450063, 'epoch': 0.064, 'step': 40}, {'loss': 0.8955, 'grad_norm': 0.8511478304862976, 'learning_rate': 0.00014351465643853216, 'epoch': 0.072, 'step': 45}, {'loss': 0.9266, 'grad_norm': 0.7750667333602905, 'learning_rate': 0.00013674509717256364, 'epoch': 0.08, 'step': 50}, {'loss': 0.8124, 'grad_norm': 0.8506602048873901, 'learning_rate': 0.00012997553790659516, 'epoch': 0.088, 'step': 55}, {'loss': 0.9418, 'grad_norm': 0.9682239890098572, 'learning_rate': 0.00012320597864062666, 'epoch': 0.096, 'step': 60}, {'loss': 0.773, 'grad_norm': 0.7735145688056946, 'learning_rate': 0.00011643641937465815, 'epoch': 0.104, 'step': 65}, {'loss': 0.8929, 'grad_norm': 0.7298997640609741, 'learning_rate': 0.00010966686010868966, 'epoch': 0.112, 'step': 70}, {'loss': 0.9928, 'grad_norm': 0.7190122008323669, 'learning_rate': 0.00010289730084272118, 'epoch': 0.12, 'step': 75}, {'loss': 0.9523, 'grad_norm': 1.0524590015411377, 'learning_rate': 9.612774157675267e-05, 'epoch': 0.128, 'step': 80}, {'loss': 0.986, 'grad_norm': 0.9351544380187988, 'learning_rate': 8.935818231078417e-05, 'epoch': 0.136, 'step': 85}, {'loss': 0.9944, 'grad_norm': 0.8332004547119141, 'learning_rate': 8.258862304481567e-05, 'epoch': 0.144, 'step': 90}, {'loss': 0.7999, 'grad_norm': 0.6815103888511658, 'learning_rate': 7.581906377884717e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8923, 'grad_norm': 0.743851900100708, 'learning_rate': 6.904950451287867e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9217, 'grad_norm': 0.695155680179596, 'learning_rate': 6.227994524691018e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8328, 'grad_norm': 0.8324121832847595, 'learning_rate': 5.551038598094168e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8577, 'grad_norm': 0.9073755145072937, 'learning_rate': 4.874082671497318e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0728, 'grad_norm': 0.839188277721405, 'learning_rate': 4.197126744900469e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8481, 'grad_norm': 0.7452049255371094, 'learning_rate': 3.5201708183036184e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8451, 'grad_norm': 0.7526001930236816, 'learning_rate': 2.843214891706769e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8741, 'grad_norm': 0.7760483026504517, 'learning_rate': 2.166258965109919e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9465, 'grad_norm': 0.7568925619125366, 'learning_rate': 1.4893030385130694e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8768, 'grad_norm': 0.7815085649490356, 'learning_rate': 8.123471119162198e-06, 'epoch': 0.232, 'step': 145}, {'loss': 0.9341, 'grad_norm': 0.7367031574249268, 'learning_rate': 1.3539118531936995e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 394.6366, 'train_samples_per_second': 3.041, 'train_steps_per_second': 0.38, 'total_flos': 4888333847519232.0, 'train_loss': 0.9110364341735839, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=55261) Reporting loss: 0.9110364341735839

100%|██████████| 150/150 [06:34<00:00,  2.63s/it]

Trial status: 17 TERMINATED | 1 PENDING
Current time: 2025-11-29 18:04:16. Total running time: 2hr 9min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   PENDING      0.000257423    16             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

Trial train_sft_tune_d3cd79f6 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_d3cd79f6 config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00026 |
| r                                             16 |
+--------------------------------------------------+
(train_sft_tune pid=57239) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=57239) 2025-11-29 18:04:22.958803: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=57239) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=57239) E0000 00:00:1764439462.983040   57301 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=57239) E0000 00:00:1764439462.990195   57301 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=57239) W0000 00:00:1764439463.009639   57301 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=57239) W0000 00:00:1764439463.009691   57301 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=57239) W0000 00:00:1764439463.009698   57301 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=57239) W0000 00:00:1764439463.009702   57301 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=57239) 🦥 Unsloth Zoo will now patch everything to make training faster!
(train_sft_tune pid=57239) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=57239)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=57239) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=57239) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=57239)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=57239) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:04:46. Total running time: 2hr 10min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=57239) [2025-11-29 18:04:47,329 E 57239 57281] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=57239) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=57239) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=57239) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=57239)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=57239) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=57239) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=57239)  "-____-"     Trainable parameters = 11,272,192 of 1,247,086,592 (0.90% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=57239) Unsloth: Will smartly offload gradients to save VRAM!

  1%|          | 1/150 [00:12<30:15, 12.18s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:05:16. Total running time: 2hr 10min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|▏         | 2/150 [00:14<15:23,  6.24s/it]
  2%|▏         | 3/150 [00:17<11:25,  4.66s/it]
  3%|▎         | 4/150 [00:19<09:24,  3.87s/it]
  3%|▎         | 5/150 [00:21<07:43,  3.20s/it]

(train_sft_tune pid=57239) {'loss': 1.074, 'grad_norm': 0.9973900318145752, 'learning_rate': 0.0002059381882514176, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:09,  2.98s/it]
  5%|▍         | 7/150 [00:26<06:50,  2.87s/it]
  5%|▌         | 8/150 [00:29<06:38,  2.80s/it]
  6%|▌         | 9/150 [00:32<06:25,  2.73s/it]
  7%|▋         | 10/150 [00:34<06:16,  2.69s/it]

(train_sft_tune pid=57239) {'loss': 0.8988, 'grad_norm': 0.8355251550674438, 'learning_rate': 0.0002503214184780162, 'epoch': 0.02}

  7%|▋         | 11/150 [00:37<06:19,  2.73s/it]
  8%|▊         | 12/150 [00:39<05:58,  2.60s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:05:46. Total running time: 2hr 11min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  9%|▊         | 13/150 [00:42<06:14,  2.73s/it]
  9%|▉         | 14/150 [00:45<05:50,  2.58s/it]
 10%|█         | 15/150 [00:46<05:17,  2.35s/it]

(train_sft_tune pid=57239) {'loss': 0.999, 'grad_norm': 0.9168313145637512, 'learning_rate': 0.00024144477243269647, 'epoch': 0.02}

 11%|█         | 16/150 [00:49<05:27,  2.45s/it]
 11%|█▏        | 17/150 [00:52<05:49,  2.63s/it]
 12%|█▏        | 18/150 [00:54<05:18,  2.41s/it]
 13%|█▎        | 19/150 [00:57<05:22,  2.46s/it]
 13%|█▎        | 20/150 [00:58<04:42,  2.18s/it]

(train_sft_tune pid=57239) {'loss': 0.926, 'grad_norm': 1.120644450187683, 'learning_rate': 0.00023256812638737675, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:00<04:35,  2.14s/it]
 15%|█▍        | 22/150 [01:02<04:38,  2.17s/it]
 15%|█▌        | 23/150 [01:05<04:44,  2.24s/it]
 16%|█▌        | 24/150 [01:08<04:58,  2.37s/it]
 17%|█▋        | 25/150 [01:10<05:01,  2.41s/it]

(train_sft_tune pid=57239) {'loss': 0.8619, 'grad_norm': 0.7861015200614929, 'learning_rate': 0.00022369148034205702, 'epoch': 0.04}
Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:06:16. Total running time: 2hr 11min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 17%|█▋        | 26/150 [01:13<05:24,  2.61s/it]
 18%|█▊        | 27/150 [01:15<05:07,  2.50s/it]
 19%|█▊        | 28/150 [01:18<05:16,  2.59s/it]
 19%|█▉        | 29/150 [01:20<04:46,  2.37s/it]
 20%|██        | 30/150 [01:23<05:23,  2.70s/it]

(train_sft_tune pid=57239) {'loss': 1.0061, 'grad_norm': 0.7436686158180237, 'learning_rate': 0.0002148148342967373, 'epoch': 0.05}

 21%|██        | 31/150 [01:26<05:28,  2.76s/it]
 21%|██▏       | 32/150 [01:28<05:01,  2.55s/it]
 22%|██▏       | 33/150 [01:32<05:17,  2.71s/it]
 23%|██▎       | 34/150 [01:34<05:06,  2.64s/it]
 23%|██▎       | 35/150 [01:36<04:44,  2.48s/it]

(train_sft_tune pid=57239) {'loss': 0.8937, 'grad_norm': 0.8448885679244995, 'learning_rate': 0.0002059381882514176, 'epoch': 0.06}

 24%|██▍       | 36/150 [01:38<04:37,  2.43s/it]
 25%|██▍       | 37/150 [01:41<04:41,  2.49s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:06:47. Total running time: 2hr 12min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 25%|██▌       | 38/150 [01:43<04:32,  2.44s/it]
 26%|██▌       | 39/150 [01:46<04:40,  2.53s/it]
 27%|██▋       | 40/150 [01:49<04:40,  2.55s/it]

(train_sft_tune pid=57239) {'loss': 0.7852, 'grad_norm': 0.9131698608398438, 'learning_rate': 0.00019706154220609784, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:51<04:39,  2.57s/it]
 28%|██▊       | 42/150 [01:54<04:41,  2.61s/it]
 29%|██▊       | 43/150 [01:56<04:17,  2.40s/it]
 29%|██▉       | 44/150 [01:59<04:22,  2.47s/it]
 30%|███       | 45/150 [02:00<04:02,  2.31s/it]

(train_sft_tune pid=57239) {'loss': 0.8963, 'grad_norm': 0.851144552230835, 'learning_rate': 0.00018818489616077814, 'epoch': 0.07}

 31%|███       | 46/150 [02:03<04:15,  2.45s/it]
 31%|███▏      | 47/150 [02:06<04:26,  2.59s/it]
 32%|███▏      | 48/150 [02:09<04:38,  2.73s/it]
 33%|███▎      | 49/150 [02:11<04:18,  2.56s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:07:17. Total running time: 2hr 12min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 33%|███▎      | 50/150 [02:15<04:31,  2.72s/it]

(train_sft_tune pid=57239) {'loss': 0.9262, 'grad_norm': 0.7357345819473267, 'learning_rate': 0.00017930825011545839, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:18<04:52,  2.96s/it]
 35%|███▍      | 52/150 [02:21<04:38,  2.84s/it]
 35%|███▌      | 53/150 [02:23<04:32,  2.81s/it]
 36%|███▌      | 54/150 [02:26<04:26,  2.77s/it]
 37%|███▋      | 55/150 [02:28<04:05,  2.58s/it]

(train_sft_tune pid=57239) {'loss': 0.8136, 'grad_norm': 0.8583413362503052, 'learning_rate': 0.00017043160407013869, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:31<04:13,  2.70s/it]
 38%|███▊      | 57/150 [02:33<03:53,  2.51s/it]
 39%|███▊      | 58/150 [02:36<03:59,  2.60s/it]
 39%|███▉      | 59/150 [02:39<04:03,  2.68s/it]
 40%|████      | 60/150 [02:41<03:57,  2.64s/it]

(train_sft_tune pid=57239) {'loss': 0.941, 'grad_norm': 0.9538723826408386, 'learning_rate': 0.00016155495802481896, 'epoch': 0.1}
Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:07:47. Total running time: 2hr 13min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 41%|████      | 61/150 [02:44<04:05,  2.76s/it]
 41%|████▏     | 62/150 [02:48<04:31,  3.08s/it]
 42%|████▏     | 63/150 [02:52<04:33,  3.14s/it]
 43%|████▎     | 64/150 [02:55<04:42,  3.28s/it]
 43%|████▎     | 65/150 [02:57<04:11,  2.96s/it]

(train_sft_tune pid=57239) {'loss': 0.7718, 'grad_norm': 0.7776494026184082, 'learning_rate': 0.00015267831197949923, 'epoch': 0.1}

 44%|████▍     | 66/150 [03:00<04:09,  2.97s/it]
 45%|████▍     | 67/150 [03:03<03:48,  2.75s/it]
 45%|████▌     | 68/150 [03:05<03:30,  2.56s/it]
 46%|████▌     | 69/150 [03:07<03:14,  2.40s/it]
 47%|████▋     | 70/150 [03:10<03:32,  2.66s/it]

(train_sft_tune pid=57239) {'loss': 0.893, 'grad_norm': 0.7211959362030029, 'learning_rate': 0.0001438016659341795, 'epoch': 0.11}
Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:08:17. Total running time: 2hr 13min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 47%|████▋     | 71/150 [03:13<03:42,  2.82s/it]
 48%|████▊     | 72/150 [03:16<03:28,  2.67s/it]
 49%|████▊     | 73/150 [03:18<03:29,  2.72s/it]
 49%|████▉     | 74/150 [03:21<03:20,  2.64s/it]
 50%|█████     | 75/150 [03:24<03:20,  2.67s/it]

(train_sft_tune pid=57239) {'loss': 0.9927, 'grad_norm': 0.6945906281471252, 'learning_rate': 0.0001349250198888598, 'epoch': 0.12}

 51%|█████     | 76/150 [03:26<03:17,  2.66s/it]
 51%|█████▏    | 77/150 [03:29<03:11,  2.63s/it]
 52%|█████▏    | 78/150 [03:31<02:56,  2.45s/it]
 53%|█████▎    | 79/150 [03:33<02:49,  2.39s/it]
 53%|█████▎    | 80/150 [03:36<02:53,  2.48s/it]

(train_sft_tune pid=57239) {'loss': 0.9528, 'grad_norm': 1.067307472229004, 'learning_rate': 0.00012604837384354005, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:38<02:56,  2.55s/it]
 55%|█████▍    | 82/150 [03:41<02:57,  2.60s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:08:47. Total running time: 2hr 14min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 55%|█████▌    | 83/150 [03:44<02:49,  2.53s/it]
 56%|█████▌    | 84/150 [03:46<02:40,  2.43s/it]
 57%|█████▋    | 85/150 [03:49<02:46,  2.56s/it]

(train_sft_tune pid=57239) {'loss': 0.9854, 'grad_norm': 0.920030415058136, 'learning_rate': 0.00011717172779822035, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:51<02:34,  2.41s/it]
 58%|█████▊    | 87/150 [03:54<02:43,  2.60s/it]
 59%|█████▊    | 88/150 [03:57<02:45,  2.67s/it]
 59%|█████▉    | 89/150 [04:00<02:53,  2.84s/it]
 60%|██████    | 90/150 [04:02<02:34,  2.57s/it]

(train_sft_tune pid=57239) {'loss': 0.9946, 'grad_norm': 0.8487441539764404, 'learning_rate': 0.00010829508175290062, 'epoch': 0.14}

 61%|██████    | 91/150 [04:04<02:21,  2.41s/it]
 61%|██████▏   | 92/150 [04:06<02:22,  2.46s/it]
 62%|██████▏   | 93/150 [04:09<02:20,  2.47s/it]
 63%|██████▎   | 94/150 [04:11<02:13,  2.38s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:09:17. Total running time: 2hr 14min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 63%|██████▎   | 95/150 [04:14<02:18,  2.52s/it]

(train_sft_tune pid=57239) {'loss': 0.801, 'grad_norm': 0.6696354746818542, 'learning_rate': 9.94184357075809e-05, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:16<02:12,  2.46s/it]
 65%|██████▍   | 97/150 [04:19<02:18,  2.62s/it]
 65%|██████▌   | 98/150 [04:22<02:21,  2.72s/it]
 66%|██████▌   | 99/150 [04:25<02:25,  2.86s/it]
 67%|██████▋   | 100/150 [04:27<02:10,  2.62s/it]

(train_sft_tune pid=57239) {'loss': 0.8929, 'grad_norm': 0.7248489260673523, 'learning_rate': 9.054178966226117e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:30<02:03,  2.53s/it]
 68%|██████▊   | 102/150 [04:32<01:56,  2.43s/it]
 69%|██████▊   | 103/150 [04:35<01:57,  2.51s/it]
 69%|██████▉   | 104/150 [04:37<01:58,  2.57s/it]
 70%|███████   | 105/150 [04:40<01:55,  2.57s/it]

(train_sft_tune pid=57239) {'loss': 0.9216, 'grad_norm': 0.6878664493560791, 'learning_rate': 8.166514361694146e-05, 'epoch': 0.17}

 71%|███████   | 106/150 [04:42<01:49,  2.50s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:09:47. Total running time: 2hr 15min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 71%|███████▏  | 107/150 [04:45<01:53,  2.64s/it]
 72%|███████▏  | 108/150 [04:48<01:57,  2.79s/it]
 73%|███████▎  | 109/150 [04:51<01:52,  2.74s/it]
 73%|███████▎  | 110/150 [04:53<01:41,  2.53s/it]

(train_sft_tune pid=57239) {'loss': 0.8325, 'grad_norm': 0.8215689063072205, 'learning_rate': 7.278849757162173e-05, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:56<01:46,  2.74s/it]
 75%|███████▍  | 112/150 [04:59<01:47,  2.84s/it]
 75%|███████▌  | 113/150 [05:01<01:36,  2.60s/it]
 76%|███████▌  | 114/150 [05:04<01:36,  2.69s/it]
 77%|███████▋  | 115/150 [05:06<01:29,  2.56s/it]

(train_sft_tune pid=57239) {'loss': 0.856, 'grad_norm': 0.9012001752853394, 'learning_rate': 6.3911851526302e-05, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:09<01:25,  2.50s/it]
 78%|███████▊  | 117/150 [05:12<01:28,  2.68s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:10:17. Total running time: 2hr 15min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 79%|███████▊  | 118/150 [05:15<01:29,  2.78s/it]
 79%|███████▉  | 119/150 [05:18<01:27,  2.83s/it]
 80%|████████  | 120/150 [05:20<01:19,  2.64s/it]

(train_sft_tune pid=57239) {'loss': 1.0726, 'grad_norm': 0.8472265601158142, 'learning_rate': 5.5035205480982284e-05, 'epoch': 0.19}

 81%|████████  | 121/150 [05:23<01:21,  2.82s/it]
 81%|████████▏ | 122/150 [05:26<01:21,  2.90s/it]
 82%|████████▏ | 123/150 [05:29<01:15,  2.78s/it]
 83%|████████▎ | 124/150 [05:32<01:15,  2.91s/it]
 83%|████████▎ | 125/150 [05:35<01:09,  2.79s/it]

(train_sft_tune pid=57239) {'loss': 0.8483, 'grad_norm': 0.7413655519485474, 'learning_rate': 4.615855943566256e-05, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:38<01:07,  2.81s/it]
 85%|████████▍ | 127/150 [05:40<01:04,  2.79s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:10:47. Total running time: 2hr 16min 17s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 85%|████████▌ | 128/150 [05:43<00:59,  2.71s/it]
 86%|████████▌ | 129/150 [05:44<00:50,  2.41s/it]
 87%|████████▋ | 130/150 [05:47<00:49,  2.49s/it]

(train_sft_tune pid=57239) {'loss': 0.844, 'grad_norm': 0.7596032619476318, 'learning_rate': 3.7281913390342843e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:50<00:46,  2.47s/it]
 88%|████████▊ | 132/150 [05:52<00:46,  2.56s/it]
 89%|████████▊ | 133/150 [05:54<00:41,  2.43s/it]
 89%|████████▉ | 134/150 [05:58<00:44,  2.79s/it]
 90%|█████████ | 135/150 [06:01<00:41,  2.76s/it]

(train_sft_tune pid=57239) {'loss': 0.8739, 'grad_norm': 0.7664045691490173, 'learning_rate': 2.8405267345023113e-05, 'epoch': 0.22}

 91%|█████████ | 136/150 [06:04<00:39,  2.83s/it]
 91%|█████████▏| 137/150 [06:06<00:33,  2.55s/it]
 92%|█████████▏| 138/150 [06:08<00:30,  2.56s/it]
 93%|█████████▎| 139/150 [06:11<00:27,  2.53s/it]

Trial status: 17 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:11:17. Total running time: 2hr 16min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 9d59f08d with train_loss=0.9106097141901652 and params={'lr': 0.00019078187856269867, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_d3cd79f6   RUNNING      0.000257423    16             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=57239) {'loss': 0.946, 'grad_norm': 0.7552558779716492, 'learning_rate': 1.952862129970339e-05, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:13<00:24,  2.41s/it]
 94%|█████████▍| 141/150 [06:15<00:22,  2.47s/it]
 95%|█████████▍| 142/150 [06:18<00:20,  2.51s/it]
 95%|█████████▌| 143/150 [06:21<00:18,  2.58s/it]
 96%|█████████▌| 144/150 [06:24<00:16,  2.75s/it]
 97%|█████████▋| 145/150 [06:26<00:13,  2.65s/it]

(train_sft_tune pid=57239) {'loss': 0.8766, 'grad_norm': 0.7898035645484924, 'learning_rate': 1.0651975254383668e-05, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:29<00:10,  2.56s/it]
 98%|█████████▊| 147/150 [06:31<00:07,  2.55s/it]
 99%|█████████▊| 148/150 [06:34<00:05,  2.64s/it]
 99%|█████████▉| 149/150 [06:36<00:02,  2.55s/it]
100%|██████████| 150/150 [06:39<00:00,  2.58s/it]

(train_sft_tune pid=57239) {'loss': 0.933, 'grad_norm': 0.7347177267074585, 'learning_rate': 1.7753292090639446e-06, 'epoch': 0.24}

Trial train_sft_tune_d3cd79f6 completed after 1 iterations at 2025-11-29 18:11:44. Total running time: 2hr 17min 15s
+--------------------------------------------------+
| Trial train_sft_tune_d3cd79f6 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                          446.26 |
| time_total_s                              446.26 |
| training_iteration                             1 |
| train_loss                               0.91035 |
+--------------------------------------------------+
(train_sft_tune pid=57239) {'train_runtime': 400.4739, 'train_samples_per_second': 2.996, 'train_steps_per_second': 0.375, 'train_loss': 0.9103546333312988, 'epoch': 0.24}
(train_sft_tune pid=57239) history of tuning  [{'loss': 1.074, 'grad_norm': 0.9973900318145752, 'learning_rate': 0.0002059381882514176, 'epoch': 0.008, 'step': 5}, {'loss': 0.8988, 'grad_norm': 0.8355251550674438, 'learning_rate': 0.0002503214184780162, 'epoch': 0.016, 'step': 10}, {'loss': 0.999, 'grad_norm': 0.9168313145637512, 'learning_rate': 0.00024144477243269647, 'epoch': 0.024, 'step': 15}, {'loss': 0.926, 'grad_norm': 1.120644450187683, 'learning_rate': 0.00023256812638737675, 'epoch': 0.032, 'step': 20}, {'loss': 0.8619, 'grad_norm': 0.7861015200614929, 'learning_rate': 0.00022369148034205702, 'epoch': 0.04, 'step': 25}, {'loss': 1.0061, 'grad_norm': 0.7436686158180237, 'learning_rate': 0.0002148148342967373, 'epoch': 0.048, 'step': 30}, {'loss': 0.8937, 'grad_norm': 0.8448885679244995, 'learning_rate': 0.0002059381882514176, 'epoch': 0.056, 'step': 35}, {'loss': 0.7852, 'grad_norm': 0.9131698608398438, 'learning_rate': 0.00019706154220609784, 'epoch': 0.064, 'step': 40}, {'loss': 0.8963, 'grad_norm': 0.851144552230835, 'learning_rate': 0.00018818489616077814, 'epoch': 0.072, 'step': 45}, {'loss': 0.9262, 'grad_norm': 0.7357345819473267, 'learning_rate': 0.00017930825011545839, 'epoch': 0.08, 'step': 50}, {'loss': 0.8136, 'grad_norm': 0.8583413362503052, 'learning_rate': 0.00017043160407013869, 'epoch': 0.088, 'step': 55}, {'loss': 0.941, 'grad_norm': 0.9538723826408386, 'learning_rate': 0.00016155495802481896, 'epoch': 0.096, 'step': 60}, {'loss': 0.7718, 'grad_norm': 0.7776494026184082, 'learning_rate': 0.00015267831197949923, 'epoch': 0.104, 'step': 65}, {'loss': 0.893, 'grad_norm': 0.7211959362030029, 'learning_rate': 0.0001438016659341795, 'epoch': 0.112, 'step': 70}, {'loss': 0.9927, 'grad_norm': 0.6945906281471252, 'learning_rate': 0.0001349250198888598, 'epoch': 0.12, 'step': 75}, {'loss': 0.9528, 'grad_norm': 1.067307472229004, 'learning_rate': 0.00012604837384354005, 'epoch': 0.128, 'step': 80}, {'loss': 0.9854, 'grad_norm': 0.920030415058136, 'learning_rate': 0.00011717172779822035, 'epoch': 0.136, 'step': 85}, {'loss': 0.9946, 'grad_norm': 0.8487441539764404, 'learning_rate': 0.00010829508175290062, 'epoch': 0.144, 'step': 90}, {'loss': 0.801, 'grad_norm': 0.6696354746818542, 'learning_rate': 9.94184357075809e-05, 'epoch': 0.152, 'step': 95}, {'loss': 0.8929, 'grad_norm': 0.7248489260673523, 'learning_rate': 9.054178966226117e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9216, 'grad_norm': 0.6878664493560791, 'learning_rate': 8.166514361694146e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8325, 'grad_norm': 0.8215689063072205, 'learning_rate': 7.278849757162173e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.856, 'grad_norm': 0.9012001752853394, 'learning_rate': 6.3911851526302e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.0726, 'grad_norm': 0.8472265601158142, 'learning_rate': 5.5035205480982284e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8483, 'grad_norm': 0.7413655519485474, 'learning_rate': 4.615855943566256e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.844, 'grad_norm': 0.7596032619476318, 'learning_rate': 3.7281913390342843e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8739, 'grad_norm': 0.7664045691490173, 'learning_rate': 2.8405267345023113e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.946, 'grad_norm': 0.7552558779716492, 'learning_rate': 1.952862129970339e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8766, 'grad_norm': 0.7898035645484924, 'learning_rate': 1.0651975254383668e-05, 'epoch': 0.232, 'step': 145}, {'loss': 0.933, 'grad_norm': 0.7347177267074585, 'learning_rate': 1.7753292090639446e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 400.4739, 'train_samples_per_second': 2.996, 'train_steps_per_second': 0.375, 'total_flos': 4888333847519232.0, 'train_loss': 0.9103546333312988, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=57239) Reporting loss: 0.9103546333312988

100%|██████████| 150/150 [06:40<00:00,  2.67s/it]

Trial status: 18 TERMINATED | 1 PENDING
Current time: 2025-11-29 18:11:47. Total running time: 2hr 17min 17s
Logical resource usage: 0/2 CPUs, 0/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   PENDING      0.00027346     32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

Trial train_sft_tune_1c4d1a57 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_1c4d1a57 config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00027 |
| r                                             32 |
+--------------------------------------------------+
(train_sft_tune pid=59248) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=59248) 2025-11-29 18:11:59.637645: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=59248) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=59248) E0000 00:00:1764439919.664709   59308 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=59248) E0000 00:00:1764439919.671420   59308 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=59248) W0000 00:00:1764439919.688813   59308 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=59248) W0000 00:00:1764439919.688845   59308 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=59248) W0000 00:00:1764439919.688848   59308 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=59248) W0000 00:00:1764439919.688849   59308 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=59248) 🦥 Unsloth Zoo will now patch everything to make training faster!

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:12:17. Total running time: 2hr 17min 47s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=59248) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=59248)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=59248) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=59248) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=59248)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=59248) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=59248) [2025-11-29 18:12:24,027 E 59248 59289] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=59248) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=59248) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=59248) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=59248)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=59248) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=59248) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=59248)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=59248) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:12:47. Total running time: 2hr 18min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:12<32:02, 12.90s/it]
  1%|▏         | 2/150 [00:15<16:09,  6.55s/it]
  2%|▏         | 3/150 [00:17<11:50,  4.83s/it]
  3%|▎         | 4/150 [00:20<09:35,  3.94s/it]
  3%|▎         | 5/150 [00:22<07:49,  3.24s/it]

(train_sft_tune pid=59248) {'loss': 1.0734, 'grad_norm': 0.712337851524353, 'learning_rate': 0.00021876823093564774, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:07,  2.97s/it]
  5%|▍         | 7/150 [00:27<06:45,  2.83s/it]
  5%|▌         | 8/150 [00:29<06:30,  2.75s/it]
  6%|▌         | 9/150 [00:32<06:15,  2.66s/it]
  7%|▋         | 10/150 [00:34<06:06,  2.62s/it]

(train_sft_tune pid=59248) {'loss': 0.898, 'grad_norm': 0.5964944958686829, 'learning_rate': 0.0002659165565683304, 'epoch': 0.02}
Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:13:17. Total running time: 2hr 18min 48s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

  7%|▋         | 11/150 [00:37<06:08,  2.65s/it]
  8%|▊         | 12/150 [00:39<05:49,  2.53s/it]
  9%|▊         | 13/150 [00:42<06:06,  2.68s/it]
  9%|▉         | 14/150 [00:45<05:44,  2.53s/it]
 10%|█         | 15/150 [00:46<05:11,  2.31s/it]

(train_sft_tune pid=59248) {'loss': 0.9992, 'grad_norm': 0.6559410691261292, 'learning_rate': 0.0002564868914417939, 'epoch': 0.02}

 11%|█         | 16/150 [00:49<05:22,  2.40s/it]
 11%|█▏        | 17/150 [00:52<05:45,  2.60s/it]
 12%|█▏        | 18/150 [00:54<05:17,  2.41s/it]
 13%|█▎        | 19/150 [00:57<05:23,  2.47s/it]
 13%|█▎        | 20/150 [00:58<04:43,  2.18s/it]

(train_sft_tune pid=59248) {'loss': 0.9264, 'grad_norm': 0.800760805606842, 'learning_rate': 0.00024705722631525735, 'epoch': 0.03}

 14%|█▍        | 21/150 [01:00<04:36,  2.15s/it]
 15%|█▍        | 22/150 [01:02<04:36,  2.16s/it]
 15%|█▌        | 23/150 [01:05<04:44,  2.24s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:13:47. Total running time: 2hr 19min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 16%|█▌        | 24/150 [01:08<05:02,  2.40s/it]
 17%|█▋        | 25/150 [01:10<05:05,  2.45s/it]

(train_sft_tune pid=59248) {'loss': 0.8618, 'grad_norm': 0.5607792139053345, 'learning_rate': 0.0002376275611887208, 'epoch': 0.04}

 17%|█▋        | 26/150 [01:13<05:29,  2.66s/it]
 18%|█▊        | 27/150 [01:15<05:08,  2.51s/it]
 19%|█▊        | 28/150 [01:18<05:21,  2.64s/it]
 19%|█▉        | 29/150 [01:20<04:53,  2.43s/it]
 20%|██        | 30/150 [01:24<05:32,  2.77s/it]

(train_sft_tune pid=59248) {'loss': 1.0052, 'grad_norm': 0.5227808356285095, 'learning_rate': 0.00022819789606218427, 'epoch': 0.05}

 21%|██        | 31/150 [01:27<05:36,  2.83s/it]
 21%|██▏       | 32/150 [01:29<05:04,  2.58s/it]
 22%|██▏       | 33/150 [01:32<05:22,  2.76s/it]
 23%|██▎       | 34/150 [01:35<05:11,  2.69s/it]
 23%|██▎       | 35/150 [01:37<04:49,  2.52s/it]

(train_sft_tune pid=59248) {'loss': 0.8914, 'grad_norm': 0.600588321685791, 'learning_rate': 0.00021876823093564774, 'epoch': 0.06}
Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:14:17. Total running time: 2hr 19min 48s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 24%|██▍       | 36/150 [01:39<04:42,  2.48s/it]
 25%|██▍       | 37/150 [01:42<04:45,  2.52s/it]
 25%|██▌       | 38/150 [01:44<04:41,  2.51s/it]
 26%|██▌       | 39/150 [01:47<04:48,  2.60s/it]
 27%|██▋       | 40/150 [01:50<04:45,  2.60s/it]

(train_sft_tune pid=59248) {'loss': 0.7841, 'grad_norm': 0.6622087955474854, 'learning_rate': 0.00020933856580911117, 'epoch': 0.06}

 27%|██▋       | 41/150 [01:52<04:43,  2.60s/it]
 28%|██▊       | 42/150 [01:55<04:44,  2.63s/it]
 29%|██▊       | 43/150 [01:57<04:25,  2.49s/it]
 29%|██▉       | 44/150 [02:00<04:29,  2.55s/it]
 30%|███       | 45/150 [02:02<04:08,  2.37s/it]

(train_sft_tune pid=59248) {'loss': 0.8951, 'grad_norm': 0.6146034002304077, 'learning_rate': 0.00019990890068257466, 'epoch': 0.07}

 31%|███       | 46/150 [02:05<04:20,  2.51s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:14:47. Total running time: 2hr 20min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 31%|███▏      | 47/150 [02:07<04:30,  2.62s/it]
 32%|███▏      | 48/150 [02:11<04:42,  2.76s/it]
 33%|███▎      | 49/150 [02:13<04:20,  2.58s/it]
 33%|███▎      | 50/150 [02:16<04:33,  2.73s/it]

(train_sft_tune pid=59248) {'loss': 0.925, 'grad_norm': 0.5271040201187134, 'learning_rate': 0.0001904792355560381, 'epoch': 0.08}

 34%|███▍      | 51/150 [02:19<04:52,  2.95s/it]
 35%|███▍      | 52/150 [02:22<04:36,  2.82s/it]
 35%|███▌      | 53/150 [02:24<04:28,  2.77s/it]
 36%|███▌      | 54/150 [02:27<04:18,  2.70s/it]
 37%|███▋      | 55/150 [02:29<03:57,  2.50s/it]

(train_sft_tune pid=59248) {'loss': 0.8125, 'grad_norm': 0.6387473940849304, 'learning_rate': 0.00018104957042950156, 'epoch': 0.09}

 37%|███▋      | 56/150 [02:32<04:00,  2.56s/it]
 38%|███▊      | 57/150 [02:34<03:40,  2.37s/it]
 39%|███▊      | 58/150 [02:36<03:45,  2.45s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:15:17. Total running time: 2hr 20min 48s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 39%|███▉      | 59/150 [02:39<03:47,  2.50s/it]
 40%|████      | 60/150 [02:41<03:41,  2.46s/it]

(train_sft_tune pid=59248) {'loss': 0.9406, 'grad_norm': 0.6769661903381348, 'learning_rate': 0.00017161990530296505, 'epoch': 0.1}

 41%|████      | 61/150 [02:44<03:47,  2.55s/it]
 41%|████▏     | 62/150 [02:48<04:12,  2.87s/it]
 42%|████▏     | 63/150 [02:51<04:16,  2.94s/it]
 43%|████▎     | 64/150 [02:54<04:24,  3.08s/it]
 43%|████▎     | 65/150 [02:56<03:55,  2.77s/it]

(train_sft_tune pid=59248) {'loss': 0.7702, 'grad_norm': 0.5625646114349365, 'learning_rate': 0.00016219024017642849, 'epoch': 0.1}

 44%|████▍     | 66/150 [02:59<03:56,  2.81s/it]
 45%|████▍     | 67/150 [03:01<03:39,  2.65s/it]
 45%|████▌     | 68/150 [03:03<03:22,  2.47s/it]
 46%|████▌     | 69/150 [03:05<03:07,  2.31s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:15:47. Total running time: 2hr 21min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 47%|████▋     | 70/150 [03:09<03:26,  2.58s/it]

(train_sft_tune pid=59248) {'loss': 0.8904, 'grad_norm': 0.5119406580924988, 'learning_rate': 0.00015276057504989195, 'epoch': 0.11}

 47%|████▋     | 71/150 [03:12<03:36,  2.75s/it]
 48%|████▊     | 72/150 [03:14<03:25,  2.64s/it]
 49%|████▊     | 73/150 [03:17<03:26,  2.68s/it]
 49%|████▉     | 74/150 [03:19<03:16,  2.59s/it]
 50%|█████     | 75/150 [03:22<03:16,  2.62s/it]

(train_sft_tune pid=59248) {'loss': 0.9896, 'grad_norm': 0.4926659166812897, 'learning_rate': 0.0001433309099233554, 'epoch': 0.12}

 51%|█████     | 76/150 [03:25<03:14,  2.63s/it]
 51%|█████▏    | 77/150 [03:27<03:10,  2.61s/it]
 52%|█████▏    | 78/150 [03:29<02:55,  2.44s/it]
 53%|█████▎    | 79/150 [03:31<02:48,  2.37s/it]
 53%|█████▎    | 80/150 [03:34<02:50,  2.43s/it]

(train_sft_tune pid=59248) {'loss': 0.9518, 'grad_norm': 0.736748456954956, 'learning_rate': 0.00013390124479681887, 'epoch': 0.13}

 54%|█████▍    | 81/150 [03:37<02:53,  2.52s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:16:18. Total running time: 2hr 21min 48s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 55%|█████▍    | 82/150 [03:39<02:56,  2.60s/it]
 55%|█████▌    | 83/150 [03:42<02:48,  2.52s/it]
 56%|█████▌    | 84/150 [03:44<02:39,  2.42s/it]
 57%|█████▋    | 85/150 [03:47<02:44,  2.53s/it]

(train_sft_tune pid=59248) {'loss': 0.9859, 'grad_norm': 0.6533635854721069, 'learning_rate': 0.00012447157967028234, 'epoch': 0.14}

 57%|█████▋    | 86/150 [03:49<02:32,  2.39s/it]
 58%|█████▊    | 87/150 [03:52<02:42,  2.58s/it]
 59%|█████▊    | 88/150 [03:55<02:43,  2.64s/it]
 59%|█████▉    | 89/150 [03:58<02:50,  2.80s/it]
 60%|██████    | 90/150 [04:00<02:29,  2.49s/it]

(train_sft_tune pid=59248) {'loss': 0.9935, 'grad_norm': 0.6293796896934509, 'learning_rate': 0.00011504191454374579, 'epoch': 0.14}

 61%|██████    | 91/150 [04:02<02:18,  2.35s/it]
 61%|██████▏   | 92/150 [04:04<02:21,  2.44s/it]
 62%|██████▏   | 93/150 [04:07<02:19,  2.45s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:16:48. Total running time: 2hr 22min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 63%|██████▎   | 94/150 [04:09<02:12,  2.36s/it]
 63%|██████▎   | 95/150 [04:12<02:16,  2.48s/it]

(train_sft_tune pid=59248) {'loss': 0.7992, 'grad_norm': 0.4747442305088043, 'learning_rate': 0.00010561224941720925, 'epoch': 0.15}

 64%|██████▍   | 96/150 [04:14<02:09,  2.40s/it]
 65%|██████▍   | 97/150 [04:17<02:16,  2.57s/it]
 65%|██████▌   | 98/150 [04:20<02:19,  2.68s/it]
 66%|██████▌   | 99/150 [04:23<02:23,  2.82s/it]
 67%|██████▋   | 100/150 [04:25<02:07,  2.55s/it]

(train_sft_tune pid=59248) {'loss': 0.8936, 'grad_norm': 0.5158261060714722, 'learning_rate': 9.618258429067271e-05, 'epoch': 0.16}

 67%|██████▋   | 101/150 [04:27<02:02,  2.49s/it]
 68%|██████▊   | 102/150 [04:29<01:56,  2.44s/it]
 69%|██████▊   | 103/150 [04:32<01:57,  2.51s/it]
 69%|██████▉   | 104/150 [04:35<01:57,  2.55s/it]
 70%|███████   | 105/150 [04:37<01:54,  2.54s/it]

(train_sft_tune pid=59248) {'loss': 0.9209, 'grad_norm': 0.48453769087791443, 'learning_rate': 8.675291916413617e-05, 'epoch': 0.17}
Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:17:18. Total running time: 2hr 22min 48s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 71%|███████   | 106/150 [04:40<01:49,  2.48s/it]
 71%|███████▏  | 107/150 [04:43<01:53,  2.64s/it]
 72%|███████▏  | 108/150 [04:46<01:57,  2.80s/it]
 73%|███████▎  | 109/150 [04:48<01:52,  2.74s/it]
 73%|███████▎  | 110/150 [04:50<01:40,  2.51s/it]

(train_sft_tune pid=59248) {'loss': 0.8323, 'grad_norm': 0.5854776501655579, 'learning_rate': 7.732325403759964e-05, 'epoch': 0.18}

 74%|███████▍  | 111/150 [04:54<01:46,  2.73s/it]
 75%|███████▍  | 112/150 [04:57<01:48,  2.85s/it]
 75%|███████▌  | 113/150 [04:59<01:36,  2.61s/it]
 76%|███████▌  | 114/150 [05:02<01:36,  2.69s/it]
 77%|███████▋  | 115/150 [05:04<01:27,  2.50s/it]

(train_sft_tune pid=59248) {'loss': 0.8563, 'grad_norm': 0.6317325234413147, 'learning_rate': 6.789358891106309e-05, 'epoch': 0.18}

 77%|███████▋  | 116/150 [05:06<01:24,  2.49s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:17:48. Total running time: 2hr 23min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 78%|███████▊  | 117/150 [05:09<01:28,  2.70s/it]
 79%|███████▊  | 118/150 [05:12<01:29,  2.80s/it]
 79%|███████▉  | 119/150 [05:15<01:27,  2.83s/it]
 80%|████████  | 120/150 [05:18<01:19,  2.65s/it]

(train_sft_tune pid=59248) {'loss': 1.07, 'grad_norm': 0.5824708342552185, 'learning_rate': 5.8463923784526555e-05, 'epoch': 0.19}

 81%|████████  | 121/150 [05:21<01:22,  2.83s/it]
 81%|████████▏ | 122/150 [05:24<01:21,  2.92s/it]
 82%|████████▏ | 123/150 [05:26<01:15,  2.78s/it]
 83%|████████▎ | 124/150 [05:30<01:15,  2.92s/it]
 83%|████████▎ | 125/150 [05:32<01:10,  2.81s/it]

(train_sft_tune pid=59248) {'loss': 0.8451, 'grad_norm': 0.5188380479812622, 'learning_rate': 4.903425865799001e-05, 'epoch': 0.2}

 84%|████████▍ | 126/150 [05:35<01:08,  2.84s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:18:18. Total running time: 2hr 23min 48s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 85%|████████▍ | 127/150 [05:38<01:04,  2.82s/it]
 85%|████████▌ | 128/150 [05:40<00:59,  2.72s/it]
 86%|████████▌ | 129/150 [05:42<00:50,  2.39s/it]
 87%|████████▋ | 130/150 [05:45<00:49,  2.50s/it]

(train_sft_tune pid=59248) {'loss': 0.8445, 'grad_norm': 0.5404607653617859, 'learning_rate': 3.960459353145347e-05, 'epoch': 0.21}

 87%|████████▋ | 131/150 [05:47<00:47,  2.49s/it]
 88%|████████▊ | 132/150 [05:50<00:46,  2.58s/it]
 89%|████████▊ | 133/150 [05:52<00:41,  2.43s/it]
 89%|████████▉ | 134/150 [05:56<00:44,  2.79s/it]
 90%|█████████ | 135/150 [05:59<00:41,  2.78s/it]

(train_sft_tune pid=59248) {'loss': 0.8721, 'grad_norm': 0.5428161025047302, 'learning_rate': 3.017492840491693e-05, 'epoch': 0.22}

 91%|█████████ | 136/150 [06:02<00:40,  2.86s/it]
 91%|█████████▏| 137/150 [06:03<00:33,  2.57s/it]
 92%|█████████▏| 138/150 [06:06<00:30,  2.57s/it]

Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:18:48. Total running time: 2hr 24min 18s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

 93%|█████████▎| 139/150 [06:08<00:27,  2.53s/it]
 93%|█████████▎| 140/150 [06:11<00:24,  2.44s/it]

(train_sft_tune pid=59248) {'loss': 0.9426, 'grad_norm': 0.5381970405578613, 'learning_rate': 2.074526327838039e-05, 'epoch': 0.22}

 94%|█████████▍| 141/150 [06:13<00:22,  2.49s/it]
 95%|█████████▍| 142/150 [06:16<00:20,  2.53s/it]
 95%|█████████▌| 143/150 [06:19<00:18,  2.59s/it]
 96%|█████████▌| 144/150 [06:22<00:16,  2.76s/it]
 97%|█████████▋| 145/150 [06:24<00:13,  2.69s/it]

(train_sft_tune pid=59248) {'loss': 0.8746, 'grad_norm': 0.565272331237793, 'learning_rate': 1.1315598151843848e-05, 'epoch': 0.23}

 97%|█████████▋| 146/150 [06:27<00:10,  2.60s/it]
 98%|█████████▊| 147/150 [06:29<00:07,  2.58s/it]
 99%|█████████▊| 148/150 [06:32<00:05,  2.63s/it]
 99%|█████████▉| 149/150 [06:34<00:02,  2.55s/it]
100%|██████████| 150/150 [06:37<00:00,  2.60s/it]

(train_sft_tune pid=59248) {'loss': 0.9321, 'grad_norm': 0.5273623466491699, 'learning_rate': 1.885933025307308e-06, 'epoch': 0.24}
Trial status: 18 TERMINATED | 1 RUNNING | 1 PENDING
Current time: 2025-11-29 18:19:18. Total running time: 2hr 24min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: d3cd79f6 with train_loss=0.9103546333312988 and params={'lr': 0.00025742273531427197, 'r': 16, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_1c4d1a57   RUNNING      0.00027346     32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_abe18d76   PENDING      0.000283148    32             64                                            |
+--------------------------------------------------------------------------------------------------------------------+

Trial train_sft_tune_1c4d1a57 completed after 1 iterations at 2025-11-29 18:19:18. Total running time: 2hr 24min 49s
+--------------------------------------------------+
| Trial train_sft_tune_1c4d1a57 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         443.531 |
| time_total_s                             443.531 |
| training_iteration                             1 |
| train_loss                               0.90925 |
+--------------------------------------------------+
(train_sft_tune pid=59248) {'train_runtime': 398.587, 'train_samples_per_second': 3.011, 'train_steps_per_second': 0.376, 'train_loss': 0.9092532189687094, 'epoch': 0.24}
(train_sft_tune pid=59248) history of tuning  [{'loss': 1.0734, 'grad_norm': 0.712337851524353, 'learning_rate': 0.00021876823093564774, 'epoch': 0.008, 'step': 5}, {'loss': 0.898, 'grad_norm': 0.5964944958686829, 'learning_rate': 0.0002659165565683304, 'epoch': 0.016, 'step': 10}, {'loss': 0.9992, 'grad_norm': 0.6559410691261292, 'learning_rate': 0.0002564868914417939, 'epoch': 0.024, 'step': 15}, {'loss': 0.9264, 'grad_norm': 0.800760805606842, 'learning_rate': 0.00024705722631525735, 'epoch': 0.032, 'step': 20}, {'loss': 0.8618, 'grad_norm': 0.5607792139053345, 'learning_rate': 0.0002376275611887208, 'epoch': 0.04, 'step': 25}, {'loss': 1.0052, 'grad_norm': 0.5227808356285095, 'learning_rate': 0.00022819789606218427, 'epoch': 0.048, 'step': 30}, {'loss': 0.8914, 'grad_norm': 0.600588321685791, 'learning_rate': 0.00021876823093564774, 'epoch': 0.056, 'step': 35}, {'loss': 0.7841, 'grad_norm': 0.6622087955474854, 'learning_rate': 0.00020933856580911117, 'epoch': 0.064, 'step': 40}, {'loss': 0.8951, 'grad_norm': 0.6146034002304077, 'learning_rate': 0.00019990890068257466, 'epoch': 0.072, 'step': 45}, {'loss': 0.925, 'grad_norm': 0.5271040201187134, 'learning_rate': 0.0001904792355560381, 'epoch': 0.08, 'step': 50}, {'loss': 0.8125, 'grad_norm': 0.6387473940849304, 'learning_rate': 0.00018104957042950156, 'epoch': 0.088, 'step': 55}, {'loss': 0.9406, 'grad_norm': 0.6769661903381348, 'learning_rate': 0.00017161990530296505, 'epoch': 0.096, 'step': 60}, {'loss': 0.7702, 'grad_norm': 0.5625646114349365, 'learning_rate': 0.00016219024017642849, 'epoch': 0.104, 'step': 65}, {'loss': 0.8904, 'grad_norm': 0.5119406580924988, 'learning_rate': 0.00015276057504989195, 'epoch': 0.112, 'step': 70}, {'loss': 0.9896, 'grad_norm': 0.4926659166812897, 'learning_rate': 0.0001433309099233554, 'epoch': 0.12, 'step': 75}, {'loss': 0.9518, 'grad_norm': 0.736748456954956, 'learning_rate': 0.00013390124479681887, 'epoch': 0.128, 'step': 80}, {'loss': 0.9859, 'grad_norm': 0.6533635854721069, 'learning_rate': 0.00012447157967028234, 'epoch': 0.136, 'step': 85}, {'loss': 0.9935, 'grad_norm': 0.6293796896934509, 'learning_rate': 0.00011504191454374579, 'epoch': 0.144, 'step': 90}, {'loss': 0.7992, 'grad_norm': 0.4747442305088043, 'learning_rate': 0.00010561224941720925, 'epoch': 0.152, 'step': 95}, {'loss': 0.8936, 'grad_norm': 0.5158261060714722, 'learning_rate': 9.618258429067271e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.9209, 'grad_norm': 0.48453769087791443, 'learning_rate': 8.675291916413617e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8323, 'grad_norm': 0.5854776501655579, 'learning_rate': 7.732325403759964e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8563, 'grad_norm': 0.6317325234413147, 'learning_rate': 6.789358891106309e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.07, 'grad_norm': 0.5824708342552185, 'learning_rate': 5.8463923784526555e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8451, 'grad_norm': 0.5188380479812622, 'learning_rate': 4.903425865799001e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8445, 'grad_norm': 0.5404607653617859, 'learning_rate': 3.960459353145347e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8721, 'grad_norm': 0.5428161025047302, 'learning_rate': 3.017492840491693e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9426, 'grad_norm': 0.5381970405578613, 'learning_rate': 2.074526327838039e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8746, 'grad_norm': 0.565272331237793, 'learning_rate': 1.1315598151843848e-05, 'epoch': 0.232, 'step': 145}, {'loss': 0.9321, 'grad_norm': 0.5273623466491699, 'learning_rate': 1.885933025307308e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 398.587, 'train_samples_per_second': 3.011, 'train_steps_per_second': 0.376, 'total_flos': 4944308261511168.0, 'train_loss': 0.9092532189687094, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=59248) Reporting loss: 0.9092532189687094

100%|██████████| 150/150 [06:38<00:00,  2.66s/it]

Trial train_sft_tune_abe18d76 started with configuration:
+--------------------------------------------------+
| Trial train_sft_tune_abe18d76 config             |
+--------------------------------------------------+
| lora_alpha                                    64 |
| lr                                       0.00028 |
| r                                             32 |
+--------------------------------------------------+
(train_sft_tune pid=61238) 🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.

(train_sft_tune pid=61238) 2025-11-29 18:19:32.538808: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
(train_sft_tune pid=61238) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(train_sft_tune pid=61238) E0000 00:00:1764440372.561911   61297 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(train_sft_tune pid=61238) E0000 00:00:1764440372.572832   61297 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(train_sft_tune pid=61238) W0000 00:00:1764440372.597931   61297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=61238) W0000 00:00:1764440372.597960   61297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=61238) W0000 00:00:1764440372.597962   61297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(train_sft_tune pid=61238) W0000 00:00:1764440372.597964   61297 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.

(train_sft_tune pid=61238) 🦥 Unsloth Zoo will now patch everything to make training faster!

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:19:48. Total running time: 2hr 25min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=61238) ==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.2.
(train_sft_tune pid=61238)    \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
(train_sft_tune pid=61238) O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
(train_sft_tune pid=61238) \        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
(train_sft_tune pid=61238)  "-____-"     Free license: http://github.com/unslothai/unsloth
(train_sft_tune pid=61238) Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

(train_sft_tune pid=61238) [2025-11-29 18:19:56,197 E 61238 61279] core_worker_process.cc:837: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(train_sft_tune pid=61238) Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.
(train_sft_tune pid=61238) The model is already on multiple devices. Skipping the move to device specified in `args`.
(train_sft_tune pid=61238) ==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
(train_sft_tune pid=61238)    \\   /|    Num examples = 5,000 | Num Epochs = 1 | Total steps = 150
(train_sft_tune pid=61238) O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
(train_sft_tune pid=61238) \        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
(train_sft_tune pid=61238)  "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)
  0%|          | 0/150 [00:00<?, ?it/s]

(train_sft_tune pid=61238) Unsloth: Will smartly offload gradients to save VRAM!
Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:20:18. Total running time: 2hr 25min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

  1%|          | 1/150 [00:13<32:20, 13.02s/it]
  1%|▏         | 2/150 [00:15<16:11,  6.57s/it]
  2%|▏         | 3/150 [00:17<11:48,  4.82s/it]
  3%|▎         | 4/150 [00:20<09:36,  3.95s/it]
  3%|▎         | 5/150 [00:22<07:53,  3.27s/it]
  3%|▎         | 5/150 [00:22<07:53,  3.27s/it]

(train_sft_tune pid=61238) {'loss': 1.0731, 'grad_norm': 0.7151323556900024, 'learning_rate': 0.00022651825452063817, 'epoch': 0.01}

  4%|▍         | 6/150 [00:24<07:09,  2.99s/it]
  5%|▍         | 7/150 [00:27<06:43,  2.82s/it]
  5%|▌         | 8/150 [00:29<06:28,  2.74s/it]
  6%|▌         | 9/150 [00:32<06:16,  2.67s/it]

(train_sft_tune pid=61238) {'loss': 0.8974, 'grad_norm': 0.5996041297912598, 'learning_rate': 0.00027533684385698255, 'epoch': 0.02}

  7%|▋         | 10/150 [00:35<06:07,  2.63s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:20:48. Total running time: 2hr 26min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

  7%|▋         | 11/150 [00:37<06:09,  2.66s/it]
  8%|▊         | 12/150 [00:39<05:48,  2.52s/it]
  9%|▊         | 13/150 [00:42<06:05,  2.67s/it]
  9%|▉         | 14/150 [00:45<05:46,  2.55s/it]
 10%|█         | 15/150 [00:47<05:18,  2.36s/it]
 10%|█         | 15/150 [00:47<05:18,  2.36s/it]

(train_sft_tune pid=61238) {'loss': 0.999, 'grad_norm': 0.660984456539154, 'learning_rate': 0.0002655731259897137, 'epoch': 0.02}

 11%|█         | 16/150 [00:49<05:27,  2.44s/it]
 11%|█▏        | 17/150 [00:52<05:48,  2.62s/it]
 12%|█▏        | 18/150 [00:54<05:17,  2.40s/it]
 13%|█▎        | 19/150 [00:57<05:25,  2.48s/it]

(train_sft_tune pid=61238) {'loss': 0.9264, 'grad_norm': 0.805461585521698, 'learning_rate': 0.0002558094081224448, 'epoch': 0.03}

 13%|█▎        | 20/150 [00:59<04:51,  2.24s/it]
 14%|█▍        | 21/150 [01:01<04:46,  2.22s/it]
 15%|█▍        | 22/150 [01:03<04:42,  2.21s/it]
 15%|█▌        | 23/150 [01:05<04:47,  2.26s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:21:18. Total running time: 2hr 26min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 16%|█▌        | 24/150 [01:08<05:03,  2.41s/it]

(train_sft_tune pid=61238) {'loss': 0.862, 'grad_norm': 0.561738133430481, 'learning_rate': 0.0002460456902551759, 'epoch': 0.04}

 17%|█▋        | 25/150 [01:11<05:08,  2.47s/it]
 17%|█▋        | 26/150 [01:14<05:32,  2.68s/it]
 18%|█▊        | 27/150 [01:16<05:10,  2.52s/it]
 19%|█▊        | 28/150 [01:19<05:19,  2.62s/it]
 19%|█▉        | 29/150 [01:21<04:50,  2.40s/it]

(train_sft_tune pid=61238) {'loss': 1.005, 'grad_norm': 0.5221573114395142, 'learning_rate': 0.00023628197238790703, 'epoch': 0.05}

 20%|██        | 30/150 [01:24<05:31,  2.76s/it]
 21%|██        | 31/150 [01:27<05:35,  2.82s/it]
 21%|██▏       | 32/150 [01:29<05:03,  2.57s/it]
 22%|██▏       | 33/150 [01:32<05:21,  2.75s/it]
 23%|██▎       | 34/150 [01:35<05:11,  2.68s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:21:48. Total running time: 2hr 27min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=61238) {'loss': 0.8913, 'grad_norm': 0.6027233600616455, 'learning_rate': 0.00022651825452063817, 'epoch': 0.06}

 23%|██▎       | 35/150 [01:37<04:55,  2.57s/it]
 24%|██▍       | 36/150 [01:40<04:47,  2.52s/it]
 25%|██▍       | 37/150 [01:42<04:46,  2.54s/it]
 25%|██▌       | 38/150 [01:45<04:36,  2.46s/it]
 26%|██▌       | 39/150 [01:47<04:44,  2.56s/it]

(train_sft_tune pid=61238) {'loss': 0.784, 'grad_norm': 0.6632370948791504, 'learning_rate': 0.00021675453665336925, 'epoch': 0.06}

 27%|██▋       | 40/150 [01:50<04:44,  2.59s/it]
 27%|██▋       | 41/150 [01:53<04:43,  2.60s/it]
 28%|██▊       | 42/150 [01:55<04:42,  2.61s/it]
 29%|██▊       | 43/150 [01:57<04:17,  2.41s/it]
 29%|██▉       | 44/150 [02:00<04:22,  2.48s/it]

(train_sft_tune pid=61238) {'loss': 0.8951, 'grad_norm': 0.6128838658332825, 'learning_rate': 0.00020699081878610038, 'epoch': 0.07}

 30%|███       | 45/150 [02:02<04:05,  2.34s/it]
 31%|███       | 46/150 [02:05<04:19,  2.49s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:22:18. Total running time: 2hr 27min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 31%|███▏      | 47/150 [02:08<04:28,  2.60s/it]
 32%|███▏      | 48/150 [02:11<04:39,  2.74s/it]
 33%|███▎      | 49/150 [02:13<04:18,  2.56s/it]

(train_sft_tune pid=61238) {'loss': 0.9253, 'grad_norm': 0.5263161659240723, 'learning_rate': 0.00019722710091883147, 'epoch': 0.08}

 33%|███▎      | 50/150 [02:16<04:32,  2.72s/it]
 34%|███▍      | 51/150 [02:19<04:51,  2.94s/it]
 35%|███▍      | 52/150 [02:22<04:34,  2.81s/it]
 35%|███▌      | 53/150 [02:24<04:26,  2.75s/it]
 36%|███▌      | 54/150 [02:27<04:18,  2.69s/it]

(train_sft_tune pid=61238) {'loss': 0.8126, 'grad_norm': 0.6400496959686279, 'learning_rate': 0.0001874633830515626, 'epoch': 0.09}

 37%|███▋      | 55/150 [02:29<03:57,  2.50s/it]
 37%|███▋      | 56/150 [02:32<04:01,  2.57s/it]
 38%|███▊      | 57/150 [02:34<03:39,  2.36s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:22:48. Total running time: 2hr 28min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 39%|███▊      | 58/150 [02:36<03:44,  2.44s/it]
 39%|███▉      | 59/150 [02:39<03:47,  2.50s/it]

(train_sft_tune pid=61238) {'loss': 0.9408, 'grad_norm': 0.676042377948761, 'learning_rate': 0.00017769966518429374, 'epoch': 0.1}

 40%|████      | 60/150 [02:41<03:43,  2.49s/it]
 41%|████      | 61/150 [02:44<03:49,  2.58s/it]
 41%|████▏     | 62/150 [02:48<04:13,  2.88s/it]
 42%|████▏     | 63/150 [02:51<04:16,  2.95s/it]
 43%|████▎     | 64/150 [02:54<04:24,  3.08s/it]

(train_sft_tune pid=61238) {'loss': 0.7704, 'grad_norm': 0.5662220120429993, 'learning_rate': 0.00016793594731702482, 'epoch': 0.1}

 43%|████▎     | 65/150 [02:56<03:56,  2.78s/it]
 44%|████▍     | 66/150 [02:59<03:55,  2.81s/it]
 45%|████▍     | 67/150 [03:01<03:37,  2.62s/it]
 45%|████▌     | 68/150 [03:03<03:20,  2.45s/it]
 46%|████▌     | 69/150 [03:05<03:07,  2.32s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:23:18. Total running time: 2hr 28min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=61238) {'loss': 0.8906, 'grad_norm': 0.5121301412582397, 'learning_rate': 0.00015817222944975595, 'epoch': 0.11}

 47%|████▋     | 70/150 [03:09<03:26,  2.58s/it]
 47%|████▋     | 71/150 [03:12<03:36,  2.74s/it]
 48%|████▊     | 72/150 [03:14<03:23,  2.61s/it]
 49%|████▊     | 73/150 [03:17<03:25,  2.67s/it]
 49%|████▉     | 74/150 [03:19<03:19,  2.63s/it]

(train_sft_tune pid=61238) {'loss': 0.9896, 'grad_norm': 0.4921525716781616, 'learning_rate': 0.00014840851158248709, 'epoch': 0.12}

 50%|█████     | 75/150 [03:22<03:18,  2.64s/it]
 51%|█████     | 76/150 [03:25<03:14,  2.63s/it]
 51%|█████▏    | 77/150 [03:27<03:09,  2.60s/it]
 52%|█████▏    | 78/150 [03:29<02:54,  2.43s/it]
 53%|█████▎    | 79/150 [03:31<02:49,  2.38s/it]

(train_sft_tune pid=61238) {'loss': 0.9521, 'grad_norm': 0.7406879663467407, 'learning_rate': 0.00013864479371521817, 'epoch': 0.13}

 53%|█████▎    | 80/150 [03:34<02:52,  2.46s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:23:48. Total running time: 2hr 29min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 54%|█████▍    | 81/150 [03:37<02:55,  2.54s/it]
 55%|█████▍    | 82/150 [03:40<02:56,  2.59s/it]
 55%|█████▌    | 83/150 [03:42<02:48,  2.52s/it]
 56%|█████▌    | 84/150 [03:44<02:42,  2.46s/it]

(train_sft_tune pid=61238) {'loss': 0.9861, 'grad_norm': 0.6523405313491821, 'learning_rate': 0.0001288810758479493, 'epoch': 0.14}

 57%|█████▋    | 85/150 [03:47<02:48,  2.59s/it]
 57%|█████▋    | 86/150 [03:49<02:35,  2.42s/it]
 58%|█████▊    | 87/150 [03:52<02:43,  2.59s/it]
 59%|█████▊    | 88/150 [03:55<02:45,  2.66s/it]
 59%|█████▉    | 89/150 [03:58<02:52,  2.83s/it]

(train_sft_tune pid=61238) {'loss': 0.9936, 'grad_norm': 0.6355248689651489, 'learning_rate': 0.00011911735798068041, 'epoch': 0.14}

 60%|██████    | 90/150 [04:00<02:30,  2.50s/it]
 61%|██████    | 91/150 [04:02<02:19,  2.36s/it]
 61%|██████▏   | 92/150 [04:05<02:20,  2.42s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:24:18. Total running time: 2hr 29min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 62%|██████▏   | 93/150 [04:07<02:18,  2.42s/it]
 63%|██████▎   | 94/150 [04:09<02:12,  2.36s/it]

(train_sft_tune pid=61238) {'loss': 0.7994, 'grad_norm': 0.47393959760665894, 'learning_rate': 0.00010935364011341152, 'epoch': 0.15}

 63%|██████▎   | 95/150 [04:12<02:16,  2.49s/it]
 64%|██████▍   | 96/150 [04:14<02:10,  2.41s/it]
 65%|██████▍   | 97/150 [04:17<02:16,  2.58s/it]
 65%|██████▌   | 98/150 [04:20<02:18,  2.67s/it]
 66%|██████▌   | 99/150 [04:23<02:23,  2.82s/it]

(train_sft_tune pid=61238) {'loss': 0.8938, 'grad_norm': 0.5157880187034607, 'learning_rate': 9.958992224614262e-05, 'epoch': 0.16}

 67%|██████▋   | 100/150 [04:25<02:07,  2.55s/it]
 67%|██████▋   | 101/150 [04:27<02:01,  2.48s/it]
 68%|██████▊   | 102/150 [04:30<01:54,  2.39s/it]
 69%|██████▊   | 103/150 [04:32<01:56,  2.48s/it]
 69%|██████▉   | 104/150 [04:35<01:57,  2.54s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:24:48. Total running time: 2hr 30min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=61238) {'loss': 0.921, 'grad_norm': 0.48527804017066956, 'learning_rate': 8.982620437887376e-05, 'epoch': 0.17}

 70%|███████   | 105/150 [04:38<01:54,  2.54s/it]
 71%|███████   | 106/150 [04:40<01:48,  2.47s/it]
 71%|███████▏  | 107/150 [04:43<01:52,  2.62s/it]
 72%|███████▏  | 108/150 [04:46<01:56,  2.78s/it]
 73%|███████▎  | 109/150 [04:49<01:52,  2.74s/it]

(train_sft_tune pid=61238) {'loss': 0.8324, 'grad_norm': 0.587901771068573, 'learning_rate': 8.006248651160487e-05, 'epoch': 0.18}

 73%|███████▎  | 110/150 [04:51<01:40,  2.50s/it]
 74%|███████▍  | 111/150 [04:54<01:46,  2.72s/it]
 75%|███████▍  | 112/150 [04:57<01:47,  2.83s/it]
 75%|███████▌  | 113/150 [04:59<01:36,  2.61s/it]
 76%|███████▌  | 114/150 [05:02<01:36,  2.69s/it]

(train_sft_tune pid=61238) {'loss': 0.8562, 'grad_norm': 0.6328353881835938, 'learning_rate': 7.029876864433598e-05, 'epoch': 0.18}

 77%|███████▋  | 115/150 [05:04<01:27,  2.51s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:25:18. Total running time: 2hr 30min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 77%|███████▋  | 116/150 [05:06<01:24,  2.47s/it]
 78%|███████▊  | 117/150 [05:09<01:27,  2.66s/it]
 79%|███████▊  | 118/150 [05:13<01:29,  2.79s/it]
 79%|███████▉  | 119/150 [05:15<01:27,  2.84s/it]

(train_sft_tune pid=61238) {'loss': 1.07, 'grad_norm': 0.5834261178970337, 'learning_rate': 6.0535050777067097e-05, 'epoch': 0.19}

 80%|████████  | 120/150 [05:18<01:19,  2.65s/it]
 81%|████████  | 121/150 [05:21<01:21,  2.83s/it]
 81%|████████▏ | 122/150 [05:24<01:21,  2.92s/it]
 82%|████████▏ | 123/150 [05:27<01:15,  2.80s/it]
 83%|████████▎ | 124/150 [05:30<01:16,  2.93s/it]

(train_sft_tune pid=61238) {'loss': 0.8452, 'grad_norm': 0.5193501114845276, 'learning_rate': 5.0771332909798204e-05, 'epoch': 0.2}

 83%|████████▎ | 125/150 [05:32<01:10,  2.81s/it]
 84%|████████▍ | 126/150 [05:35<01:07,  2.83s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:25:49. Total running time: 2hr 31min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 85%|████████▍ | 127/150 [05:38<01:04,  2.82s/it]
 85%|████████▌ | 128/150 [05:41<01:00,  2.75s/it]
 86%|████████▌ | 129/150 [05:42<00:50,  2.41s/it]

(train_sft_tune pid=61238) {'loss': 0.8445, 'grad_norm': 0.5420095324516296, 'learning_rate': 4.1007615042529326e-05, 'epoch': 0.21}

 87%|████████▋ | 130/150 [05:45<00:49,  2.49s/it]
 87%|████████▋ | 131/150 [05:47<00:46,  2.47s/it]
 88%|████████▊ | 132/150 [05:50<00:46,  2.57s/it]
 89%|████████▊ | 133/150 [05:52<00:41,  2.44s/it]
 89%|████████▉ | 134/150 [05:56<00:44,  2.79s/it]

(train_sft_tune pid=61238) {'loss': 0.8721, 'grad_norm': 0.5420523881912231, 'learning_rate': 3.1243897175260433e-05, 'epoch': 0.22}

 90%|█████████ | 135/150 [05:59<00:41,  2.77s/it]
 91%|█████████ | 136/150 [06:02<00:39,  2.84s/it]
 91%|█████████▏| 137/150 [06:04<00:33,  2.57s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:26:19. Total running time: 2hr 31min 49s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+

 92%|█████████▏| 138/150 [06:06<00:30,  2.58s/it]
 93%|█████████▎| 139/150 [06:09<00:27,  2.54s/it]

(train_sft_tune pid=61238) {'loss': 0.9427, 'grad_norm': 0.5391674637794495, 'learning_rate': 2.1480179307991548e-05, 'epoch': 0.22}

 93%|█████████▎| 140/150 [06:11<00:24,  2.42s/it]
 94%|█████████▍| 141/150 [06:13<00:22,  2.48s/it]
 95%|█████████▍| 142/150 [06:16<00:20,  2.54s/it]
 95%|█████████▌| 143/150 [06:19<00:18,  2.60s/it]
 96%|█████████▌| 144/150 [06:22<00:16,  2.77s/it]

(train_sft_tune pid=61238) {'loss': 0.8746, 'grad_norm': 0.5671724677085876, 'learning_rate': 1.1716461440722663e-05, 'epoch': 0.23}

 97%|█████████▋| 145/150 [06:24<00:13,  2.67s/it]
 97%|█████████▋| 146/150 [06:27<00:10,  2.60s/it]
 98%|█████████▊| 147/150 [06:29<00:07,  2.59s/it]
 99%|█████████▊| 148/150 [06:32<00:05,  2.67s/it]
 99%|█████████▉| 149/150 [06:35<00:02,  2.58s/it]

Trial status: 19 TERMINATED | 1 RUNNING
Current time: 2025-11-29 18:26:49. Total running time: 2hr 32min 19s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_abe18d76   RUNNING      0.000283148    32             64                                            |
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
+--------------------------------------------------------------------------------------------------------------------+
(train_sft_tune pid=61238) {'loss': 0.9321, 'grad_norm': 0.5292474627494812, 'learning_rate': 1.952743573453777e-06, 'epoch': 0.24}

100%|██████████| 150/150 [06:37<00:00,  2.61s/it]
2025-11-29 18:26:51,431	INFO tune.py:1009 -- Wrote the latest version of all result files and experiment state to '/root/ray_results/llama_lora_hpo' in 0.0135s.

Trial train_sft_tune_abe18d76 completed after 1 iterations at 2025-11-29 18:26:51. Total running time: 2hr 32min 21s
+--------------------------------------------------+
| Trial train_sft_tune_abe18d76 result             |
+--------------------------------------------------+
| checkpoint_dir_name                              |
| time_this_iter_s                         444.127 |
| time_total_s                             444.127 |
| training_iteration                             1 |
| train_loss                               0.90928 |
+--------------------------------------------------+

Trial status: 20 TERMINATED
Current time: 2025-11-29 18:26:51. Total running time: 2hr 32min 21s
Logical resource usage: 2.0/2 CPUs, 0.5/1 GPUs (0.0/1.0 accelerator_type:T4)
Current best trial: 1c4d1a57 with train_loss=0.9092532189687094 and params={'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
+--------------------------------------------------------------------------------------------------------------------+
| Trial name                status                lr     r     lora_alpha     iter     total time (s)     train_loss |
+--------------------------------------------------------------------------------------------------------------------+
| train_sft_tune_3e6a0a4a   TERMINATED   5.61848e-05    32             32        1            489.926       0.932573 |
| train_sft_tune_a367bbff   TERMINATED   2.02994e-05    32             16        1            470.899       0.969457 |
| train_sft_tune_1ee09412   TERMINATED   2.60244e-05    16             16        1            462.288       0.962189 |
| train_sft_tune_e9b87c19   TERMINATED   3.50943e-05     8             16        1            436.332       0.953403 |
| train_sft_tune_f628069f   TERMINATED   7.2761e-05     16             32        1            439.088       0.928065 |
| train_sft_tune_bad7439a   TERMINATED   0.0001356      32             64        1            446.411       0.913461 |
| train_sft_tune_6193e7f8   TERMINATED   1.4578e-05     16             64        1            454.236       0.951955 |
| train_sft_tune_df75121a   TERMINATED   4.54764e-05    16             32        1            438.256       0.936859 |
| train_sft_tune_ef9c592d   TERMINATED   1.26719e-05    16             64        1            436.884       0.95557  |
| train_sft_tune_f6d5bc07   TERMINATED   0.000158739    16             64        1            440.693       0.912382 |
| train_sft_tune_53da69d4   TERMINATED   0.000179674    32             16        1            444.349       0.920856 |
| train_sft_tune_d33d8ede   TERMINATED   0.000407619     8             64        1            436.761       0.918131 |
| train_sft_tune_5ba5374a   TERMINATED   0.0004791       8             64        1            435.813       0.922889 |
| train_sft_tune_eebd3616   TERMINATED   0.000125219    32             64        1            451.151       0.91428  |
| train_sft_tune_dab9ed39   TERMINATED   0.000126527    32             64        1            446.89        0.914174 |
| train_sft_tune_9d59f08d   TERMINATED   0.000190782    32             64        1            443.46        0.91061  |
| train_sft_tune_03394dc9   TERMINATED   0.000196317    16             64        1            440.069       0.911036 |
| train_sft_tune_d3cd79f6   TERMINATED   0.000257423    16             64        1            446.26        0.910355 |
| train_sft_tune_1c4d1a57   TERMINATED   0.00027346     32             64        1            443.531       0.909253 |
| train_sft_tune_abe18d76   TERMINATED   0.000283148    32             64        1            444.127       0.90928  |
+--------------------------------------------------------------------------------------------------------------------+

(train_sft_tune pid=61238) {'train_runtime': 398.7935, 'train_samples_per_second': 3.009, 'train_steps_per_second': 0.376, 'train_loss': 0.9092795387903849, 'epoch': 0.24}
(train_sft_tune pid=61238) history of tuning  [{'loss': 1.0731, 'grad_norm': 0.7151323556900024, 'learning_rate': 0.00022651825452063817, 'epoch': 0.008, 'step': 5}, {'loss': 0.8974, 'grad_norm': 0.5996041297912598, 'learning_rate': 0.00027533684385698255, 'epoch': 0.016, 'step': 10}, {'loss': 0.999, 'grad_norm': 0.660984456539154, 'learning_rate': 0.0002655731259897137, 'epoch': 0.024, 'step': 15}, {'loss': 0.9264, 'grad_norm': 0.805461585521698, 'learning_rate': 0.0002558094081224448, 'epoch': 0.032, 'step': 20}, {'loss': 0.862, 'grad_norm': 0.561738133430481, 'learning_rate': 0.0002460456902551759, 'epoch': 0.04, 'step': 25}, {'loss': 1.005, 'grad_norm': 0.5221573114395142, 'learning_rate': 0.00023628197238790703, 'epoch': 0.048, 'step': 30}, {'loss': 0.8913, 'grad_norm': 0.6027233600616455, 'learning_rate': 0.00022651825452063817, 'epoch': 0.056, 'step': 35}, {'loss': 0.784, 'grad_norm': 0.6632370948791504, 'learning_rate': 0.00021675453665336925, 'epoch': 0.064, 'step': 40}, {'loss': 0.8951, 'grad_norm': 0.6128838658332825, 'learning_rate': 0.00020699081878610038, 'epoch': 0.072, 'step': 45}, {'loss': 0.9253, 'grad_norm': 0.5263161659240723, 'learning_rate': 0.00019722710091883147, 'epoch': 0.08, 'step': 50}, {'loss': 0.8126, 'grad_norm': 0.6400496959686279, 'learning_rate': 0.0001874633830515626, 'epoch': 0.088, 'step': 55}, {'loss': 0.9408, 'grad_norm': 0.676042377948761, 'learning_rate': 0.00017769966518429374, 'epoch': 0.096, 'step': 60}, {'loss': 0.7704, 'grad_norm': 0.5662220120429993, 'learning_rate': 0.00016793594731702482, 'epoch': 0.104, 'step': 65}, {'loss': 0.8906, 'grad_norm': 0.5121301412582397, 'learning_rate': 0.00015817222944975595, 'epoch': 0.112, 'step': 70}, {'loss': 0.9896, 'grad_norm': 0.4921525716781616, 'learning_rate': 0.00014840851158248709, 'epoch': 0.12, 'step': 75}, {'loss': 0.9521, 'grad_norm': 0.7406879663467407, 'learning_rate': 0.00013864479371521817, 'epoch': 0.128, 'step': 80}, {'loss': 0.9861, 'grad_norm': 0.6523405313491821, 'learning_rate': 0.0001288810758479493, 'epoch': 0.136, 'step': 85}, {'loss': 0.9936, 'grad_norm': 0.6355248689651489, 'learning_rate': 0.00011911735798068041, 'epoch': 0.144, 'step': 90}, {'loss': 0.7994, 'grad_norm': 0.47393959760665894, 'learning_rate': 0.00010935364011341152, 'epoch': 0.152, 'step': 95}, {'loss': 0.8938, 'grad_norm': 0.5157880187034607, 'learning_rate': 9.958992224614262e-05, 'epoch': 0.16, 'step': 100}, {'loss': 0.921, 'grad_norm': 0.48527804017066956, 'learning_rate': 8.982620437887376e-05, 'epoch': 0.168, 'step': 105}, {'loss': 0.8324, 'grad_norm': 0.587901771068573, 'learning_rate': 8.006248651160487e-05, 'epoch': 0.176, 'step': 110}, {'loss': 0.8562, 'grad_norm': 0.6328353881835938, 'learning_rate': 7.029876864433598e-05, 'epoch': 0.184, 'step': 115}, {'loss': 1.07, 'grad_norm': 0.5834261178970337, 'learning_rate': 6.0535050777067097e-05, 'epoch': 0.192, 'step': 120}, {'loss': 0.8452, 'grad_norm': 0.5193501114845276, 'learning_rate': 5.0771332909798204e-05, 'epoch': 0.2, 'step': 125}, {'loss': 0.8445, 'grad_norm': 0.5420095324516296, 'learning_rate': 4.1007615042529326e-05, 'epoch': 0.208, 'step': 130}, {'loss': 0.8721, 'grad_norm': 0.5420523881912231, 'learning_rate': 3.1243897175260433e-05, 'epoch': 0.216, 'step': 135}, {'loss': 0.9427, 'grad_norm': 0.5391674637794495, 'learning_rate': 2.1480179307991548e-05, 'epoch': 0.224, 'step': 140}, {'loss': 0.8746, 'grad_norm': 0.5671724677085876, 'learning_rate': 1.1716461440722663e-05, 'epoch': 0.232, 'step': 145}, {'loss': 0.9321, 'grad_norm': 0.5292474627494812, 'learning_rate': 1.952743573453777e-06, 'epoch': 0.24, 'step': 150}, {'train_runtime': 398.7935, 'train_samples_per_second': 3.009, 'train_steps_per_second': 0.376, 'total_flos': 4944308261511168.0, 'train_loss': 0.9092795387903849, 'epoch': 0.24, 'step': 150}]
(train_sft_tune pid=61238) Reporting loss: 0.9092795387903849
Best config: {'lr': 0.00027346028866955967, 'r': 32, 'lora_alpha': 64}
Best train_loss: 0.9092532189687094

100%|██████████| 150/150 [06:38<00:00,  2.66s/it]

We now add LoRA adapters so we only need to update 1 to 10% of all parameters!

In [ ]:
model = FastLanguageModel.get_peft_model(
    model,
    r = 32, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                      "gate_proj", "up_proj", "down_proj",],
    lora_alpha = 64,
    lora_dropout = 0, # Supports any, but = 0 is optimized
    bias = "none",    # Supports any, but = "none" is optimized
    # [NEW] "unsloth" uses 30% less VRAM, fits 2x larger batch sizes!
    use_gradient_checkpointing = "unsloth", # True or "unsloth" for very long context
    random_state = 3407,
    use_rslora = False,  # We support rank stabilized LoRA
    loftq_config = None, # And LoftQ
)

Unsloth 2025.11.6 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

<a name="Data"></a>
### Data Prep
We now use the `Llama-3.1` format for conversation style finetunes. We use [Maxime Labonne's FineTome-100k](https://huggingface.co/datasets/mlabonne/FineTome-100k) dataset in ShareGPT style. But we convert it to HuggingFace's normal multiturn format `("role", "content")` instead of `("from", "value")`/ Llama-3 renders multi turn conversations like below:

```
<|begin_of_text|><|start_header_id|>user<|end_header_id|>

Hello!<|eot_id|><|start_header_id|>assistant<|end_header_id|>

Hey there! How are you?<|eot_id|><|start_header_id|>user<|end_header_id|>

I'm great thanks!<|eot_id|>
```

We use our `get_chat_template` function to get the correct chat template. We support `zephyr, chatml, mistral, llama, alpaca, vicuna, vicuna_old, phi3, llama3` and more.

We now use `standardize_sharegpt` to convert ShareGPT style datasets into HuggingFace's generic format. This changes the dataset from looking like:
```
{"from": "system", "value": "You are an assistant"}
{"from": "human", "value": "What is 2+2?"}
{"from": "gpt", "value": "It's 4."}
```
to
```
{"role": "system", "content": "You are an assistant"}
{"role": "user", "content": "What is 2+2?"}
{"role": "assistant", "content": "It's 4."}
```

We look at how the conversations are structured for item 5:

And we see how the chat template transformed these conversations.

**[Notice]** Llama 3.1 Instruct's default chat template default adds `"Cutting Knowledge Date: December 2023\nToday Date: 26 July 2024"`, so do not be alarmed!

In [ ]:
from trl import SFTTrainer
from transformers import TrainingArguments, DataCollatorForSeq2Seq
from unsloth import is_bfloat16_supported

trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    dataset_text_field = "text",
    max_seq_length = max_seq_length,
    data_collator = DataCollatorForSeq2Seq(tokenizer = tokenizer),
    dataset_num_proc = 2,
    packing = False, # Can make training 5x faster for short sequences.
    args = TrainingArguments(
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 4,
        warmup_steps = 5,
        #num_train_epochs = 2, # Set this for 1 full training run.
        max_steps = 2000,
        learning_rate = 2e-4,
        fp16 = not is_bfloat16_supported(),
        bf16 = is_bfloat16_supported(),
        logging_steps = 1,
        save_steps = 10,                  # <--- Save every 10 steps
        save_total_limit = 1,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        output_dir = "/content/drive/MyDrive/llm_training/outputs",
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=6):   0%|          | 0/20022 [00:00<?, ? examples/s]

<a name="Train"></a>
### Train the model
Now let's use Huggingface TRL's `SFTTrainer`! More docs here: [TRL SFT docs](https://huggingface.co/docs/trl/sft_trainer). We do 60 steps to speed things up, but you can set `num_train_epochs=1` for a full run, and turn off `max_steps=None`. We also support TRL's `DPOTrainer`!

We also use Unsloth's `train_on_completions` method to only train on the assistant outputs and ignore the loss on the user's inputs.

In [ ]:
from unsloth.chat_templates import train_on_responses_only
trainer = train_on_responses_only(
    trainer,
    instruction_part = "<|start_header_id|>user<|end_header_id|>\n\n",
    response_part = "<|start_header_id|>assistant<|end_header_id|>\n\n",
)

Map (num_proc=6):   0%|          | 0/20022 [00:00<?, ? examples/s]

In [ ]:
from transformers.trainer_utils import get_last_checkpoint

output_dir = "/content/drive/MyDrive/llm_training/outputs"
last_ckpt = get_last_checkpoint(output_dir)
print("Last checkpoint:", last_ckpt)

trainer.train(resume_from_checkpoint=last_ckpt)

The model is already on multiple devices. Skipping the move to device specified in `args`.

Last checkpoint: /content/drive/MyDrive/llm_training/outputs/checkpoint-5006

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 20,022 | Num Epochs = 2 | Total steps = 5,006
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

TrainOutput(global_step=5006, training_loss=0.0, metrics={'train_runtime': 0.0223, 'train_samples_per_second': 1796789.651, 'train_steps_per_second': 224621.142, 'total_flos': 3.4595987163439104e+16, 'train_loss': 0.0, 'epoch': 2.0})

We verify masking is actually done:

In [ ]:
tokenizer.decode(trainer.train_dataset[5]["input_ids"])

'<|begin_of_text|><|begin_of_text|><|start_header_id|>system<|end_header_id|>\n\nCutting Knowledge Date: December 2023\nToday Date: 26 July 2024\n\n<|eot_id|><|start_header_id|>user<|end_header_id|>\n\nHow do astronomers determine the original wavelength of light emitted by a celestial body at rest, which is necessary for measuring its speed using the Doppler effect?<|eot_id|><|start_header_id|>assistant<|end_header_id|>\n\nAstronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

In [ ]:
space = tokenizer(" ", add_special_tokens = False).input_ids[0]
tokenizer.decode([space if x == -100 else x for x in trainer.train_dataset[5]["labels"]])

'                                                                  Astronomers make use of the unique spectral fingerprints of elements found in stars. These elements emit and absorb light at specific, known wavelengths, forming an absorption spectrum. By analyzing the light received from distant stars and comparing it to the laboratory-measured spectra of these elements, astronomers can identify the shifts in these wavelengths due to the Doppler effect. The observed shift tells them the extent to which the light has been redshifted or blueshifted, thereby allowing them to calculate the speed of the star along the line of sight relative to Earth.<|eot_id|>'

We can see the System and Instruction prompts are successfully masked!

In [ ]:
# checkpoint_path = "/content/drive/MyDrive/model_checkpoints/checkpoint-200"
trainer_stats = trainer.train(resume_from_checkpoint=False)

The model is already on multiple devices. Skipping the move to device specified in `args`.
==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 20,022 | Num Epochs = 1 | Total steps = 2,000
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 4
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 4 x 1) = 8
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

Unsloth: Will smartly offload gradients to save VRAM!

 You can also use a `TextStreamer` for continuous inference - so you can see the generation token by token, instead of waiting the whole time!

<a name="Save"></a>
### Saving, loading finetuned models
To save the final model as LoRA adapters, either use Huggingface's `push_to_hub` for an online save or `save_pretrained` for a local save.

**[NOTE]** This ONLY saves the LoRA adapters, and not the full model. To save to 16bit or GGUF, scroll down!

In [ ]:
save_path = "/content/drive/MyDrive/code_model_v2"
model.save_pretrained_merged(save_path, tokenizer, save_method="merged_16bit")

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [00:34<00:00, 34.01s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [01:21<00:00, 81.51s/it]

Unsloth: Merge process complete. Saved to `/content/drive/MyDrive/code_model_v2`

Now if you want to load the LoRA adapters we just saved for inference, set `False` to `True`:

You can also use Hugging Face's `AutoModelForPeftCausalLM`. Only use this if you do not have `unsloth` installed. It can be hopelessly slow, since `4bit` model downloading is not supported, and Unsloth's **inference is 2x faster**.

In [ ]:
from unsloth import FastLanguageModel   # import this FIRST
import torch

max_seq_length = 2048
dtype = None
load_in_4bit = True

save_path = "/content/drive/MyDrive/lora_model"

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name     = save_path,    # 👈 use the Drive folder as model_name
    max_seq_length = max_seq_length,
    dtype          = dtype,
    load_in_4bit   = load_in_4bit,
)

🦥 Unsloth: Will patch your computer to enable 2x faster free finetuning.
🦥 Unsloth Zoo will now patch everything to make training faster!
==((====))==  Unsloth 2025.11.4: Fast Llama patching. Transformers: 4.57.1.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.741 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.9.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.5.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.33.post1. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!

model.safetensors:   0%|          | 0.00/1.03G [00:00<?, ?B/s]

generation_config.json:   0%|          | 0.00/234 [00:00<?, ?B/s]

Unsloth 2025.11.4 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens.

In [ ]:
# Merge to 16bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_16bit", token = "")

# Merge to 4bit
if False: model.save_pretrained_merged("model", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "merged_4bit", token = "")

# Just LoRA adapters
if False: model.save_pretrained_merged("model", tokenizer, save_method = "lora",)
if False: model.push_to_hub_merged("hf/model", tokenizer, save_method = "lora", token = "")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [Wiki page](https://github.com/unslothai/unsloth/wiki#gguf-quantization-options)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/drive/1WZDi7APtQ9VsvOrQSSC5DDtxq159j8iZ?usp=sharing)

Now, use the `model-unsloth.gguf` file or `model-unsloth-Q4_K_M.gguf` file in `llama.cpp` or a UI based system like `GPT4All`. You can install GPT4All by going [here](https://gpt4all.io/index.html).

**[NEW] Try 2x faster inference in a free Colab for Llama-3.1 8b Instruct [here](https://colab.research.google.com/drive/1T-YBVfnphoVc8E2E854qF3jdia2Ll2W2?usp=sharing)**

In [ ]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("model", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if True: model.push_to_hub_gguf("FatimaZh/model", tokenizer, token = "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")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("FatimaZh/model", tokenizer, quantization_method = "f16", token = "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")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("model", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("FatimaZh/model", tokenizer, quantization_method = "q4_k_m", token = "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")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "hf/model", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "", # Get a token at https://huggingface.co/settings/tokens
    )

Unsloth: Converting model to GGUF format...
Unsloth: Merging model weights to 16-bit format...

config.json:   0%|          | 0.00/894 [00:00<?, ?B/s]

Found HuggingFace hub cache directory: /root/.cache/huggingface/hub
Checking cache directory for required files...
Cache check failed: model.safetensors not found in local cache.
Not all required files found in cache. Will proceed with downloading.
Checking cache directory for required files...
Cache check failed: tokenizer.model not found in local cache.
Not all required files found in cache. Will proceed with downloading.

Unsloth: Preparing safetensor model files:   0%|          | 0/1 [00:00<?, ?it/s]

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

Unsloth: Preparing safetensor model files: 100%|██████████| 1/1 [00:26<00:00, 26.59s/it]

Note: tokenizer.model not found (this is OK for non-SentencePiece models)

Unsloth: Merging weights into 16bit: 100%|██████████| 1/1 [00:23<00:00, 23.86s/it]

Unsloth: Merge process complete. Saved to `/tmp/unsloth_gguf__r0iybnq`
Unsloth: Converting to GGUF format...
==((====))==  Unsloth: Conversion from HF to GGUF information
   \\   /|    [0] Installing llama.cpp might take 3 minutes.
O^O/ \_/ \    [1] Converting HF to GGUF f16 might take 3 minutes.
\        /    [2] Converting GGUF f16 to ['q8_0'] might take 10 minutes each.
 "-____-"     In total, you will have to wait at least 16 minutes.

Unsloth: Installing llama.cpp. This might take 3 minutes...
Unsloth: Updating system package directories
Unsloth: All required system packages already installed!
Unsloth: Install llama.cpp and building - please wait 1 to 3 minutes
Unsloth: Cloning llama.cpp repository
Unsloth: Install GGUF and other packages

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/u54VK8m8tk) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other links:
1. Zephyr DPO 2x faster [free Colab](https://colab.research.google.com/drive/15vttTpzzVXv_tJwEk-hIcQ0S9FcEWvwP?usp=sharing)
2. Llama 7b 2x faster [free Colab](https://colab.research.google.com/drive/1lBzz5KeZJKXjvivbYvmGarix9Ao6Wxe5?usp=sharing)
3. TinyLlama 4x faster full Alpaca 52K in 1 hour [free Colab](https://colab.research.google.com/drive/1AZghoNBQaMDgWJpi4RbffGM1h6raLUj9?usp=sharing)
4. CodeLlama 34b 2x faster [A100 on Colab](https://colab.research.google.com/drive/1y7A0AxE3y8gdj4AVkl2aZX47Xu3P1wJT?usp=sharing)
5. Mistral 7b [free Kaggle version](https://www.kaggle.com/code/danielhanchen/kaggle-mistral-7b-unsloth-notebook)
6. We also did a [blog](https://huggingface.co/blog/unsloth-trl) with 🤗 HuggingFace, and we're in the TRL [docs](https://huggingface.co/docs/trl/main/en/sft_trainer#accelerate-fine-tuning-2x-using-unsloth)!
7. `ChatML` for ShareGPT datasets, [conversational notebook](https://colab.research.google.com/drive/1Aau3lgPzeZKQ-98h69CCu1UJcvIBLmy2?usp=sharing)
8. Text completions like novel writing [notebook](https://colab.research.google.com/drive/1ef-tab5bhkvWmBOObepl1WgJvfvSzn5Q?usp=sharing)
9. [**NEW**] We make Phi-3 Medium / Mini **2x faster**! See our [Phi-3 Medium notebook](https://colab.research.google.com/drive/1hhdhBa1j_hsymiW9m-WzxQtgqTH_NHqi?usp=sharing)
10. [**NEW**] We make Gemma-2 9b / 27b **2x faster**! See our [Gemma-2 9b notebook](https://colab.research.google.com/drive/1vIrqH5uYDQwsJ4-OO3DErvuv4pBgVwk4?usp=sharing)
11. [**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/drive/1WZDi7APtQ9VsvOrQSSC5DDtxq159j8iZ?usp=sharing)
12. [**NEW**] We make Mistral NeMo 12B 2x faster and fit in under 12GB of VRAM! [Mistral NeMo notebook](https://colab.research.google.com/drive/17d3U-CAIwzmbDRqbZ9NnpHxCkmXB6LZ0?usp=sharing)

<div class="align-center">
  <a href="https://github.com/unslothai/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/u54VK8m8tk"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://ko-fi.com/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Kofi button.png" width="145"></a></a> Support our work if you can! Thanks!
</div>